### ISSUE TITLE
High/Low Band plots with holes don't trigger auto scale on Y axis

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#100]
Continuing from #93, this is the current state:
https://jsfiddle.net/danyalejandro/93utgkbx/10/

![image](https://user-images.githubusercontent.com/1218608/73111540-791f6e00-3ebf-11ea-8909-1e8623bf560a.png)
Which doesn't break anymore :D However, note how the Y axis always starts from 0 when a "hole" is displayed on screen. If I zoom in enough to avoid displaying the hole region, the expected autoscale for Y axis kicks in:

![image](https://user-images.githubusercontent.com/1218608/73111600-b5eb6500-3ebf-11ea-90ae-c8136ca32abe.png)

Is this the expected behavior?

Thank you

**Comment by leeoniya** [comment]
this looks like a bug.

uPlot runs `Math.min()` and `Math.max()` in a dumb loop over the data. i'm guessing that loop coerces `null` to 0, which becomes the scale's min. without the gap, it behaves correctly: https://jsfiddle.net/oy2ewj9v/

i pushed a fix in db2eac32f140ce4978318a250c826e7a28108082. it reduces perf a bit by 1-2ms for the 166k bench.

**Comment by leeoniya** [comment]
heads up, `spanGaps` opt has moved from global to per-series.

**Comment by danyalejandro** [comment]
Thank you! This works wonderfully now.
![image](https://user-images.githubusercontent.com/1218608/73229129-89d51b80-412d-11ea-848c-39ad913ba3f9.png)
