### ISSUE TITLE
detect setScale hook triggered by left mouse drag

### ISSUE THREAD

**Issue by RonnieLincoln** [leeoniya/uPlot#1000]
Hi,

SetScale hook is triggered by `setData`, `setScale`, mouse drag, double click.

Is there any way to know it exactly from mouse drag?

:)

**Comment by RonnieLincoln** [comment]
by the way, I am using v1.6.17

**Comment by RonnieLincoln** [comment]
Solved it by setting a mark in `cursor.bind.mouseup` MouseListenerFactory .

**Comment by leeoniya** [comment]
you can add a `setSelect` hook and set some `viaDrag = true` flag in there.
