### ISSUE TITLE
Difficulty getting x-axis scale to update for a live scatterplot

### ISSUE THREAD

**Issue by ewz4** [leeoniya/uPlot#1001]
Hello,

I am attempting to create a live scatter plot, and I would like the x-axis scale to have its range auto-adjust as the data points change. It seems like I can set the scale range before I call `setData`, but once I call it, that range gets locked in.

```
export type FacetValues = any[];
export type FacetSeries = FacetValues[];
export type FacetedData = [_: null, ...series: FacetSeries];

export const formatData = (xValues: number[], yValues: number[], uPlotInstance: uPlot) => {

  const formattedData: FacetedData = [null, [xValues, yValues]];
  
  const xMin = Math.min(...xValues)
  const xMax = Math.max(...xValues);
  
  uPlotInstance.scales['x'].range = () => uPlot.rangeNum(xMin, xMax, 0.1, true)
  uPlotInstance.setData(newFormattedData as unknown as uPlot.AlignedData);
  uPlotInstance.redraw();
};
```
So in the above code, I'll call `formatData()` as my x and y values change. The first time, the x-axis will get scaled to the first input set's max and min. Subsequent calls with different `xMin` and `xMax` values won't change the range for the x-axis scale.

Similarly, if I take out the the range setting line, the first `formatData` call will scale the x-axis properly and automatically, but after that, the x-axis doesn't change to even as the data's bounds change.

I am wondering what the proper way to automatically adjust the x-axis scale would be. Thanks in advance for your help!

**Comment by PabloAlexis611** [comment]
I don't think you need to call `redraw` - calling `setData` will reset the scales unless told not to (passing an extra boolean argument as `false`)

I have configured axis like this in the past and it works.

``` ts
x: {
  time: false,
  range: (_u, dataMin, dataMax) => {
    if (dataMin) {
      return uPlot.rangeNum(dataMin, dataMax, 0.1, true)
    }
    // Set default scale values when plots are empty.
    return [0, 10];
  },
},
```

By default the `range` function comes with 3 parameters - the uplot instance, min value, and max value and you don't need to calculate them - but I think you might be overriding that?

Try doing this:

``` ts
uPlotInstance.scales['x'].range = (_u, dataMin, dataMax) => uPlot.rangeNum(dataMin, dataMax, 0.1, true)
```

(you don't need to calculate manually what min/max are either - just use the arguments the function has, i think that should just work)

**Comment by ewz4** [comment]
Thank you so much! Yeah removing the `redraw()` function allowed me to auto-scale the x-axis without any manual processing on my end.
