### ISSUE TITLE
TypeError on series deletion after upgrading to v1.6.31

### ISSUE THREAD

**Issue by Loori-R** [leeoniya/uPlot#1004]
**Description:**
After updating to [v1.6.31](https://github.com/leeoniya/uPlot/releases/tag/1.6.31), an error occurs when trying to delete series.

**Error:**
```
TypeError: Cannot read properties of null (reading 'remove')
```

**Location:**
The error occurs in the following line of code:
https://github.com/leeoniya/uPlot/blob/f98d1d34d92a128f18fbaac9293910eed85ea19c/src/uPlot.js#L1086

**Comment by leeoniya** [comment]
would you mind making a fiddle?

i cannot reproduce an error here: https://leeoniya.github.io/uPlot/demos/add-del-series.html

**Comment by Loori-R** [comment]
@leeoniya It seems that this error occurs when trying to delete the first series (which is bound to the X-axis) using `u.delSeries(0)`. In other cases, the deletion works correctly.

**Comment by leeoniya** [comment]
i don't think this is a regression in 1.6.31, i checked out 1.6.30 and switched to `sidx = 0` and still get the same error.

https://github.com/leeoniya/uPlot/blob/f98d1d34d92a128f18fbaac9293910eed85ea19c/demos/add-del-series.html#L82

the existence of the `delSeries` API is for streaming / IoT use cases where devices may appear/disappear randomly and we dont want to destroy/re-init every 100ms. for these cases there's no need to ever to delete the shared x series. outside of high frequency use cases, if you have any kind of config changes, you should simply destroy and re-init the plot with the new config. this is what we do in Grafana without issue, and it's very simple to reason about.

**Comment by photron** [comment]
> would you mind making a fiddle?
> 
> i cannot reproduce an error here: https://leeoniya.github.io/uPlot/demos/add-del-series.html

I can make this TypeError happen on every delSeries call in the add-del-series demo, if I set the option cursor.points.show to false.

``` diff
diff --git a/demos/add-del-series.html b/demos/add-del-series.html
index e5c816d..05468a4 100644
--- a/demos/add-del-series.html
+++ b/demos/add-del-series.html
@@ -56,6 +56,11 @@
                                                fill: "rgba(0,0,255,0.1)",
                                        },
                                ],
+                               cursor: {
+                                       points: {
+                                               show: false,
+                                       },
+                               },
                        };
 
                        let u = new uPlot(opts, data, document.body);
```
