### ISSUE TITLE
Identifying Zoom Out Behavior - Various Approaches

### ISSUE THREAD

**Issue by majew7** [leeoniya/uPlot#1005]
Hello and thanks in advance!

**Context:** Sometimes I plan to load into `UplotReact`, a subset of samples, rather than all the samples to save time on loading data from the server.  We have very large data.

And when a user zooms out (via double-click), I want the application to fetch more data from the server for a larger time span.

NOTE: We use `setScale()` and custom `onZoomTimeChange()` today to adjust the current time range in the url, as the user moves through their time series data.

**My Question:** How can I know if a user double-clicked, so that I know to fetch more data from the server.  I’ve considered:

 - OPTION A: Manual Comparison: Read from hook `setScale()`, and compare the time scale “x-axis” values returned against the last saved values in React state.  If the time window got larger, then I know that the user double-clicked to zoom out, and I can fetch more data.

- OPTION B: Unsure…

Thoughts @leeoniya?  I was hoping to hear various options and advice too.     Appreciated.

**Comment by leeoniya** [comment]
memoing previous range seems fine.

double click in uPlot _normally_ means "zoom to fit existing x data". but you can hook into the doubleclick listener using `cursor.bind.dblclick` option and do something else, like determine new zoomed out range and fetch data for it. 

https://github.com/leeoniya/uPlot/blob/f98d1d34d92a128f18fbaac9293910eed85ea19c/dist/uPlot.d.ts#L440
