### ISSUE TITLE
Issues with uPlot integration in React Flow

### ISSUE THREAD

**Issue by AlexSKuznetsov** [leeoniya/uPlot#1009]
Hi there,

I’m experiencing several issues while using uPlot in combination with [React Flow](https://reactflow.dev/). 

Could you please assist me in resolving these issues?

I’ve created a Stackblitz with examples of the issues: [Stackblitz Link](https://stackblitz.com/edit/y23e7r?file=ResizeRotateNode.jsx,Chart.tsx)

Issues:
- The line appears blurred from the start.
- The crosshair is missing the point on hover over the line values.

https://github.com/user-attachments/assets/15ebc5ce-794a-472c-a163-81348630b958

Thank you in advance for your help!

**Comment by leeoniya** [comment]
unfortunately there is no simple solution that can be added to uPlot to account for the containing DOM being css transformed. i would suggest reaching out in the [React Flow repo](https://github.com/xyflow/xyflow) for a solution that would be node-content-agnostic. it looks like the scale transform is the main thing to avoid here, the x/y transform appears to work okay. the way to keep uPlot sharp is to use the `.setSize()` api to size it to its container, and not rely on css scaling, which will worsen the resolution.

![image](https://github.com/user-attachments/assets/6896e811-afb3-4728-97eb-66ef39450f52)
