### ISSUE TITLE
Setting bar widths not working anymore in recent uPlot versions

### ISSUE THREAD

**Issue by TPU22** [leeoniya/uPlot#1011]
The behavior of how the bar widths are set in uPlot seems to have changed maybe around 1.6.29 or afterwards. I cannot anymore force the bar widths by simply 
`paths: uPlot.paths.bars({
align: -1,
gap: -0,
size: [width, Infinity] })`

The recent versions do not follow the width setting anymore (so that the bars would overlap each other), but rather the bar widths are truncated so two bars cannot intersect each other. I have a time series where the bars should have the width of a full hour in the X-axis, but the data and time series is sampled with higher frequency than just once per hour. However, the data that I am plotting is null except when the minutes of the time points are zero. Hence, I have earlier just plotted the data with a fixed width because the null values are not rendered. I set the width of the bar in order to get the bars of non-null data extended and aligned with each other (extension over the null data points, naturally). 

How to accomplish this in recent versions of uPlot?

**Comment by leeoniya** [comment]
please make a jsFiddle that shows a simple failing setup that worked for you before. e.g. https://jsfiddle.net/q2m7o1dc/

**Comment by TPU22** [comment]
Old version behavior (I would like to have this behavior in the recent versions also): https://jsfiddle.net/ph593z1j/2/
New version behavior: https://jsfiddle.net/Ljqanrz5/

The only difference in the Fiddles is in the version of uPlot.

**Comment by leeoniya** [comment]
thanks.

i think the new behavior is correct and the old behavior is actually the weird one. the bars cannot be wider than the "minimum detected x spacing", which is the smallest x delta between adjacent non-undefined y values. `null` in uPlot means "explicit gap", which is exactly how it behaves in recent versions.

if you want the previous behavior you can use `undefined` instead of `null`:

```js
let data = [
  [0, 1, 2, 3, 4,5, 6, 7 ,8, 9],
  [0, undefined, 2, undefined, 4, undefined, 6, undefined, 8, undefined],
];
```

**Comment by TPU22** [comment]
Thanks, this is what I wanted! However, there is one minor issue left. If nulls are replaced by undefined, the shown value is taken from the nearest neighbor node that is not undefined. How can I show the value of the "bar" that covers the area of the mouse (in my case, the _next_ defined node value, not the nearest where the cursor is)?

**Comment by TPU22** [comment]
I found an answer. The trick is to use the dataIdx setting for the cursor.
```
cursor: {
    dataIdx: (self, seriesIdx, hoveredIdx, cursorXVal) => {
        let xValues = self.data[0];
        let yValues = self.data[seriesIdx];
        if (seriesIdx == 1) {
            if (yValues[hoveredIdx] == undefined) {
                return null;
            }
        }
        return hoveredIdx;
    }
},
```
