### ISSUE TITLE
Horizontal lines for an inverted chart

### ISSUE THREAD

**Issue by CheapGamma** [leeoniya/uPlot#1012]
Hi! first of all i want to say that this is an awesome library, i used Echarts before.
I have a problem, I can't figure out how to set a horizontal line to Yaxis, at a certain level in relation to Xaxis.

So I have:

 ```

            scales: {
                x: {
                    time: false, range: (u, min, max) => [min - 1, max + 1],
                    dir: 1,
                    ori: 1,
                },
                y: {
                    auto: true,
                    dir: 1,
                    ori: 0,
                }
            },

```
and
 ```

            axes: [
                {
                    label: ‘X’,
                    side: 3, // left
                },
                {
                    label: ‘Y’,
                    side: 2, // Bottom
                },
                
            ],

```

I tried the trendline example. But firstly I don't need a vertical line, and secondly the horizontal line doesn't fit in the required mark on the X axis even if I set the parameters manually...

```

                        let x0 = u.valToPos(0, 'x', true);
                        let y0 = u.valToPos(50, 'y', true);
                        let x1 = u.valToPos(88, 'x', true);
                        let y1 = u.valToPos(50, 'y', true);
```

![Снимок экрана 2024-10-22 035929](https://github.com/user-attachments/assets/5867446d-075d-4322-b949-4af494c4184f)

and thirdly, because I'm using ResponsibleContainer, as you can see the horizontal line is moving out of the chart.

One more thing, I tried the example from [https://github.com/leeoniya/uPlot/issues/203#issuecomment-643426245](https://github.com/leeoniya/uPlot/issues/203#issuecomment-643426245).
but again because of the inverted chart, the lines are not aligned correctly.

thank you!

**Comment by leeoniya** [comment]
hi, i am not sure that i understand exactly what you're trying to accomplish.

can you please make a jsfiddle of your example above, like https://jsfiddle.net/q2m7o1dc/

if possible, please draw an example of what you would like to see.

**Comment by CheapGamma** [comment]
> hi, i am not sure that i understand exactly what you're trying to accomplish.
> 
> can you please make a jsfiddle of your example above, like https://jsfiddle.net/q2m7o1dc/
> 
> if possible, please draw an example of what you would like to see.

For sure! 
1. https://jsfiddle.net/o82Lmext/5/ this is what I have now.
2. but I want to achive :

![Снимок экрана 2024-10-22 120908](https://github.com/user-attachments/assets/b2bd2917-891f-4718-9ddf-467682a772f9)

well... how do I draw a line that is parallel to the Y-axis, and is at mark 4 on the X-axis?

**Comment by CheapGamma** [comment]
I tried again and this is the result [https://jsfiddle.net/zgvawrm8/6/](https://jsfiddle.net/zgvawrm8/6/) but as you can see, the line is not at 4 mark at all

**Comment by leeoniya** [comment]
https://jsfiddle.net/17ye3kwg/

```js
  hooks: {
    draw: [
      u => {
        let x4 = u.valToPos(4, 'x', true);
        let ylft = u.valToPos(u.scales.y.min, 'y', true);
        let yrgt = u.valToPos(u.scales.y.max, 'y', true);
        u.ctx.save();
        u.ctx.beginPath();
        u.ctx.moveTo(ylft, x4);
        u.ctx.lineTo(yrgt, x4);
        u.ctx.strokeStyle = 'orange';
        u.ctx.stroke();
        u.ctx.restore();
      }
    ]
  }
```

it might make life a little easier if you use `uPlot.orient()`, which gives you some canvas function wrappers that swap the coordinate space. e.g.

https://github.com/leeoniya/uPlot/blob/f98d1d34d92a128f18fbaac9293910eed85ea19c/src/paths/linear.js#L24

https://github.com/leeoniya/uPlot/blob/f98d1d34d92a128f18fbaac9293910eed85ea19c/src/paths/utils.js#L24-L61

**Comment by CheapGamma** [comment]
> https://jsfiddle.net/17ye3kwg/

Awesome! Thank you so much! I'm just starting to get familiar with uPlot, but I'm impressed with the functionality and flexibility!
