### ISSUE TITLE
Demo Ranger grips are removed when clicking on chart

### ISSUE THREAD

**Issue by lucianbaciu** [leeoniya/uPlot#1014]
The issue can be easily reproduced on:
https://leeoniya.github.io/uPlot/demos/zoom-ranger-grips.html

When clicking outside of the selection, it dissapears.

If this is the desired behavior? are there workarounds?

**Comment by leeoniya** [comment]
hmm, this regressed in 69bbad5bd00e84f6b45e8c0236e251de65374e45

**Comment by leeoniya** [comment]
looking at what i was working on around the same time in Grafana, https://github.com/grafana/grafana/pull/72163 looks like it may have been related.

**Comment by leeoniya** [comment]
duplicate of https://github.com/leeoniya/uPlot/issues/936

**Comment by leeoniya** [comment]
i've reverted the relevant change and will test in Grafana to make sure it does not cause any breakage.

**Comment by lucianbaciu** [comment]
Thank you!
