### ISSUE TITLE
Is it possible to modify labels values?

### ISSUE THREAD

**Issue by CheapGamma** [leeoniya/uPlot#1016]
Hello! I'm still on track and step to step learn uPlot! 

I have a question, is it possible to modify legends values? 

For instance, on the image, if value will be 4 000 000 instead of 40, and I wish to modify it with my script, how can I do that?

![Снимок экрана 2024-11-01 174619](https://github.com/user-attachments/assets/67e0be02-b08f-4224-b454-ac79c0f8a3ce)

**Comment by leeoniya** [comment]
you can see here:

https://github.com/leeoniya/uPlot/blob/f98d1d34d92a128f18fbaac9293910eed85ea19c/bench/uPlot.html#L99

**Comment by CheapGamma** [comment]
> you can see here:
> 
> https://github.com/leeoniya/uPlot/blob/f98d1d34d92a128f18fbaac9293910eed85ea19c/bench/uPlot.html#L99

yeah, thank you very much! 

`
                    {
                        label: 'Label',
                        stroke: themeStyle.lineRed,
                        fill: themeStyle.areaRed,
                        width: 1,
                        points: { show: false },
                        //dash: [10, 5],
                        value: (u, value) => helpers_js.formatCash(value), 
                    },`
it's worked!
