### ISSUE TITLE
Where are we headed?

### ISSUE THREAD

**Issue by backspaces** [leeoniya/uPlot#1018]
I basically want to know the future o uPlot. Is it under active development? What are the next updates? Scatter plots? Docs? Are we in bug fixing mode, the existing plots are fine?

I really love the refreshing simplicity and blazing speed, but I need to choose a plot lib for a NetLogo style implementation with lightweight plotting widgets.

If we are curbing development, what libraries would you recommend?

Thanks!

**Comment by leeoniya** [comment]
it's not curbed. it's just slowed down.

i have some breaking changes planned for v2, including more ergonomic support for scatter plots, heatmaps. you can already do both with `mode: 2`, but it you still need to bring your own spatial index and hook up too much stuff.

https://leeoniya.github.io/uPlot/demos/scatter.html
https://leeoniya.github.io/uPlot/demos/latency-heatmap.html

also having something that is "series index" scale and "color scale" would be useful so it was less hacky to do barcharts and state timeline stuff.

maybe finally add some form of built-in tooltip.

maybe use a second canvas for interaction layer. with 3000 series it becomes slow to update position of 3000 hover points in the DOM: https://github.com/leeoniya/uPlot/issues/922

axis-aware scale ranging so it can better guarantee ticks at the edges/outside the data limits.

a lot of these are deep, rather complex changes. hopefully i can get it all in by end of 2025 and some minimal compat wrapper to ease migrating from v1, but no promises.

there won't be any fundamental things that v2 will allow you to do that you cannot do with v1, it will just be more ergonomic, and a bit more batteries included.

**Comment by leeoniya** [comment]
btw, i work at Grafana, where uPlot runs most core panels, so it will for sure be maintained for quite a while.
