### ISSUE TITLE
Exception when using setSeries if cursor: {show: false}

### ISSUE THREAD

**Issue by Zultanic** [leeoniya/uPlot#1021]
Hi, I think I have found a bug in the function `toggleDOM`. I have tuned off the legend, and cursor and am using a custom legend to toggle series on and off with the `setSeries` fucntion. In this case the line `let pt = cursorOnePt ? cursorPts[0] : cursorPts[i]` can result in `pt = null` which is then used in elTrans causing the exception. I resolved this in my code with a check for null but maybe you have a better idea or I am using the function incorrectly.

**Comment by leeoniya** [comment]
thanks, linked commit should fix it. try it out :)
