### ISSUE TITLE
[Question] Attach a Slider on all Y Axes.

### ISSUE THREAD

**Issue by RonnieLincoln** [leeoniya/uPlot#1023]
Hi there, just a question.

When setup multiple Y axes( more then 3 ), it seems like it's not intuitive to see the Scale.

How about this?
If we make all `u-series` a slider that automatically move on `u-axis` ( or y axis ), it will be good.

And how to do this?

**Comment by leeoniya** [comment]
can you show me an example?

**Comment by RonnieLincoln** [comment]
Thank you for your response.

![image](https://github.com/user-attachments/assets/c816b9d0-8d20-4af6-b05f-7fbc113f3d89)

each `u-series` is slide or move on the `y-axis` when mouse moving over canvas.

**Comment by leeoniya** [comment]
ok, thanks. this would be a nice demo to add. should be pretty easy.

each axis already has a dom element overlay `.u-axis`. you can use an `init` hook to find these elements in the dom and add your own elements that you will update with `.textContent` and `.style.transform` inside a `setLegend` hook.

**Comment by RonnieLincoln** [comment]
Thank you for your response.
You are right. It works. This is `setLegend` code in my case.
```js
  setLegend: [
      // for tooltips
      (u) => {
          console.log('setLegend')

          if (!u.cursor.idx) return

          const cursorPts = document.querySelectorAll('.u-cursor-pt')

          u.axes.forEach((axis, idx) => {
              if (idx === 0) return;

              const tooltip = axis._el.firstElementChild

              tooltip.style.transform = window._retrieveTranslationY(cursorPts.item(idx - 1).style.transform, -26)
              tooltip.textContent = u.legend.values[idx]._
          });

      },
  ],
```

https://github.com/user-attachments/assets/954996f7-29da-4f8f-a379-1e8f335d411c

**Comment by leeoniya** [comment]
nice. i'd probably do it a bit differently instead of reading back cursor pt styles and re-applying them i would simply recompute the positions using cursor.idxs to read back the raw data and call `u.valToPos(data[seriesIdx][pointIdx])`.

would you like to make a PR for the above demo similar to https://github.com/leeoniya/uPlot/blob/master/demos/area-fill.html and i can tweak it a bit?

**Comment by RonnieLincoln** [comment]
sure, I will do it

**Comment by leeoniya** [comment]
thanks!
