### ISSUE TITLE
when use log axis,with base 2,but the min range is lower than 1e-16,it would crash,can't render a curve 

### ISSUE THREAD

**Issue by wxyer** [leeoniya/uPlot#1027]

**Comment by leeoniya** [comment]
what version are you using?

the log demo have base 2 values below this: https://leeoniya.github.io/uPlot/demos/log-scales2.html

**Comment by leeoniya** [comment]
this was fixed in 1.6.31:

https://github.com/leeoniya/uPlot/compare/1.6.30...1.6.31

please update

**Comment by StefanoVuerich** [comment]
Good morning @leeoniya 

I getting same error but when I switch to 1.6.30 I got compilation error:

Module parse failed: Unexpected token (2751:25)

...that I think is related to https://github.com/leeoniya/uPlot/issues/599
