### ISSUE TITLE
Legend control options

### ISSUE THREAD

**Issue by ryantxu** [leeoniya/uPlot#104]
This library looks super promising -- I am evaluating how well it would to to render graphs for grafana.  Currently we use flot... we keep trying other libs, but they all fall down for various reasons.

I have a super super basic example panel https://github.com/ryantxu/grafana-uPlot-panel

is there any way to remove the built-in legend, and just get a callback on hover?

**Comment by ryantxu** [comment]
figured it out :)

```

    const opts = {
      width,
      height,
      legend: {
        show: false,
      },
...
```

**Comment by leeoniya** [comment]
@dgl is also working on a grafana/prometheus prototype,  think: https://github.com/dgl/mongrid
