### ISSUE TITLE
Question: how do I use tzDate?

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#106]
Hello, and thank you for all your work in this project so far.

I'm trying to plot a series of values with UTC timestamps obtained from a server. Every time I zoom in, I query the server for data in the interval provided by uplot.scales.x and plot the response.

As I'm located in British Columbia / Canada (GMT-7 minus 1 hour from daylight savings right now), the range obtained for uplot.scales.x appears shifted 7 or 8 hours depending on the time of the year I'm viewing:

![image](https://user-images.githubusercontent.com/1218608/73291673-81282800-41b5-11ea-9388-144926b6c4f4.png)

Could I use tzDate to add the offset in a smart way so that I don't have to calculate DST differences for every sample? I'm trying to do this manually but its starting to become a mini-project.

**Comment by leeoniya** [comment]
it should be no more complicated than:

```js
{
  tzDate: ts => uPlot.tzDate(new Date(ts * 1e3), "America/Vancouver"),
}
```

more demos: https://github.com/leeoniya/uPlot/blob/master/demos/timezones-dst.html

**Comment by danyalejandro** [comment]
Finally works, thank you for this simple example!
