### ISSUE TITLE
Interaction callbacks (hover, click, zoom)

### ISSUE THREAD

**Issue by ryantxu** [leeoniya/uPlot#109]
I am looking at how to integrate this into grafana -- what is the best way to get a callback after user input?

Is there anything like:
```
 onHover( evt, row )
 onClick( evt, row, column )
 onZoom( evt, xmin, xmax, ymin, ymax )
 onReset ??? the double click?
```
or plans to add that?

In particular, we would like to use our own legend, tooltip and zoom behavior

**Comment by leeoniya** [comment]
take a look at the list of available `.hooks` in #48.

a good portion of the demos use plugins/hooks, so read through those: https://github.com/leeoniya/uPlot/tree/master/demos

look through the trove of closed issues with "hooks": https://github.com/leeoniya/uPlot/issues?utf8=%E2%9C%93&q=hooks

> In particular, we would like to use our own legend, tooltip and zoom behavior

all do-able.

`{legend: {show: false}}`, `setCursor` hook, `.setScale()`, `.setSelect()`

**Comment by ryantxu** [comment]
yes -- I can get all these events 🎉
