### ISSUE TITLE
option to accept millisecond timestamps

### ISSUE THREAD

**Issue by ryantxu** [leeoniya/uPlot#114]
As I understand it, the reason for unix timestamps (seconds) as the supported time format is that the precision is rarely necessary when showing graphs over a wide time span.  makes sense.  #60 

I don't get why it is better to encourage seconds over milliseconds for the raw data, and require extra work/processing/etc to support milliseconds.  Regardless of the semantic meaning (seconds,milliseconds,etc) all numbers are 64bits in javascript, so what are we really saving?  json text bytes?  shorter console.log messages?

When looking at how to best integrate with our existing millisecond model I see a few paths to work around this choice -- totally possible, but I wonder if it is is better solved as a config option somewhere in the library.  Potentially a global flag saying "assume all timestamps are seconds|milliseconds"

IIUC -- the current best practice would be to just convert all millisecond data to floating point and pass that in.

**Comment by leeoniya** [comment]
> so what are we really saving? json text bytes?

yes. text does not compress *so* well that an extra, useless "000" x 500k datapoints would be negligible. if you need the extra precision, you're talking about an extra 500k bytes for the `.`, but if you don't need it you're saddled with 500k x 3 bytes for literally no reason.

> but I wonder if it is is better solved as a config option somewhere in the library. Potentially a global flag saying "assume all timestamps are seconds|milliseconds"

a configurable `x` multiplier per uPlot instance sounds reasonable. default would be `1e3` but can be changed to `1`.

**Comment by leeoniya** [comment]
after glancing back at [1], there's actually quite lot that would need to change from being static to being conditioned on the multiplier. also the docs will need to come with the caveat everywhere that the args can have different meanings based on the multiplier. i'm not convinced that the value-add here is worth it. the easiest thing uPlot can do is to run the 1-liner pre-processing division loop for you, but this is too trivial to be add to the API.

internally uPlot operates on numbers and only instantiates transient Date objects (very infrequently) as necessary for determining calendar breakpoints and formatting legend values or x-axis ticks.

sorry, i think this will be a no from me; you'll have to pre-process the ms-resolution timestamps to floats.

[1] https://github.com/leeoniya/uPlot/blob/master/src/opts.js
