### ISSUE TITLE
Gaps become visible and connected at a certain width

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#121]
I'm reporting this bug with screenshots first because it's difficult for me to get the exact data in the right format, just in case the solution is something simple. Otherwise, I think I can attach the data later.

This data gap becomes visible at a specific plot width (same data, same everything else). I'm only including canvas dimensions because I don't believe this is happening outside of the canvas:

plot.canvas width 635:

![image](https://user-images.githubusercontent.com/1218608/73992270-6ff0c100-4903-11ea-8e45-06f498730d4d.png)

plot.canvas width 634:

![image](https://user-images.githubusercontent.com/1218608/73992187-299b6200-4903-11ea-9413-9b1c0a64552f.png)

plot.canvas width 633:

![image](https://user-images.githubusercontent.com/1218608/73992245-564f7980-4903-11ea-8080-916163365045.png)

Same behavior in Chrome & Firefox, same data, same everything, just changing the width option. I didn't find any other width that caused this, just 634.

What do you think could cause this behavior?

**Comment by leeoniya** [comment]
myinitial thought is that it's caused by rounding errors while the draw loop accumulates high/low values per pixel.

reproducing this might be tricky with random datasets, so it would be helpful if you can provide that.

**Comment by leeoniya** [comment]
i tried to trigger this by adding gaps into random trend data and resizing by 1px increments, but could not reproduce :(

does this span any gaps at any sizes for you?

https://jsfiddle.net/Lqzyhwmx/

**Comment by danyalejandro** [comment]
I think I can come up with a reproducible sample today, sorry for the delay.

**Comment by danyalejandro** [comment]
Here you go! Sorry for the super weird use case, I'm grabbing the data dynamically and don't know what to expect nor in what format:

https://jsfiddle.net/danyalejandro/93utgkbx/53/

**Comment by leeoniya** [comment]
fixed!

> Sorry for the super weird use case

no need to apologize.

this wasn't that weird a case, and without it the bug would have gone undetected probably for a long time.

thanks!
