### ISSUE TITLE
Can high/low bands support stroke?

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#122]
I'm currently trying to draw low/high bands without a center line, but when their values match the line dissapears (empty area).

Going back to example:
https://jsfiddle.net/danyalejandro/93utgkbx/36/

Would it be possible for low/high bands to draw the line?

Thank you.

**Comment by leeoniya** [comment]
i'm not quite sure what you're asking for.

i can make the band's filled shape also strokable, which would stroke the entire shape and not just the place where low = high. it would look like below, but i'm not sure this is what you're after.

there is no way to make the band draw anything besides the shape of the band. where would it get the data from to draw the line down the center?

![image](https://user-images.githubusercontent.com/43234/74075824-3343c900-49da-11ea-833c-29af0cfa2d9f.png)

**Comment by leeoniya** [comment]
the easiest solution though, might simply be to add some tiny value to the high or low band, so they're not *exactly* equal in the data you pass to uPlot, and tweak the `series.value((self, raw, idx) => displayValue)` to lookup by `idx` in the "real" data and display that:

https://jsfiddle.net/ymj6sf4h/

**Comment by danyalejandro** [comment]
Thank you for your quick response and the (impressive) example.

Sorry I didn't word my question in a clear way. This is what I was trying to describe:
![image](https://user-images.githubusercontent.com/1218608/74077002-18208b80-49d1-11ea-9608-99cbfba169b4.png)

**Comment by leeoniya** [comment]
bands are now stroked by default and require `series.width: 0` to skip stroking.
