### ISSUE TITLE
Incorrect date scale breaks/labels

### ISSUE THREAD

**Issue by geotheory** [leeoniya/uPlot#124]
As your `months.html` demo illustrates, the x-scale labels are not working out right. I'm seeing two `Mar` entries and no `Oct`.  Surely not intended behaviour?

![image](https://user-images.githubusercontent.com/1282581/74094064-e7287f80-4ad2-11ea-9947-34a034d9cb43.png)

**Comment by leeoniya** [comment]
odd. i'm not seeing this over here when pulling up https://leeoniya.github.io/uPlot/demos/months.html

maybe some timezone or locale-specific date parsing differences going on.

what IANA timezone name [1] is your machine set to? my tz America/Chicago and the locale is en-US.

can you run this fiddle [2] and verify we're seeing the same timestamp array from your console?

mine is this:

```js
[1483228800,1485907200,1488326400,1491004800,1493596800,1496275200,1498867200,1501545600,1504224000,1506816000,1509494400,1512086400,1514764800,1517443200,1519862400,1522540800,1525132800,1527811200,1530403200,1533081600,1535760000,1538352000,1541030400,1543622400,1546300800,1548979200,1551398400,1554076800,1556668800,1559347200,1561939200,1564617600,1567296000,1569888000,1572566400,1575158400]`;
```

if our timestamps are different, then maybe it's an issue with `Date.parse` used in the demo, or something else demo-related. if you try swapping in my timestamps does it behave normally?

![image](https://user-images.githubusercontent.com/43234/74094772-3e672980-4aac-11ea-931a-079dec7321c2.png)

[1] https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
[2] https://jsfiddle.net/k9oLght5/

**Comment by geotheory** [comment]
I'm running on macOS in `Europe/London` timezone and `en_GB` locale.  I get the same result with that jsfiddle, and also when I substitute those timestamps.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/1282581/74095097-a5ec9b80-4ae3-11ea-8b05-6e64eb669228.png">

**Comment by geotheory** [comment]
If you can suggest any bits of the script to run debugger I can give it a try tomorrow.

**Comment by geotheory** [comment]
I should add.. the legend of returning the correct date values on hover, so it looks like label parse issue.

**Comment by leeoniya** [comment]
ok, i'm able to reproduce this by switching my machine to the London tz. i prototyped simple fix which seems to work, but if someone wants to customize `axis.values`, this particular fix will cause API non-uniformity. i'm gonna spend some time getting a proper fix in place, since tz/dst handling is the tickiest part of the whole codebase, and it's easy to make a works-85%-of-the-time mistake that's difficult to catch.

**Comment by leeoniya** [comment]
i think this is fixed. 🤞

**Comment by geotheory** [comment]
Works for me. Nice job :)
