### ISSUE TITLE
Suggestion: Add transparency to default grid stroke

### ISSUE THREAD

**Issue by ldstein** [leeoniya/uPlot#127]
Hi @leeoniya,

I'd like to suggest changing the default grid stroke color from "#eee" to "rgba(0,0,0,0.07)".

On a white background, visually there will be no noticeable difference between the two.

Once you start drawing highlighted ranges behind the grid, I feel a bit of transparency on the grid lines will generally result in a nicer aesthetic (might need to view the image below at 100% to see the effect).

![image](https://user-images.githubusercontent.com/3657344/74436708-03edfa00-4ebb-11ea-9e33-d17d52ff6d77.png)

**Comment by leeoniya** [comment]
agreed!

this improved the candlestick demo, too :)
