### ISSUE TITLE
Zoom Endstop

### ISSUE THREAD

**Issue by GatCode** [leeoniya/uPlot#129]
Hello,
I am struggling to stop the diagram at the endpoints of the data.

For example when a user zooms out completely, a view like the one below is possible.
![Bildschirmfoto 2020-02-16 um 16 10 07](https://user-images.githubusercontent.com/19287308/74607207-20ff1480-50d7-11ea-8a64-4d84da6716a6.jpg)

I tried to alter the setScale option to stop at the endpoints but I couldn't achieve a smooth result.

In the end I would like that no matter how much a user zooms out, the maximum would be this:
![Bildschirmfoto 2020-02-16 um 16 10 19](https://user-images.githubusercontent.com/19287308/74607224-5146b300-50d7-11ea-9233-8942e634c622.jpg)

Has someone already fixed my problem or could someone please help me out?

**Comment by leeoniya** [comment]
i'll probably make this the default behavior for the wheel-zoom demo. it should be just a matter of clamping `nxMin`, `nxMax` and `nxRange` after comparing to data[0] min/max values.

i'm currently working on #112, so won't get to this until that's resolved.

https://github.com/leeoniya/uPlot/blob/dd07c04deb504a2148ec11a81db10035ce1e98c8/demos/zoom-wheel.html#L31-L33

**Comment by leeoniya** [comment]
this is done.
