### ISSUE TITLE
figure out what to do for touch events

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#13]
hopefully without bloating too much code. might just resort to on-screen buttons hooked up to an API rather than dealing with implementing gesture / double-tap detection (lots of extra code, probably fragile)

https://news.ycombinator.com/item?id=21210843

**Comment by fifafu** [comment]
touch handling would make this an instant killer library on mobile devices! Especially in mobile apps performance matters a lot and it's very hard to find performant charting libraries that perform well with big amounts of data. 
Chart.js has great touch handling but is just too slow for some of our use cases.

Thanks for considering this!

It is probably complicated to do in a nice way,

**Comment by leeoniya** [comment]
since i opened this issue, uPlot has gained a healthy API, i think everything that's needed for handling touch events is now possible as a plugin.

https://leeoniya.github.io/uPlot/demos/wheel-zoom.html

is a good starting point for such an implementation, if you'd be interested in contributing one.

**Comment by fifafu** [comment]
Thanks for the pointers! Unfortunately I can't even handle my own project's workload at the moment, thus this definitely won't be in the next few weeks.
However I'll do some contract work on a project that definitely needs high performant charts on mobile devices later this year - possibly I can get paid to work on it then :-) 

Thanks for this great library!

**Comment by leeoniya** [comment]
> Thanks for this great library!

glad you're finding it useful.

i might write a minimal demo myself just to close out this issue sometime soon.

**Comment by leeoniya** [comment]
turned out that "soon" was the past 2 hours: https://leeoniya.github.io//uPlot/demos/zoom-touch.html

there's still a bit of unfinished handling for 1-touch panning, but 2-touch pinch/pan works pretty well.

**Comment by fifafu** [comment]
Works great!
