### ISSUE TITLE
How Tweak Graph Sizes?

### ISSUE THREAD

**Issue by switchtrue** [leeoniya/uPlot#133]
I was previously using uPlot as of 7f620f40da360e81f314910362e3db401bf8d2d5 today I upgraded 46f699a3029762787fe042896e24a50a6fc51a6b. The upgrade was smooth with the only breaking change I noticed being `color` -> `stroke` which I vaguely recall seeing an issue mention this.

However, whilst it works the sizing seems to work quite differently.

In 7f620f40da360e81f314910362e3db401bf8d2d5 (older) the height and width attributes would apply to the canvas, thus the graph itself would fill this space:
<img width="348" alt="Screen Shot 2020-02-26 at 8 08 03 pm" src="https://user-images.githubusercontent.com/1535972/75329440-b9657800-58d3-11ea-957a-d9a627c5d46d.png">

In 46f699a3029762787fe042896e24a50a6fc51a6b (latest) the overall graph (including axes) fills the space and the canvas itself is the full size which seems like a good change. However, the graph itself seems to be padded within this. In particular, when hiding an axis (x in this case) the graph itself remains the same size.
<img width="391" alt="Screen Shot 2020-02-26 at 7 59 53 pm" src="https://user-images.githubusercontent.com/1535972/75328893-d64d7b80-58d2-11ea-8d2c-007792026ef1.png">
![Screen Shot 2020-02-26 at 2 59 09 pm](https://user-images.githubusercontent.com/1535972/75326088-1ceca700-58ce-11ea-8b3a-e1072a10c075.png)

Is there anyway to eliminate the padding around the graph itself? So I can get back closer to the previous functionality. In particular without the x-axis it would be good if I could get the graph to fill the entire height.

**Comment by leeoniya** [comment]
probably what you're seeing is a combination of the default y `axis.size` (this did not change) and `gutters.y` (this got added to behave similarly to `gutters.x`.

y gutters are added to provide a buffer for axis tick labels at the edges, else they would get cut off. you can tweak both `axis.size` and `gutters.y`, but beware of having cut-off labels:

https://jsfiddle.net/t03ae7vo/2/

**Comment by leeoniya** [comment]
i'm gonna close this, but feel free to discuss further if more clarification is needed.

**Comment by switchtrue** [comment]
Ah, I see that makes sense. Exactly what I was looking for though. Thank you.
