### ISSUE TITLE
Low-High bands extend to borders when setScale zooms to an area with a gap

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#137]
Consider the following example:

https://jsbin.com/henonehena/3/edit?html,js,output

The example renders perfectly until I invoke setScale(). When I use setScale() to alter the viewport so that there's no data before / after the signal, the high/low canvas polygon gets "stretched" to the border.

Use case: I implemented wheel-zoom and reload data after setScale(). My data signals often have gaps, so the user can eventually trigger this bug.

**Comment by leeoniya** [comment]
this looks like a side-effect of 

https://github.com/leeoniya/uPlot/blob/a9f777f9abd3196a2b1806434cfaac2ce9d0ec33/src/Line.js#L708

combined with not accounting for a data-less start or end of a scale in

https://github.com/leeoniya/uPlot/blob/a9f777f9abd3196a2b1806434cfaac2ce9d0ec33/src/Line.js#L662
