### ISSUE TITLE
How to overwrite the dblclick event?

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#138]
Before a recent change, manually setting the ondblclick property on uplot's canvas allowed to re-implement the dblclick behavior. Now, I can't figure out how to set the event listener for dblclick. I'm currently trying this in the **ready** hook:

```
onReadyCbk = (uplot) => {
        uplot.ctx.canvas.addEventListener('dblclick', this.onDblClickCbk)
}
```
No luck so far. Any tips?

**Comment by leeoniya** [comment]
you'll probably want to attach any event listeners to the `.over` (which covers the plot area over the canvas now).

```js
uplot.root.querySelector(".over").addEventListener('dblclick', this.onDblClickCbk)
```

**Comment by joanneBio** [comment]
To attach event listener using ```uplot.root.querySelector(".over").addEventListener('dblclick', this.onDblClickCbk)``` will add another action when double-click. Is that possible to stop the chart from zoom out when double click in some situation?

**Comment by leeoniya** [comment]
you can use a capturing event listener and then call `event.stopPropagation()` when you want to prevent zoom reset.

https://javascript.info/bubbling-and-capturing

**Comment by joanneBio** [comment]
Thank @leeoniya I tried but it doesn't work. It seems that there are more complicated things involved in double click event
