### ISSUE TITLE
Support for IE 11

### ISSUE THREAD

**Issue by x2764tech** [leeoniya/uPlot#139]
Been experimenting with getting this working in IE 11, as we're often plotting masses of data (6 lines of data with ~10K points) and this is the only library I've found that doesn't have the users constantly hitting refresh...
There are a few issues:
- Polyfills for Object.assign and Point2D (currently using core-js and point2d-polyfill) - I consider this a reasonable requirement
- Transpilation - currently arrow functions are included in distribution code - I've got around this by including `node_modules/uplot/` in my babel paths, and I'm happy to live with this.
- [Use of _sticky_ Regex in fmtDate](https://github.com/leeoniya/uPlot/blob/master/src/fmtDate.js#L111) - currently I've got around this by using global Regex, but I'm not sure what the differences are, and whether you'd accept a pull request that tries to use sticky regex with global regex fallback. (Just reading https://github.com/mjavascript/practical-modern-javascript/blob/master/ch07.asciidoc#sticky-matching-flag-y and realise this might introduce some subtle bugs). 
**[EDIT]** core-js tries to patch sticky Regex, but it seems very slow, and, as it stands, causes an infinite loop (see https://github.com/zloirock/core-js/issues/754)
**[EDIT 2]** It might be easier to handle the matching with a global regex or a simpler parser.

I've only got as far as a smoke test, so will update this with any other issues and work-arounds. I'll try to get a pull-request together, as I'd prefer not to have to maintain a fork.

**Comment by leeoniya** [comment]
> Polyfills for Object.assign and Point2D (currently using core-js and point2d-polyfill) - I consider this a reasonable requirement

`Object.assign` might be replaced before 1.0 by a custom deep-merge [1], since this would allow better handling of partial options.

> Transpilation - currently arrow functions are included in distribution code

not the es5 build: https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.iife.min.js

[1] https://github.com/leeoniya/uPlot/blob/master/src/utils.js#L189

**Comment by leeoniya** [comment]
i've switched the regex from `/yi` to `/gi`.

**Comment by x2764tech** [comment]
Amazing. Thanks. I'll test this today, but this all looks good.

**Comment by x2764tech** [comment]
Just to confirm, this is great. There is a problem with DPI settings, but it's more than usable for my situation.

**Comment by leeoniya** [comment]
> There is a problem with DPI setting

odd, since IE11 supports devicePixelRatio.

**Comment by leeoniya** [comment]
@x2764tech 

`Object.assign` has been removed.

however, this doesn't mean uPlot has ie11 support. since ie11 does not support the Intl `timeZone` option [1], any date/time features will always use the browser's local timezone. not sure if that's a dealbreaker in your case, but i expect it would be for many.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

**Comment by x2764tech** [comment]
Thanks for the update - the lack of timezone support information isn't an issue for me at the moment - most end users are in the UK (which is UTC 1/2 the year), and are used to seeing a graph in UTC time. 

Thanks again for the great work

**Comment by gMakaan** [comment]
Also ie11 has no arrow functions and spread operator support, but uPlot `src` can be recompiled with [babel](https://babeljs.io) for legacy browsers

**Comment by leeoniya** [comment]
/dist already has an es5 iife build
