### ISSUE TITLE
Is there a "beginAtZero" option like in ChartJs?

### ISSUE THREAD

**Issue by Apollo3zehn** [leeoniya/uPlot#143]
Hi, thanks for you great library! Its fast and produces pretty graphs.

I try to plot different time series where I don't know the min/max values in advance. But I would like to always include the zero crossing in the plot (like ChartJs's option 'beginAtZero'). I worked around this by modifying your [code](https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.iife.js#L1251-L1252) to ensure that 0 is always included:
```
sc.min = min(0, s.min = minMax$1[0]);
sc.max = max(0, s.max = minMax$1[1]);
```

Is there an alternative to achieve this without modifying the source? I tried to set the opt.scales property to ```min = 0``` but this throws an error because ```max``` is undefined.

**Comment by leeoniya** [comment]
you should be able to manually expand the range of the y scale with the same logic as above, similar to #142:

```js
{
  scales: {
    y: {
      range: (u, min, max) => [
        Math.min(0, min),
        Math.max(0, max),
      ]
    }
  }
}
```

(on phone; untested)

**Comment by leeoniya** [comment]
actually, the above answer is incomplete. `range` takes the raw data min/max, but for y scales, uPlot adds extra padding. this logic is exposed as a static util function `uPlot.rangeNum()`: https://github.com/leeoniya/uPlot/blob/45405648e64330b6aa7e33569ad301461225c48d/src/utils.js#L55

you'll want to run the raw min/max through this to replicate the native padding logic, and then apply the range expansion:

```js
{
  scales: {
    y: {
      range: (u, dataMin, dataMax) => {
        let [min, max] = uPlot.rangeNum(dataMin, dataMax, true);
        return [
          Math.min(0, min),
          Math.max(0, max),
        ];
      }
    }
  }
}
```

**Comment by Apollo3zehn** [comment]
Thanks, this works perfectly. I have another problem with the y-ticks but I will create a separate issue for that.
