### ISSUE TITLE
y-ticks on canvas are drawn outside the canvas

### ISSUE THREAD

**Issue by Apollo3zehn** [leeoniya/uPlot#144]
I have a problem with single and multiple y-axis that the ticks of the left-most axis are not drawn properly within the canvas:

![grafik](https://user-images.githubusercontent.com/20972129/76026712-9d934f00-5f2f-11ea-8d28-c0dad597a070.png)

I tracked down the issue to [this](https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.iife.js#L1704) line. When the text alignment is "LEFT", the text may not be drawn anymore within the canvas, even with positive x-coordinates. Maybe this is a non-issue, because I don't know how the width of a scale is determined. Is this a fixed value or dynamically calculated depending on the actual tick label width?

My ticks are generated like this:
```js
values: (self, ticks) => ticks.map(rawValue => rawValue.toPrecision(3) + " " + unit)
```

**Comment by leeoniya** [comment]
there is no axes auto-sizing in uPlot. all axes dims are static. in this case the defaults are too small.

play around with `axis.size`.
