### ISSUE TITLE
How can I remove markers from my plot?

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#151]
![image](https://user-images.githubusercontent.com/1218608/76646849-f0b16700-6518-11ea-8b8c-0eacd44f25cb.png)

I'm drawing the markers myself and would like to get rid of the white marker circles drawn by uplot. How do I do this? Maybe I'm blind but I didn't see this in the docs.

**Comment by leeoniya** [comment]
`series.points.show: false`, though you might prefer to tweak the style of the ones uPlot provides, unless you're doing something really custom.

```js
series.points: {
  show,
  size,
  width,
  stroke,
  fill,
}
```

show can also be a function which draws your custom points if you need more tweaking options than those provided above - the draw-hooks demo does this:

https://github.com/leeoniya/uPlot/blob/dd4d7812860f63bcb787d3653b3a0994c0437b6f/demos/draw-hooks.html#L171-L175

**Comment by leeoniya** [comment]
the default impl of `show` is a function which returns `true` or `false` to render points conditionally, based on available space:

https://github.com/leeoniya/uPlot/blob/master/src/opts.js#L279-L297

**Comment by danyalejandro** [comment]
Works perfect, thank you.

Yes, I thought about using the hook, but I'm rendering markers using different data from the series I'm drawing with uplot, and I'm also drawing other elements. Besides, I don't want to couple uplot with data it shouldn't really be aware of.
