### ISSUE TITLE
Change the properties of the cursor

### ISSUE THREAD

**Issue by Karim-Elshal** [leeoniya/uPlot#154]
How can I change x, y properties after running the chart?
Unfortunately, this plugin does not work with me

```js
function changeCursor()
{

    return {
        hooks: {
            ready: u => {
                let plot = u.root.querySelector(".over");
                $(plot).hover(
                () => {                 
                    u.setCursor({x: false, y: true});      // mouse enter
                },
                () => {                 
                    u.setCursor({x: false, y: false});     // mouse leave
                });
            }
        }
    };
}
```

**Comment by leeoniya** [comment]
hey @Karim-Elshal 

how should this be different than just initializing with `cursor: {x: false}`?

https://jsfiddle.net/yLg4f3zb/

`cursor.x` and `cursor.y` cannot be changed after initialization. these properties are used to determine what dom should be created and updated. if you need to update the visibility after init, you can modify `style.display` of `.cursor-x` or `.cursor-y`:

https://jsfiddle.net/cm1o6h4z/

if you want to make a plugin which adjusts the default options, you can override `opts.cursor` in the `plugin.opts` callback:

```js
return {
  opts: (u, opts) => {
    uPlot.assign(opts, {
      cursor: {x: false},
    })
  },
  hooks: {...}
}
```

**Comment by Karim-Elshal** [comment]
Thanks so much, leeoniya
It is working now as I need  :)

I wonder, is there an explanation of how to control the date format on the x-axis?
As it changes automatically after making the zoom.
I need to make multiple formats, a different format for each one.

**Comment by leeoniya** [comment]
the easiest way is to define your own `axis.values` array:

https://github.com/leeoniya/uPlot/tree/master/docs#axis--grid-opts

the default array looks like this:

https://github.com/leeoniya/uPlot/blob/master/src/opts.js#L138-L151
