### ISSUE TITLE
Add margins to plot

### ISSUE THREAD

**Issue by CrashLaker** [leeoniya/uPlot#156]
Hi all,

Probably I missed it but how can I add margins to the plot to avoid the labels from being cut off?

![image](https://user-images.githubusercontent.com/4432491/76803326-50796d80-67b8-11ea-838c-e00efcd56341.png)

Regards,
C.

**Comment by leeoniya** [comment]
increase `axis.size`

**Comment by CrashLaker** [comment]
It worked. Thank you @leeoniya  :)

Also appending this doc for future reference  
 https://github.com/leeoniya/uPlot/tree/master/docs#axis--grid-opts
