### ISSUE TITLE
sigplot impl

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#161]
this looks neat: https://github.com/LGSInnovations/sigplot

seems to also use 2d context (not webgl). minified size is 274 KB.

cc @mrecachinas ;)

EDIT: some more: https://github.com/naver/billboard.js/wiki/Comparison-table

**Comment by mrecachinas** [comment]
Hi @leeoniya 👋 -- Let @maihde and I know if you have any questions regarding SigPlot. We have a benchmark script under https://github.com/LGSInnovations/sigplot/tree/master/benchmark that you can feel free to play around with.

BTW -- cool library! :)
