### ISSUE TITLE
Canvas plots can become blank on page refresh (mobile)

### ISSUE THREAD

**Issue by danekasper** [leeoniya/uPlot#163]
Plot canvas' can become blank when many are shown on screen and page is refreshed (on mobile device).  

Testing with Safari and Chrome on iOS13.3 iphoneSE. Typically initial page load renders most of the plots. Any subsequent refreshes and plots can start to show as blank. You can can still click on the canvas and it will provide value and draw cross-hairs.

It only starts happening after passing ~40 canvas. I suspect it might be a memory issue / outside of uPlot's domain, but not sure why it would show some of the time, but not others. At some point no plots will show at all until loading a new tab. 

Any thoughts on having lots of plots on one page? 

Was happening on [https://danekasper.github.io/viz/covid](https://danekasper.github.io/viz/covid),  plots were fine when there were a few countries, now there are ~170 plots. Same behavior is seen using the simple plotting below. Didn't seem to make a difference with how many datapoints in each chart.  
```
for (var i=0; i<60; i++) {
      makeChart('Chart ' + i);
    }

  function makeChart(title_ = 'test') {
      var loop = 1e1;

      let data = [
        Array(loop),
        Array(loop),
      ];

      for (var i = 0; i < loop; i++) {
        let x = 2 * Math.PI * i / loop;
        let y = Math.sin(x);

        data[0][i] = x;
        data[1][i] = y;
      }

      const opts = {
        title: title_,
        width: 500, 
        height: 250,
        scales: {
          x: {
            time: false,
          },
          y: {
            auto: false,
            range: [-1.5, 1.5],
          },
        },
        series: [
          {
            label: "x",
          },
          {
            label: "sin(x)",
            stroke: "red",
          }
        ],
      };

      let u = new uPlot(opts, data, document.body);
    }
```

example: cross-hair and values still rendered
![IMG_1438](https://user-images.githubusercontent.com/5305693/77505584-b13f2f00-6eb7-11ea-8658-b911f9bf9370.PNG)

**Comment by leeoniya** [comment]
> I suspect it might be a memory issue / outside of uPlot's domain

this is almost certainly the issue. more specifically, you run into GPU memory limits when trying to allocate many and/or huge canvases. i've had wonkiness issues like this on integrated gpus, too. im not surprised an iphone se bumps into limits.

i'd recommend some combo of pagination, lazy loading/unloading and/or png-ifing the canvases.

@danyalejandro also renders hundreds of plots per pg, i wonder if he's run into this too.
