### ISSUE TITLE
Ability to set custom month names

### ISSUE THREAD

**Issue by rlz** [leeoniya/uPlot#166]
I'm using uPlot for my project with Russian localization. First of all, thank you for the great project! One problem though. To render months name I have to copy/paste your format function and just change names of months. It will be nice if it can be done easier, e. g. provide them via plot opts. Also, note that in Russian short versions are not always 3 letters, but 3 and 4 depending on the month, so it needs to be 2 options one for full names and the second for the short versions.

**Comment by leeoniya** [comment]
@rlz i've added this in da9df64.

demo/usage: https://leeoniya.github.io/uPlot/demos/months-ru.html

**Comment by leeoniya** [comment]
closing as resolved, let me know if you have further concerns.
