### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by MehrdadKhnzd** [leeoniya/uPlot#170]
Is your library supports vertical zooming? Or can you add this feature easily? Or how can I proceed if I want to implement it myself and make a PR?

**Comment by leeoniya** [comment]
try `cursor.drag.y: true`.

**Comment by MehrdadKhnzd** [comment]
Special thanks, it works like a charm!

**Comment by MehrdadKhnzd** [comment]
Hello again! I decided to reopen this so I don't have to add new issues for my other questions.
How can I get data from the current mouse position? I mean the ones that you're showing on the bottom of the chart yourself. I want to show them manually in other places.

**Comment by leeoniya** [comment]
> I decided to reopen this so I don't have to add new issues for my other questions.

i'd actually prefer that you open new issues. that way the questions & answers are easy to point to later without unrelated topics in the discussion.

`self.cursor.idx` points to the current index in the data.

**Comment by MehrdadKhnzd** [comment]
Thanks for the quick answer! Ok then, I'm gonna open new issues for my new questions! :D
But now for this question, how can I prevent the showing of the bottom labels?

**Comment by MehrdadKhnzd** [comment]
Thanks again! One last question in this section before I open other issues! :D
How can I show/hide the lines of the graph like the action that I can do with the legends of it? It seems that it's related to the `series.show` property but I don't know how to modify it properly without re-rendering the whole graph.

**Comment by leeoniya** [comment]
`.setSeries(0, {show: false})`

**Comment by MehrdadKhnzd** [comment]
I have already tried this, but it gives me this error:
`
TypeError: Cannot read property 'style' of undefined
`

**Comment by leeoniya** [comment]
can you create a jsfiddle or provide code that i can run which triggers the essiue?

**Comment by leeoniya** [comment]
sorry, i meant `.setSeries(1, {show: false})`, since series[0] are x values and cannot be toggled on/off. not sure if that eas causing the issue.

**Comment by MehrdadKhnzd** [comment]
Yeah, the index was the problem. Thanks again, now it works fine!
