### ISSUE TITLE
box plots

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#179]
surely if we can draw candlesticks and bars:

https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html
https://leeoniya.github.io/uPlot/demos/multi-bars.html

we can re-use the majority of the code for box plots:

https://luwes.github.io/sinuous/bench/results/

this page uses the fastest js framework to draw the slowest plots (via plotly). a meager 17 plots with almost no data takes an absurd ~1500ms. to add insult to injury, it loads a [3.17MB plotly lib]( https://cdn.plot.ly/plotly-latest.min.js). sheesh!

![image](https://user-images.githubusercontent.com/43234/79643813-6210b500-816a-11ea-8510-79e53e8ccb6e.png)

final destination here will probably include the ability to do grouped box plots like the bars demo. e.g.

![image](https://user-images.githubusercontent.com/43234/79794311-a7261a00-8317-11ea-8728-1820c490c877.png)

cc @ldstein @luwes

**Comment by luwes** [comment]
this would be awesome! let me know when it's in and I'll replace it right away 👍

**Comment by leeoniya** [comment]
@luwes if you'd like a change of pace from your DOM universe, perhaps you'd like to contribute this?

it should be really straightforward to tweak the 84 lines of candlestick code to make this happen:

https://github.com/leeoniya/uPlot/blob/1ef39ef1899bacb5a3ae7209cfd0f2600d9590e3/demos/candlestick-ohlc.html#L130-L214

if you're interested in working on this, i'll prioritize #180 :)

**Comment by leeoniya** [comment]
the bar demo might be another good starting point: https://leeoniya.github.io/uPlot/demos/multi-bars.html

**Comment by luwes** [comment]
at the moment I'm working on a commercial project which will take up most of my free time but I'll keep it in mind when I work on the benchmark graphs again 👍

**Comment by leeoniya** [comment]
i was too curious, so i worked on this today.

i adapted the OHLC demo and initial results are promising, to say the least:

- loading & parsing `results.json`
- computing all stats
- plotting all 17 metrics charts
- with all 155 frameworks on each chart

plotly:

- 4757ms
- mem: 73.5MB peak, 73.5MB final

![image](https://user-images.githubusercontent.com/43234/79706937-7d6de400-8280-11ea-99c2-0ed69f643fe0.png)

uPlot:

- 246ms (js + rendering + system)
- mem: 4.5MB peak, 2.3MB final

![image](https://user-images.githubusercontent.com/43234/79706999-a42c1a80-8280-11ea-9c88-0f928e69a19a.png)

**Comment by luwes** [comment]
wow! this is looking good, small difference 😅

**Comment by leeoniya** [comment]
turns out i made a mistake...in plotly's favor :D. uPlot was rendering all 155 frameworks (both keyed and non-keyed), while plotly was only rendering keyed (37% fewer). i updated to render just the top 30 keyed and the new stats are:

- 140ms (js + rendering + system)
- mem: 3.4MB peak, 2.1MB final

i expect this to go up a bit once i add 30 framework toggles to the dom of each chart, but i think it'll stay well within 200ms.

**Comment by leeoniya** [comment]
this is done: https://leeoniya.github.io/uPlot/demos/box-whisker.html
