### ISSUE TITLE
Scale Options

### ISSUE THREAD

**Issue by stuck1233333** [leeoniya/uPlot#18]
What are the different options we can use for scale (%, mb are provided in the example). What are the rest?

**Comment by leeoniya** [comment]
scales are just string keys. they have no implicit meaning. they're just a way to group different series onto the same scale.

the actual work is done via `incrs` and `values` options:

https://github.com/leeoniya/uPlot/blob/master/src/opts.js#L59-L60

**Comment by leeoniya** [comment]
this will be properly documented in the near future.
