### ISSUE TITLE
Set Series Stroke After Initialization

### ISSUE THREAD

**Issue by MehrdadKhnzd** [leeoniya/uPlot#182]
How to properly change series stroke color after initialization?

**Comment by leeoniya** [comment]
there's no official api to do this because i don't think it's a common requirement (unless you can convince me otherwise), but you can get it done with something like:

```js
u.series[1].stroke = "blue";
u.redraw();
u.root.querySelector(".series:nth-child(2) .ident").style.borderColor = "blue";
```

demo: https://jsfiddle.net/hzf0a83q/1/

**Comment by MehrdadKhnzd** [comment]
I have a dynamic graph where people can customize the graph as they like, including axes and series colors. I don't know if it's convincing or not. :D
By the way thanks for your response!

**Comment by leeoniya** [comment]
> I have a dynamic graph where people can customize the graph as they like, including axes and series colors.

i assume this happens once during setup and not during normal plot usage. even in this case, it would be cheap and easy to destroy and recreate the chart on any config changes to get a preview. the provided "solution" is then just an optimization which can make this a tiny bit better. :)

**Comment by MehrdadKhnzd** [comment]
Yes, there's always the way of destroying and recreating, I asked this to see if a better solution exists. Thanks!

**Comment by olivren** [comment]
The workaround is not working anymore, certainly due to a change in the internal representation of the plot.

I found another way to achieve the same goal: you can delete a series with `delSeries` and add it again with `addSeries` with a different color in the options.

https://jsfiddle.net/t549gy02/2/
