### ISSUE TITLE
fix lightweight-charts bench

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#185]
it looks like the full time range is not being shown here:

https://leeoniya.github.io/uPlot/bench/lightweight-charts.html

@timocov am i setting this correctly?

https://github.com/leeoniya/uPlot/blob/193085438300389ff28bc479fc275875168b9c6d/bench/lightweight-charts.html#L63-L66

**Comment by timocov** [comment]
Yes, we have limitation for minimal bar spacing, thus we can't show more than 1 bar per 1 pixel.

**Comment by timocov** [comment]
See https://github.com/tradingview/lightweight-charts/issues/251

**Comment by leeoniya** [comment]
thanks for the update.

i should probably drop it from the bench results then?

you guys still seem to process all the data (probably for panning). when i trim the data to the 1920px chart width i get 144/2/4/78 for initial render.

**Comment by leeoniya** [comment]
i've removed it from the perf table & chart for now, but will keep the demo code in case anyone asks or if the situation ever changes (let me know!).
