### ISSUE TITLE
timeline plots

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#188]
should be pretty easy:

![image](https://user-images.githubusercontent.com/43234/80637713-117c4000-8a25-11ea-9410-65bf9d4376cd.png)

![image](https://user-images.githubusercontent.com/43234/80644987-24484200-8a30-11ea-9f67-cff045720a79.png)

**Comment by leeoniya** [comment]
related: gantt charts

![excel-gantt-chart-template-free](https://user-images.githubusercontent.com/43234/80892972-e0ee0d80-8c93-11ea-888d-74a4f8ecec0c.png)

**Comment by EmiPhil** [comment]
Where's the development of this plugin at? I'm thinking of getting a few more 

> should be pretty easy

jobs under my belt before going back to finish #216 but if you are like 90% done then I don't want to restart.

**Comment by leeoniya** [comment]
i've not started this, but let's talk through what makes sense to implement and what's too much. (gantt is probably a step too far.)

honestly, i'd prefer to address #184 first so we have some generic utilities that plugins can re-use, e.g. hz distribution of series datapoints, vt distribution of series as might be required here. another useful thing that vertical distribution can do is plot multiple line series with vertical offsets (imagine cpu history trendlines in a 64 core processor...if they all overlap it becomes impossible to read and the only alternative is multiple uplots, which is not great).

then we can built atop these to flesh out similar plugins instead of copy-paste-tweaking for each plugin. i already started to feel this when working on #179.

**Comment by CrashLaker** [comment]
Some other examples.

https://github.com/vasturiano/timelines-chart

![image](https://user-images.githubusercontent.com/4432491/106785560-8fc5dc80-665e-11eb-910a-ec2d9bb37c58.png)


https://webmaster444.github.io/d3/gantt_chart2/index.html

![image](https://user-images.githubusercontent.com/4432491/106785627-a5d39d00-665e-11eb-9452-3dfdc01a3ce8.png)

**Comment by leeoniya** [comment]
initial demo now here: https://leeoniya.github.io/uPlot/demos/timeline-discrete.html

**Comment by mariorl** [comment]
Hi, I'm playing with gantt plugin, is there a easy way to add trend lines to the same graph?

**Comment by leeoniya** [comment]
have example image or link?

**Comment by mariorl** [comment]
oh, is the same example you posted "initial demo now here: https://leeoniya.github.io/uPlot/demos/timeline-discrete.html", I translated the data to be ploted to server side but the result is the same, but for now my attempts for draw a single trend line not worked, may be the dataset sizes

**Comment by leeoniya** [comment]
yes, i meant an example of what you want. where do you want the trendline, i dont understand.
