### ISSUE TITLE
Rendering fails if a timeseries never changes value

### ISSUE THREAD

**Issue by dgl** [leeoniya/uPlot#19]
See http://dg.cx/uplot-nochange-timeseries.html (should see two graphs, only one works). But essentially `findIncr` returns nothing if the value in a series never changes.

[Thanks for writing this, looks ideal for writing a fast Prometheus frontend...]

**Comment by leeoniya** [comment]
right now there's an implicit assumption that the x-axis contains ascending unix timestamps. but that will be made more generic (simply numeric, ascending and unique) in the near future.

see https://github.com/leeoniya/uPlot/issues/2

**Comment by leeoniya** [comment]
also see https://github.com/leeoniya/uPlot/issues/9

**Comment by dgl** [comment]
urm, this is the y axis, sorry simplified too much in the example, same happens if they are real timestamps.

**Comment by leeoniya** [comment]
ah, sorry. you're right. dismissed this too fast. i'm having my coffee now.

**Comment by leeoniya** [comment]
i guess it would make sense to fall back to some minimum value for `valDelta`. e.g.

```js
let pxPerUnit = dim / (valDelta || 1);
```

**Comment by leeoniya** [comment]
ok, i think this is properly squashed. let me know if i missed something.

thanks for reporting!

**Comment by leeoniya** [comment]
heads up if you're testing, API has changed to provide data separately from the opts in https://github.com/leeoniya/uPlot/commit/b7827343121eb63f4e7512c4fd76a2edc53e3c78
