### ISSUE TITLE
Create a changelog page?

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#199]
Not sure how open you are to this, but even after version 1.x the project is very active, and the number of features has grown a lot. Maybe you could create some simple CHANGELOG.md or something similar so that people updating to the latest version of the plugin know what to watch out for?

**Comment by leeoniya** [comment]
> after version 1.x the project is very active, and the number of features has grown a lot

i would disagree with this statement. maybe the demos (non-core) have expanded a bit. the only major features were addSeries/delSeries. you might be thinking further back, since you've been on board since pre-1.0.

the changelog is here:

https://github.com/leeoniya/uPlot/releases

**Comment by danyalejandro** [comment]
thank you for the link!

**Comment by cdeutsch** [comment]
The releases page is better than nothing, but a summary in words of what changed would be awesome.

Currently you have to go through the source code and figure it out yourself. That's not really a CHANGELOG

**Comment by leeoniya** [comment]
yes, i will go back and update these soon. more details: https://github.com/leeoniya/uPlot/issues/388.

**Comment by ImLunaHey** [comment]
can this please be reopened? not seeing a changelog or any notes for most releases. 😞

**Comment by ImLunaHey** [comment]
@leeoniya also why wasn't version `1.6.24` a major since its a breaking change?
