### ISSUE TITLE
Export as jpeg/png

### ISSUE THREAD

**Issue by stuck1233333** [leeoniya/uPlot#20]
Can we export chart as jpeg/png?

**Comment by leeoniya** [comment]
the grid & trendlines are drawn on canvas, so those are easy to export. but the cursor, hover points, legend and axis labels are dom-based. i'm considering moving the axis labels to canvas in #16, but there are big trade-offs (like everything you can style with CSS for free becomes impossible with canvas unless i add a bunch more code to at least offer some very basics). i'm still on the fence whether or not the trade-offs are worth it. initially i will be optimizing the label rendering but still keeping it dom-based.

**Comment by leeoniya** [comment]
i don't think that generating static charts is going to be something uPlot will focus on. there are plenty of good and fast server-side solutions for this case. if someone really needs to grab the chart after it's rendered they'll just have to make do with a screenshot.

**Comment by idcrook** [comment]
I was just about to file a :question: issue asking about saving as an image, including plot's axes labels and legend, etc. after having searched for a related issue with no results. then, as I was typing up the new issue, this one popped up in related issues suggestions.

My exact question was already answered above, so I will just add additional phrasings for related tasks.

Just to reiterate the resolution of this same question, other libraries should be considered for:
 - static images of plots or charts
 - saving image downloads of plot or chart programmatically
 - saving charts with the labels, legend, and title, etc. as a static image
 - capturing "printable" images/.png for printing or sharing

thanks for this library.

**Comment by Christian-Sander** [comment]
For future reference, using [html2canvas ](https://github.com/niklasvh/html2canvas) could be an option. It works for my application, but it increases the binary size of the page by ~45 kB.

**Comment by leeoniya** [comment]
the way to do it is like this: https://leeoniya.github.io/uPlot/demos/svg-image.html

**Comment by Christian-Sander** [comment]
That is quite interesting!

I managed to adapt it to make it download the image, however, I have not managed to correctly save it as a png image yet in Edge. Firefox works as expected.

There is an issue accessing the canvas once the img element has been drawn to it because it becomes tainted and CORS does not allow calling toDataURL().

`DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

I'm somewhat confused by this, as all data comes from the same domain? Do I need to adjust the headers sent by the server to allow this? I don't see any preflight requests to the server. The image is rendering correctly to the webpage.
I have tried setting img.crossOrigin="Anonymous" as mentioned in many places without success.

If I call toDataURL() before the img.onload handler is called, the saved image will miss the elements from the SVG image.

Here's the extract of the code I'm using:
```
let img = new Image();
// img.crossOrigin = "anonymous";
let blob = new Blob([svgText], {type: 'image/svg+xml;charset=utf-8'});
let url = DOMURL.createObjectURL(blob);

img.onload = () => {
    ctx.fillStyle = "white";
    ctx.fillRect(0, 0, can.width, can.height);
    ctx.drawImage(img, 0, 0);
    ctx.drawImage(uplot.ctx.canvas, 0, (rect2.top - rect.top) * pxRatio);
    DOMURL.revokeObjectURL(url);
    var a = document.createElement('a');
    a.href = can.toDataURL();
    a.download = title + ".png";
    a.click();
};

img.src = url;
```

Any ideas?

**Comment by Christian-Sander** [comment]
Possibly related: https://stackoverflow.com/questions/42263223/how-do-i-handle-cors-with-html2canvas-and-aws-s3-images

**Comment by Christian-Sander** [comment]
After some more searching I found that it is a Chrome bug together with a workaround: https://stackoverflow.com/questions/50824012/why-does-this-svg-holding-blob-url-taint-the-canvas-in-chrome

Here's my working implementation to render the chart to an image (including a white background) and then downloading it:
```
function downloadImage(){
    let pxRatio = devicePixelRatio;

    let rect = uplot.root.getBoundingClientRect();
    // rect of uPlot's canvas to get y shift due to title above it (if any)
    let rect2 = uplot.ctx.canvas.getBoundingClientRect();

    let htmlContent = uplot.root.outerHTML;

    //NOTE: Use correct index here to address uPlot stylesheet. Needs to be in a separate resource for this to work.
    let uPlotCssRules = document.styleSheets[1].cssRules;
    let cssContent = "";
    for (let { cssText } of uPlotCssRules)
        cssContent += `${cssText} `;

    let width = Math.ceil(rect.width * pxRatio);
    let height = Math.ceil(rect.height * pxRatio);

    let viewBox = `0 0 ${Math.ceil(rect.width)} ${Math.ceil(rect.height)}`;

    // An SVG image is used to draw the HTML elements to an img element and then to a canvas
    let svgText = `
        <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="${viewBox}">
            <style>
                body { margin: 0; padding: 0; }
                ${cssContent}
            </style>
            <foreignObject width="100%" height="100%">
                <body xmlns="http://www.w3.org/1999/xhtml">${htmlContent}</body>
            </foreignObject>
        </svg>
    `;

    let can = document.createElement('canvas');
    let ctx = can.getContext('2d');
    can.width = width;
    can.height = height;
    can.style.width = Math.ceil(rect.width) + "px";
    can.style.height = Math.ceil(rect.height) + "px";
    let img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
        /* Once the SVG image is loaded in the img element,
            * we can start drawing on the canvas and download the file afterwards */
        ctx.fillStyle = "white";
        ctx.fillRect(0, 0, can.width, can.height);
        ctx.drawImage(img, 0, 0);
        ctx.drawImage(uplot.ctx.canvas, 0, (rect2.top - rect.top) * pxRatio);
        var a = document.createElement('a');
        a.href = can.toDataURL();
        a.download = title + ".png";
        a.click();
    };

    let blob = new Blob([svgText], {type: 'image/svg+xml;charset=utf-8'});
    
    /* Using blob.toDataURL() taints the img element due to a bug in Chrome, see
        * https://stackoverflow.com/questions/50824012/why-does-this-svg-holding-blob-url-taint-the-canvas-in-chrome 
        * The workaround here converts the blob to a DataURL which avoids the bug. */
    var reader = new FileReader();
    reader.readAsDataURL(blob);
    reader.onload = function(e) {
        img.src = e.target.result;
    }
}
```

**Comment by leeoniya** [comment]
> After some more searching I found that it is a Chrome bug together with a workaround:

interesting. i wonder why the workaround is still needed in Sep 2022; that bug was fixed in Jan 2019 🤔

**Comment by Christian-Sander** [comment]
Honestly, no idea, I haven't looked deeper into that bug. I can only confirm that this workaround fixed the issue I was seeing.

**Comment by alextrastero** [comment]
Hey, posting this here as maybe someone ran into this issue or knows of a possible solution.

On a click of a button I render a new chart into a container and export it. Different users with different devicePixelRatio's get different blurred results of the chart.

This is an example of an exported chart when zoomed out (top text is created by me, bottom values is chart):

![Image](https://github.com/user-attachments/assets/be2669df-35e9-4a30-a9bc-e627b182f1db)

zoomed in:

![Image](https://github.com/user-attachments/assets/e9665042-281e-470b-98e2-110b5a2af8ef)

Is there any way to redraw the chart with a specific DPR? or some other solution

**Comment by leeoniya** [comment]
there's currently no way to do this.

uPlot hooks up a `matchMedia` query to detect browser zoom level changes and dispatches a custom `dppxchange` evenf on `window`. all uPlot instances listen to this event and grab the global `devicePixelRatio` before redrawing.

https://github.com/leeoniya/uPlot/blob/472232aff08a931d777b38456d9d417c937d0504/src/dom.js#L33
https://github.com/leeoniya/uPlot/blob/472232aff08a931d777b38456d9d417c937d0504/src/uPlot.js#L213
https://github.com/leeoniya/uPlot/blob/472232aff08a931d777b38456d9d417c937d0504/src/uPlot.js#L3349-L3352

**Comment by leeoniya** [comment]
i've added per-instance `pxRatio` control in https://github.com/leeoniya/uPlot/commit/58a67b2c61e02533d98eecd4882e4eb5229575b9

it wasn't a tiny change, so it will be a couple months before it's tested well enough to make it into the next release. until then please test it out and let me know how it works for you.

you can either grab the files from `/dist` or update your `package.json` to

```
"uplot": "leeoniya/uPlot#58a67b2c61e02533d98eecd4882e4eb5229575b9"
```

![Image](https://github.com/user-attachments/assets/8526af5a-5c91-40ba-978a-dbeb3607fc13)

**Comment by alextrastero** [comment]
Amazing! Thank you so much.

Just with a clean install I got the following error

```
  if (u.legend.values) {
    const withTime = [Resolution.HOUR, Resolution.TEN_MINUTES].includes(resolution);
    caption = dateTimeHumanizeUtc(`${u.legend.values[0]._}`, withTime); // Cannot read properties of undefined (reading '_')
  } else {
    caption = '';
  }
```

**Comment by alextrastero** [comment]
Sorry, that's not your code... my bad

**Comment by alextrastero** [comment]
Results are perfect so far

![Image](https://github.com/user-attachments/assets/034ab723-3cd2-40cd-aa94-5733a0f19cc7)

**Comment by alextrastero** [comment]
Hiya @leeoniya - we're now using version 1.6.32 since we needed recent changes/fixes. But the opts.pxRatio issue mentioned is still present.

It's currently not possible to override pixel ratio per instance for an offscreen export canvas.

You mentioned above that it might take some time... would you consider releasing this?

**Comment by alextrastero** [comment]
ping @leeoniya this is really bugging us, I can give it a go if you want??

**Comment by leeoniya** [comment]
this works on current master: https://leeoniya.github.io/uPlot/demos/issues/issue-20-export-pxratio.html

new 1.7.0 release coming in a few weeks.
