### ISSUE TITLE
an example of candlestick from websocket or csv (tick data)

### ISSUE THREAD

**Issue by pannet1** [leeoniya/uPlot#201]
can you please post an example of candlestick from csv (tick data). i have tried 2 libraries in python and they are terribly slow.

**Comment by leeoniya** [comment]
please attach the csv

**Comment by pannet1** [comment]
attached.

realized late that you do python as well. so for academic interest the libs i used were matplotlib and bokeh. essentially, i am consuming ask/bid from websocket, writing it to csv and reading back as OHLC dfs.

[BHARATFORG-EQ.csv.zip](https://github.com/leeoniya/uPlot/files/4594823/BHARATFORG-EQ.csv.zip)


> please attach the csv

**Comment by leeoniya** [comment]
> realized late that you do python as well.

i do not. not sure where you got this from since i have exactly 0 python repos :D

> so for academic interest the libs i used were matplotlib and bokeh. essentially, i am consuming ask/bid from websocket, writing it to csv and reading back as OHLC dfs.

as for the data format, you might consider preparing the data by parsing the datetime strings into unix timestamps and and packing everything into a space-efficient format like JSONH [1]. this way you don't need to send it all and then parse the csv on the client (e.g. with PapaParse [2]).

a candlestick or box plot requires 4 values, your csv contains 2 values with unlabeled columns. i don't know what to do with this.

![image](https://user-images.githubusercontent.com/43234/81328673-eae08980-9062-11ea-9e74-407e2bfaa8c7.png)

[1] https://github.com/WebReflection/JSONH
[2] https://www.papaparse.com/

**Comment by pannet1** [comment]
thanks. sorry, somehow i overlooked the python thingy.
i get what you are saying. just a recap for you. i need to:

- get incoming price instrument name, price feed from websocket from broker api
- convert it into JSONH
- animate the candlestick chart from first row of the series.

one problem though, what happens in case of disconnection from the broker api. will i loose the data and have to start again from the current one (a sort of browser refresh)

i dont get it in a convenient csv format online. so presently i am doing this.

- subscribe to websocket and read the streaming data
- store the instrument, time, buy_price, sell_price (like the csv i sent you earlier).
- read the csv and create the OHLC data from the csv (time/price)

OHLC data points are derived from the csv i sent you. for example for 5 min candlestick, i have a open, close, a highest and lowest price in that time frame.

**Comment by leeoniya** [comment]
i have this mostly working, but i need to refactor the plugin a bit to accommodate an x scale that isn't `distr: 2`, which the plugin code currently assumes.

**Comment by leeoniya** [comment]
ok, here's what i got.

your original is `BHARATFORG-EQ.csv` was 3.38MB. my `BHARATFORG.json` with timestamps is 1.89MB and looks like below. it's CSV-like, so should be almost as easy to append to:

```js
[
1588861240353,288.00,288.30,
1588861241228,288.05,288.40,
1588861242515,288.10,288.40,
1588861243919,288.05,288.40,
1588861245332,288.05,288.30,
1588861246712,288.15,288.35,
1588861248197,288.05,288.25,
1588861249526,288.05,288.25,
...
]
```

the parsing, adapting and aggregation looks like this, with the final `askData` being in the proper format for the updated [candlestick-ohlc demo](https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html).


```js
function aggregate(data2, idx, period) {
    let data3 = [
        [],        // ts
        [],        // o
        [],        // h
        [],        // l
        [],        // c
    ];

    let ts = 0;
    let o, h, l, c;

    function push() {
        data3[0].push(Math.round(ts / 1000));
        data3[1].push(o);
        data3[2].push(h);
        data3[3].push(l);
        data3[4].push(c);
    }

    for (let i = 0; i < data2[0].length; i++) {
        let its = data2[0][i];

        if (its >= ts + period) {
            if (i > 0)
                push();

            // re-init
            ts = its;
            o = data2[idx][i];

            h = data2[idx][i];
            l = data2[idx][i];
            c = data2[idx][i];
        }
        else {
            h = Math.max(h, data2[idx][i]);
            l = Math.min(l, data2[idx][i]);
            c = data2[idx][i];
        }
    }

    push();

    return data3;
}

fetch("BHARATFORG.json").then(r => r.json()).then(data => {
    let numCols = 3;
    let numRows = data.length / numCols;

    let data2 = [
        Array(numRows),        // ts
        Array(numRows),        // ask
        Array(numRows),        // bid
    ];

    for (let i = 0, j = 0; i < data.length; i += numCols, j++) {
        data2[0][j] = data[i];
        data2[1][j] = data[i+1];
        data2[2][j] = data[i+2];
    }

    let period = 5 * 60 * 1000;
    let askData = aggregate(data2, 1, period);
});
```

the changes to the ohlc demo would look like this:

```js
// (askData)
const data = [
    [1588861240,1588861542,1588861843,1588862143,1588862443,1588862743,1588863044,1588863344,1588863644,1588863944,1588864245,1588864546,1588864848,1588865148,1588865450,1588865751,1588866052,1588866352,1588866652,1588866953,1588867254,1588867554,1588867857,1588868157,1588868458,1588868759,1588869061,1588869361,1588869661,1588869962,1588870264,1588870564,1588870864,1588871167,1588871468,1588871768,1588872069,1588872370,1588872670,1588872970,1588873271,1588873572,1588873873,1588874174,1588874474,1588874775,1588875076,1588875377,1588875677,1588875978,1588876278,1588876580,1588876881,1588877182,1588877483,1588877783,1588878083,1588878383,1588878684,1588878984,1588879285,1588879585,1588879885],
    [288,290.1,289.85,290.75,289.05,290.8,290.7,288.75,289,286.2,286.5,286.75,287.15,287.55,287.4,285.9,284.75,284.15,285.7,284.25,285.2,284.35,285.1,284.55,284.55,284.25,283.85,283.5,283.2,283.85,283.45,284.6,284.9,284.45,284.35,284.65,284.55,284.4,284.25,284.35,285.85,285.6,285.9,286.05,285.35,284.75,284.8,284.45,285.55,285.8,285.25,285.65,284.6,284.65,284.65,285.4,285.6,285.05,285.15,284.6,284.6,284.15,284.45],
    [291.6,292.3,291.15,291.8,291.2,291.4,290.8,289.35,289.2,287.55,287.15,288.25,288,287.65,287.4,286.25,285.2,285.75,285.8,285.4,285.25,285.2,285.1,284.65,284.75,284.35,284.75,284.1,284.05,283.95,284.6,284.95,284.9,284.6,284.7,284.7,284.85,284.55,284.45,286.25,286,286.3,286.3,286.25,285.35,284.85,284.95,287.1,285.8,286.2,286.1,285.95,284.75,285.7,285.7,285.6,285.7,285.25,285.25,284.8,284.6,284.55,284.65],
    [288,289.55,289.6,288.5,288.75,290.45,288.5,288.75,286.2,286.2,285.35,286.75,287,287.2,285.65,284.55,284.05,284,284.15,284.25,284.3,284,284.1,284.05,284.2,282.65,283.5,283.15,283.05,283.2,283.4,284.25,284,284,284.35,284.3,284.3,284,284.25,284.35,285.5,285.6,285.9,285.15,284.6,284.6,284.45,283.7,284.8,285.1,284.2,284.3,283.3,284.4,284.6,285,285.05,284.6,284.6,284.5,284.1,284.1,284.35],
    [289.9,289.95,290.75,289.05,290.8,290.7,288.75,288.95,286.2,286.5,286.75,287.15,287.55,287.2,285.9,284.65,284.15,285.75,284.25,285.2,284.35,285.2,284.55,284.55,284.25,283.85,283.5,283.2,283.85,283.4,284.6,284.9,284.4,284.35,284.65,284.5,284.4,284.25,284.3,285.85,285.6,285.9,286,285.35,284.75,284.8,284.45,285.85,285.8,285.2,285.7,284.6,284.65,284.6,285.4,285.6,285.05,285.15,284.6,284.6,284.15,284.45,284.65]
];

// probably want to add more granularity to the tooltip display
const fmtDate = uPlot.fmtDate("{YYYY}-{MM}-{DD} {HH}:{mm}:{ss}");
```

and maybe remove `opts.scales.x.distr: 2` from the opts, for the x scale to be linear rather than uniform, which skips squashes time gaps like weekends.

**Comment by pannet1** [comment]
thank you so much. i am a Javascript novice. first i have to talk with broker API and get the data. this itself is herculean task. please give me few days, so that i will let you know the success failure.

note: i could generate my own UNIX timestamp because its real time data and hence no need to depend on the API. so timestamp is not a big deal breaker.

> ok, here's what i got.
> 
> your original is `BHARATFORG-EQ.csv` was 3.38MB. my `BHARATFORG.json` with timestamps is 1.89MB and looks like below. it's CSV-like, so should be almost as easy to append to:
> 
> ```js
> [
> 1588861240353,288.00,288.30,
> 1588861241228,288.05,288.40,
> 1588861242515,288.10,288.40,
> 1588861243919,288.05,288.40,
> 1588861245332,288.05,288.30,
> 1588861246712,288.15,288.35,
> 1588861248197,288.05,288.25,
> 1588861249526,288.05,288.25,
> ...
> ]
> ```
> 
> the parsing, adapting and aggregation looks like this, with the final `askData` being in the proper format for the updated [candlestick-ohlc demo](https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html).
> 
> ```js
> function aggregate(data2, idx, period) {
>     let data3 = [
>         [],        // ts
>         [],        // o
>         [],        // h
>         [],        // l
>         [],        // c
>     ];
> 
>     let ts = 0;
>     let o, h, l, c;
> 
>     function push() {
>         data3[0].push(Math.round(ts / 1000));
>         data3[1].push(o);
>         data3[2].push(h);
>         data3[3].push(l);
>         data3[4].push(c);
>     }
> 
>     for (let i = 0; i < data2[0].length; i++) {
>         let its = data2[0][i];
> 
>         if (its >= ts + period) {
>             if (i > 0)
>                 push();
> 
>             // re-init
>             ts = its;
>             o = data2[idx][i];
> 
>             h = data2[idx][i];
>             l = data2[idx][i];
>             c = data2[idx][i];
>         }
>         else {
>             h = Math.max(h, data2[idx][i]);
>             l = Math.min(l, data2[idx][i]);
>             c = data2[idx][i];
>         }
>     }
> 
>     push();
> 
>     return data3;
> }
> 
> fetch("BHARATFORG.json").then(r => r.json()).then(data => {
>     let numCols = 3;
>     let numRows = data.length / numCols;
> 
>     let data2 = [
>         Array(numRows),        // ts
>         Array(numRows),        // ask
>         Array(numRows),        // bid
>     ];
> 
>     for (let i = 0, j = 0; i < data.length; i += numCols, j++) {
>         data2[0][j] = data[i];
>         data2[1][j] = data[i+1];
>         data2[2][j] = data[i+2];
>     }
> 
>     let period = 5 * 60 * 1000;
>     let askData = aggregate(data2, 1, period);
> });
> ```
> 
> the changes to the ohlc demo would look like this:
> 
> ```js
> // (askData)
> const data = [
>     [1588861240,1588861542,1588861843,1588862143,1588862443,1588862743,1588863044,1588863344,1588863644,1588863944,1588864245,1588864546,1588864848,1588865148,1588865450,1588865751,1588866052,1588866352,1588866652,1588866953,1588867254,1588867554,1588867857,1588868157,1588868458,1588868759,1588869061,1588869361,1588869661,1588869962,1588870264,1588870564,1588870864,1588871167,1588871468,1588871768,1588872069,1588872370,1588872670,1588872970,1588873271,1588873572,1588873873,1588874174,1588874474,1588874775,1588875076,1588875377,1588875677,1588875978,1588876278,1588876580,1588876881,1588877182,1588877483,1588877783,1588878083,1588878383,1588878684,1588878984,1588879285,1588879585,1588879885],
>     [288,290.1,289.85,290.75,289.05,290.8,290.7,288.75,289,286.2,286.5,286.75,287.15,287.55,287.4,285.9,284.75,284.15,285.7,284.25,285.2,284.35,285.1,284.55,284.55,284.25,283.85,283.5,283.2,283.85,283.45,284.6,284.9,284.45,284.35,284.65,284.55,284.4,284.25,284.35,285.85,285.6,285.9,286.05,285.35,284.75,284.8,284.45,285.55,285.8,285.25,285.65,284.6,284.65,284.65,285.4,285.6,285.05,285.15,284.6,284.6,284.15,284.45],
>     [291.6,292.3,291.15,291.8,291.2,291.4,290.8,289.35,289.2,287.55,287.15,288.25,288,287.65,287.4,286.25,285.2,285.75,285.8,285.4,285.25,285.2,285.1,284.65,284.75,284.35,284.75,284.1,284.05,283.95,284.6,284.95,284.9,284.6,284.7,284.7,284.85,284.55,284.45,286.25,286,286.3,286.3,286.25,285.35,284.85,284.95,287.1,285.8,286.2,286.1,285.95,284.75,285.7,285.7,285.6,285.7,285.25,285.25,284.8,284.6,284.55,284.65],
>     [288,289.55,289.6,288.5,288.75,290.45,288.5,288.75,286.2,286.2,285.35,286.75,287,287.2,285.65,284.55,284.05,284,284.15,284.25,284.3,284,284.1,284.05,284.2,282.65,283.5,283.15,283.05,283.2,283.4,284.25,284,284,284.35,284.3,284.3,284,284.25,284.35,285.5,285.6,285.9,285.15,284.6,284.6,284.45,283.7,284.8,285.1,284.2,284.3,283.3,284.4,284.6,285,285.05,284.6,284.6,284.5,284.1,284.1,284.35],
>     [289.9,289.95,290.75,289.05,290.8,290.7,288.75,288.95,286.2,286.5,286.75,287.15,287.55,287.2,285.9,284.65,284.15,285.75,284.25,285.2,284.35,285.2,284.55,284.55,284.25,283.85,283.5,283.2,283.85,283.4,284.6,284.9,284.4,284.35,284.65,284.5,284.4,284.25,284.3,285.85,285.6,285.9,286,285.35,284.75,284.8,284.45,285.85,285.8,285.2,285.7,284.6,284.65,284.6,285.4,285.6,285.05,285.15,284.6,284.6,284.15,284.45,284.65]
> ];
> 
> // probably want to add more granularity to the tooltip display
> const fmtDate = uPlot.fmtDate("{YYYY}-{MM}-{DD} {HH}:{mm}:{ss}");
> ```
> 
> and maybe remove `opts.scales.x.distr: 2` to keep the x scale linear (rather than evenly-distributed), which squashes time gaps without data (like weekends). if you prefer to keep you data in CSV and with datetime strings, then i trust you can manage to adapt it as needed.

**Comment by leeoniya** [comment]
if you're more comfortable with python, then use python to do the aggregation and conversion from csv to json. make a route on your server like `/quotes/:symbol?period=5min` and then use python to read the csv, aggregate the data and return the final json in the format required by the ohlc chart code.

**Comment by leeoniya** [comment]
i'm gonna close this, but feel free to ask if any further clarification is needed.
