### ISSUE TITLE
Is there value in complementing setData with pushData?

### ISSUE THREAD

**Issue by noobymcnoob** [leeoniya/uPlot#207]
In my code, I have something like below to push/update data in real time. I believe this would be generally valuable and allow some optimization for uPlot (even though uPlot is fast enough in this case for me).

If you agree, perhaps a suggested interface could be `function pushData(row,dropOldData)`

Here is my code:

```
    _onPushData: function(row) {
        if (row.length == 0) return;
        var data = this.plot.data.slice(0);
        var ii;
        if(row[0] == data[0][data[0].length-1]) {
            // just update last row
            for(ii = 0; ii < row.length; ++ii) {
                data[ii][data[ii].length-1] = row[ii];
            }
        } else {
            // new row, get rid of old row
            for(ii = 0; ii < data.length; ++ii) {
                data[ii].shift();
            }
            for(ii = 0; ii < row.length; ++ ii) {
                data[ii].push(row[ii]);
            }
        }
        this.plot.setData(data,false);
        requestAnimationFrame(this._redrawFunc);
    },
```

**Comment by leeoniya** [comment]
there is definitely *some* value in an api like this, the question is, how much and how often? i had https://github.com/leeoniya/uPlot/issues/62 open for a while but decided that the exact conditions required to benefit from this api were too niche to justify the extra code.

how much data are you feeding?

**Comment by noobymcnoob** [comment]
Thanks for the code review! I'm not sure what would be the fastest way to do it (shift vs slice for example) but I see your sliding indices example uses slice so I will switch to that instead. Same idea. That being said, the most frequent operation is "updating the last point" between 30/60 times per second.

You are right to be wary in adding to uPlot's interface, the small surface area helps you keep things simple. Perhaps the example code is enough, I don't know. All I know is plotly does streaming data terribly and uPlot is beautiful so if there is something that helps you make it faster for streaming data, you may want to consider it.

**Comment by leeoniya** [comment]
candlesticks effectively act as accumulators, so if you need to only update the last one you can optimize by tracking the last candle's ohcl values and only call setData() when those values exceed the prior min/max limits. that should reduce the updates by a good amount i imagine.
