### ISSUE TITLE
Zoom interacting with plugins that use the draw hook

### ISSUE THREAD

**Issue by noobymcnoob** [leeoniya/uPlot#211]
Trying to integrate the wheel zoom plugin and I notice that when I've manually drawn stuff onto the canvas, it rightfully doesn't work under zoom because the paths are nowhere to be found. And if I "redraw" the whole plot, I get a comical stretching of the visualization.

I believed the right thing to do is to rewrite the candlestick plugin to use [Series.paths](https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.esm.d.ts#L307) function instead so i tried this but I have the same problem which is confusing:

https://plnkr.co/edit/ZqgCeERiF3OHkalr

If you try zooming in on the test case above, the paths disappear. If you modify the code so that you force a redraw after setScale in the wheel-zoom plugin, then the zoom isn't as nice.

Am I way off base here? What should I be doing instead? Why do the paths disappear?

Thanks.

**Comment by noobymcnoob** [comment]
Looks like the reason is that when time:true for a series, there is some bug which I don't understand.

At least that fixes the zoom problem once I use paths!

**Comment by noobymcnoob** [comment]
Not sure if you want to fix whatever issue is happening, so I'm leaving the issue open.

If you uncomment the // time: false call in `makeChart.js` from the plunkr, you can see that zoom works but if you comment it back out, the zoom has a bug to do with this line:

`var stamp = s[2] == 7 && diffYear || s[2] == 4 && diffDate || s[2] == 2 && diffMinu ? s[3] : s[1];`

Because apparently 's' is undefined.

**Comment by leeoniya** [comment]
perhaps you're hitting this? https://github.com/leeoniya/uPlot/issues/195

though i'm not sure why `time` would have any effect on this...

**Comment by noobymcnoob** [comment]
It could be that but I'm happy with the workaround for now anyway. Feel
free to close if you like!

**Comment by leeoniya** [comment]
`setScale` expects indices rather than scale values for min/max when `distr: 2` (uniform spacing). the internal drag zoom accounted for this (below) but the wheel-zoom plugin did not. try the updated wheel-zoom code.

https://github.com/leeoniya/uPlot/blob/66bf60de10c632188679478e9d7554cddaef2189/src/uPlot.js#L1731-L1740

**Comment by leeoniya** [comment]
> `setScale` expects indices rather than scale values for min/max when distr: 2 (uniform spacing).

eh, this is a surprising API. i should really fix this in the core.

**Comment by leeoniya** [comment]
so, this part of the API is fixed by b5fefa47977e79dd513009008e0ef62fc51411a3.

however, that's not the end of the story. i've opened #212 to track the rest.
