### ISSUE TITLE
How to change font style of labels on the left and bottom axis.

### ISSUE THREAD

**Issue by hunble** [leeoniya/uPlot#214]
How can we change the color of the text in canvas? No Class associated.

**Comment by leeoniya** [comment]
`axis.stroke` is font color

`axis.font` is font size, font-weight, font-style and font-family:
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font

https://leeoniya.github.io/uPlot/demos/axis-control.html
