### ISSUE TITLE
Create blank empty plot

### ISSUE THREAD

**Issue by jasonatball** [leeoniya/uPlot#217]
What's the best way to create a blank empty plot ready to call addSeries on? When I try to construct with an empty data array I get "Cannot read property '-1' of undefined". My use case is as a real-time graphing tool where users can add items to graph so I'd like to start out with a "blank" canvas.

**Comment by leeoniya** [comment]
hey @jasonatball 

https://github.com/leeoniya/uPlot/issues/162

probably worth starting a Recipes or FAQ wiki page instead of crawling through issues.

**Comment by jasonatball** [comment]
Thanks that's exactly what I was looking for. I had read the bottom of that issue but didn't see the note at the top. I ended up doing this which makes sense for my 1Hz data:

    min: Math.round(new Date().getTime() / 1000),
    max: Math.round(new Date().getTime() / 1000) + 1000

**Comment by jasonatball** [comment]
@leeoniya It appears that leaves a blank series since data is ```[[], []]```. My workaround was to delSeries(1) and then addSeries({ ... }, 1). Is that the best solution?

**Comment by leeoniya** [comment]
yeah, that's not ideal. but omitting the seriers *almost* works. i think it's just a matter of not creating a default y series here:

https://github.com/leeoniya/uPlot/blob/b5fefa47977e79dd513009008e0ef62fc51411a3/src/uPlot.js#L208

this should be a pretty easy quality of life improvement.

**Comment by leeoniya** [comment]
625f6003a50c3f0c5caf2725061661aa0a3ef35f makes it possible to omit both series and data entirely:

https://jsfiddle.net/9twvyr2L/

**Comment by jasonatball** [comment]
Thanks for the excellent help. We maintain the [COSMOS](https://github.com/BallAerospace/COSMOS) project so as a fellow maintainer I appreciate the help.

**Comment by leeoniya** [comment]
sure!

**Comment by jasonatball** [comment]
I was playing with your jsfiddle and tried this:

```
let u = new uPlot(opts, null, document.body);
u.addSeries({
  label: 'TEST',
  stroke: 'red'
})
u.setData([[1],[1]])
```
But nothing happens.

**Comment by jasonatball** [comment]
In my own application when I call addSeries I get the following stack:
```
TypeError: Cannot read property 'scale' of undefined
    at Xn (uPlot.iife.min.js:2)
    at Object.Bn.s.addSeries (uPlot.iife.min.js:2)
```

**Comment by leeoniya** [comment]
interesting. looks like some kind of bundling SNAFU:

where the hell did the `splice()` go?

https://github.com/leeoniya/uPlot/blob/625f6003a50c3f0c5caf2725061661aa0a3ef35f/src/uPlot.js#L379-L385

https://github.com/leeoniya/uPlot/blob/625f6003a50c3f0c5caf2725061661aa0a3ef35f/dist/uPlot.iife.js#L1112-L1117

something somewhere seems to think that splice has no side-effects and is getting removed.

time to open up a rollup bug perhaps. gonna try to isolate it in the REPL first.

**Comment by leeoniya** [comment]
could not get a simple repro in their REPL. opened https://github.com/rollup/rollup/issues/3555. hopefully some answers soon :\

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot/commit/abacd02d19403048dbfd30b2004238e203a25598 moves some code around to work around the bug.

**Comment by jasonatball** [comment]
I was able to link to your new release and it seems to be working great! I look forward to the next release. Thanks again!

**Comment by leeoniya** [comment]
v1.0.9 is out

**Comment by sausin** [comment]
Just wanted to drop by and say - Thank you! The whole experience with the package (including the way you're handling issues) is just awesome :+1: 

One a side note - sorry, for the unnecessary pinging

**Comment by leeoniya** [comment]
@sausin thanks, happy to help! ([most of the time](#233))

**Comment by sausin** [comment]
Some friction will always exist!

What I saw as being important is that if any PR / issue is not taken forward, then the explanation is put in right there. It's good book keeping (for future self too), and a good place for people experiencing the same issue / planning to introduce a PR to check out before own/other's time is spent in vain.

Hoping the library will stick to the <30 kB mark that you've discussed. (As an aside, I'm kind of jealous that the hey.com bundle size is ~40 kB total - damn!).

**Comment by leeoniya** [comment]
> (As an aside, I'm kind of jealous that the hey.com bundle size is ~40 kB total - damn!).

i'm getting around 35KB, and ~8KB of that is unused.

not sure what exactly is impressive about what could/should easily be a mostly-empty static page with 0 KB js, actually requiring 35KB of js?

my 9-5's heaviest e-commerce page is ~65kb of js, which includes a ton of products pulled from a db, modals/lightboxes, nested tabs, pagination, gallery, shopping cart UI, is fully responsive and rehydrated on the client: https://us.thermosoft.com/floor-heating/systems/warmstep-mats?track=0

(?track=0 disables google & bing analytics, otherwise they add more js than the rest of our page).

**Comment by sausin** [comment]
The ~40 kB bundle size is for the actual application (not the current static page) that [dhh](https://twitter.com/dhh/status/1265718008191709185?lang=en) has been discussing on twitter.

It was an observation that things are awesome with people trying to put in efforts minimizing their app footprint. uPlot is an effort in the same direction on the chart front :smiley:
