### ISSUE TITLE
Values not updating when hovering over plot while zoomed out

### ISSUE THREAD

**Issue by ItsMeFrancois** [leeoniya/uPlot#222]
When I load the page and hovering over the plot the values on the bottom will not be updated and stay fixed to the first element. When zoomed in everything is working properly. After fully zooming out again will result in the proper behavior. Zooming in and out again will result in the buggy behavoir again. You can see this bug in the GIF below:
![bug_report](https://user-images.githubusercontent.com/46143633/82055392-b30bbe80-96c0-11ea-82d0-159a9ca38a82.gif)
Code used: [bug.txt](https://github.com/leeoniya/uPlot/files/4635060/bug.txt)

**Comment by leeoniya** [comment]
hey @ItsMeFrancois 

this is not enough information here for me to help you.

does this issue exist in the demos? if not, i'll need a codepen, jsfiddle, etc. or full example code that exhibits the issue.

all i can tell is that maybe you're using the mousewheel zoom plugin :shrug:

**Comment by ItsMeFrancois** [comment]
I edited my inital message and added the source code as a text document there.

**Comment by leeoniya** [comment]
your data is strings, but it must be numeric:

yours:

```js
const data = [
	["0", "1", "2", "3"],
	["3", "6", "20", "18"],
];
```

correct:

```js
const data = [
	[0, 1, 2, 3],
	[3, 6, 20, 18],
];
```
