### ISSUE TITLE
Double-click seems to override scale specification

### ISSUE THREAD

**Issue by sausin** [leeoniya/uPlot#223]
First off, thanks for the amazing work on this library!

I have managed to get everything working as desired. Only one issue (please point it out if it's an error on my part) that I have found is described below.

- Create a chart object with time series data
- set `options.scales.x` as below where the min and max timestamps (in my case, random data generated with timestamps in previous hour):
```json
{
    "time": true,
    "auto": false,
    "min":  "<timestamp low>",
    "max": "<timestamp high>"
}
```
- Render the chart (view it)
- Double click on the chart area

This results in the time series being reset (and in my particular case) all data gets hidden as it resets it to 24 hours from the current hour to next day.

For reference, my browser in a non GMT timezone (browser).

**Comment by leeoniya** [comment]
hey @sausin 

without runnable code i can only provide some general info:

- `opts.scales.x.min/max` are *initial* scale/zoom values, they are not static or hard limits.
- `u.scales.x.min/max` are the *current* scale values (will change with zoom-in/out.
- `opts.scales.x.range` allows you to adjust the min/max as needed. you may find what you need in #187 or the contained jsfiddle: https://jsfiddle.net/x8wsmg2a/

**Comment by sausin** [comment]
Thanks @leeoniya 

I'll try to create a fiddle with the data I have to help with the debugging. Will also try out range to see if it can help me out.

**Comment by sausin** [comment]
Here is the fiddle: https://jsfiddle.net/dst0ejr5/4/

Another issue that seems to be happening is that the values being 'selected' below are only the very extreme (first and last). Hovering on the other values doesn't really work

**Comment by EmiPhil** [comment]
Is there a reason why your timestamps are going backwards in time?

**Comment by EmiPhil** [comment]
Basically when you were zooming back out, uPlot was correctly finding the min timestamp of your data set which was the last one in your case. You were able to get it to display on the first render by telling uPlot that the max was the min and the min was the max.

**Comment by sausin** [comment]
Thanks a lot @EmiPhil !!

**Comment by leeoniya** [comment]
> Thanks a lot @EmiPhil !!

indeed :)
