### ISSUE TITLE
an example needed for plotting text on candlestick chart

### ISSUE THREAD

**Issue by pannet1** [leeoniya/uPlot#224]
i am unable to comprehend how `draw` or `drawSeries` hooks works under the hood. can you please provide a standalone example of plotting text on candlestick chart with hardcode data.  usecase is news https://www.forexfactory.com/calendar on x (time) and y (price)

**Comment by leeoniya** [comment]
e.g.

```js
u.ctx.font = '12px Arial';
u.ctx.textBaseline = 'bottom';
u.ctx.textAlign = 'center';
u.ctx.fillText(close, timeAsX, highAsY);
```

https://jsfiddle.net/20dzjs6x/

**Comment by pannet1** [comment]
it works great. i am able to replicate the same locally. 

actually, we will not have the text on all candlesticks (like highAsY). i want to show the number of shares bought or sold on the particular timeAsX as sharesAsY. Also please note that the source of the plot will not be OHLC. So this will be purely random and not necessarily be present on every candlestick plotted. i will make an attempt to create a plugin with the starter code you gave me. meanwhile, it will be highly appreciated, if you could provide me with some hints to speed up the coding.



> e.g.
> 
> ```js
> u.ctx.font = '12px Arial';
> u.ctx.textBaseline = 'bottom';
> u.ctx.textAlign = 'center';
> u.ctx.fillText(close, timeAsX, highAsY);
> ```
> 
> https://jsfiddle.net/20dzjs6x/
