### ISSUE TITLE
ohlc with vol

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#225]
![1](https://user-images.githubusercontent.com/44717154/82161250-09f3ce00-9850-11ea-8334-6ae5da559739.png)

hi, impressed by the performance of this lib. trying to use it for drawing OHLC charts with vol. can not find exisiting samples since usually Vol is of a different scale than the OHLC range. typically a vol section is a bar section that is below the ohlc section. Guess I can draw ohlc and vol seperately, but not sure how to draw them together.Please help.
BTW, for testing, I made up a dataset using the Gold data but with vol being the 5th in the dataset.
const data = [
[1546300800,1546387200,1546473600,1546560000,1546819200,1546905600,1546992000,1547078400,1547164800,1547424000],
  [1284.7,1319.9,1318.7,1328,1317.6,1321.6,1314.3,1325,1319.3,1323.1],
  [1284.75,1320.6,1327,1330.8,1326.8,1321.6,1326,1328,1325.8,1327.1],
  [1282.85,1315,1318.7,1309.6,1317.6,1312.9,1312.4,1319.1,1319,1321],
  [1283.35,1315.3,1326.1,1317.4,1321.5,1317.4,1323.5,1319.2,1321.3,1323.3],
  [56,3,72,99,77.2,10,6,23,5,10],
];

**Comment by leeoniya** [comment]
> Guess I can draw ohlc and vol seperately, but not sure how to draw them together.

yeah, my advice would be to draw the volume as a separate series. this way you you can use `.valToPos()` along the separate y scale, put an axis there, and control the ticks/labels.

**Comment by hz2018tv** [comment]
want to have the ohlc and vol sections to zoom in/out together with one operation, so not sure whether that happens if they are seperated charts?

**Comment by leeoniya** [comment]
i didnt mean to draw them in separate charts, you can draw them in the same chart.

i'll add this to the demo later today. can you give me a list of actual daily GOLD volumes for all of 2019?

what differentiates gray and red bars in your image?

**Comment by hz2018tv** [comment]
Thanks!. regarding the vol data, I made up some numbers for testing, but I went to grab some actual data from web for your reference. 

"Date","Price","Open","High","Low","Vol.","Change %"
"May 17, 2020","30.39","29.71","30.48","29.61","-","3.26%"
"May 15, 2020","29.43","27.64","29.92","27.24","-","6.79%"
"May 14, 2020","27.56","25.56","27.96","25.18","160.51K","8.98%"
"May 13, 2020","25.29","25.30","26.45","24.79","150.86K","-1.90%"
"May 12, 2020","25.78","24.49","26.23","24.22","212.34K","6.79%"
"May 11, 2020","24.14","24.49","25.58","23.67","179.59K","-2.43%"
"May 08, 2020","24.74","23.35","24.99","23.26","205.18K","5.05%"
"May 07, 2020","23.55","24.09","26.74","22.94","310.26K","-1.83%"
"May 06, 2020","23.99","25.52","26.08","22.58","381.17K","-2.32%"
"May 05, 2020","24.56","21.24","25.49","21.13","387.24K","20.45%"
"May 04, 2020","20.39","19.11","21.42","18.05","311.49K","3.08%"
"May 01, 2020","19.78","19.04","20.48","18.07","403.20K","4.99%"
"Apr 30, 2020","18.84","15.64","19.44","15.45","545.34K","25.10%"
"Apr 29, 2020","15.06","13.35","16.78","12.67","554.13K","22.04%"
"Apr 28, 2020","12.34","12.96","13.69","10.07","897.09K","-3.44%"
"Apr 27, 2020","12.78","16.84","16.98","11.88","623.20K","-24.56%"
"Apr 24, 2020","16.94","16.78","17.97","15.64","600.22K","2.67%"
"Apr 23, 2020","16.50","14.20","18.26","13.35","833.58K","19.74%"
"Apr 22, 2020","13.78","13.12","16.18","10.26","1.24M","37.66%"
"Apr 21, 2020","10.01","-14.00","13.86","-16.74","18.44K","-126.60%"
"Apr 20, 2020","-37.63","17.73","17.85","-40.32","247.95K","-305.97%"
"Apr 17, 2020","18.27","20.00","20.22","17.31","240.63K","-8.05%"

**Comment by hz2018tv** [comment]
> what differentiates gray and red bars in your image?

the color of the vol is the same as the color of the ohlc, I guess.

**Comment by leeoniya** [comment]
> Thanks!. regarding the vol data, I made up some numbers for testing, but I went to grab some actual data from web for your reference.

i'm not looking for a reference, i need a properly formatted full array of actual volume data that i can copy/paste into the existing demo:

https://github.com/leeoniya/uPlot/blob/e31a2793c5c5942f08f0c6cc47a54f4e06163409/demos/candlestick-ohlc.html#L224-L230

**Comment by hz2018tv** [comment]
i.c. I did not have those data formatted out, instead I made up a very small subset (around 10 entries) with real date,o,h,l,c, plus a fake row of vol data in the original post 
didnt even realize the data in the candlestick demo were the actual data from 2018/12/31 to 2019/10/24, also not sure where the data came from. but I still went to investing.com and grabbed the data for that time frame and parsed it. so the 5th row in the data should be 
['1,507.50', '0.71K', '0.52K', '2.72K', '2.48K', '2.39K', '4.81K', '0.46K', '1.00K', '6.69K', '2.99K', '4.42K', '4.10K', '2.86K', '1.82K', '2.30K', '2.72K', '2.92K', '2.77K', '2.76K', '1.00K', '1.56K', '1.65K', '1.60K', '0.54K', '1.06K', '1.74K', '0.29K', '0.64K', '1.79K', '1.44K', '1.60K', '2.19K', '2.51K', '1.28K', '1.18K', '0.93K', '2.06K', '0.0k', '0.0k', '1.34K', '0.90K', '0.79K', '1.58K', '0.87K', '0.75K', '0.58K', '1.45K', '0.12K', '0.84K', '0.41K', '0.86K', '2.06K', '1.53K', '1.20K', '0.55K', '0.87K', '2.45K', '1.99K', '1.81K', '0.61K', '1.56K', '0.76K', '0.70K', '1.05K', '0.56K', '1.57K', '0.85K', '1.04K', '0.61K', '1.42K', '0.93K', '0.41K', '0.30K', '0.99K', '0.94K', '0.58K', '1.80K', '1.37K', '0.86K', '0.86K', '0.0k', '1.13K', '0.43K', '0.32K', '1.26K', '2.56K', '1.31K', '1.80K', '0.23K', '0.72K', '0.46K', '0.42K', '0.11K', '0.41K', '0.74K', '0.49K', '0.59K', '1.01K', '0.31K', '0.74K', '1.33K', '0.74K', '0.31K', '0.99K', '0.17K', '0.08K', '0.46K', '0.20K', '0.0k', '0.0k', '0.07K', '0.47K', '1.62K', '0.27K', '0.08K', '0.21K', '0.11K', '0.34K', '0.20K', '0.66K', '0.05K', '0.04K', '0.30K', '0.12K', '0.01K', '0.02K', '0.04K', '0.26K', '0.21K', '0.14K', '0.38K', '0.00K', '0.15K', '0.06K', '0.00K', '0.0k', '0.08K', '0.06K', '0.18K', '0.02K', '0.23K', '0.04K', '0.08K', '0.00K', '0.00K', '0.05K', '0.04K', '0.05K', '0.07K', '0.03K', '0.01K', '0.11K', '0.14K', '0.05K', '0.14K', '0.06K', '0.12K', '0.02K', '0.00K', '0.01K', '0.01K', '0.23K', '0.02K', '0.08K', '0.01K', '0.00K', '0.04K', '0.14K', '0.00K', '0.02K', '0.13K', '0.00K', '0.00K', '0.00K', '0.00K', '0.01K', '0.05K', '0.03K', '0.04K', '0.0k', '0.0k', '0.03K', '0.07K', '0.05K', '0.00K', '0.03K', '0.17K', '0.05K', '0.00K', '0.00K', '0.00K', '0.00K', '0.00K', '0.05K', '0.20K', '0.00K', '0.03K', '0.05K', '0.02K', '0.15K', '0.0k', '0.0k', '0.00K', '0.00K', '0.00K', '0.01K', '0.40K', '0.05K', '0.55K', '0.10K', '0.00K', '0.01K', '0.10K', '0.08K', '0.08K', '0.0k', '0.05K'], hopefully you can just paste into the demo code.

**Comment by leeoniya** [comment]
i ended up using randomized volume data for the demo.

https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html
