### ISSUE TITLE
sync cursor with legends combined

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#227]
hi, in the sync cursor demo, could we combine the legends of all sync'ed charts into one, since they are sharing "time" together, and put the combined legends in one line at the top of the first big chart?

**Comment by leeoniya** [comment]
after the charts are initialized, you can technically detach the dom elements from each legend and re-assemble your own legend from them as you'd like and it should continue to work.

this would only become problematic if you're dynamically adding or removing series via addSeries() or delSeries() apis.
