### ISSUE TITLE
replace all the chart series with new series

### ISSUE THREAD

**Issue by Karim-Elshal** [leeoniya/uPlot#230]
Hi,
I am trying to create a dynamic chart
I can change the data by setData and I need too to change the series but unfortunately, I don't know how can I change it
Note: The number of series is not constant all time
Thanks

**Comment by leeoniya** [comment]
like this?

https://leeoniya.github.io/uPlot/demos/add-del-series.html

**Comment by Karim-Elshal** [comment]
Yes, Thanks
Is it possible to delete all series at the same time?
or Should I make a loop to delete it one by one?

**Comment by leeoniya** [comment]
> or Should I make a loop to delete it one by one?

yes. wrapping the loop with `u.batch()` may help with performance if you have a lot of data or series.

https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L57

**Comment by Karim-Elshal** [comment]
When I used the new version of the library so I can use addSeries and delSeries, something became not work
This example:
https://jsfiddle.net/3q1vo4th/

From this topic:
https://github.com/leeoniya/uPlot/issues/158

**Comment by leeoniya** [comment]
timeAxisVals now has more arguments. changing to this works:

```js
u.axes[0].values = (...args) => showVals ? timeAxisVals(...args) : [];
```

https://jsfiddle.net/d6othup3/

**Comment by Karim-Elshal** [comment]
Thanks leeoniya :)
