### ISSUE TITLE
Possible to inset axis labels?

### ISSUE THREAD

**Issue by mrkurt** [leeoniya/uPlot#235]
I'm doing some fun custom formatting on values, and they're actually long enough I'd rather have them inset over the graph area. Is that possible?

Right now they seem to be overflowing out the left side of the canvas. If insets aren't possible this is something I want to debug. :)

![image](https://user-images.githubusercontent.com/7724/82763250-ec80b000-9dcb-11ea-9349-40c700213c3c.png)

**Comment by leeoniya** [comment]
sure!

set a negative `axis.gap`, also probably turn off the ticks in that case:

https://jsfiddle.net/0hug8Ldo/
