### ISSUE TITLE
Axes control

### ISSUE THREAD

**Issue by rubyzhao** [leeoniya/uPlot#24]
For axes y: space works as expected, but min and max looks not working.
For axes x: the display is always time type, even I use type: "n". 
```js
axes: {
          x: [
               {
                 type: "n",
                 scale: 'x',
                  //values: (vals, space) => vals.map(v => v*100),
                  min: 0,
                  max: 10,
                  space: 50,
                }
            ],
            y: [
                {    type: "n",  //"t" is for time; "n" for number
                     scale: 'y',
                     //values: (vals, space) => vals.map(v => v*1),
                     min: -20,
                     max: 20,
                     space: 50,
                }
            ],
}
```

**Comment by leeoniya** [comment]
there is only a single x axis, so it should be an object, not an array.

 also, min/max should be specified using `scales` & `range`. see https://github.com/leeoniya/uPlot/blob/master/demos/stream-data.html#L185

**Comment by rubyzhao** [comment]
Please see the result: https://github.com/rubyzhao/uPlot_MyChart_Line/blob/master/LinePlotFrom_uPlot_Chartjs.pptx
and the project https://github.com/rubyzhao/uPlot_MyChart_Line

I want get the similar result as from Chart.js(slide#1). How to set min/mix, space, name for X and Y axis with uPlot? I have tried a few times without lucky. Please help.

**Comment by leeoniya** [comment]
keep in mind that setting a fixed range on `x` will prevent zooming along the x axis. it's easier to simply restrict the x range in the original data (i commented out the x range restriction below).

in the future please attach images directly to the github issue so i don't have to open powerpoint files just to view images.

```js
var loop = 130000;

let data = [
    Array(loop),
    Array(loop),
];

for (var i = 0; i < loop; i++) {
    let x = 2 * Math.PI * i / loop;
    let y = Math.sin(x);

    data[0][i] = x;
    data[1][i] = y;
}

const opts = {
    width: 1048,
    height: 600,
    cursor: true,
    scales: {
        x: {
            type: "n",
        //  auto: false,
        //  range: (min, max) => [0, 6],
        },
        y: {
            auto: false,
            range: (min, max) => [-1.2, 1.2],
        },
    },
    series: {
        x: {
            type: "n",
            label: "x",
        },
        y: [
            {
                label: "sin(x)",
                color: "red",
                width: 2,
            }
        ],
    },
    axes: {
        x: {
            type: "n",
        },
        y: [
            {
                space: 50,
            }
        ],
     }
};

let u = new uPlot(opts, data);
document.body.appendChild(u.root);
```

**Comment by rubyzhao** [comment]
Thanks for your prompt help. I have tried your code. Now x axis becomes number format. But still some other issues were left:
1. min and max for x and y axis still doesn't work. I don't want the sin curve reaches the most top and bottom, left and right. For example, I want use min and max for y axis to control the most bottom and top value, Please refer slide#1 from Chart.js
2. label(name) for x and y axis still didn't show along x and y axis.
3. How to show title(name of the plot, on top center) of the  of the plot?

Suggestion:
x and y were defined 3 times in Scales, Series and Axes. type: 'n' were repeated three times. Can you merged to two: Series and Axes?

**Comment by leeoniya** [comment]
you might be missing some CSS. take a look at the demo: https://leeoniya.github.io/uPlot/demos/axis-control.html

> Suggestion: x and y were defined 3 times in Scales, Series and Axes. type: 'n' were repeated three times. Can you merged to two: Series and Axes?

series and axes do not always have a 1:1 mapping, so this would not work. for example, you can have an axis from a derived scale: https://leeoniya.github.io/uPlot/demos/derived-scale.html

the opts are structured this way to provide the most flexibility, so it ends up looking a bit like a relational database with a bit of repetition in the mappings, but the apis are much more powerful. the `n` in each case overrides a different set of defaults in other non-specified opts that assume normally `t`.

> How to show title(name of the plot, on top center) of the of the plot?

this does not exist yet. i will probably consider it together with #11

**Comment by leeoniya** [comment]
another reason axes/series cannot be merged is because series can be toggled on/off and if multiple series need the same axis visible then what happens if yout turn off the series with the axis definition in it?

**Comment by leeoniya** [comment]
ok, i pushed a commit that makes axes & series inherit the `type` from their scale. this should reduce some opts noise.

**Comment by rubyzhao** [comment]
I compared your just provided example  [(https://leeoniya.github.io/uPlot/demos/axis-control.html)]) with the previous one your provided early above. The label has to be under axes section  again to show along axes.  This is not CSS issue.  Now it is very clear. Thanks again.

**Comment by leeoniya** [comment]
i think i will improve the logic for numeric y scale padding. it should not be necessary to use a static min/max to make sure the buffer is added. right now if a series min/max lands exactly on an incr, it may prevent the buffer from getting added.

**Comment by leeoniya** [comment]
ok, the auto-scaling logic is better now. so you should not need the static y range for your example.
