### ISSUE TITLE
Cancel Drag / Min Drag Distance

### ISSUE THREAD

**Issue by EmiPhil** [leeoniya/uPlot#245]
It would be nice to be able to specify an option to only start dragging if the mouse has moved a certain distance (and if the mouse goes past that distance and then back in, cancel the drag instead of zooming in on the little area)

**Comment by leeoniya** [comment]
i wonder if just binding to the native dragstart/dragend events would be sufficient to set a flag in app-space?

https://developer.mozilla.org/en-US/docs/Web/API/Document/dragstart_event

otherwise exposing it as a cursor property seems most logical (similar to cursor.lock/cursor.locked).

**Comment by leeoniya** [comment]
i'd be fine adding a `cursor.drag.dist`
