### ISSUE TITLE
"TypeError: Cannot read property 'scale' of undefined" after upgrade to 1.0.9

### ISSUE THREAD

**Issue by ALEUT** [leeoniya/uPlot#252]
I got this exception after upgrade from 1.0.8 to 1.0.9:
![image](https://user-images.githubusercontent.com/4101909/83328543-6a413180-a28c-11ea-9653-c8e7ffd15b46.png)

My configuration is:
```
export const uPlotDefaultOptions: uPlot.Options = {
  title: '* use ctrl + scroll to zoom, double click to reset scale',
  width: window.innerWidth - 48,
  height: 600,
  class: 'mb-3',
  plugins: [wheelZoomPlugin({factor: 0.75}) as any],
  series: [{label: 'Timestamp'}],
  axes: [{}],
  tzDate: ts => new Date(getUTCDateFromLocal(ts * 1000)),
  fmtDate: tpl => uPlot.fmtDate(fixUplotDateTimeTemplate(tpl)),
};
```

**Comment by leeoniya** [comment]
can you please post a runnable repro?

**Comment by ALEUT** [comment]
> can you please post a runnable repro?

It will take some time, I just played with my code and noticed, that before I had:
`series: [{label: 'Timestamp'}],`
and it was ok for version 1.0.8, for 1.0.9 I tried with
`series: [{label: 'Timestamp'}, {label: 'Value'}],`
and only after that it works fine.

I have simple structure like timestamp - value.

**Comment by leeoniya** [comment]
just pushed some tweaks that should handle this now. thanks for reporting.

**Comment by leeoniya** [comment]
out of curiosity, what is this trying to do?

```js
  tzDate: ts => new Date(getUTCDateFromLocal(ts * 1000)),
  fmtDate: tpl => uPlot.fmtDate(fixUplotDateTimeTemplate(tpl)),
```

is there a case when uPlot's native fmtDate and tzDate dont do what you need?

**Comment by ALEUT** [comment]
> out of curiosity, what is this trying to do?
> 
> ```js
>   tzDate: ts => new Date(getUTCDateFromLocal(ts * 1000)),
>   fmtDate: tpl => uPlot.fmtDate(fixUplotDateTimeTemplate(tpl)),
> ```
> 
> is there a case when uPlot's native fmtDate and tzDate dont do what you need?

I know about tzDate, but my function looks works faster (but works with UTC only).
Regarding fixUplotDateTimeTemplate, I just fix the format for my needs like
```
case '{YYYY}-{MM}-{DD} {h}:{mm}{aa}':
      return '{DD}-{MM}-{YYYY} {HH}:{mm}:{ss}';
```

**Comment by leeoniya** [comment]
i actually noticed howslowtzDate was yesterday, which is what 3c6ed55a2d3ee61aa771d0dddffae7fe90b803c9 was about. but that doeant help much for densely packed data.

i was actually wondering if UTC was common enough to fast-path in tzDate without re-parsing.

i assume your `getUTCDateFromLocal` does something like?

```js
let d = new Date(ts * 1e3);
return new Date.UTC(d.getUTCFullYear(), ...);
```

**Comment by leeoniya** [comment]
actually, that wouldn't work, you'd probably do this:

https://stackoverflow.com/a/11964609

**Comment by ALEUT** [comment]
@leeoniya  you're right:
```
const getTimezoneOffset = (date: number): number => new Date(date).getTimezoneOffset() * 60 * 1000;

export const getUTCDateFromLocal = (date: number): number => date + getTimezoneOffset(date);
```

**Comment by leeoniya** [comment]
f085444 adds a tzDate fast path for `Etc/UTC`, can you test it out?

**Comment by ALEUT** [comment]
> [f085444](https://github.com/leeoniya/uPlot/commit/f08544436e435eaffe49371d5e2bf91f2fbbb21b) adds a tzDate fast path for `Etc/UTC`, can you test it out?

Works fine for me, identical to what I have.
