### ISSUE TITLE
spanGaps with null data at head or tail causes path-filling oddities

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#253]
https://github.com/phoenixframework/phoenix_live_dashboard/pull/149

![demo](https://user-images.githubusercontent.com/168677/83660196-64dc3380-a579-11ea-8451-e049d03ce075.gif)

need to investigate. might be an oversight in either gap detection or clip construction.

https://github.com/leeoniya/uPlot/blob/fa0074ba18d0276a8845204781781d0bead6384a/src/uPlot.js#L915-L940

**Comment by leeoniya** [comment]
hmm, cannot reproduce in simple case: https://jsfiddle.net/n4dL96gh/

cc @mcrumm can you take a look at what you guys are doing to figure out what's going on?

**Comment by mcrumm** [comment]
Sure, I'll export some sample series data so you can take a closer look.

We generate a lot of null interspersed data, so ours may be more of an alignment problem, I'm not sure.

**Comment by leeoniya** [comment]
ah, it needs `spanGaps: true`: https://jsfiddle.net/tbxw34n0/

**Comment by leeoniya** [comment]
this should be fixed now.

@mcrumm can you plz re-test with latest build?

**Comment by mcrumm** [comment]
Here's a test on latest. Unfortunately it's not the exact same dataset:
![spangaps](https://user-images.githubusercontent.com/168677/83806802-e65dbf80-a666-11ea-96dd-86713ea330df.gif)

**Comment by leeoniya** [comment]
ok, thanks. that's looking correct now.
