### ISSUE TITLE
Add demo: Bar chart with ladder-based heatmap

### ISSUE THREAD

**Issue by bluemonk3y** [leeoniya/uPlot#258]
The barchart-heatmap allows time series information to be plotted using a ladder on the Y axis. For each X-time slice a ladder represents points of interest at specific Y values. The colour of the ladder entry is determined by another series that uses the same index. The demo provides cursor tracking to show the ladder information and supports click events on ladder entries.

**Comment by leeoniya** [comment]
i'm calling this done. if you'd like to submit improvements, please open a PR.
