### ISSUE TITLE
Zooming in on a single point with 'distr: 2' breaks the x scale

### ISSUE THREAD

**Issue by FrozenKite** [leeoniya/uPlot#263]
I'm using `distr: 2` on the x scale. When the zoom range only covers a single point, the scale seems to break as shown below. I assume this is an effect of `distr: 2` trying to snap the edges to data points but it only has a single point to work with.

![0](https://user-images.githubusercontent.com/65102280/85358826-802bc600-b4c9-11ea-898e-751b8ded17b7.png)

This is also reproducible in the [candlestick demo](https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html):

![cd](https://user-images.githubusercontent.com/65102280/85358970-e0226c80-b4c9-11ea-9da1-2e0ddd055ef5.png)

**Comment by leeoniya** [comment]
thanks, i'll look into this over the weekend.

**Comment by FrozenKite** [comment]
Closing as this seems to be fixed in 1.1.2, thanks!

**Comment by leeoniya** [comment]
heh, looks like you're right :)
