### ISSUE TITLE
Y position of tick labels 

### ISSUE THREAD

**Issue by Cloud11PL** [leeoniya/uPlot#265]
Hi!

I came across an issue where the tick labels when y gutter is set to 0 can be cut from the top or overlap with each other. Is there a way to change their y position so that they can be closer together?

![image](https://user-images.githubusercontent.com/13994677/85833846-ac2d9c80-b792-11ea-9d0e-1e3c04a65afa.png)

**Comment by leeoniya** [comment]
hey @Cloud11PL 

well, them getting cut off at the extremes is expected. the whole purpose of the gutters is to prevent this there is currently no option to control per-label alignment, which is what you'd need here (e.g. the "0" would be align bottom while the rest would be "middle").

labels overlapping each other as a result of setting y gutters to 0 is unexpected. can you put up a jsfiddle that has this issue?

**Comment by leeoniya** [comment]
closing for now, let me know if you're able to put up some code that reproduces the issue.
