### ISSUE TITLE
title&legend font control (color/face)

### ISSUE THREAD

**Issue by polishcode** [leeoniya/uPlot#266]
It would be great to have out of the box control over font color/face for title & legend.
Thank you.

**Comment by leeoniya** [comment]
hey @polishcode 

i'd prefer not to provide control for chart elements that can be styled using CSS.

**Comment by polishcode** [comment]
Hi @leeoniya ,
Thanks for prompt response. Thats understandable.
Then maybe a small example in docs on how to **properly** achieve that for those that rather code in C++ than in html/js/css?
Thanks!
p

**Comment by leeoniya** [comment]
here's an example of simple overrides: https://jsfiddle.net/hyu4o8sr/

Phoenix Live Dashboard does fairly extensive legend customization by adding more rules: https://github.com/phoenixframework/phoenix_live_dashboard/blob/master/assets/css/app/components/_charts.scss#L13-L113

**Comment by polishcode** [comment]
Thank you, exactly what I needed.
