### ISSUE TITLE
range, point & line annotations

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#27]
http://dygraphs.com/gallery/#g/highlighted-weekends
http://dygraphs.com/gallery/#g/highlighted-region

also annotations along the axes/scales (vt or hz lines that mark some specific event in time or some level along a y axis).

series annotations [1] will probably be handled by #10:

[1] http://dygraphs.com/gallery/#g/annotations

**Comment by mcintyre94** [comment]
Would this cover the functionality displayed in this Apex charts demo: https://apexcharts.com/javascript-chart-demos/line-charts/line-chart-annotations/?

**Comment by leeoniya** [comment]
pretty much, though uPlot almost certainly won't be dealing with the the label positioning. i'll add the labels to the legend but leave anything fancier to be implemented externally.

**Comment by leeoniya** [comment]
@mcintyre94

i think actually this should be possible to do outside the core via a plugin. uPlot provides everything you need for this, like translating scale values to coordinates and hooks to when the view or data changes.

take a look at the composable `tooltips` and `wheel-zoom` demos:

https://leeoniya.github.io/uPlot/demos/tooltips.html
https://leeoniya.github.io/uPlot/demos/wheel-zoom.html

 would you be interested in prototyping an annotations plugin?

**Comment by leeoniya** [comment]
following up on #76...

a couple things to keep in mind:

i would prefer all text labels to be drawn in the dom since you get CSS styling, text wrapping and interactivity for free. the same thinking applies for the actual regions/lines/points - if they're on canvas, they're effectively static (without adding a bunch of extra code), but if they're drawn using dom elements, then we get a lot more for free, like hover interaction, on-demand labels & options for label placement libs that respect dom element bounds, etc.

the price we pay for drawing regions/lines/points in the dom is the inability to place them anywhere except above or below the full canvas (you cannot place them in between the grid and the series) - i'm not sure if this is a show-stopper for keeping everything in the dom - it might be since we'll want the text labels to be above everything, but i can see wanting the annotations themselves be between the grid and series.

another option would be to have the grid on a separate canvas, but this wastes a bunch of memory by allocating an entire canvas region just to draw some lines - which is not great for full-screen plots, e.g. 1920x1080.

**Comment by leeoniya** [comment]
this is all now easy enough to do in userland that it can be delegated to a plugin.

highlighted-weekends remains a bit tricky because of the required timezone and dst accounting, but #119 exists for this specific case.
