### ISSUE TITLE
[question] Contiguous bar charts?

### ISSUE THREAD

**Issue by kyleconroy** [leeoniya/uPlot#270]
The Heroku dashboard has a memory usage graph that looks like this:

<img width="1054" alt="Screen Shot 2020-07-09 at 3 15 23 PM" src="https://user-images.githubusercontent.com/34893/87096213-292b2e00-c1f7-11ea-8dae-c29b84ad8e9a.png">

Is it possible to have uPlot render in a similar style?

**Comment by leeoniya** [comment]
yeah, it's possible by implementing user-defined `series.paths`. i imagine it'll be ~30 LOC.

this demo does it inline, but you can easily turn it into a reusable plugin that augments opts.

https://github.com/leeoniya/uPlot/blob/master/demos/line-smoothing.html

**Comment by leeoniya** [comment]
https://leeoniya.github.io/uPlot/demos/line-stepped.html

besides a couple changed lines, the new demo is basically identical code to the smoothing demo. both demos can be made more efficient by pre-computing the coords to avoid doing it twice in the loop, but with these small data-sets the difference would be negligible.
