### ISSUE TITLE
[PSA] className updates in v1.1 will break custom styles (and perhaps plugins)

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#272]
context: https://github.com/leeoniya/uPlot/pull/260

to reduce the probability that uPlot's rather-general DOM classNames will collide with various css frameworks (like Bulma, Tailwind, Bootstrap, etc.), I've decided to `u-*` prefix and slightly tweak uPlot's classNames for better clarity. unfortunately, this will break custom styles and any code or plugins which relied on `querySelector`. the good news is that the DOM structure remains the same and the default stylesheet rules remain intact, so the required changes should be purely mechanical.

the full commit (which also updates all demos/plugins is https://github.com/leeoniya/uPlot/commit/f5c6b31b048898e0dceec795e8c843d118581036, but the relevant portion to follow is the [uPlot.css diff](https://github.com/leeoniya/uPlot/commit/f5c6b31b048898e0dceec795e8c843d118581036#diff-a85b0897d754d73612acf824ffe9c033).

additionally, all classNames have been extracted into [domClasses.js](https://github.com/leeoniya/uPlot/blob/master/src/domClasses.js), which can ease maintenance of any custom builds/forks which prefer to modify them.

cc @archdragon @mcrumm @Cryptkeeper @ryantxu @danyalejandro

**Comment by NeoLegends** [comment]
Hey! 

It's great the class names are now more unlikely to collide with other classes, but why didn't you issue a 2.0 (semver-breaking) for this? Our project just got bitten by this where a seemingly innocent `yarn update` caused breaking change, even if they are purely visual.

**Comment by leeoniya** [comment]
you're right. i really need to be more disciplined about this (if i was, we'd be at version 7ish by now), or maybe state that uPlot does not follow strict semver.

to me, 2.0 implies massive API changes that might require a lot of time and/or thought to adjust to. most auto-updating strategies will prevent most people from installing and/or testing breaking changes, which would lead to latent bugs hanging around for months or years. so in a someone self-serving fashion, i do sometimes push breaking changes in minor versions if the time to adapt to them is minimal and/or purely search-and-replace mechanical (as is the case here). also, the goal of keeping this lib small in byte size and being only supported by 1 person in his free time (me), means i cannot maintain multiple API compatibility wrappers.

i still try to be careful though, and so far this strategy has not caused a huge angry mob to descend upon me, but i don't think this will be manageable or good, long-term.

anyways, please accept me apology, for whatever it's worth.
