### ISSUE TITLE
streaming render mode (discuss)

### ISSUE THREAD

**Issue by ryantxu** [leeoniya/uPlot#273]
I'm not sure where to post this -- so let me know if there is something else.

I am making good progress with: https://github.com/grafana/grafana/pull/21835

I am focusing on grafana's streaming support now -- https://leeoniya.github.io/uPlot/demos/stream-data.html looks good.  Of couse webgl *may* be the right answer, but we really just need things to look reasonable updating ~10hz.  I am getting good results with uPlot, but there are a few render artifacts that make things flicker or jumpy:
1. render is triggered on changing data, but the rate is not super consistent
2. it looks like double-buffering may help.  (less noticeable when light theme, super apparent with dark theme)

What do you think about a render mode that:
1. accepts a relative time range.  ie: Date.now()-6000
2. updates as quickly as possible with double buffering:
```
(function drawFrame() {
    requestAnimationFrame(drawFrame);
    primaryCtx.save(); //Freeze redraw

   ... do the render stuff ...  

    primaryCtx.restore(); //And now do the redraw
})();
```
3. mouse interaction would stop the streaming and let you interact normally -- a la https://london.my-netdata.io/default.html, double click would return to the configured 

where do you think the appropriate place is for these kind of features?

**Comment by leeoniya** [comment]
> Of couse webgl may be the right answer, but we really just need things to look reasonable updating ~10hz. I am getting good results with uPlot, but there are a few render artifacts that make things flicker or jumpy:

can you show me the render artifacts you're referring to? if you send updates at only 10Hz (like the demo does), of course things will be jumpy. are you expecting uPlot to transition/animate between data updates? like this example which destroys my laptop's CPU fan? https://nagix.github.io/chartjs-plugin-streaming/

> it looks like double-buffering may help. (less noticeable when light theme, super apparent with dark theme)

i'm pretty sure double-buffering is already done by Canvas in browsers and nothing extra needs to be done by the user (https://stackoverflow.com/a/5208791). can you show me any demo online where it makes a difference in a single-pass render architecture like uPlot?

the only streaming artifact issue i'm aware of https://github.com/leeoniya/uPlot/issues/241, but this is a side-effect of the way that uPlot does downsampling, and where much of its speed comes from. this would only be noticeable if you're doing 60fps updates.

there are webgl-based solutions, but i have not seen any which do not cause my laptop fan to turn into a jet engine:

https://danchitnis.github.io/webgl-plot-examples/

**Comment by leeoniya** [comment]
there's something like http://smoothiecharts.org/, but that is only drawing 6 datapoints per series (it adds 1 new datapoint every 1000ms and drops the oldest one).

to do this type of smooth-looking animation you have to have future data that is occluded, which effectively makes it a delayed stream, *and* you have to have data which arrives predictably. if those two conditions are satisfied, it's possible to do some kind of constant-rate canvas translate in an off-screen buffer. all of this is just for a UI "effect", and it's not something uPlot is likely to implement.

**Comment by ryantxu** [comment]
The more I work with uPlot the more impressed I am!

Yes, i think living with flicker is ok, and the smooth updates are totally possible without changes to the library

**Comment by leeoniya** [comment]
> The more I work with uPlot the more impressed I am!

thanks :)
