### ISSUE TITLE
❤️ Sponsorship or dontations?

### ISSUE THREAD

**Issue by kyleconroy** [leeoniya/uPlot#276]
Any plan to accept donations or sponsors? I've found uPlot incredibly useful and would like to support its development.

**Comment by leeoniya** [comment]
hey @kyleconroy thanks for the offer. i'll try to set up a funding channel in the next week or so.

**Comment by bluemonk3y** [comment]
@leeoniya have you looked at getting sponsorship status on GitHub?

**Comment by leeoniya** [comment]
okay, the piggy bank is all set up now.

cc @Cryptkeeper, if still interested.

**Comment by traverseda** [comment]
I'm a fan of uplot but I don't actually use it for anything. $5 a month is a bit much (I like to spread my donations out over a large number of small projects, if they were all at $5 that would end up being a lot) but I'd be happy to do $1 per month, if that was supported.

**Comment by kyleconroy** [comment]
@leeoniya I somehow missed this. Sponsored!

**Comment by leeoniya** [comment]
@kyleconroy thank you :heart: !

@traverseda i have added a super special, non-user $1 tier for you. i always thought that tier was $0 :D

donations will be used for very important purchases:

![image](https://user-images.githubusercontent.com/43234/126885545-f14161f6-bcb2-49f8-9104-68b7324a93fd.png)

**Comment by leeoniya** [comment]
@traverseda @daeyounglim thanks!
