### ISSUE TITLE
min/max bands

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#28]
http://dygraphs.com/gallery/#g/temperature-sf-ny

dygraphs calls them "error bars" but a uPlot impl would be generic min/max. this will require area fill code to be added.

dunno if the bands should be their own series or be defined as part of an existing one.

the data format would probably be

```js
const data = [
  [0,1,2,3,4],  // x vals
  [
    [7,3,5,7,9],  // main values (can be median, mean, geo mean, etc)
    [7,3,5,7,9],  // min vals
    [7,3,5,7,9],  // max vals
  ]
];
```

**Comment by danyalejandro** [comment]
This is exactly what's preventing me from switching over. I work in a research center where we plot sensor data that's too dense to render without downsampling, so we instead plot min/average/max values. I believe people like us would be the main users of uPlot since our use case is not covered by other libs (I've used them all).

**Comment by leeoniya** [comment]
how many series do you normally analyze in the same graph?

as a hack, you can easily plot the min & max as additional series if there's only 1-3 series shown at once.

a good question is at what point does semi-transparent banding become a usability issue? the problem is similar to area-fill charts: e.g. https://www.chartphp.com/wp-content/uploads/area.png

what happens is now you have alpha-composed colors in the overlaped sections that don't match anything shown in the legend.

**Comment by danyalejandro** [comment]
We plot only 1 signal per plot, as shown in the attachment.

Our sensor dashboards (webpages) contain about 100-200 plots, which get manually reviewed by a (non-technical) scientist every day. They just scroll through the page looking for unusual trends. Each scientist spends less than 10 seconds per plot unless he notices something weird, so we value agile visual cues.

![image](https://user-images.githubusercontent.com/1218608/67603940-2652e080-f72f-11e9-8466-261061d5811b.png)

I also thought about plotting min/max as extra lines, but they just can't replace how the shaded min/max area becomes a visual "blob" you can quickly interpret. It's just easier on the brain, specially when you're hastly scrolling through plots.

If you limit the min-max shade to single plots that would fulfill our use case, and maybe you won't need to handle transparency.

**Comment by leeoniya** [comment]
> Our sensor dashboards (webpages) contain about 100-200 plots, which get manually reviewed by a (non-technical) scientist every day.

out of curiosity, what charting lib are you using now? are the dashboards publicly available?

> If you limit the min-max shade to single plots that would fulfill our use case, and maybe you won't need to handle transparency.

artificially limiting it to one series would be silly since you get transparency "for free" with `<canvas>`, so there's nothing special that needs to be done to handle it.

i agree that for a single series, area-fill and/or bands can make sense. the implementation should be pretty easy. i might do a prototype this weekend and see how much code it adds.

**Comment by danyalejandro** [comment]
We're using Dycharts for time-series, Plotly for complex charts and Chartjs for real-time animated plots. Unfortunately our code is private as it uses web services my company doesn't maintain for public usage.

Thank you, I would really appreciate this functionality.

**Comment by leeoniya** [comment]
i took a quick stab at it and it turned out pretty well. see the `min-max-bands` [1] branch and the demo [2]. there's about a 5% perf hit but avoiding that means duplicating a bunch of code. i'll see if it can be mitigated another way.

![image](https://user-images.githubusercontent.com/43234/67613730-73a67080-f776-11e9-80d3-c7554120b074.png)

so the way it works is that data and bands should be defined as two normal *consecutive* series in mins,maxes order and both series must set `band: true`. there's still a bit of work to do regarding toggling them on/off together but feel free to test what's done so far.

[1] https://github.com/leeoniya/uPlot/tree/min-max-bands
[2] https://github.com/leeoniya/uPlot/blob/min-max-bands/demos/min-max-bands.html

**Comment by leeoniya** [comment]
ok, the toggle issue is fixed and the branch is merged into master. let me know how it works out and open additional issues for bugs.

https://leeoniya.github.io/uPlot/demos/high-low-bands.html
