### ISSUE TITLE
Couple of API questions

### ISSUE THREAD

**Issue by mindv0rtex** [leeoniya/uPlot#281]
Thank you so much for the performant charting library. My use case involves plotting around a thousand charts, each with a fairly small number of points (in small hundreds). I originally used Plotly and it was a disaster, but uPlot renders the entire page in under a second. I do have a couple of questions on its usage:

- How can I specify the distance between the y axis label and the axis itself? The issue I'm having is that the axis label is rendered on top of the tick labels:

<img width="83" alt="Screen Shot 2020-07-31 at 12 14 30" src="https://user-images.githubusercontent.com/10409817/89054816-6e8ad900-d327-11ea-8527-3b5eb9dee045.png">

- You indicate that there is no built-in support for panning but it can be implemented if need be. Is the `zoom-touch` example a good starting point to do so? My JS is almost non-existent, so it's a bit of a challenge for me...

- My time series are unequally spaced and I pad them with null values as indicated in the docs. The question I have is whether you think it is possible, with not too much effort, to make the bottom widget display the value at the closest point in time to the current cursor position for all series. Right now it displays the value of only one time series and shows the other one as zero:

<img width="1002" alt="Screen Shot 2020-07-31 at 12 26 56" src="https://user-images.githubusercontent.com/10409817/89055906-308eb480-d329-11ea-9195-1a505fc59b4e.png">

Thank you!

**Comment by leeoniya** [comment]
> How can I specify the distance between the y axis label and the axis itself?

tweak `axis.size`, `axis.labelSize` and `axis.gap`:

https://github.com/leeoniya/uPlot/tree/master/docs#axis--grid-opts

though for large numbers with a lot of 0s, you might insteed consider overriding `axis.values` to render using a shorter notation to maximize the plotting area. e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toExponential

> You indicate that there is no built-in support for panning but it can be implemented if need be. Is the zoom-touch example a good starting point to do so?

i would say the touch pan/zoom demo is much more complex than a simple panning implementation. the trick is deciding what to do with the normal drag-zoom. i guess i can disable drag-zooming on the wheel-zoom demo and add simple drag-panning to that.

> The question I have is whether you think it is possible, with not too much effort, to make the bottom widget display the value at the closest point in time to the current cursor position for all series.

it's possible if you decide what "time" should display when each value can fall on a different time. one option would be to use a table-style legend like https://leeoniya.github.io/uPlot/demos/time-periods.html and show the correct tome for each?

**Comment by mindv0rtex** [comment]
> i would say the touch pan/zoom demo is much more complex than a simple panning implementation. the trick is deciding what to do with the normal drag-zoom. i guess i can disable drag-zooming on the wheel-zoom demo and add simple drag-panning to that.

From my experience with other charting libs, if you could hint to me how to implement panning with Shift+mouse drag, that would be all I need, so that I can both zoom and pan. 

> it's possible if you decide what "time" should display when each value can fall on a different time. one option would be to use a table-style legend like https://leeoniya.github.io/uPlot/demos/time-periods.html and show the correct time for each?

I think you understood what I had in mind, but just to make sure, here is a screenshot from Plotly:
<img width="901" alt="Screen Shot 2020-07-31 at 14 26 49" src="https://user-images.githubusercontent.com/10409817/89066021-b8c98580-d33a-11ea-85cc-6debe11d5ace.png">
Here I hover over Feb 11 and Plotly picks the Feb 8 point from the second series.

**Comment by leeoniya** [comment]
i'll add a mechanism soon for refining the hovered index per series, which would make the non-aligned hover and legend display easier to implement.

meanwhile...

https://github.com/leeoniya/uPlot/commit/56db9398a33bf16c5ab41c70948252c000a63697 adds wheel-drag panning to the [zoom-wheel demo](https://leeoniya.github.io/uPlot/demos/zoom-wheel.html) (in the x direction). this way i don't have to disable standard zoom behavior with normal mouse button drag. you can tweak this further to suit your needs. if you want to disable standard zoom by toggling off the `cursor.drag` options:

https://github.com/leeoniya/uPlot/blob/56db9398a33bf16c5ab41c70948252c000a63697/dist/uPlot.d.ts#L239-L250

> My JS is almost non-existent, so it's a bit of a challenge for me...

since my time is rather limited currently, i would recommend asking for additional/general JS and DOM help on stackoverflow.

**Comment by leeoniya** [comment]
ef5648c adds a `cursor.dataIdx` API, which is a transform from the hovered index into the final data index used for legend display and cursor points rendering. this api can be used to implement a search over the series' data to find the nearest non-null index:

https://leeoniya.github.io/uPlot/demos/nearest-non-null.html

**Comment by mindv0rtex** [comment]
> since my time is rather limited currently, i would recommend asking for additional/general JS and DOM help on stackoverflow

I apologize if my request came across as asking for general JS help. You've addressed my questions better than I have hoped for already! I'll figure out the rest.

Огромное Вам спасибо :-)

**Comment by leeoniya** [comment]
пожалуйста :)
