### ISSUE TITLE
Sample usage in React Component ?

### ISSUE THREAD

**Issue by tawacoool** [leeoniya/uPlot#283]
Do you have any example on how to use this with React ?

**Comment by leeoniya** [comment]
i don't use React, so i'm afraid i cannot provide too much guidance here.

i hacked something together based on the first code snippet from https://reactjs.org/docs/integrating-with-other-libraries.html

https://codesandbox.io/s/zen-banach-hj711?file=/src/MyPlot.js

while this technically kinda works, i doubt it's the idiomatic way of doing it, especially now that everything new in react-land is based on useState & useEffect hooks.

if someone wants to contribute a proper integration example, there's already an empty wiki prepared:

https://github.com/leeoniya/uPlot/wiki/Integration-Examples

**Comment by ewoodbury** [comment]
Played with your example a bit, here it is using hooks. The useRef hook is a bit unintuitive, so hopefully this can help someone:
https://codesandbox.io/s/black-sun-md3js9-mq7m3

**Comment by nielsuit227** [comment]
@ewoodbury Do you have some example usage with useRef? The plots are amazing, but getting them stateful is a bit of a pain.
