### ISSUE TITLE
Change Y scale with 'auto' or static range dynamically

### ISSUE THREAD

**Issue by zhiyishou** [leeoniya/uPlot#285]
I got a request that need to place a button that change the Y scale range to 'auto' or [0, 360], after a lot of tries and issues read, the code below could work but I don't sure it's the best approach. 

I set option to 
```
option = {
    scales:{
        y:{
            auto: true    
        }
    }
}

chart = new uPlot(...);
```

and call the setScale after setData:
```
chart.setData(data);

if(isYRangeFixed){
    chart.setScale('y',{
        min: 0,
        max: 360
    };
}
```

I suspect the code is inefficient, maybe the `setData` trigger redraw and `setScale` trigger twice?  when I use `setData(data, false)` x scale will stop auto scaling, is there a efficient way to achieve this function?

I just get into the project about 4 hours after I have been tortured by ECharts to realtime data streaming for years.

Thanks

**Comment by leeoniya** [comment]
you should leave `scale.auto: true` and use `scale.range` to conditionally override the autoscaling:

https://jsfiddle.net/3p4o0s5z/

**Comment by zhiyishou** [comment]
Awesome!!! You just made my day, I have spent one night for this question, thank you very much.

**Comment by leeoniya** [comment]
no problem.

actually, the proper answer is to re-use uPlot's default internal ranging logic [1]. this way you don't get a scale range that's exactly from `dataMin` to `dataMax`, but has additional padding applied above and below, and some 0-related affinity as well:

```js
y: {
   range: (self, dataMin, dataMax) => isYRangeFixed ? [0, 360] : uPlot.rangeNum(dataMin, dataMax, 0.1, true)
}
```

[1] https://github.com/leeoniya/uPlot/blob/958f28b5e537d8437732679650b5397377877c89/src/uPlot.js#L182-L184
