### ISSUE TITLE
Zoom touch demo throws error

### ISSUE THREAD

**Issue by soapnrope** [leeoniya/uPlot#286]
Zoom touch demo throws error when pinching on mobile device or chrome emulator.

https://leeoniya.github.io/uPlot/demos/zoom-touch.html

![image](https://user-images.githubusercontent.com/6512443/89631419-6db6f180-d8a9-11ea-8b34-47b6f2359196.png)

Looks like scale.min/max is NaN after first pan, although couldn't figure out the quick fix.

**Comment by leeoniya** [comment]
> Looks like scale.min/max is NaN after first pan

there was a known issue with panning using only one finger, which is now fixed. i suspect this was the cause here as well.

let me know if this still happens, (and with exact steps to reproduce).
