### ISSUE TITLE
line-step demo has incorrect path values for first and last points

### ISSUE THREAD

**Issue by tomforster** [leeoniya/uPlot#288]
I'm not confident enough in my correctness here to create this as a pull request, but I believe that demo/line_stepped.html line 45 needs to be converted to a canvas position rather than using the raw data, i.e. change:

`stroke.moveTo(Math.round(xdata[0]), Math.round(ydata[0]));`
to
`stroke.moveTo(Math.round(u.valToPos(xdata[0], scaleX, true)), Math.round(u.valToPos(ydata[0], scaleY, true)));`

It may also be missing the final vertical line as it skips the final index in the loop, my naive fix is to add:

`if(i === i1-1) stroke.lineTo(x1, y1);`

below line 54.

**Comment by leeoniya** [comment]
hey @tomforster 

yep, both those fixes look good to me if you wanna PR them.

please use loose equality and 2 lines for the `if`:

```js
if (i == i1 - 1)
  stroke.lineTo(x1, y1);
```

thanks!
