### ISSUE TITLE
log scales

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#29]
this might be somewhat involved, since grid & axes ticks are equally spaced right now, and determination of granularity is based around this fact.

**Comment by danekasper** [comment]
Hi Leeoniya, I thought perhaps I might be able to hack in a log10 and pow10 to draw a log scale. It works for the set values, but the auto determination of the interim steps does it's own thing. Can I override it? Or, is it as you say, somewhat involved?
![image](https://user-images.githubusercontent.com/5305693/76301481-6ac3cf00-6312-11ea-92f7-fe0d678dede4.png)
(https://danekasper.github.io/viz/covid)

**Comment by leeoniya** [comment]
interesting :)

> Can I override it?

you can override it via `axis.split() => grid/ticks offsets array`

> Or, is it as you say, somewhat involved?

since this issue was opened the internals have been revamped significantly and are more conducive to making this work in the core. if you want to take a stab at it, that would be cool.

the idea is to be able to set `scales.y.distr = 3` and have any axes using it, plus cursor/live legend to behave logarithmically.

the core parts to augment would be

1. anything that checks `distr`
2. a version of `axis.split` that can return grid/tick offsets that make sense for any given min/max range.
3. a version of `axis.values` which can take those offsets and return an array of tick labels which will not collide during rendering.
4. the internal `scaleValueAtPos()`, `getYPos()` must take into account the scale distr and return the correct canvas or css offsets
5. if the x axis can be logorithmic, then `closestIdxFromXpos()` & `closestIdx()` will also need to account for a logarithmic distr.

i think that's basically it.

**Comment by leeoniya** [comment]
i've made some progress. here's a log-log plot:

![image](https://user-images.githubusercontent.com/43234/85231392-29849600-b3bc-11ea-8e5b-60992e2e6411.png)

@Cryptkeeper, looks like a log-y would work well for the main chart on https://www.minetrack.me/, since it has one huge outlier which makes the differences in the others imperceptible.

should be ready by next release. we'll celebrate by bumping the minor version: (v1.1.0)

**Comment by leeoniya** [comment]
i expect to finish this work in the next few days.

a preview using scraped data of what the main https://www.minetrack.me/ chart would look like using log scales. cc @Cryptkeeper.

![log-scales](https://user-images.githubusercontent.com/43234/87228221-5a297100-c365-11ea-987a-68fbf1562c92.PNG)

**Comment by 153957** [comment]
Is is possible to use scientific notation for the vertical axes tick marks, and maybe only show the power of 10 lines.
for example just the 10⁻¹, 10⁰, 10¹, 10², 10³, 10⁴, 10⁵, 10⁶, etc..

**Comment by leeoniya** [comment]
> Is is possible to use scientific notation for the vertical axes tick marks

yes it's always possible to do this by customizing `axis.values`, which is the tick value formatter. i'm going to avoid implicitly intertwining `scale` and `axis` options, though, to keep everything as atomic as possible without magic. also, some people might prefer to use javascript's native `.toExponential()`, which outputs numbers like `5e-1`, which is more readable than superscripts at smaller font sizes.

> and maybe only show the power of 10 lines

this is possible by customizing `axis.split`. the current implementation in my local WIP is below, and should be easy to override with a version that uses an adjusted splitting strategy. it's unlikely that uPlot will add an axis-level toggle which specifically caters log scales (again, to avoid intertwining scale/axis concerns, though i guess you can argue that *internally* uPlot already auto-switches splitting strategies based on the axis's scale :D).

```js
export function logAxisSplits(self, scaleMin, scaleMax, incr, pctSpace, forceMin) {
  const splits = [];

  let split = incr = scaleMin;

  do {
    splits.push(split);
    split = +(split + incr).toFixed(12);
    if (split >= incr * 10)
      incr = split;
  } while (split <= scaleMax);

  return splits;
}
```

**Comment by leeoniya** [comment]
on second thought, i'll make `.toExponential()` the default formatting strategy on log-scale axes, since on log-log plots this will reduce the likelyhood of label collisions along x, as the labels are likely to get long.

**Comment by leeoniya** [comment]
it looks like this will take a bit longer, but it will end up much better.

an inconvenient property of log scales is that it's mathematically impossible to plot negative numbers, or 0 on a log scale because log10 is undefined for numbers <= 0.

the current implementation would have to come with this unfortunate caveat. and the internals made some assumptions that all data would be > 0 to simplify some ranging and axis splitting logic.

the good news is that a simple thing called a Log Modulus Transform [1] can be used to remove these limitations. however, it will also be necessary to update the ranging and splitting logic to account for a full data range. as well as more testing.

[1] https://blogs.sas.com/content/iml/2014/07/14/log-transformation-of-pos-neg.html

**Comment by leeoniya** [comment]
there is now log support via `scale.distr = 3`.

in the end, using the log modulous transform was not as straightforward as the article made it look. they use `+1` in `L(x) = sign(x) * log(|x| + 1)` because it happens to work for that dataset since for a range of 0-10k, 1 is basically 0. but this doesnt work if your dataset is eg 0.01 - 10. in that case you might want to use 0.001 as the offset. there is also a bunch of additional code that needs to go in to determine exactly how many magnitudes below and above zero make logical sense to show, and how to handle the cross-over at 0.

anyways, i didn't want to hold up this issue to figure this all out, especially since for 99% of cases it's assumed that all data will be > 0. i originally thought that log scales would be a great way to squash outliers without losing detail, but this is really only true for *high* outliers; the effect on *low* outliers is quite the opposite and you would end up possibly making the situation worse by allocating more chart area to them. so, log scales just a good way to view data as a % rather than absolute values on a wide scale range, which they do quite well:

https://leeoniya.github.io/uPlot/demos/log-scales.html

i can revisit the log-modulus thing in the future if it ever comes up.
