### ISSUE TITLE
Series fill below 0

### ISSUE THREAD

**Issue by evanbarter** [leeoniya/uPlot#292]
Hi, thanks for the helpful library.

Just wondering if I've missed something here. When setting a fill on a series with mixed positive and negative points, the fill is always (0,y). Is there any way to fill (minY, y)?

<img width="503" alt="Screen Shot 2020-08-21 at 11 33 55 AM" src="https://user-images.githubusercontent.com/583308/90925830-c0fb6a80-e3a6-11ea-8be9-f9e999a12fd0.png">

**Comment by leeoniya** [comment]
another use for it here: https://leeoniya.github.io/uPlot/demos/y-shifted-series.html
