### ISSUE TITLE
First display without data

### ISSUE THREAD

**Issue by zhiyishou** [leeoniya/uPlot#294]
Thanks for Contributors' work on this project, it grows so fast and robust.

I'm plotting streaming data from usb, a problem is when the data is not starting, the chart will not show up. I was use below codes in V1.1.0 to make chart show up with empty data for a better user experience.
```
let chart = new uPlot(option, [
        [0],
        [0]
    ], chartDom);

chart.setData([
    [],
    []
])

//the chart will display now and nothing plotted
```

Below is a screenshot in V1.1.2
![image](https://user-images.githubusercontent.com/5999163/91172078-31d7b500-e70e-11ea-9fe8-a787023eb663.png)

Seems in latest version it's not working, only cursor and series legend showing, maybe is there an another way to achieve this? I checked and got no solution from latest commits.

**Comment by zhiyishou** [comment]
Looks using `setData([])` to clear the data plot is not working either.

But with redraw() will works.
```
function clearChart(){
    chart.setData([]);
    chart.redraw();
}
```

Is the latest commits do some thing about limitation of minimum points number?

**Comment by leeoniya** [comment]
hi @zhiyishou 

i have found several bugs with scale setting when there is 0 or 1 points. i am working to fix them but it may be several days.

**Comment by leeoniya** [comment]
@zhiyishou please try the latest build.

the proper way to create a chart which handles empty data (by setting pre-defined scales) is below. you can then use `.setData(null)` to clear the chart.

https://github.com/leeoniya/uPlot/blob/2bee98484d7fde9fb2513df470f90a65313e29bb/demos/no-data.html#L18-L46

**Comment by zhiyishou** [comment]
@leeoniya I have tested latest version and works great, thanks for your contribution.
