### ISSUE TITLE
Using only certain series for scaling

### ISSUE THREAD

**Issue by noobymcnoob** [leeoniya/uPlot#297]
Is it possible to configure the Scale https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L285 such that only certain series are used for scaling the axis?

I tried setting `auto` to false, as well as `min/max` to `null` but seems like there is no way to exclude certain series from scaling.

The reason is that I am only interested in seeing certain series if they close in on another series (think moving average).

Any suggestions?

**Comment by leeoniya** [comment]
i'll add `series.auto` so they can be excluded

**Comment by noobymcnoob** [comment]
> i'll add `series.auto` so they can be excluded

Awesome! Will try it out when ready. I've got a bunch of series that I currently disable manually when I don't want to see them which is slightly annoying.

**Comment by leeoniya** [comment]
even without this, i think you should be able to get this done be implementing a custom `scale.range`:

untested:

```js
{
    scales: {
        y: {
            auto: true,
            range: (u, dataMin, dataMax) => {
                let min = Infinity;
                let max = -Infinity;
                
                u.series.forEach((s, i) => {
                    if (i > 0 && series.auto !== false) {
                        min = Math.min(min, s.min);
                        max = Math.max(max, s.max);
                    }
                });

                return uPlot.rangeNum(min, max, 0.1 true);
            }
        },
    }
    series: [
        {},
        {
            auto: false
        },
        {},
    ],
}
```

the benefit of `series.auto` would be

1. elegance (less custom code)
2. uPlot can avoid scanning the series to git the initial s.min & s.max

**Comment by noobymcnoob** [comment]
I would say given your goals for the library to keep things simple that performance is a valid reason but I like your example here, I think this will work. I will try it out today. Thanks again.

**Comment by noobymcnoob** [comment]
Can confirm this works, after spending 2 hours debugging a data issue :-) 

Thanks Leon!
