### ISSUE TITLE
scatter instead of line

### ISSUE THREAD

**Issue by gebrits** [leeoniya/uPlot#3]
Would it be easy (and still performant) to be able to choose for a scatterplot instead of linechart per series?

**Comment by leeoniya** [comment]
i think a scatter plot at the density of the bench would perform worse than a line chart, but this would be true of any chart lib. i do plan on adding an option to also render data points (whether or not it's a good idea for the data quantity is another matter). i think adding an option afterwards to disable line drawing should be easy.

i think this would logically follow #2

**Comment by leeoniya** [comment]
i may have to walk back on this one. the main issue is that a single series cannot have multiple y values. uPlot expects a csv-like data structure:

```js
const data = [
  [1566453600, 1566457260, 1566460860, 1566464460],   // Unix timestamps
  [0.54,       0.15,       3.27,       7.51      ],   // CPU
  [12.85,      13.21,      13.65,      14.01     ],   // RAM
  [0.52,       1.25,       0.75,       3.62      ],   // TCP Out
];
```

it relies on a binary search over the ascending x values to look up the corresponding values of y at that single point. even if you sorted x/y pairs by their x values, uPlot requires that everything is properly aligned. let's say you had these x/y pairs: `[2,5], [2,9], [4,7],[5,1]`, the data would need to be massaged into this format of multiple series:

```js
const data = [
  [2,    4,    5], 
  [5,    7,    1]
  [9, null, null],
];
```

it's an ugly, inefficient hack. ideally, an efficient scatterplot dataset would look like this: 

```js
const data = [
  [2, 5, 2, 9, 4, 7, 5,1]    // series 1
  ...
];
```

but this would drastically change the way in which data is searched, iterated, re-scaled, etc. i think that probably only 50% of the existing code could be reused (mostly related to DOM and actual Canvas loops), but everything else would have to be written differently.

**Comment by leeoniya** [comment]
long story short, i dont see this happening in the near future, though additional chart types which can be represented by the current data structure will be supported (see https://github.com/leeoniya/uPlot/issues/9)
