### ISSUE TITLE
Drawing multiple series when one of series have fewer values (rest is nulls)

### ISSUE THREAD

**Issue by FrantisekPostl** [leeoniya/uPlot#302]
hi, i'm using uPlot version 1.1.2, chrome version 85.0.4183.102.

When i have multiple seris and one of them don't have all values (rest is filled with null), i'll get this result.

Flow rate have last value 3.9.2020, Hladina test have all values.

![uplot-bug](https://user-images.githubusercontent.com/45075510/93077936-e1f36a80-f689-11ea-8dda-d4b9cebbf0c7.png)

**Comment by leeoniya** [comment]
please provide your dataset so i can reproduce the issue.

**Comment by FrantisekPostl** [comment]
Hi. thank you for quick response, here it is:

[chart data.txt](https://github.com/leeoniya/uPlot/files/5224119/chart.data.txt)

**Comment by leeoniya** [comment]
your timestamps are not in strictly ascending order:

https://github.com/leeoniya/uPlot/tree/master/docs#data-format

![image](https://user-images.githubusercontent.com/43234/93233883-39084680-f741-11ea-936b-226778c2c280.png)

**Comment by FrantisekPostl** [comment]
Thank you
