### ISSUE TITLE
scale.range of default x/y scales should be initialized without series

### ISSUE THREAD

**Issue by NoahBres** [leeoniya/uPlot#309]
I get the following error when upgrading to uPlot 1.2.1:

![Screen Shot 2020-09-19 at 10 14 49 PM](https://user-images.githubusercontent.com/6739076/93693440-8976ff80-fac5-11ea-955e-ebee2abe3552.png)

Line in question:

![Screen Shot 2020-09-19 at 10 15 07 PM](https://user-images.githubusercontent.com/6739076/93693446-9398fe00-fac5-11ea-95c0-67230d3f5b5f.png)

 
Honestly not sure if this error is due to 1.2.1 specifically. I upgraded directly from 1.1.2 so I will roll back and see which versions causes the issue.

**Comment by NoahBres** [comment]
Might actually be something wrong with my build configuration. Please disregard until I figure it out.

**Comment by leeoniya** [comment]
it's almost certainly the next commit following 1.2.1: https://github.com/leeoniya/uPlot/commit/fe5fac73eaf1caf753a5eb9fea6b41cbc0a9bea4

that code runs for y scales of empty charts (without data).

the default scale ranging functions get initialized as part of iterating the series arrays (since series can implicitly initialize new scales simply by specifying a unique key):

https://github.com/leeoniya/uPlot/commit/fe5fac73eaf1caf753a5eb9fea6b41cbc0a9bea4

however, there are always default x and y scales created on init. so i'm guessing you are initializing a data-less plot with no y series? (i'm on a phone but i think those are the necessary conditions here).

a repro would obviously help.

**Comment by NoahBres** [comment]
> however, there are always default x and y scales created on init. so i'm guessing you are initializing a data-less plot with no y series?

I believe I was doing this but I switched some code around and generated data before the graph is initialized (it's a live visualization so data is streaming) and it does not seem to change anything.

I am hoping to get a live reproduction up but that is having it's own different issue :P

**Comment by NoahBres** [comment]
Ah. It was an empty y series. My apologies. It was due to some async problems.
Thank you so much for your patience!

**Comment by leeoniya** [comment]
no problem. i still think this is an issue, though.

the solution is most likely to also init `scale.range` for the default scales here:

https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L246

**Comment by jasonatball** [comment]
I'm seeing the same issue since 1.2.1:
```
TypeError: wsc.range is not a function
    at setScales (webpack-internal:///./node_modules/uplot/dist/uPlot.esm.js:1624)
    at setScale (webpack-internal:///./node_modules/uplot/dist/uPlot.esm.js:2320)
    at _setScale (webpack-internal:///./node_modules/uplot/dist/uPlot.esm.js:2403)
    at _setSize (webpack-internal:///./node_modules/uplot/dist/uPlot.esm.js:1306)
    at Object.setSize (webpack-internal:///./node_modules/uplot/dist/uPlot.esm.js:1312)
    at VueComponent.resize
```

**Comment by leeoniya** [comment]
> Is there an easy workaround? I display my empty chart and then dynamically add items to it.

i think the recommendation going forward if you want to handle a data-less (or series-less) case will be to explcitly provide `scale.range` which handles the `null` case when there is no data from which to autoscale. this will be better than relying on uPlot to do some sort of ambiguous "right thing" magic.

see the first example here:

https://github.com/leeoniya/uPlot/blob/master/demos/no-data.html

**Comment by jasonatball** [comment]
Interesting. Before I was just doing this in my scales:
```
        scales: {
          x: {
            min: Math.round(new Date().getTime() / 1000),
            max: Math.round(new Date().getTime() / 1000) + 1000
          },
          y: {
            min: -100,
            max: 100
          }
        }
```
Your example has me doing this now which works:
```
        scales: {
          x: {
            range(u, dataMin, dataMax) {
              if (dataMin == null) return [1566453600, 1566497660]
              return [dataMin, dataMax]
            }
          },
          y: {
            range(u, dataMin, dataMax) {
              if (dataMin == null) return [-100, 100]
              return uPlot.rangeNum(dataMin, dataMax, 0.1, true)
            }
          }
        }
```

**Comment by leeoniya** [comment]
yeah, that method turned out to be tricky to support in the case when you go from data to no-data but the original min/max is now gone
 also in combo with range it becomes very inconsistent to explain. using only range handles all cases clearly.

**Comment by NoahBres** [comment]
I'm late but thank you so much! You're awesome <3
