### ISSUE TITLE
logical-stepped y-shifted chart

### ISSUE THREAD

**Issue by vinnitu** [leeoniya/uPlot#312]
Hi!

Trying implement for logical serial data (0 or 1) something like this

![image](https://user-images.githubusercontent.com/432168/94118937-ddcc0780-fe56-11ea-9718-7918f8d3cac0.png)

to show logical level metrics on same chart

I saw **y-shifted-series.html** and **line-stepped.html** with custom paths

Here is [my implementation](https://jsfiddle.net/cs6e8o94/1/) of logical-stepped chart with custom paths (**null** for gap, **undefined** for unknown value)

To make y-shifted chart I planned use **fillTo** key in series but can understand how do is properly.

Can you direct me to rational implementation way?

Thank!

**Comment by leeoniya** [comment]
i guess there's a bit of overlap with #188 as well :)

> To make y-shifted chart I planned use fillTo key in series but can understand how do is properly.

`fillTo` is a parameter used only by uPlot's internal path builder. this setting will have no effect when you're building your own paths (as you have to for stepped charts), but you can see that the logic is very easy to replicate in your own path builder:

https://github.com/leeoniya/uPlot/blob/e796aa62cd4129da820aedf8777818d5115fd116/src/uPlot.js#L1125-L1127

the two demos you found can be combined to create the chart you're showing. unfortunately, i don't currently have time to do this for you.

**Comment by leeoniya** [comment]
another route you might consider is using multiple charts in a vertical arrangement. disable x axis & legend display on all but the bottom one, synchronize cursors across them all, and use a single stacked legend by pulling values from a shared data  array based on hovered index (via `series.values`, see https://leeoniya.github.io/uPlot/demos/time-periods.html)

this will be somewhat less efficient than a single chart but you can avoid the y shifting code in the path builder and will only need the stepped code as-is. it may also have the benefit of not having to null-fill the series if your incoming per-series data is not exactly aligned.

**Comment by leeoniya** [comment]
stepped paths are now part of the core, so it should be easy to replicate the y-shfted demo using them: https://jsfiddle.net/4pfkj7tm/
