### ISSUE TITLE
Can i show image use uplot?

### ISSUE THREAD

**Issue by hxse** [leeoniya/uPlot#316]
For example, Find a common png images, Convert it to RPG Array.
And show RPG Array with uplot.

**Comment by leeoniya** [comment]
uPlot exposes a `self.ctx` property, which can be used to draw on the canvas:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData
