### ISSUE TITLE
Major tick alignment

### ISSUE THREAD

**Issue by benmccann** [leeoniya/uPlot#32]
I wrote a feature for Chart.js that I've been calling "major ticks". I think it's best demonstrated with this example: https://www.chartjs.org/samples/latest/scales/time/financial.html

As you can see, it makes sure that the first hour, day, month, etc. is chosen for use as a label and formatted differently.

Is this a feature you'd be interested in adding to uPlot? If so, I'd be happy to help describe how it works in more detail. It's slightly slower than just naive label display since it needs to do some extra calculation, but not by much. In Chart.js it's an option so you can turn it on and off, and I'm sure we could do the same here.

**Comment by leeoniya** [comment]
i think this is already possible in uPlot since https://github.com/leeoniya/uPlot/issues/12 by overriding some implicit opts for time scales/axes.

the major/minor labels are determined here: https://github.com/leeoniya/uPlot/blob/master/src/opts.js#L102

**Comment by leeoniya** [comment]
the initial tick along the time axis is also determined here: https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L395

**Comment by benmccann** [comment]
Wow, that's great! Thanks so much for the response :-)

It'll probably take me a little while before I get time to try this out, but I'm looking forward to playing around with it

**Comment by leeoniya** [comment]
@benmccann if you're up for contributing code to uPlot, #10 is a good one (and quasi finance-related). i don't think #29 is gonna work out for uPlot since that'll need tentacles into everywhere.

**Comment by benmccann** [comment]
The links above don't work anymore, so pasting permalinks here for my later reference

First tick: https://github.com/leeoniya/uPlot/blob/5b7e0681395a3ea6cd2b05de0583ca14632b5e80/src/uPlot.js#L395

`axis.values` and `axis.range`: https://github.com/leeoniya/uPlot/blob/5b7e0681395a3ea6cd2b05de0583ca14632b5e80/src/uPlot.js#L215

**Comment by leeoniya** [comment]
you're probably better off linking the current code:

https://github.com/leeoniya/uPlot/blob/42169be506338fb392e52379fb94f501d50aef17/src/opts.js#L129-L234

**Comment by benmccann** [comment]
Thanks!

A small performance improvement I noticed in the current code is that it looks like the `let s =` line could be moved outside `ticks.map` so that you only have to do it once

**Comment by benmccann** [comment]
> values can be:
a function with the form (self, ticks, space) => values where ticks is an array of raw values along the axis' scale, space is the determined tick spacing in CSS pixels and values is an array of formated tick labels.

One question about this section in the README. Does the `ticks` array that's passed in contain one entry per data point or one entry per label?

**Comment by leeoniya** [comment]
per label. the actual tick determination is done by timeAxisTicks.
