### ISSUE TITLE
feature Canvas2D to WebGL

### ISSUE THREAD

**Issue by hxse** [leeoniya/uPlot#323]
I found a package that can convert canvas to webgl.
https://github.com/jagenjo/Canvas2DtoWebGL
Consider integrating it into Uplot to further improve performance?
Is it feasible to use in the exposed self.ctx property of uplot?

**Comment by leeoniya** [comment]
hey @hxse 

i've considered this, along with some other 2D renderers that have canvas-like semantics that have WebGL backends: [two.js](https://two.js.org/) and [Pixi.js](https://www.pixijs.com/).

one major drawback is the additional size. Canvas2DtoWebGL relies on 175 KB of litegl plus 50 KB of gl-matrix:

https://github.com/jagenjo/litegl.js/blob/master/build/litegl.min.js
https://github.com/toji/gl-matrix/blob/master/dist/gl-matrix-min.js

native webgl does not provide a way to draw lines of a thickness > 1 [1], so your shaders must draw the lines as triangles. additionally, uPlot uses `Path2D` objects for path caching, which Canvas2DtoWebGL does not support. most webgl implementations i've seen do not support gaps in the data - they assume typed arrays without null values.

> Is it feasible to use in the exposed self.ctx property of uplot?

from what i've seen, i don't think it's very feasible and the size increase would be quite large. the performance impact is likely to be minimal unless all of uPlot's path-building accommodations were rewritten into native webgl shaders, which is certainly not a simple task.

[1] https://stackoverflow.com/questions/47444239/how-to-use-gl-linewidth
