### ISSUE TITLE
.setScale() for Y should also bail when exceeding max precision

### ISSUE THREAD

**Issue by entaroadun7** [leeoniya/uPlot#324]
Hi,

I'm new to uPlot and I just started to get familiar with this awesome library. While doing some tests based on the provided example (https://leeoniya.github.io/uPlot/bench/uPlot.html) and with "drag" option enabled for both axes I'm getting some issues when zooming chart multiple times (40-50). Errors from the console log:

    uPlot.iife.min.js:2 Uncaught TypeError: Cannot read property '0' of undefined
    at uPlot.iife.min.js:2
    at Array.forEach (<anonymous>)
    at uPlot.iife.min.js:2
    at ue (uPlot.iife.min.js:2)
    at We (uPlot.iife.min.js:2)
    at HTMLDocument.Ie (uPlot.iife.min.js:2)_

Google Chrome version: 85.0.4183.121
Operating System: Ubuntu 18.04.5 LTS
Kernel: Linux 4.15.0-118-generic
Architecture: x86-64

**How to reproduce the problem:**
1. Use the example https://leeoniya.github.io/uPlot/bench/uPlot.html
2. Change cursor.drag option to:
    `cursor: {
        drag: {
          x: true,
          y: true
        }
      }`
3. Do the zoom on the chart multiple (40-50) times

I'm also trying to use uPlot in the Angular + Electron environment. When testing the same example with "drag" option enabled for X and Y axes I'm getting the following issues:

    core.js:4081 ERROR TypeError: getIncrSpace is not a function or its return value is not iterable
    at uPlot.esm.js:2134
    at Array.forEach (<anonymous>)
    at drawAxesGrid (uPlot.esm.js:2119)
    at paint (uPlot.esm.js:2291)
    at batch (uPlot.esm.js:2565)
    at HTMLDocument.mouseUp (uPlot.esm.js:2909)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27137)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)

When adding more Series (11) for the Angular + Electron example I'm getting "out of memory" exception. Probably this is an issue with wrong configuration of the Angular+Electron on my side, but maybe it's something related to the first problem described ?

Thank you in advance.

**Comment by leeoniya** [comment]
hi @entaroadun7 

there are some provisions in `.setScale()` for the limiting X axis zoom and bailing at resolutions that would run into Number precision limits when generating axis ticks. it looks like a similar thing is happening for Y axes and i need to add similar bail-outs. this will have the side-effect that running into a precision limit on one y axis will prevent zooming into all others on the same scale.

https://github.com/leeoniya/uPlot/blob/1a468670fca6ee1a10d2af0bae71da705f241092/src/uPlot.js#L1415-L1426

> Probably this is an issue with wrong configuration of the Angular+Electron on my side

yeah, you'll likely need to isolate & repro this in a browser env to troubleshoot further.

**Comment by leeoniya** [comment]
the attached patch should improve the situation significantly.

**Comment by entaroadun7** [comment]
Hi @leeoniya 

thank you very much for solving the issue. I tested the commit https://github.com/leeoniya/uPlot/commit/091b19c9eef6514c91b4ac50cc623921ddc49fdd and it fixed the issue described in the first post, but after introducing the changes in the commit  https://github.com/leeoniya/uPlot/commit/04c054156c3941ab1ab8bf8ab3cb9eea2d923d32 it seems that both cases "_uPlot.iife.min.js:2 Uncaught TypeError: Cannot read property '0' of undefined_" and "_core.js:4081 ERROR TypeError: getIncrSpace is not a function or its return value is not iterable_" are back again. Would you be able to check that one for me too ?

Best regards,
entaroadun7

**Comment by leeoniya** [comment]
can yu please provide a repro to trigger this? i can no longer trigger the original conditions as descrived for the uPlot bench. here's the code i'm using:

```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>μPlot Demo</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="../dist/uPlot.min.css">
        <style>
            body {
                margin: 0;
            }

            .u-legend.u-inline .u-value {
                width: 150px;
                text-align: left;
            }
        </style>
    </head>
    <body>
        <script src="../dist/uPlot.iife.js"></script>
        <h2 id="wait">Loading lib....</h2>

        <script>
            function round2(val) {
                return Math.round(val * 100) / 100;
            }

            function round3(val) {
                return Math.round(val * 1000) / 1000;
            }

            function prepData(packed) {
                console.time("prep");

                // epoch,idl,recv,send,read,writ,used,free

                const numFields = packed[0];

                packed = packed.slice(numFields + 1);

                // 55,550 data points x 3 series = 166,650
                let data = [
                    Array(packed.length/numFields),
                    Array(packed.length/numFields),
                    Array(packed.length/numFields),
                    Array(packed.length/numFields),
                ];

                for (let i = 0, j = 0; i < packed.length; i += numFields, j++) {
                    data[0][j] = packed[i] * 60;
                    data[1][j] = round3(100 - packed[i+1]);
                    data[2][j] = round2(100 * packed[i+5] / (packed[i+5] + packed[i+6]));
                    data[3][j] = packed[i+3];
                }

            /*
                function filter(d) {
                    return d.filter((d, i) => Math.round(i/1000) % 5 != 2);
                }

                data[0] = filter(data[0]);
                data[1] = filter(data[1]);
                data[2] = filter(data[2]);
                data[3] = filter(data[3]);
            */
            /*
                data[0] = data[0].slice(0, 1000);
                data[1] = data[1].slice(0, 1000);
                data[2] = data[2].slice(0, 1000);
                data[3] = data[3].slice(0, 1000);

                data[1][35] = null;
                data[1][36] = null;
                data[2][730] = null;
            */
                console.timeEnd("prep");

                return data;
            }

            function makeChart(data) {
                console.time("chart");

                const opts = {
                    title: "Server Events",
                    width: 1920,
                    height: 600,
                //    cursor: {
                //        x: false,
                //        y: false,
                //    },
                    cursor: {
                        drag: {
                            x: true,
                            y: true,
                        }
                    },
                //    scales: {
                //        x: {
                //            time: false
                //    },
                    series: [
                        {},
                        {
                            label: "CPU",
                            scale: "%",
                            value: (u, v) => v == null ? "-" : v.toFixed(1) + "%",
                            stroke: "red",
                            width: 1/devicePixelRatio,
                        },
                        {
                            label: "RAM",
                            scale: "%",
                            value: (u, v) => v == null ? "-" : v.toFixed(1) + "%",
                            stroke: "blue",
                            width: 1/devicePixelRatio,
                        },
                        {
                            label: "TCP Out",
                            scale: "mb",
                            value: (u, v) => v == null ? "-" : v.toFixed(2) + " MB",
                            stroke: "green",
                            width: 1/devicePixelRatio,
                        }
                    ],
                    axes: [
                        {},
                        {
                            scale: "%",
                            values: (u, vals, space) => vals.map(v => +v.toFixed(1) + "%"),
                        },
                        {
                            side: 1,
                            scale: "mb",
                            size: 60,
                            values: (u, vals, space) => vals.map(v => +v.toFixed(2) + " MB"),
                            grid: {show: false},
                        },
                    ],
                };

                let uplot = new uPlot(opts, data, document.body);

                wait.textContent = "Done!";
                console.timeEnd("chart");

                return uplot;
            }

            let wait = document.getElementById("wait");
            wait.textContent = "Fetching data.json (2.07MB)....";
            fetch("data.json").then(r => r.json()).then(packed => {
                wait.textContent = "Rendering...";
                let data = prepData(packed);
                let u;

                setTimeout(() => {
                    u = makeChart(data)
                }, 0);

                setTimeout(() => {
                    u.batch(u => {
                        u.setScale('x', {min: 1567600710.4851427, max: 1567600710.4993143});
                        u.setScale('%', {min: 14.573779120014906, max: 14.573779120043511});
                    })
                }, 2000);

                setTimeout(() => {
                    u.batch(u => {
                        u.setScale('x', {min: 1568046215.2288318, max: 1568046215.2345016});
                        u.setScale('%', {min: 14.573779120022353, max: 14.573779120022357});
                    })
                }, 4000);
            });
        </script>
    </body>
</html>
```

**Comment by entaroadun7** [comment]
Hi @leeoniya,

you're right. The issue is resolved. Sorry for misleading you. Probably I wrongly rebuild the application and the version 1.2.2 from package.json was used and not the newest one when doing the test.

**Comment by leeoniya** [comment]
ok, thanks.
