### ISSUE TITLE
Chart not showing

### ISSUE THREAD

**Issue by antonioift** [leeoniya/uPlot#325]
Hi,
I've tried to implement uPlot to my html page.

If I put the graph like this:
`let u = new uPlot(opts, data, document.body);`
everything is good.

If I try to put in another place:
`let u = new uPlot(opts, data, document.getElementById("myChart"));`
the title and labels are showing but no pen on the chart.

![Immagine 2020-10-07 092003](https://user-images.githubusercontent.com/72490171/95299662-5df26400-087e-11eb-8e3d-8316bdc20c2f.png)

I tried with the examples but same situation.

How can I solve that?

Thanks,
Antonio

**Comment by leeoniya** [comment]
you have not provided enough information for me to help you.

you can see here that `document.getElementById('plot675795242')` works as expected: https://jsfiddle.net/buyzhq76/

i need to see your code. please create a jsFiddle that shows your problem.

**Comment by antonioift** [comment]
Here it is:

https://jsfiddle.net/nhw4mfyx/2/

Doing some tests, I found that there is an "incompatibility" with the vue component.
If I delete that, the plot is working as expected.

What can I do?

Thanks.

**Comment by leeoniya** [comment]
i'm not very familiar with Vue, but you probably want to use its `mounted` option [1] to init the chart: https://jsfiddle.net/ksj3cyrv/

[1] https://vuejs.org/v2/api/#mounted

**Comment by antonioift** [comment]
Perfect!!! Now is working good.

Thank you very much!
