### ISSUE TITLE
range selector with min/max grips

### ISSUE THREAD

**Issue by MartijnHarmenzon** [leeoniya/uPlot#330]
Just some questions.. Are there any plans for a range selector like dygraphs/plotly? Or perhaps as a plugin? Or is this part of the non-features?

https://dygraphs.com/gallery/#g/range-selector

**Comment by MartijnHarmenzon** [comment]
Just noticed #181. Would be awesome if this would ever be implemented.

**Comment by leeoniya** [comment]
it was definitely implemented as a plugin, in a few different demos. check the **Zooming** section:

https://leeoniya.github.io/uPlot/demos/index.html

**Comment by leeoniya** [comment]
i'll have something in a few days.

**Comment by leeoniya** [comment]
i've added a demo which should serve as a good starting point. feel free to contribute improvements.

https://leeoniya.github.io/uPlot/demos/zoom-ranger-grips.html
