### ISSUE TITLE
backgroundColor is sometime undefined

### ISSUE THREAD

**Issue by GitHubLionel** [leeoniya/uPlot#331]
Hi,

First, thanks for this great library. Really super :)
I notice that in line 1267 of "uPlot.iife.js" : indic.style.backgroundColor = s.fill;
s.fill is sometime undefined so I correct with this : 
indic.style.backgroundColor = (s.fill == undefined ? "rgba(0,0,0,0.07)" : s.fill);
Not sure that it is good but it works :)

Also in the demo candlestick-ohlc.html, on line 52 : if (currIdx !== u.cursor.idx) {
u.cursor.idx is sometime null so I correct with this : 
if ((currIdx !== u.cursor.idx) && (u.cursor.idx !== null)) {

Best regards,
Lionel

**Comment by leeoniya** [comment]
hey @GitHubLionel 

does `undefined` cause any adverse effects?

i'm sure there are many places in the codebase which end up this way, but unless it causes issues, i don't really want to add extra checks all over the place.

**Comment by GitHubLionel** [comment]
Hi,

No adverse effects detected but warning in Firefox. But I think it is better to avoid some futures problems !
I looked deeper and the problem can by solve simply by default initialization for the "fill" property. 
Just add fill: "rgba(0,0,0,0.00)", to the xSeriesOpts property (line 860) and to ySeriesOpts (line 990).

Best regards,
Lionel

**Comment by leeoniya** [comment]
should be fixed now (apparently `null` works okay).

thanks!

**Comment by GitHubLionel** [comment]
Great :)
