### ISSUE TITLE
Easily add vertical line to chart

### ISSUE THREAD

**Issue by GoodMorgon** [leeoniya/uPlot#332]
Hello,

First off, great package! (long-time fan of dygraphs)

Is there a way to easily add a vertical line to a graph? I've checked the API and docs but there didn't seem to be a documented way, but I'm thinking it shouldn't be that hard...

Thanks!

**Comment by GoodMorgon** [comment]
Closing for https://github.com/leeoniya/uPlot/issues/119

**Comment by leeoniya** [comment]
you simply draw on `self.ctx` in a hook of your choice.

i assume you figured it out :)

**Comment by leeoniya** [comment]
> Closing for #119

#220 actually seemed to work correctly when i tested it a few months back. i wanted to first wrap my head around exactly how it worked prior to merging. cc @EmiPhil :D
