### ISSUE TITLE
try some strategies for auto axis.size

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#333]
cc @mckn,

brain dump:

calculating axis size automatically is likely to be a tricky chicken-egg situation since the tick labels are dynamic (based on the rendered data) and are calculated based on the configured available space as well as tick density. this means guesstimating based on some default value, doing a full render pass then possibly doing a second re-render after measuring and hoping the tick density doesnt change enough to render different labels with new metrics that invalidate your measurements. rinse and repeat.

also, i'm not sure if you're looking for continuous axis size adjustment (like during zooming and tick label changes), or simply an an initial calc during init.

i'm certainly open to discussing different estimation strategies, but would like to avoid doing expensive pre-renders of all axis ticks, measuring them all, resizing and repeating until some convergance happens, since this would eat into perf quite a bit (i think).

main concerns here is that continuous axis size re-eval may require at least 2x the renders:

1. pre-render the grid & ticks with an initial default axis.size value.
2. take measurements of all ticks to see if the size is sufficient, too small, or too large.
3. adjust the size as needed, force a full re-render and pray your new metrics did not alter the tick density to now render different labels.

it may not be that scary since grid rendering is pretty cheap compared to path rendering, though ideally we can better guesstimate the labels without actually rendering them, but that seems unlikely especiallly if label auto-rotation or auto axis.space ever becomes necessary.

preferably, this auto-sizing behavior can be done in a way which allows a custom logic to make the appropriate strategy/perf tradeoffs, such as:

- expose an `axis._splits` that holds the tick values.
- provide some `axis.measure` callback that fires to allow a self.ctx.measureText() loop over the axis._splits array. this function can then mutate axis.size and return `false` to indicate that a full chart size recalc and re-render is needed.
- uplot will accumulate all axis.measure() results and force a resize/re-render (prior to any series path renders) if any return false.

this strategy would keep uPlot out of the perf-killing business and offload that to the lib consumer, allowing them to decide how many re-render passes they're willing to sacrifice.

**Comment by mckn** [comment]
Really interesting ideas! I'm kind of new this this project so I don't really follow all the difference scenarios but I agree with the conclusion that we don't want to introduce any new re-rendering.

How do we calculate the positioning for the different axis today? My take on this was basically the following:

- For any of the axis on either left or right side of the graph we need to find out how much space the longest formatted value we want do display takes in width.

- For any of the axis on either top or bottom side of the graph we need to find out how much space the longest formatted value we want to display takes in height.

Then we also need to take into consideration the scenarios where we have multiple scales on either of the axis. But if we could figure out (in a smart way) what those are we should be able to use the `measureText` function on the context, right?

**Comment by torkelo** [comment]
this I think is the top prio issue for the Grafana uplot Graph.

**Comment by leeoniya** [comment]
👍

**Comment by leeoniya** [comment]
working on this now.

**Comment by leeoniya** [comment]
@torkelo, @mckn 

i think what's needed in uPlot is now done.

see demo: https://leeoniya.github.io/uPlot/demos/axis-autosize.html

**Comment by torkelo** [comment]
Nice!
