### ISSUE TITLE
Add tooltip to main code

### ISSUE THREAD

**Issue by GitHubLionel** [leeoniya/uPlot#335]
Hi

In the demo candlestick-ohlc, there is a great plugin for ToolTip.
Problem, this plugin use the Legend and so you can not have the two in the same time.
I think tooltip is quite often usefull so I try to put it directly in the main code. 
So to activate it, now you just add "tooltip : { show: true}" in the option.
I check most of the demos and all seems to be ok :)
I have tagged the code by : /* tooltip begin */ ... /* tooltip end */
See zip file.

Best regards,
Lionel
[tooltip.zip](https://github.com/leeoniya/uPlot/files/5401648/tooltip.zip)

**Comment by leeoniya** [comment]
closing in favor of #344 (which you mentioned includes this).
