### ISSUE TITLE
Incorrect typings for plugin support

### ISSUE THREAD

**Issue by mckn** [leeoniya/uPlot#338]
Looks like the following typings is incorrect:
https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L201

Or if feels like it when I compare it to the following code that seems to expect the opts function to return options and not being a void function call. I guess it might still work since we are mutating the opts object but then it might be better to update the code on call site:
https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L241

**Comment by leeoniya** [comment]
you're right, it should be `=> void | Options` i guess.

**Comment by mckn** [comment]
Yeah, or maybe even `=> Options` to keep it consistent.

**Comment by leeoniya** [comment]
i think my concern was about this signalling that mutation was not okay and would lead to people doing pointless deep copies.

**Comment by mckn** [comment]
> i think my concern was about this signalling that mutation was not okay and would lead to people doing pointless deep copies.

Ah, ok ok - then I would probably just change the call site and keep the current typings :)
