### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by kbrgl** [leeoniya/uPlot#34]
Hi!

uPlot seems to be perfect for my needs since I don’t need most of the knobs and whistles offered by other libraries. Thanks for making this!

Would it be possible to see it published as an NPM package?

**Comment by leeoniya** [comment]
it's not quite ready for publishing yet because i dont feel like republishing after every few commits. i'll publish once the pace slows down, the docs are fleshed out and v1 is tagged.

until then you can grab & require `./dist/uPlot.cjs.js`

**Comment by kbrgl** [comment]
That’s fine, thank you!

**Comment by joshvillbrandt** [comment]
Also came looking for an npm package. I'll look for something else if this isn't ready to be distributed. Super excited by your work though!!

PS: You could set up an automated pipeline to do the publishing work for you! I've used TravisCI and CircleCI for this. Maybe Github has it's own thing now too. 🤷‍♂️

**Comment by leeoniya** [comment]
@joshvillbrandt

still a couple breaking changes coming (#131), but soon ;)

**Comment by leeoniya** [comment]
1.0.0 is tagged and published:

https://github.com/leeoniya/uPlot/releases/tag/1.0.0
https://www.npmjs.com/package/uplot
