### ISSUE TITLE
Edit gridlines width + make uplot fill whole parent div

### ISSUE THREAD

**Issue by GoodMorgon** [leeoniya/uPlot#341]
Hello,

Is there a way to edit the colour and width of the background gridlines of a plot (see image)?

Additional, any solution for making uplot fill the whole containing div? I cannot make my plot 'flush' with an item on the same y-height (outside of picture). I've tried to modify the css properties of `u-under` and `u-over` but to no success...

 
![Untitled](https://user-images.githubusercontent.com/55554176/96754091-1ec12880-13d1-11eb-9bcc-9657fc4f7895.png)

**Comment by leeoniya** [comment]
> Is there a way to edit the colour and width of the background gridlines of a plot (see image)?

yes:

https://github.com/leeoniya/uPlot/blob/936c9b242a8e006707b239a6386e7814e13534f7/dist/uPlot.d.ts#L474-L490

> Additional, any solution for making uplot fill the whole containing div? I cannot make my plot 'flush' with an item on the same y-height (outside of picture). I've tried to modify the css properties of u-under and u-over but to no success...

you can adjust the `gutters` or `axis.size`, but you're more likely to end up with cut-off labels during zooming, etc. for a static chart it's probably okay.

https://github.com/leeoniya/uPlot/blob/936c9b242a8e006707b239a6386e7814e13534f7/dist/uPlot.d.ts#L179-L183

https://github.com/leeoniya/uPlot/blob/936c9b242a8e006707b239a6386e7814e13534f7/dist/uPlot.d.ts#L435-L436

you might also consider adding a box-shadow to better visually align the edges:

```css
.uplot {
  box-shadow: 0px 0px 3px 1px rgba(0,0,0,0.3);
}
```

**Comment by happyteque** [comment]
Looks like you have removed gutters...

**Comment by leeoniya** [comment]
they have been replaced by a much better, and more explicit `padding`. see these commits from december: https://github.com/leeoniya/uPlot/search?q=padding&type=commits

**Comment by happyteque** [comment]
It's hard to keep up ... 😉 

I am trying to get a graph with nothing around it, no u-under no u-over no padding no nothing, I need the curve to "touch" the rest of the page around it. But event passing these options there is still 40px or so blank space in the canvas around the graph.
```
options = {
      width: 328,
      height: 210,
      legend: { show: false },
      select: { show: false, left: 0, top: 0, width: 0, height: 0 },
      padding: [null, null, null, null],
      series: [
        {},
        {
          show: true,
          spanGaps: false,
          width: 2,
          value: (self: any, rawValue: any) => rawValue.toFixed(2),
        },
      ],
    };
```

**Comment by leeoniya** [comment]
padding null means auto. you need 0. you shouldn't need to set padding if you hide all axes. check out the opts set in the sparklines demo.

https://github.com/leeoniya/uPlot/blob/master/demos/sparklines.html

**Comment by happyteque** [comment]
Brilliant, that does it, thanks!
