### ISSUE TITLE
Add option to disable double-click x-scale-resetting

### ISSUE THREAD

**Issue by Venryx** [leeoniya/uPlot#342]
It would be nice if there were either an option, or a way to use the plugin/hooks system, that would allow one to disable the x-scale resetting that currently occurs for chart double-clicks.

**Comment by Venryx** [comment]
In the meantime, I've found this dom-based workaround:
```
// after chart has been created, run the below
const uplotDiv = uplotInstance.root;
uplotDiv.addEventListener("dblclick", e=>{
	e.stopPropagation();
}, {capture: true});
```

It works for now, but is inelegant, since it requires manipulating the dom event-propogation system. (and cannot be configured until after the chart has been created/rendered)

**Comment by leeoniya** [comment]
heh, i was gonna suggest that work-around :)

there's actually a way to do this now on `master`, but it's not in a tagged release yet. see #298.
