### ISSUE TITLE
Using uPlot.d.ts TypeScript type definitions while directly loading this library from github.io

### ISSUE THREAD

**Issue by b4git** [leeoniya/uPlot#346]
Hi,

I was just wondering if there is a way to make the type definitions to be available in a TypeScript file whose corresponding transpiled JavaScript file intends to use the library functions which are loaded using the script tag `<script src="https://leeoniya.github.io/uPlot/dist/uPlot.iife.js"></script>`.

Example error: In a file `TestChart.ts`

```
/// <reference path="./uPlot.d.ts" />

// other statements

let u = new uPlot(opts, data, document.body); // this line shows error : "cannot find name uPlot`

```

**Comment by leeoniya** [comment]
my TypeScript interop knowledge is unfortunately not great right now. this seems like a more general TS question than a uPlot question. maybe try asking on StackOverflow?

**Comment by b4git** [comment]
I found out that if we define `strictly only the Types` in `*.d.ts` file,  then it is possible to  achieve what we want, but the problem is that classes cannot be directly instantiated with `let u = new uPlot()` instead we need a separate constructor or factory function that can return a new instance. For example: `let u = UPlotInterface.createUPlotInstance()`. So, currently we cannot achieve it, but we need to add a function in the `uPlot` library that returns the constructed instance for a given class instead of using the `new` keyword.

It is a minor addition of one function for each class, but it will certainly be helpful. So, would you please consider this?

**Comment by leeoniya** [comment]
`new` has not been required since https://github.com/leeoniya/uPlot/commit/ff251c8c16b5120e2ef1b6584347ad6386a61344.

you can treat `uPlot` as a factory function as well.

is there a way to just modify the typings to support both cases?

**Comment by b4git** [comment]
I'm experimenting with it, but one minor issue I am having is single identifier `uPlot` being used as `class` and `function` and `namespace` or `module` name.

**Comment by leeoniya** [comment]
i'm not entirely sure that the namespace is even needed. the initial PR was done this way, so i simply used it as a starting point and expanded on it. esbuild, for example, exports types without a namespace: https://github.com/evanw/esbuild/blob/master/lib/types.ts
