### ISSUE TITLE
Single x-axis but arbitrary number of y-axis with independent range values possibly shifted (or stacked).

### ISSUE THREAD

**Issue by b4git** [leeoniya/uPlot#350]
The [y-shifted series demo](https://leeoniya.github.io/uPlot/demos/y-shifted-series.html) is quite close to the description,  but it has a uniform range. What would be the best way to provide unique and independent set of range values for each shift?

For example, what we are looking for is similar to a single chart with single x-axis but with multiple series data in different panels with completely independent y-axis range values as in this financial chart screenshot:

![image](https://user-images.githubusercontent.com/63267629/97793821-23e75a00-1bbf-11eb-83fc-e0b296635961.png)

**Comment by leeoniya** [comment]
for more complex cases like this you're probably better off using several stacked charts and syncing the cursors. you can disable the x axis on all but the bottom one and pretty much get this effect.

https://leeoniya.github.io/uPlot/demos/sync-cursor.html

**Comment by b4git** [comment]
Yeah, that's what I realized immediately after posting this question. It is possibly best to use multiple  synced charts. Thanks for confirming.

**Comment by giancarlocp** [comment]
Is it posible to plot multiple (more than 2) Y axes?
Something like [this](https://canvasjs.com/javascript-charts/line-chart-multiple-axis/) or [that](https://plotly.com/javascript/multiple-axes/)

![image](https://i.ibb.co/PgbhsWF/2021-01-19-09-23-09.png)
![image](https://i.ibb.co/3kL6yN1/2021-01-19-09-20-21.png)

**Comment by leeoniya** [comment]
yes, you can have as many as you need. they are all added the same way. see how it's done in https://leeoniya.github.io/uPlot/bench/uPlot.html
