### ISSUE TITLE
Scaling plot when using ctrl + / - in browser

### ISSUE THREAD

**Issue by GoodMorgon** [leeoniya/uPlot#352]
Hello,

My graphs don't rescale to the window when using the browser zoom (ctrl + / -). :(

Probably the fix is very easy... but couldn't find it.  Is there a fix to this issue?

- when rendering plot
![Untitled](https://user-images.githubusercontent.com/55554176/97975495-84e27e00-1dc9-11eb-8d91-9b4b35276a55.png)

- when zooming in / out
![Untitled2](https://user-images.githubusercontent.com/55554176/97975500-88760500-1dc9-11eb-9bbe-e45223876fa1.png)

**Comment by leeoniya** [comment]
there's nothing built into uPlot that allows you to specify something like 100% width. the chart width is set in  pixels and will not resize unless you tell it to resize yourself by calling `u.setSize()`.

you have to detect zooming and window resizing yourself to get what you're asking for.

see https://leeoniya.github.io/uPlot/demos/resize.html
