### ISSUE TITLE
How to format x-axis time display?

### ISSUE THREAD

**Issue by alextran1502** [leeoniya/uPlot#353]
Hello, I am looking for a way to format the x-axis time display, is there any option to do that?

![image](https://user-images.githubusercontent.com/27055614/98090944-5a84d500-1e4a-11eb-828a-3990102df3a7.png)
For example, I want to display full time in format `MM/DD/YYYY hh:mm:ss.S A` at each tick instead of just the second.

Thanks

**Comment by leeoniya** [comment]
take a look at https://github.com/leeoniya/uPlot/issues/303 and the bottom of https://github.com/leeoniya/uPlot/tree/master/docs

if you don't mind using master and would just like uniform labels, see https://github.com/leeoniya/uPlot/issues/339
