### ISSUE TITLE
Dynamically toggle cursor synchronization across multiple charts during run-time.

### ISSUE THREAD

**Issue by b4git** [leeoniya/uPlot#354]
Hi,

The cursor sync demo currently at [https://leeoniya.github.io/uPlot/demos/sync-cursor.html](https://leeoniya.github.io/uPlot/demos/sync-cursor.html) shows an example of setting cursor sync during chart creation time.

How would we enable or disable the cursor synchronization at run-time (meaning after the charts have already been created)?

Trying to toggle using `u.cursor.sync = {}` or `u.setCursor({})` do not seem to have an effect.

**Comment by leeoniya** [comment]
i don't think this is currently possible, but probably not too difficult to support.

**Comment by b4git** [comment]
Sure, in the mean time one solution could be to just create new set of charts with new settings and replace the old one, but not sure about the performance aspect of this operation.

On the side note about performance, it appears that for the large sets of dynamic data, since we need to hold on to the extra old copy of the data because we can only update the data using `u.setData` method. Is there a recommended way to only `push` or `append` only one or couple of data points (for high frequency updates) without having to keep the old copy of the data?

**Comment by leeoniya** [comment]
> On the side note about performance, it appears that for the large sets of dynamic data, we need to hold on to the extra old reference/copy of the data because we can only update the data using u.setData method

you can mutate or push directly to the existing data arrays and simply re-call setData() with them to notify uPlot of the changes.

**Comment by leeoniya** [comment]
some thoughts:

https://github.com/leeoniya/uPlot/issues/411#issuecomment-749701974
