### ISSUE TITLE
upldate multiple series at once

### ISSUE THREAD

**Issue by sniklaus** [leeoniya/uPlot#356]
First off, thank you for this great library!

I would like to set `show:false` for multiple series at once. This can easily be done through `u.setSeries(i, {show:false)` but I am under the impression that each call to `u.setSeries()` forces the plot to be redrawn. This leads to significant performance degradations if multiple (hundreds, in my case) series are update at once. Is there the possibility to call `u.setSeries()` without redrawing the plot and then calling something like `u.redraw()` once all series have been updated?

**Comment by leeoniya** [comment]
wrap all your setSeries calls in `u.batch()`:

https://github.com/leeoniya/uPlot/blob/6e63be63e5d6dadea9dc263483fe0abab5b83ad5/dist/uPlot.d.ts#L59-L60

**Comment by sniklaus** [comment]
Awesome, that works! And huge thanks for responding so quickly!

**Comment by leeoniya** [comment]
👍
