### ISSUE TITLE
[demo] moving-avg or ASAP

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#357]
http://futuredata.stanford.edu/asap/

**Comment by hugovoerman** [comment]
It would be great to integrate this (as a hook or plugin or ???) into uPlot. ASAP (As Smooth As Possible) seems a great way to make large timeseries more insightful.

**Comment by leeoniya** [comment]
the approach i'm thinking will be similar stepped line and smoothed line demos. feel free to contribute a demo based on those, or propose something different :)
