### ISSUE TITLE
Plot with 0 width and height crashes page since 1.3.0

### ISSUE THREAD

**Issue by joaopaulobdac** [leeoniya/uPlot#358]
[Here's a codesandbox link with a reproduction of this](https://codesandbox.io/s/uplot-130-crashing-p1v2t?file=/src/index.js).

The reason I'm creating a plot with 0 width and height is that I don't know the exact size of the plot container until after rendering in React. Then I use `plot.setSize` everytime the container is resized.

**Comment by leeoniya** [comment]
interesting. it's actually any integer < 75. seems related to this: 00af5edd0051cbdeac1a5766aafa53b7abde4d6b.

> The reason I'm creating a plot with 0 width and height is that I don't know the exact size of the plot container until after rendering in React.

out of curiosity, why not defer to the initial resize to initialize the chart?

**Comment by joaopaulobdac** [comment]
I'd need to initialize `plot` as `null` in the component state, and then after the first render set `plot` with the width and height. But now because `plot` is marked as nullable I'd have to check for that everywhere inside the component. It's easier to just create the plot right away and use `.setSize` after the first render :man_shrugging:

**Comment by joaopaulobdac** [comment]
> interesting. it's actually any integer < 75

For now I'm initializing the plot with width and height of 1 instead of 0 and it's not crashing anymore

**Comment by leeoniya** [comment]
fixed. thanks for the report.
