### ISSUE TITLE
Sync cursor peformance

### ISSUE THREAD

**Issue by iustinlita** [leeoniya/uPlot#363]
Hi, I set up a sync cursor configuration, like in the example, for 2 graphs using the v.1.2.2 version, having like up to ~700 entries. For some reason, at some point it runs out of memory in firefox and in chrome it crashes. This is not happening with sync disabled.

**Comment by leeoniya** [comment]
if the multi-thousands point cursor-sync demo is not crashing for you, i will need you to provide a demo that does.

https://leeoniya.github.io/uPlot/demos/sync-cursor.html

**Comment by leeoniya** [comment]
closing for now.

if you're able to provide a repro, we can re-open.
