### ISSUE TITLE
Set Range and get empty chart without data

### ISSUE THREAD

**Issue by SkyTien** [leeoniya/uPlot#365]
Hi，

I set range like the code in version 1.2.2, data is empty at the first time.

```js
      scales: {
        x: {
          // auto: false,
          range: (self, min, max) =>
            this.range > 0 ? [min, max] : [moment().subtract(10, 'minutes').unix(), moment().unix()]
        },
      },
      series: [
        {
          value: '{YYYY}-{MM}-{DD} {HH}:{mm}:{ss}'
        }
```

![image](https://user-images.githubusercontent.com/8827278/99606353-8ad09400-2a44-11eb-8f59-3144d5b61af0.png)

After version 1.3.0, the whole chart is empty, but it will get normal after setting data. 
![image](https://user-images.githubusercontent.com/8827278/99223257-22549d80-281f-11eb-85f0-8b62273fc63c.png)

Thanks for your help.

**Comment by leeoniya** [comment]
i'm not sure what you are expecting here (you did not post a picture of what you had with 1.2.2). also, i don't know what `this.range` is.

this works as i would expect: https://jsfiddle.net/s8f2Lo1h/

**Comment by SkyTien** [comment]
Hi,

I just upload the picture with 1.2.2 .
this.range is the value of my selector, can be (0, 30, 60, etc.), 
and data = [];

The same code run on 1.3.0 will get empty chart until the data is been set.

**Comment by leeoniya** [comment]
in general, you're correct. there have been some behavior changes in recent versions because i was not happy with assumed defaults. if you want to have default scale ranges (and axes/grid) without data, you now need to specify those fallbacks explicitly.

see https://jsfiddle.net/k3o7xdrt/1/ and https://github.com/leeoniya/uPlot/blob/master/demos/no-data.html

**Comment by SkyTien** [comment]
Thanks.
Maybe I can cover the whole chart before receiving data.
