### ISSUE TITLE
How can I set a time range without showing time series?

### ISSUE THREAD

**Issue by SkyTien** [leeoniya/uPlot#366]
Is it possible to do like this? 
( 60 seconds at the left bottom)
![image](https://user-images.githubusercontent.com/8827278/99224378-2bdf0500-2821-11eb-979e-5e7ed7bfc4bb.png)

Thanks for your help~

**Comment by leeoniya** [comment]
you can disable the ticks and values on the x axis like this: https://jsfiddle.net/4k51af3p/

you can set an x scale range using something like `u.setScale('x', {min: 1605678185, max: 1605678245})`. take a look through the demos, there are many examples of scale range adjustment in combo with `u.setData()`.

**Comment by SkyTien** [comment]
Hi, 

Please see this. 
https://jsfiddle.net/STien/269bo30q/1/

I wish to mark the whole time range below the chart.
The only way I know to do that is use label, but I don't think its the wright way.

**Comment by leeoniya** [comment]
yes, you can use a label: https://jsfiddle.net/gkoqvz97/

or you can draw directly on the canvas wherever you want. see "Time to draw" in this demo: https://leeoniya.github.io/uPlot/demos/draw-hooks.html

**Comment by leeoniya** [comment]
i've opened #367 for adding label alignment, but it will be a couple weeks before i get around to adding this.

**Comment by SkyTien** [comment]
Perfect!  Thank you so much.
