### ISSUE TITLE
Inconsistent u-over left offset

### ISSUE THREAD

**Issue by gyroninja** [leeoniya/uPlot#371]
When upgrading from 1.3.0 to 1.4.2 I noticed that location of my tooltip was incorrect. My tooltips are modeled after your cursor-tooltip demo and I have applied the change from 5c7a8740e5344665c128098e07f4d27eb762a86b to my program changing from using the init hook to the ready hook. While this does work for your demo, it did not fully resolve the issue in my application. After changing it to ready the value of bLeft was slightly off causing the cursor and tooltip to overlap. I ended up figuring out that this will happen if your initialize the plot with empty data such as [[], []] and then later add data to the plot. You can reproduce this issue by modifying the last line of the script in the cursor tooltip demo to.

```
const u = new uPlot(opts, [[], []], document.body);
setTimeout(() => u.setData(data), 1000);
```

A workaround for this issue is to use the setSize hook instead of ready that way.

**Comment by leeoniya** [comment]
indeed, you'll now need the help of a `setSize` hook for this case. i've updated the demo. the fact that so little broke after completely reworking the rendering strategy is kind of amazing to me.

thanks for reporting!
