### ISSUE TITLE
Hooks: Pass mouse event to setSelect hook

### ISSUE THREAD

**Issue by torkelo** [leeoniya/uPlot#373]
It would be nice to have access to the mouse event to know if keys like shift, cmd/ctrl are pressed to have different behavior when selecting a region with one of those control keys are selected. 

For example zoom in, vs create annotation region vs zoom in graph only with existing data (ie no dashboard time range change / refresh)

**Comment by leeoniya** [comment]
a method for doing this aleady exists.

see details (and demo at bottom) here: https://github.com/leeoniya/uPlot/issues/298

**Comment by torkelo** [comment]
ah, great

**Comment by leeoniya** [comment]
closing as dupe, but feel free to ping me with more specific impl questions in this issue, #298, slack, etc. 👍
