### ISSUE TITLE
Making the plots more sharper and crisper or resizing/up-sampling in combination with CSS.

### ISSUE THREAD

**Issue by b4git** [leeoniya/uPlot#376]
In some cases, the charts produced by uPlot don't look very sharp and crisp. For example: if we compare the following two charts produced by uPlot and another library, it appears that the other chart is more sharper and crisper than the uPlot demo.

uPlot's OHLC demo: https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html
Lightweight's OHLC demo: https://jsfiddle.net/TradingView/eaod9Lq8/

Trying to up-sample in combination with CSS is not working as expected. Here is one attempt to resize CSS to a lower dimension but the cursors seem to be off: https://jsfiddle.net/9xv7toj3/4/

So, just wondering why the other chart looks crisper and if it is possible to draw the uPlot's chart in higher resolution but use CSS to set smaller dimension to scale it nicely and make it look better!

**Comment by leeoniya** [comment]
> So, just wondering why the other chart looks crisper and if it is possible to draw the uPlot's chart in higher resolution but use CSS to set smaller dimension to scale it nicely

it already does this!

can you provide a screenshot of each on your screen? this is what they look like for me and look pretty similar in terms of sharpness. also, what is your browser/OS and its `devicePixelRatio`?

![image](https://user-images.githubusercontent.com/43234/100258613-e4d1cd80-2f0c-11eb-9359-a99305372b20.png)

![image](https://user-images.githubusercontent.com/43234/100258689-f74c0700-2f0c-11eb-8084-24c20a7e031b.png)

**Comment by b4git** [comment]
What I observed is that if we directly access the canvas 2d context on the console and try to draw 2 thinnest vertical lines over both of them, the line thickness of these lines are same and these lines look similar. 
![image](https://user-images.githubusercontent.com/63267629/100296942-1d949580-2f53-11eb-91df-9be6936b005f.png)
However, if you observe closely, for the Lightweight chart, the other plots and grid lines have even smaller thickness.

**Comment by b4git** [comment]
I was just playing around and observed this effect: off-setting the co-ordinate parameters with `0.5`, produced sharper line. Not sure if we can achieve even sharper than that.
![image](https://user-images.githubusercontent.com/63267629/100299217-bb3e9380-2f58-11eb-8917-a15ed66f6a6e.png)

**Comment by leeoniya** [comment]
uPlot translates the canvas by half the stroke width before drawing. (instead of adjusting all path coords by half stroke width). this is done exactly to get pixel-aligned stroking. if you draw on the canvas you need to do the same.

https://www.rgraph.net/canvas/howto-antialias.html

you can see the plugin do it here prior to drawing:

https://github.com/leeoniya/uPlot/blob/406dd367cc6c04f262d3bab66a56c9b30248ba60/demos/candlestick-ohlc.html#L144-L146

and then undo it after:

https://github.com/leeoniya/uPlot/blob/406dd367cc6c04f262d3bab66a56c9b30248ba60/demos/candlestick-ohlc.html#L214

**Comment by b4git** [comment]
Previously, I was not aware of the purpose of that translation, now it makes sense. Thanks!
