### ISSUE TITLE
API control and query of toggled series

### ISSUE THREAD

**Issue by jeancharles-roger** [leeoniya/uPlot#38]
Series can be toggled in the UI, an API to control and queries the toggled series would be really useful.

I've tested it for streamed data and it works really nicely and fast. Thanks a lot for your library !!!

**Comment by leeoniya** [comment]
yeah, i kinda wrote some notes about this today.

initial thoughts:

`.toggle(series, onOff)` where `series` is either the index or an array of indicies and `onOff` is `true` or `false` for explicit or `undefined` for implicit inversion. this API has the nice property of also being able to isolate a single series (turn off all but a specific one).

i'm thinking the same signature for #26: `.focus(series, onOff)`.

first i'm gonna split each series onto its own canvas to avoid rebuilding all paths when a single one is toggled or focused.

**Comment by jeancharles-roger** [comment]
Could you had also `toggled(): series` ?

Toggle might lead to axes changes and redraw for all series.

**Comment by leeoniya** [comment]
i'm debating whether i should just expose the internal `series`, `axes` and `scales` structures rather than adding numerous getters for various portions of these. then i would drop `.getView()` and it can just be asserted by simply reading back `plot.scales.x`.

**Comment by jeancharles-roger** [comment]
It's an option but it would allow modifying `series`, `axes` and `scales` and let the user except the chart to be updated in consequence. I don't know how complexe it would be or if it's possible to declare it as `immutable`, neither if it would actually be excepted by anyone other than me :).

**Comment by leeoniya** [comment]
it's definitely a trade-off and will be stated as such in the docs. having this reduces the amount of API i have to additionally maintain, maintain, and bloat the codebase and also improves performance by allowing direct access without perf-negative deep object cloning or other abstraction layers.

i don't know of any libraries that allow you to mutate their instance properties and expect things to just continue working as normal.

**Comment by leeoniya** [comment]
this is done.

demo: https://jsfiddle.net/yjrkp18z/

**Comment by leeoniya** [comment]
@jeancharles-roger heads up, `.toggle(idx)` has changed to `.setSeries(idx, {show: true/false})`.

you can read the current series state off the instance, so a replacement that does its own inversion would be something like:

```js
function toggle(u, i) {
  u.setSeries(i, {show: !u.series.y[i+1].show})
}
```

**Comment by jeancharles-roger** [comment]
Nice 👍.
Thanks for the heads up.

(I didn't have time to get back to a PR, I don't know when it will clear up).
