### ISSUE TITLE
How to set the cursor to last data point?

### ISSUE THREAD

**Issue by Fergo** [leeoniya/uPlot#380]
Hey there!

I need the legend to show the last data point data by default. I found the function `setCursor()`, but I don't know how to use it. I've tried with `uplot.setCursor(0)`, `uplot.setCursor(30)`, `uplot.serCursor(10,10)`, but they all put the cursor at the first data point, not the last.

Any tips?

KR,
Fergo

**Comment by leeoniya** [comment]
the cursor position is set by `{left, top}` coordinates. which you can compute from the data:

https://jsfiddle.net/aeq1d4u6/

> but I don't know how to use it

all the function signatures are available here:

https://github.com/leeoniya/uPlot/blob/65e6119f05c65744216d849a19f35dbb7d5e73aa/dist/uPlot.d.ts#L71-L72

**Comment by Fergo** [comment]
Thanks and sorry for the late reply!
