### ISSUE TITLE
Dynamically add / delete series with id reference

### ISSUE THREAD

**Issue by GoodMorgon** [leeoniya/uPlot#381]
Hello,

Is it possible to somehow append an id reference to added series (and use this reference in future deletes)? I've checked  https://leeoniya.github.io/uPlot/demos/add-del-series.html but in this example added series are simply appended with addSeries() and delSeries()...

It would be great if one could do something like .addSeries(id='data1') and then .delSeries(id='data1'). Now my solution is to iterate over all series names for an exact match if I want to remove an existing series that is not the last one...

This is useful when dynamically adding or removing series, especially when not adding in a linear fashion (a user may select from many series to be displayed).

Thanks!

**Comment by leeoniya** [comment]
it's so easy to do, that i'd rather not add it to the lib.

you can always stick your own properties onto the series config, e.g. `{key: "abc"}` and then use something like this one-liner: 

```js
u.delSeries(u.series.findIndex(s => s.key == "abc"))
```
