### ISSUE TITLE
Change time format in tooltip

### ISSUE THREAD

**Issue by hugovoerman** [leeoniya/uPlot#382]
With #355 I am able to change the dateformat of the x Axis, however, in the tooltip (I'm using the legendAsTooltipPlugin) the Time is still plotted in the default format. How can I change this?

![image](https://user-images.githubusercontent.com/13115669/100518029-5620b300-318f-11eb-976f-80a85c9afbcd.png)

Thanks for this great and superfast visualization engine!

**Comment by leeoniya** [comment]
you need to set `opts.series[0].value` to a template string or formatting function:

https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L454

**Comment by hugovoerman** [comment]
Thank you for the quick reply.
value: "{YYYY}-{MM}-{DD} {HH}:{mm}:{ss}"
did the trick!
