### ISSUE TITLE
Showing nearest point on sparse series

### ISSUE THREAD

**Issue by astromme** [leeoniya/uPlot#384]
I have two series, one that is pretty dense and the other is sparse, only 1 in 5 data points compared to the dense one. When I plot them together, I have to mouse super precisely on the x-axis to see a value for the sparse series, because most of the time it will show a value for the dense series.

The best workaround I can think of is to interpolate values myself and ensure that both datasets have values. This seems problematic because now the data is not truthful in the sense that the x/y value shown is interpolated rather than measured. 

Is there any way to make this better? Seems like the ideal might be a bias towards the series that my mouse is closest to, so when I'm close to the second series it would snap to the second series.

<img width="559" alt="Screen Shot 2020-11-28 at 1 01 27 PM" src="https://user-images.githubusercontent.com/126986/100522848-c532e300-3160-11eb-8cee-948496ae62f7.png">

**Comment by leeoniya** [comment]
have you seen https://leeoniya.github.io/uPlot/demos/nearest-non-null.html ?

**Comment by astromme** [comment]
Thanks for sharing. So if I understand this plot option code, it's checking left and right for the closest non-null value and then showing that instead of null for each timestamp? In that case, seems like it's acting as a step function with the step being at the midpoint between each non-null value. 

This is sufficient for my needs, thanks!

```
cursor: {
  dataIdx: (self, seriesIdx, hoveredIdx) => {
    let seriesData = self.data[seriesIdx];

    if (seriesData[hoveredIdx] == null) {
      let nonNullLft = hoveredIdx,
        nonNullRgt = hoveredIdx,
        i;

      i = hoveredIdx;
      while (nonNullLft == hoveredIdx && i-- > 0)
        if (seriesData[i] != null)
          nonNullLft = i;

      i = hoveredIdx;
      while (nonNullRgt == hoveredIdx && i++ < seriesData.length)
        if (seriesData[i] != null)
          nonNullRgt = i;

      return nonNullRgt - hoveredIdx > hoveredIdx - nonNullLft ? nonNullLft : nonNullRgt;
    }

    return hoveredIdx;
  }
},
```

**Comment by astromme** [comment]
Oh, there is also a custom formatter that shows time for each point independently. But it appears that this formatter requires a reference to the data array, which is hard to do in my code (React + data from Firebase + uPlot) because the data is scoped to a react component but the plot options are not (so they can be reused). 

Is there any other function signature that gives a reference to the data array?

```
values: (u, sidx, idx) => {
  //	let date = self.tzDate(data[0][idx]);
  let date = new Date(data[0][idx] * 1e3);

  return {
    Time: longDateHourMin(date),
    Value: data[sidx][idx],
  };
},
```

**Comment by leeoniya** [comment]
`u.data`?
