### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by jasonatball** [leeoniya/uPlot#388]
I think there have been several breaking changes from 1.2 to 1.3 to 1.4. I know it's a pain but can you go back to creating release notes for your [releases](https://github.com/leeoniya/uPlot/releases). The diffs are a little much to grok for someone who isn't familiar with the code base. Especially appreciated are noting API changes / breaking changes.

Thanks for uPlot!

**Comment by leeoniya** [comment]
sure, i'll do that today. some changes are not obviously breaking. if you provide some now-broken code, i'll help you fix it.

**Comment by jasonatball** [comment]
Ha, I've been holding off upgrading waiting for the change logs! I'll see if I can get through the upgrade process today.

**Comment by jasonatball** [comment]
I appear to have issues with this code now:
```
      this.plot.addSeries(
        {
          spanGaps: true,
          label: item.itemName,
          stroke: this.colors[this.data.length - 1],
          value: (self, rawValue) => rawValue && rawValue.toFixed(2),
        },
        index
      )
```
I'm getting a bunch of "Uncaught TypeError: rawValue.toFixed is not a function" when I try to mouseover. Note I have two plots up and have the cursor synced:
```
      cursor: {
        drag: {
          x: true,
          y: false,
        },
        sync: {
          key: 'cosmos',
          setSeries: true,
        },
      },
```
Let me know if you need more of the code.

**Comment by jasonatball** [comment]
Here's a link to the code which is still pretty much up to date: https://github.com/BallAerospace/COSMOS/blob/cosmos5/web/frontend/src/components/CosmosChartuPlot.vue

**Comment by jasonatball** [comment]
Something like this fixes it but I'm not sure what to use for the default value (if null):
```
          value: (self, rawValue) => rawValue == null ? '' : rawValue.toFixed(2),
```
Not sure why I wasn't getting nulls before but doesn't blank make sense?

**Comment by leeoniya** [comment]
interesting, i'll have to bisect to see exactly when this happened. but if rawValue is the one from your data, then this is a fix rather than a regression :)

> Not sure why I wasn't getting nulls before but does blank make sense?

i usually use `--`

**Comment by jasonatball** [comment]
Maybe I spoke too soon because now I can't reproduce. I used to have this:
```
value: (self, rawValue) => rawValue && rawValue.toFixed(2)
```
and I definitely have gaps in my plot so I get null values. I changed to your explicit handling of null which is better.

I'm sure others would still appreciate those release notes though :-)

**Comment by leeoniya** [comment]
> I'm sure others would still appreciate those release notes though :-)

for sure!

my current priority is ensuring a successful Flot -> uPlot transition for Grafana (my new employer). we're getting close!

there will be a few more rapid releases in the next couple weeks to handle the required use-cases, and i'll go back after the churn has settled to update the release logs more thoroughly. i don't expect any major breaking changes to land, but in typical uPlot fashion, there's no absolutist adherence to keeping complete backwards-compat; this would not work well for a lib that tries to stay lean and fast, so legacy warts get dropped or refined continuously. lesson being, upgrade often!

**Comment by leeoniya** [comment]
updated all release notes.
