### ISSUE TITLE
Disable reset of zoom when using setData()

### ISSUE THREAD

**Issue by GoodMorgon** [leeoniya/uPlot#390]
Hello again,

Is it possible to disable the reset of zoom when updating the data with setData()? I have a slider that changes the displayed data and every time the graph redraws the zoom level is reset...

**Comment by leeoniya** [comment]
yep:

https://github.com/leeoniya/uPlot/blob/005b3e0903444521f592c14cf33ab922d6e364ca/dist/uPlot.d.ts#L65-L66

**Comment by GoodMorgon** [comment]
I just tried it, but the chart series do not update correctly.

Please see the attached image. You can see the single purple dot, which is the first value of the new series after running setdata() with resetScales = false. But it only shows the first of many values, and the old values´(the purpline line under the purple dot in this case) are still present until I zoom out.

I.e. the puple line (which is the series that got updated) does not update correctly.

![Untitled](https://user-images.githubusercontent.com/55554176/101258256-a06eda80-3721-11eb-993a-99e70f7be9a6.png)

**Comment by leeoniya** [comment]
try doing

```js
u.setData(data, false)`;
u.redraw();
```

**Comment by leeoniya** [comment]
it would be much easier for me if you can make a jsfiddle for me that i can simply fix without having to recreate everything.

example: https://jsfiddle.net/q2k8fya5/

**Comment by GoodMorgon** [comment]
Sorry, 

I should be more specific in my postings. .redraw() solved the issue!
