### ISSUE TITLE
Gutters only visible when axis enabled.

### ISSUE THREAD

**Issue by LostKobrakai** [leeoniya/uPlot#392]
I'm trying to render a chart "edge to edge", but the points are overflowing the boundary. Gutters seem to only be added if I enable the axis rendering however.

<img width="217" alt="Bildschirmfoto 2020-12-07 um 17 35 18" src="https://user-images.githubusercontent.com/2489835/101377897-b3fd7b00-38b2-11eb-8847-fc79e2b51088.png">

**Comment by LostKobrakai** [comment]
I just noticed I can use a custom range to notch things to view slightly

**Comment by leeoniya** [comment]
> I just noticed I can use a custom range to notch things to view slightly

a better hack might be to add a custom-sized axis that returns an array of empty strings for its `axis.values`, and set the `axis.ticks.show: false`. this way your scale actually reflects what you want.

**Comment by leeoniya** [comment]
maybe

```
// simple variant (auto: true)
padding: [
    size,  // top
    size, // right
    size,  // bottom
    size, // left
]

// expanded variant
padding: [
    {size, auto},  // top
    {size, auto},  // right
    {size, auto},  // bottom
    {size, auto},  // left
]
```

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot/commit/d320255c4e534be284664bafbbfb4f5e3fe27152

the API i ended up with is `opts.padding: [top, right, bottom, left]`. each can be and static value, null for auto behavior (like gutters were before), or a callback function to dynamically size the padding.

`opts.gutters` is no more.

please try it out.

**Comment by LostKobrakai** [comment]
I just pulled in the latest esm build from the repo and I don't see any padding being applied to the chart. The canvas still renders the chart edge to edge cutting of the points for 0 values.

**Comment by leeoniya** [comment]
the default behavior has not changed, but you now have explicit control per side that is not dependent on axes. something like `padding: [8, 8, 8, 8]` should work.

**Comment by LostKobrakai** [comment]
That's what I tried, but without showing an axis this doesn't seem to do anything. For this usecase however I don't need axis, because the chart + updating legend is enough information.

**Comment by leeoniya** [comment]
sorry, you're right. something's still broken.

**Comment by leeoniya** [comment]
should be fixed by https://github.com/leeoniya/uPlot/commit/a91bdcecae048a805f8e8be7a139f260dad065f1

**Comment by LostKobrakai** [comment]
Seems to work now 👍
