### ISSUE TITLE
Line smoothing example is 404

### ISSUE THREAD

**Issue by silverwind** [leeoniya/uPlot#394]
README.md links to https://leeoniya.github.io/uPlot/demos/line-smoothing.html but that page just returns 404. Has it moved?

**Comment by leeoniya** [comment]
yes, there are more modes now (via https://github.com/leeoniya/uPlot/blob/master/dist/paths.esm.js).

i've merged stepped and smoothing demos: https://leeoniya.github.io/uPlot/demos/line-paths.html

the current demo index is up to date.

**Comment by silverwind** [comment]
Glad to hear this is built-in now 😉
