### ISSUE TITLE
have multiple plots sync the x-axis + crosshair

### ISSUE THREAD

**Issue by gebrits** [leeoniya/uPlot#4]
Usecase: finance time-series of N symbols of which to check their correlation. These have different y-scale, but always the same x-scale. 

Plotting them in same plot due to variance in y-scale doesn't work most of the time. 
Therefore, I want to have a couple of plots side by side. 

It would be awesome to be able to sync between plots: 

* **x-scale**. Zoom in on 1 plot, zooms in on others. Note that the user has to make sure that the same data in terms of time is given for each plot to begin with.
* **crosshair**. Hover over 1 plot, will show crosshair dotted x + y-lines (including highlighted numbers) on all plots. 

Thoughts?

**Comment by leeoniya** [comment]
i think it should be pretty easy to do. just need to iterate on the proper api for it.

it should be noted that you can already plot multiple y scales & axes on the same chart (just use a different key for each symbol) and they should rescale properly. something that could be useful to add here is th ability to set an axis color so it can be matched to a specific series wothout the need for space-wasting axis labels.

**Comment by leeoniya** [comment]
@gebrits this is done.

check out https://leeoniya.github.io/uPlot/demos/sync-cursor.html

**Comment by leeoniya** [comment]
cc @reachAravindh @sb8244

**Comment by leeoniya** [comment]
just a heads up, this api will be internalized. the public api will just be `{sync: "myKey"} `
