### ISSUE TITLE
optimize scale invalidation when toggling a series

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#40]
right now when a series is toggled, the scale associated with it is invalidated (along with all paths using that scale) and recomputed and paths redrawn.

by additionally keeping track of which series bumped the final scale min/max, we can avoid invalidating the scale when toggling a series that never affected the its associated scale. this would avoid recomputing the min/max of the scale and regenerating the other paths, which would provide a healthy improvement by avoiding most of the work. this is especially apparent when you have a lot of data-heavy series on the same scale.

what's involved is adding a prop or two to the scale itself for tagging which series indices pegged the min/max values by keeping track inside of `setScales()`, then adding a check in `toggle()` to avoid unnecessary invalidation.

**Comment by leeoniya** [comment]
hey @jeancharles-roger, thanks for #41!

i wasn't expecting anyone to pick up issues within hours of them being opened :D

i've given my proposed approach some additional thought and it has some flaws.

multiple series frequently all have min of 0 and/or max of 100 (or other common values). so pinning a specific series as the invalidation trigger is not ideal.

my current thinking is instead to add min/max properties (cache) to each series and when a series is toggled, only invalidate its scale if its min or max is lower/higher than all other shown series. this could also allow more optimizations such as not re-computing the cached min/max when the view or data remains the same. it also has the nice benefit of exposing the data min/max in the view for each series if someone wanted to show this externally.

what do you think?

**Comment by jeancharles-roger** [comment]
`good first issue` is a nice marker to know where to start 😀.

Indeed it feels better to keep track of a min and max for each series, I'll try it.

Thanks for the example.
