### ISSUE TITLE
How to update x-axis on click?

### ISSUE THREAD

**Issue by Yakabuff** [leeoniya/uPlot#401]
Hi, first time using this library. 

How would I update the x axis on button click? Currently, I'm setting an array to data where xs is an array of values in the axis

`      let data = [
        this.xs,
        this.xs.map((t, i) => vals[Math.floor(Math.random() * vals.length)]) 
      ]; `
where `this.xs =[1,2,3,4,5,6,7,8,9,10]`
but when I update `this.xs` on click, it does not update the chart. I've tried redrawing the chart with this.drawChart() but it draws a duplicate chart instead of updating 

Thanks

**Comment by leeoniya** [comment]
you have to call `plot.setData(newData)`

**Comment by bogdan-nourescu** [comment]
If you just want to show a part of the chart, you can use 
```
u.setScale('x', {min: 5, max:7});
```
If you want to redraw the chart, use `u.redraw()`
