### ISSUE TITLE
Complete documentation of "opts" object

### ISSUE THREAD

**Issue by backspaces** [leeoniya/uPlot#402]
The Docs page: https://github.com/leeoniya/uPlot/tree/master/docs is great but incomplete. Looking over the examples and code I found several.

Ex: series: paths, points; axes: show

Basically looking at the source and plucking out user-modifiable properties.

**Comment by leeoniya** [comment]
the full API is documented here:

https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts

but if you'd like to contribute some prose for the markdown doc, i'd certainly welcome it.

**Comment by backspaces** [comment]
I'm not sure I can read a d.ts file correctly.

I've been using the  Javascript here: 
  https://unpkg.com/browse/uplot@1.4.7/dist/uPlot.esm.js

**Comment by backspaces** [comment]
One example of a documentation problem for me is the third element in the constructor which is always, apparently, document.body. Is it a div where uPlot places it's divs/canvases?

**Comment by backspaces** [comment]
Loved the nifty trick for sparklines: just grab the canvas! (after turning off the axes, legend etc) Cool.

**Comment by leeoniya** [comment]
yes, it's the container into which the chart will be inserted. it can be any html element.

**Comment by backspaces** [comment]
Nice, just tried it and it works nicely. Possible ease of use might be to let it be a string which in used as an ID: 

I.e.: 

            let uplot = new uPlot(opts, data, 'uplotContainer')

.. instead of:



            let mydiv = document.getElementById('uplotContainer')
            let uplot = new uPlot(opts, data, mydiv)

**Comment by leeoniya** [comment]
the general philosophy of this project is to provide only one way (the most powerful way) to get something done. things that can easily be done externally are generally left out to minimize the API surface.

i imagine that you can just create a reusable utility function for yourself and end up in the same place:

```js
const $ = selector => document.querySelector(selector);

let uplot = new uPlot(opts, data, $("#uplotContainer"));
```
