### ISSUE TITLE
A few feature requests and questions

### ISSUE THREAD

**Issue by gkjohnson** [leeoniya/uPlot#407]
Hello! First thank you for putting this project together it's extremely useful particularly for projects with rapidly streaming data. I had a few comments, feature requests, and questions so I figured I'd lump them all together to instead of spamming issues but I'm happy to make separate issues for any or all of these with more details if they're interesting:

**Questions / Feature Requests**

1. Is the "mouse hover" crosshair (currently a horizontal and vertical dashed line) customizable? I would like to remove the horizontal line and make the vertical line solid for my use case but I didn't see anything in the d.ts file that indicated it was possible.

2. Is it possible to remove or customize the white fill on the data point dot when zoomed in? I'm customizing the rest of the graph to read well on a dark background and the white dots do not fit in well. These white-filled dots are what I'm talking about:

![image](https://user-images.githubusercontent.com/734200/102696571-46bbe500-41e4-11eb-9a2b-aa4a01e5bfd2.png)

3. Is it possible to retain the crosshair for data brushing but remove the drag-to-zoom functionality?

4. Is it possible to get the time, closest points, and point screen position that are hovered over (and typically displayed in the legend) so I can create my own custom floating labels?

**Comments**

1. Have you considered adding Github tags to the repo? It took me awhile before finally coming across the project and adding tags may make it more discoverable.

Thank you again!

**Comment by leeoniya** [comment]
> Is the "mouse hover" crosshair (currently a horizontal and vertical dashed line) customizable? I would like to remove the horizontal line and make the vertical line solid for my use case but I didn't see anything in the d.ts file that indicated it was possible.

you can set `opts.cursor.y: false` to turn off the horizontal crosshair:

https://github.com/leeoniya/uPlot/blob/258e78cdbe992a33467f398d484aabe1e8c545aa/dist/uPlot.d.ts#L394-L398

to make the vertical crosshair solid you can tweak or override the css:

https://github.com/leeoniya/uPlot/blob/258e78cdbe992a33467f398d484aabe1e8c545aa/src/uPlot.css#L106-L124

> Is it possible to remove or customize the white fill on the data point dot when zoomed in? I'm customizing the rest of the graph to read well on a dark background and the white dots do not fit in well. These white-filled dots are what I'm talking about:

you can give them an explicit `points.fill`:

https://github.com/leeoniya/uPlot/blob/9e544f5c49ef632cf4fe22078e1bc1511d7c89b4/demos/points.html#L43-L46

> Have you considered adding Github tags to the repo? It took me awhile before finally coming across the project and adding tags may make it more discoverable.

> Is it possible to retain the crosshair for data brushing but remove the drag-to-zoom functionality?

not quite sure what you mean. there are several brush demos. you'll need to be more specific.

> Is it possible to get the time, closest points, and point screen position that are hovered over (and typically displayed in the legend) so I can create my own custom floating labels?

you can always read the cursor state off of `u.cursor`, which includes the hovered index `idx` into the data arrays, e.g.:

https://github.com/leeoniya/uPlot/blob/9e544f5c49ef632cf4fe22078e1bc1511d7c89b4/demos/cursor-tooltip.html#L60-L65

good idea, i've added a few. let me know if that would have covered it:

![image](https://user-images.githubusercontent.com/43234/102700099-0eca9700-4210-11eb-9c94-9218e83aff0f.png)

**Comment by gkjohnson** [comment]
Thank you for your quick response! That answered most of my questions. 

> good idea, i've added a few. let me know if that would have covered it:

Great that looks like a good list -- `visualization` or `data-visualization` might be good tags, as well.

And here I'll give more detail on the following:

> > Is it possible to retain the crosshair for data brushing but remove the drag-to-zoom functionality?
>
> not quite sure what you mean. there are several brush demos. you'll need to be more specific.

Right now I am streaming data in at a high rate and discarding data that came before a certain time (say 1000 seconds ago) so the relevant time window stays fixed (1000 seconds ago to now). The first graph in [this demo](https://leeoniya.github.io/uPlot/demos/stream-data.html) is closest to what I'm doing. However some times there's no new data to add but I want to keep moving the graph to the left. To achieve this I'm using a function for `scale.key.range` that will return the latest time range. Given the real-time nature of the data I don't want the ability to zoom in on the data (click and drag a section) like so:

![image](https://user-images.githubusercontent.com/734200/102727652-cb3d5f00-42db-11eb-9d2c-61965284ed4f.png)

I've prevented the graph from zooming at all by not respecting the range updates in the `range` function arguments but the visual affordance for dragging is still there. I would like to disable the visual affordance (and the callback firing if possible). This is actually an issue in the first graph I linked in [the demo link above](https://leeoniya.github.io/uPlot/demos/stream-data.html). If you click and drag to zoom while the data is streaming in you can see it zoomed for a frame or two and then it pops back. Ideally you'd disable the feature in this scenario to disable that popping behavior.

**Comment by leeoniya** [comment]
> Great that looks like a good list -- visualization or data-visualization might be good tags, as well.

added.

> I would like to disable the visual affordance (and the callback firing if possible). This is actually an issue in the first graph I linked in the demo link above.

yeah, makes sense to disable zooming and selection in the streaming demos. you can see the options required for this in https://github.com/leeoniya/uPlot/commit/d74bad7e15059c478928ce40d1059475acfffb59

**Comment by gkjohnson** [comment]
Great thank you very much!
