### ISSUE TITLE
Axis question

### ISSUE THREAD

**Issue by Yakabuff** [leeoniya/uPlot#408]
Hi,

Is it possible to have labels on the x axis that are independent to the x values?

ex: I have 50 data values but I want to graph each month on the x axis.

**Comment by leeoniya** [comment]
there are a few ways to do this.

1. you can try increasing `axis.space` to force uPlot to show lower resolution ticks/gridlines. at some point it will automatically choose month boundaries.
2. you can adjust `axis.incrs` so it only contains second increments of >= 28 days.
3. you can use the `axis.splits` callback to return the array of exact x values that you want to display ticks/gridlines for. these will then flow into `axis.values` for display formatting before render.
