### ISSUE TITLE
Suggestion: Embed styles in final js build

### ISSUE THREAD

**Issue by gkjohnson** [leeoniya/uPlot#412]
With modern build processes and dependency resolution the classic approach of including a styles link at the top of the HTML page for a library can be cumbersome. Particularly if a package like uPlot is a dependency of a dependency. I think it would be much more ergonomic if the styles needed to display a chart properly were embedded automatically when just importing uPlot. This can be achieved simply by prepending the uPlot styles content when the package is imported:

```js
// uplot.esm.js
const styleTag = document.createElement( 'style' );
styleTag.innerText = /* contents of uplot.min.css */;
document.head.prepend( styleTag );
```

Ideally this would only happen when the first graph is created in order to avoid import side effects but either way it should be possible to achieve this with the rollup build. Prepending the tag will make it backwards compatible with any override styles users have included in their app, as well.

**Comment by leeoniya** [comment]
hey @gkjohnson 

definitely there are some trade-offs to this approach. the main one is that it probably eliminates any possibility of making a single css bundle. additionally, if this gets added now, people already using the stylesheet will have redundant bytes and styles loaded. i do think that leaving it external offers the most flexibility in terms of how you want to deploy it vs baking it into the js file.

it would be good to assess the perf impact of this on initial load/render times. JS is expensive to parse, so adding all the CSS to JS means it has to be parsed first as JS and then again as CSS after injection. i suspect the overall end user experience would be worse; generally, i prioritize UX over DX unless the DX is miserable, but i don't think that is the case here.

> Particularly if a package like uPlot is a dependency of a dependency.

wouldn't the bottom-most dependency take care of loading the stylesheet already to make sure it's not broken by the consumers? :thinking:

**Comment by gkjohnson** [comment]
Yeah there might be some tradeoffs. I haven't come across a package that required a manually included stylesheet in awhile so I just thought I'd suggest it. It's definitely not unusable as it is. For my case I've just written my own function to add the style tag like I outlined above when the first chart is created.

> if this gets added now, people already using the stylesheet will have redundant bytes and styles loaded

Yeah but it wouldn't break anything. If this change was made I'd think it would be a minor version change and be called out in the change log.

> wouldn't the bottom-most dependency take care of loading the stylesheet already to make sure it's not broken for its consumers? this definitely feels like the responsibility of the deps that require uPlot to function. 🤔

If two dependencies require uPlot though and they both handle the addition of uPlot styles then you'll get two instances of them on the page because they can't know about the other including the styles. In this case I would think uPlot would be the bottom most dependency and handling adding the styles would ensure that only one copy gets included in the page when being imported.

I don't feel super strongly about this it was just something I noticed I had to do when integrating with my app (React, Webpack) so I thought I see if you had any opinions on it.

Thanks!

**Comment by leeoniya** [comment]
> If two dependencies require uPlot though and they both handle the addition of uPlot styles then you'll get two instances of them on the page because they can't know about the other including the styles.

wouldn't bundlers detect and dedupe identical css imports from `node_modules`? i hope so!

then there's always gonna be the things like how do we detect which version of a stylesheet needs to be loaded if 2 deps import 2 different uplot versions and overlap in selectors (which are unversioned)? -- this isn't specific to external css, but is still a footgun that can happen.

i'd prefer to keep these bundler-specific concerns outside this repo and keep the granularity/flexibility for custom toolchains. i'm also fairly confident the load time with js-injected CSS will be worse than with explicit CSS in an external stylesheet, unless you can guarantee that there will never be another external stylesheet to skip an extra network request.

thanks for the discussion!
