### ISSUE TITLE
new hook for non-native legend updates

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#414]
right now you basically have to hook into the chatty `setCursor` hook and cache the previous `cursor.idx` to figure out if the legend needs to be updated. this is not great since it's better not to have an expensive `setCursor` hook firing on every mousemove or having to do your own idx caching, since this optimization already exists in the core.

so i want to add a new hook that would fire only when there are legend updates needed (when the hovered index changes).

the question is more one of hook naming. i'm between `setIdx`and `setLegend`. maybe the latter is better and we can pair it with a new API to actually set the native legend via `u.setLegend()`...though not sure how useful it would be if the set values are destroyed on the next cursor move (unless the cursor is disabled)...:thinking:

**Comment by marcgendron-dyze** [comment]
Their is something related that I am trying to do. I want le legend to show the latest entry when the mouse is not over. I am trying to overide the `mouseleave` behavior in a plugin to call setCursor, but that does not seams to work. Could it be included in this feature? Is there a way I can overide the current behavior until this new feature can be released?

**Comment by leeoniya** [comment]
you can probably hook into `cursor.bind.mouseleave` and manually update the legend `textContent` in the DOM after firing the original handler. it's not ideal, but not too huge a hack either, for the time being. e.g. see https://leeoniya.github.io/uPlot/demos/cursor-bind.html

**Comment by leeoniya** [comment]
actually, gimme a couple hours. i'll at least add a `u.setLegend({idx})` api that reuses the value functions defined on the series. that way you dont need to touch the dom directly.

maybe i'll figure out the hook situation today as well. this issue has been open long enough :)

**Comment by marcgendron-dyze** [comment]
Thanks. I look forward to it.

**Comment by leeoniya** [comment]
turns out there is some nuance to refactoring this if i want to avoid repeating code that is currently in the cursor updating function. the cursor has support for altering the legend and hover points _per series_, so a single `.setLegend({idx})` in isolation cannot be reused by the cursor code. will need to give it more thought...

**Comment by leeoniya** [comment]
initial work for this is merged. it was more involved than expected. still need to make a demo and test the changes thoroughly to make sure i didn't break any existing demos.

**Comment by leeoniya** [comment]
try this now:

```js
hooks: {
  setLegend: [
    u => {
      if (u.legend.idx == null) {
        u.setLegend({idx: u.data[0].length - 1}, false);
      }
    },
  ]
},
```

**Comment by marcgendron-dyze** [comment]
Wow, that was fast. In my case, setData is called each second. Every time it is called, I want to update the legend. I added the code below to make it work. If you have a better suggestion, I'm all ears. In any case, I thank you for your super fast response. 
```js
hooks: {
   setLegend: [
      u => {
         if (u.legend.idx == null) {
            u.latest = true;
            u.setLegend({ idx: u.data[0].length - 1 }, false);
         } else  {
            u.latest = false;
         }
      },
   ],
   setData: [
      u => {
         if (u.latest) {
            u.setLegend({ idx: u.data[0].length - 1 }, false);
         }
      },
   ]
},
```
