### ISSUE TITLE
How to make multicolor line/area chart?

### ISSUE THREAD

**Issue by coditori** [leeoniya/uPlot#416]
I was wonder if we can use multi-color for just one data set, I tried a list of colors but nothing happens:
```
    const data = [5, 1, -1, 1, 3]

    const opts = {
        title: "MyPlot",
        width: 800,
        height: 600,
        series: [
            {},
            {
                stroke: ["red", 'green', 'blue', "red", "black"],
                // color: ["red", 'green', 'blue', "red", "black"],
            }
        ]
    };
```

**Comment by leeoniya** [comment]
are you trying to do something like this?

![image](https://user-images.githubusercontent.com/43234/103154896-96f4f300-4760-11eb-820e-0194a1a5fb5f.png)

lines are drawn as a single Path2D object, so it is not possible to assign different strokes to different segments. you can make this work with a bit of effort by setting the stroke to a horizontal canvasgradient with hard color stops at the x value positions.

it would have some similarity to this the gradient fills demo: https://leeoniya.github.io/uPlot/demos/gradient-fill.html

here's how to create an hz gradient with hard stops and apply it to a stroke: https://jsfiddle.net/ezg64h1j/

![image](https://user-images.githubusercontent.com/43234/103155279-d7a23b80-4763-11eb-8e63-6c82861a0022.png)


```js
var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");
 
var grd = ctx.createLinearGradient(0, 0, 300, 0);
grd.addColorStop(0, 'red');
grd.addColorStop(1 / 7, 'red');

grd.addColorStop(1 / 7, 'orange');
grd.addColorStop(2 / 7, 'orange');

grd.addColorStop(2 / 7, 'yellow');
grd.addColorStop(3 / 7, 'yellow');

grd.addColorStop(3 / 7, 'green');
grd.addColorStop(4 / 7, 'green')

grd.addColorStop(4 / 7, 'blue');
grd.addColorStop(5 / 7, 'blue');

grd.addColorStop(5 / 7, 'indigo');
grd.addColorStop(6 / 7, 'indigo');

grd.addColorStop(6/7, 'violet');
grd.addColorStop(1, 'violet');



ctx.strokeStyle = grd;
ctx.beginPath();
ctx.moveTo(0,0);

ctx.lineTo(1/7 * 300, 200);
ctx.lineTo(2/7 * 300, 0);
ctx.lineTo(3/7 * 300, 200);
ctx.lineTo(4/7 * 300, 0);
ctx.lineTo(5/7 * 300, 200);
ctx.lineTo(6/7 * 300, 0);
ctx.lineTo(7/7 * 300, 200);

ctx.stroke();

//ctx.fillStyle = grd;
//ctx.fillRect(0, 0, 300, 200); 
```

i've actually been meaning to make another red-above/blue-below demo in the same category similar to these:

![image](https://user-images.githubusercontent.com/43234/103155259-90b44600-4763-11eb-84e4-6ff1d944a1ad.png)

![image](https://user-images.githubusercontent.com/43234/103155270-ad507e00-4763-11eb-9e06-eb308bfab6ad.png)

**Comment by coditori** [comment]
Chart.js has a cool method "getPixelForValue(0)" which helps to make these, at the moment I need to scale numbers between 0-1 and also my pixel range right?

**Comment by leeoniya** [comment]
> Chart.js has a cool method "getPixelForValue()"

uPlot's equivalent is `valToPos`.

> at the moment I need to scale stops between 0-1 and also consider my pixel range right?

right. you can get the current scale value ranges from `u.scales` and the plotting area dims from `u.bbox`.

maybe take a look at the demo i already linked ;)

https://github.com/leeoniya/uPlot/blob/master/demos/gradient-fill.html
