### ISSUE TITLE
auto-init scales when referenced in an axis cfg

### ISSUE THREAD

**Issue by GoodMorgon** [leeoniya/uPlot#418]
Hello,

I'm trying to create a secondary y-axis, but with the relevant data later appended after first creating the plot.

Here is my configuration:

```
let opts = {
            id: 'test',
            class: 'uPlot',
            scales: {
                     x: {time: true}
                    },
            gutters: {
                      x: 0,
                      y: 0
            },
            axes: [
                   {
                    grid: {
                           width: 0.5,
                           stroke: 'rgba(2, 128, 0, 0.5)'
                          }
                   },
                   {},
                   {
                    scale: "test",
                    values: (self, ticks) => ticks.map(rawValue => rawValue.toFixed(2) + "Test"),
                    side: 1,
                    grid: {show: false},
                   },
                   ],
            series: [
                     {}
                    ]
  }
```
I intend to later append data with `addSeries()` with `scale ='test'` but in my above code I get `TypeError: Cannot read property 'scale' of undefined` (adding a series in the above code with `scale = 'test'` makes it work).

Is there a possibility to add axes options dynamically after initial configuration? I've checked the https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts but couldn't find any.

**Comment by leeoniya** [comment]
pretty sure what's going on here is that uPlot does not try to helpfully initialize the the `test` scale for you based on it being referenced in an axis -- uPlot will only try to helpfully init under-specified axes and scales from `series` opts at the time of init.

i think that explicitly adding the `test` scale will solve your issue:

```js
scales: {
  x: {time: true}
  test: {},
},
```

it probably makes sense to add scale auto-init from axes opts as well.

**Comment by GoodMorgon** [comment]
Adding the new scale at 

```
scales: {
  x: {time: true}
  test: {},
},
```
