### ISSUE TITLE
Compressing gaps in time

### ISSUE THREAD

**Issue by kelvin-yu** [leeoniya/uPlot#426]
What is the best way to omit periods of time where there isn't any data? In my plot there are gaps where there is no data (ex. weekend). It would be best if I could remove that gap in the x axis completely.

![image](https://user-images.githubusercontent.com/9397228/103452865-f5aaf700-4ca1-11eb-9e76-553614693f0e.png)

**Comment by leeoniya** [comment]
see https://github.com/leeoniya/uPlot/issues/261
