### ISSUE TITLE
Dynamic y-shifted series

### ISSUE THREAD

**Issue by GoodMorgon** [leeoniya/uPlot#428]
Hello,

I'm trying to replicate https://leeoniya.github.io/uPlot/demos/y-shifted-series.html but where I have a  button for toggling between a 'shifted y series' mode as in the example and a normal shared y-series between my series.

Is there any way I can edit the `axes[]` and `scales[]` dynamically as needed? Or is the only way to first `destroy()` the plot and recreate it with new options?

Thanks

**Comment by leeoniya** [comment]
can you show me your current config?

**Comment by GoodMorgon** [comment]
```
 function getSize() {

            return {
                    width: document.getElementById('chart-view').offsetWidth,
                    height: document.getElementById('chart-view').offsetHeight - 30
                   }

        }

        let opts = {
                    id      : 'uplot_chart',
                    class   : 'uPlot',
                    ...getSize(),
                    scales  : {
                               x : {time: true},
                               },
                    gutters : {
                               x : 0,
                               y : 0
                              },
                    axes    : [
                               {
                                grid : {
                                        width: 0.5,
                                        stroke: 'rgba(2, 128, 0, 0.5)'
                                       }
                               },
                               {}
                               ],
                    series  : [
                               {
                                value: function (self, rawValue) {

                                    let val = dayjs.unix(rawValue).tz()

                                    if (val.hour() === 0 && val.minute() === 0) return val.utc().format('YYYY-MM-DD')
                                    return val.utc().format('YYYY-MM-DD HH:mm:ss')

                                },
                                key: 'date'
                               }
                              ]
                    }

        this.chart = new uPlot(opts, null, document.getElementById('chart'))
```

:)

**Comment by leeoniya** [comment]
this doesn't tell much at all.

the demo you're referencing has y-series definitions [1], but your code has none. in the demo, `series.value` and `series.fillTo` functions would need to return different things based on whether you're in shifted mode or not. the same goes for `axis.values` and the actual data.

https://github.com/leeoniya/uPlot/blob/master/demos/y-shifted-series.html#L42-L66

**Comment by GoodMorgon** [comment]
Yes. 

My concern is how can I change the `axes[]` and `scales[]` definitions. I meant to ask before starting to code any possible solutions.

The current options is for a 'standard' shared y-axis solution, but how can it become like the demo with y-series definitions and added `axes[]` without recreating the plot from scratch? I don't know (I've checked the docs but there doesn't seem to be a `set` api for the axes and scales).

Recreating the plot when shifting between the two 'modes' seems unnecessarily heavy for the task.

**Comment by leeoniya** [comment]
it was easier to just add it to the demo than to explain it here :D

https://leeoniya.github.io/uPlot/demos/y-shifted-series.html

**Comment by GoodMorgon** [comment]
Forgive my ignorance. 

I haven't been able to fully replicate (understand) the example to my use-case. How do I scale the plot if the data is not perfectly aligned to the interval of 10 as in the https://leeoniya.github.io/uPlot/demos/y-shifted-series.html example?

I'm using `vue` as a wrapper for the `uplot`.

```
vm_uplot = new Vue({


    el: '#chart-wrapper',

    data: {
           inview      : false,
           chart       : null,
          },

    methods: {
              add_series: function(label, stroke, key, index) {

                  this.chart.addSeries({
                                        label  : label,
                                        stroke : stroke,
                                        key    : key,
                                        fillTo : this.chart_mode.fillTo,
                                        value  : this.chart_mode.value
                                       }, index)

              }

    },

    computed: {
               chart_mode: function () {

                   let normal = {
                                 values : (u, splits)       => splits,
                                 fillTo : (u, seriesIdx)    => 0,
                                 value  : (u, v, seriesIdx) => v,
                                 data   : (data)            => data,
                                 range  : [0, 10],
                                }

                   let shifted = {
                                  values : (u, splits)       => splits.map(v => v % 10 == 0 ? "Auxilirary" + (Math.floor(v/10) + 1) : v % 10),
                                  fillTo : (u, seriesIdx)    => 10 * (seriesIdx - 1),
                                  value  : (u, v, seriesIdx) => v - 10 * (seriesIdx - 1),
                                  data   : (data)            => data.map((vals, seriesIdx) => seriesIdx < 1 ? vals : vals.map(xVal => xVal + 10 * (seriesIdx - 1))),
                                  range  : [0, 30],
                           }



                   return normal // only returning normal just for now...

               }

    },

    mounted: function () {

        function getSize() {

            return {
                    width: document.getElementById('chart-view').offsetWidth,
                    height: document.getElementById('chart-view').offsetHeight - 30
                   }

        }

        let opts = {
                    id      : 'chart',
                    class   : 'uPlot',
                    ...getSize(),
                    scales  : {
                               x : {time: true},
                               y : {range: this.chart_mode.range}
                               },
                    gutters : {
                               x : 0,
                               y : 0
                              },
                    axes    : [
                               {
                                grid : {
                                        width: 0.5,
                                        stroke: 'rgba(2, 128, 0, 0.5)'
                                       }
                               },
                               {values: this.chart_mode.values}
                               ],
                    series  : [
                               {
                                value: function (self, rawValue) {

                                    let val = dayjs.unix(rawValue).tz()

                                    if (val.hour() === 0 && val.minute() === 0) return val.utc().format('YYYY-MM-DD')
                                    return val.utc().format('YYYY-MM-DD HH:mm:ss')

                                },
                                key: 'date'
                               }
                              ]
                    }

        this.chart = new uPlot(opts, null, document.getElementById('chart'))

         function throttle(cb, limit) {

            let wait = false;

            return () => {

                if (!wait) {

                    requestAnimationFrame(cb)
                    wait = true
                    setTimeout(() => {wait = false}, limit)

                }
            }

        }

        window.addEventListener("resize", throttle(() => vm_chart.chart.setSize(getSize()), 100));

    }

})
```
These are my results with the above code.

![Untitled](https://user-images.githubusercontent.com/55554176/104123014-d585d280-5348-11eb-81cc-c5f0ce763bb5.png)

Again, I'm fairly new to Javascript... but how do I get the y-axis to scale correctly when the data is not neatly fitting `range: [0-30]`? I've tried different changes to the codes but without luck. Any help would be much appreciated.

**Comment by vinnitu** [comment]
What is **Core #4** in your example if we have only 3 series? (Core #1, Core #2  and Core #3)

![image](https://user-images.githubusercontent.com/432168/170678699-0129cab7-40d1-42c0-bce5-24eb7fda719f.png)

**Comment by vinnitu** [comment]
and what about different ranges? and autoscale by y-asix every serie? Very useful functionaliry in general

**Comment by leeoniya** [comment]
every Core label is a 0 value of that series and also the 10 value of the series below it. you can change the labels to something else.

autoscaling can be done by adjusting a lot of the demo code (similar to the stacking demos) but is likely a bad idea, since the y range becomes difficult to interpret at a glance.

**Comment by vinnitu** [comment]
Often the user needs to see a column of charts with the same time domain.
In this case it is better to display one time axis at the bottom of column.
But in my case all charts have same width with shared crossline cursor.
That is why I look at this (shifted-y) example as start point.

**Comment by leeoniya** [comment]
take a look at Inverted Log10 Y Scale demo here: https://leeoniya.github.io/uPlot/demos/log-scales2.html

it uses two charts with a synced cursor and hides the x axis on the top chart to show different ranges it also does some DOM manip during init to combine the legend from both. this strategy might work better for you.

**Comment by vinnitu** [comment]
but there are two different charts, and I don't like magic DOM manipulation like
![image](https://user-images.githubusercontent.com/432168/171491346-af867b08-c656-45c8-bf49-203c5dbf66da.png)

I can't even imagine what needs to be done for 8 charts... (It is real case)
