### ISSUE TITLE
Super nit: set the homepage in the github project

### ISSUE THREAD

**Issue by breck7** [leeoniya/uPlot#434]
GitHub let's you set a url as the "homepage" for a project. I find it super helpful to quickly see the "canonical" demo of a project.

Video of how to do it:

https://user-images.githubusercontent.com/74692/104795136-2c781700-5750-11eb-9ae0-390b47a689ec.mov

uPlot looks great! I like the idea of a tiny plotting lib.

**Comment by leeoniya** [comment]
i suppose the closest to "canonical" demo is the benchmark: https://leeoniya.github.io/uPlot/bench/uPlot.html

but uPlot's capabilities are so much larger now, that that demo only speaks to the performance, so i'm not terribly inclined to use that.

ideally, something like the header of https://d3js.org/ should be done (minus the honeycomb & parallax shenanigans) using all the stuff from https://leeoniya.github.io/uPlot/demos/index.html, and resembling the demo image https://github.com/leeoniya/uPlot/blob/master/uPlot.png

i need to find some time to put the demos into a table, and take representative snippet pngs of each, and add a bunch of keywords to the index for each entry to help people navigate to what they wanna find via Ctrl+F.

if you're interested in helping, that would be cool!

**Comment by breck7** [comment]
Sure why not!
I need to test out a few tech things for
work anyway, could kill 2 birds with one stone.

You've left a good spec, I'll see if I can
come up with a draft by next weekend.

(But don't want to stop anyone
else from doing this if they're interested)

**Comment by leeoniya** [comment]
gonna close this, but if you get around to working on demo page improvements, open an early PR before you do too much work to make sure it matches what i'm looking for. thanks!

**Comment by breck7** [comment]
Sounds good! Sorry still working on shipping a big refactor at the day job, and so realistically will be a bit longer before I have some free cycles!

`OverOptimisticTimeEstimates++;`

**Comment by leeoniya** [comment]
no worries :+1:
