### ISSUE TITLE
Dynamically change axis ticks labels formatting

### ISSUE THREAD

**Issue by zefirka** [leeoniya/uPlot#437]
Hi, @leeoniya!

I have a question about axes ticks label formatting. Can I dynamically change that? I'm trying to implement graph units plugin which should just change axes ticks label suffix. I tried to overwrite `axes[i].values` and redraw chart, but it doesn't rerender axes. I can't figure out how to update chart axes when chart is already rendered?

**Comment by leeoniya** [comment]
use, the callbacks, Luke: https://github.com/leeoniya/uPlot/blob/f0f8b085b2ba285ce6e716708279b61ab5790bd0/dist/uPlot.d.ts#L701

**Comment by zefirka** [comment]
I'm using it. But how can I dynamically change it's value and re-render axis? 

I have an example here: https://jsfiddle.net/7vztr5oL/1/

Suppose, I want to change axis labels precision to `number.fixed(3)` when I click to button.

**Comment by leeoniya** [comment]
hmm, in theory this is the way to do it: https://jsfiddle.net/ckb1wn0f/, but i think it's hitting a caching bug. since the data & scales don't change, it assumes the axes don't change, so it re-uses the cached `axis[i]._values`.

**Comment by leeoniya** [comment]
added an option to invalidate & recompute the plot geometry cache during redraw() calls, which internally re-invokes `axis.spits()` and `axis.values()`: https://jsfiddle.net/dk46jmst/
