### ISSUE TITLE
Series fill missing if lower band series not shown

### ISSUE THREAD

**Issue by stephanme** [leeoniya/uPlot#438]
uplot 1.6.1

I use the new bands feature for a stacked graph visualizing availability data (I know your concerns ...). The basic idea is to show availability information (uptime, downtime, unmonitored) by different fill colors. The sum is always 100%.

![uplot-bands-1](https://user-images.githubusercontent.com/1076668/105068257-066cb280-5a81-11eb-9e06-6b209bee0491.png)

Series configuration:

```
      series: [
        {
          label: 'Time',
        },
        {
          label: 'Unmonitored',
          paths: uPlot.paths.stepped({align:  1}),
          stroke: '#FFBB00',
          fill: '#FFBB0022', // yellow
          width: 1.2,
          points: noPoints,
        },
        {
          label: 'Downtime',
          paths: uPlot.paths.stepped({align:  1}),
          stroke: '#A60000',
          fill: '#A6000022', // red
          width: 1.2,
          points: noPoints,
        },
        {
          label: 'Uptime',
          paths: uPlot.paths.stepped({align:  1}),
          stroke: '#00CC00',
          fill: '#00CC0022', // green
          width: 1.2,
          points: noPoints,
        },
      ],
      bands: [
        {
          series: [1,2], // fill Unmonitored to Downtime
          fill: '#FFBB0022', // yellow
        },
        {
          series: [2,3], // fill Downtime to Uptime
          fill: '#A6000022', // red
        },
      ],
```

Btw. the bands feature introduced with 1.6 is much nicer than my previous hack with own fillTo function + patched SteppedPathBuilder that misuses one of the fillTo parameters.

Now, the user can disable e.g. the uptime series in order to see the downtime with higher resolution (checkboxes in upper left corner). When the user clicks on the checkboxes, the stacked graph data is recalculated and e.g. uPlot.setSeries(1, { show: false }) is called. Works in principle but the fill color for a highSeriesIdx series is missing when the lowSeriesIdx series is not shown.

See the following examples:

unmonitored (idx=1) not shown - works as expected.
![uplot-bands-2](https://user-images.githubusercontent.com/1076668/105068368-27350800-5a81-11eb-8822-cf04de531138.png)

downtime (idx=2) not shown - yellow fill for unmonitored missing (e.g. on the right).
![uplot-bands-3](https://user-images.githubusercontent.com/1076668/105068389-2d2ae900-5a81-11eb-9528-eeedc9ad99ea.png)

uptime (idx=3) not shown - red fill for downtime missing, but yellow fill is shown
![uplot-bands-4](https://user-images.githubusercontent.com/1076668/105068410-33b96080-5a81-11eb-94d2-b8d320ec3b69.png)

**Comment by leeoniya** [comment]
i think you'll need to shuffle around the bands defs as part of your toggle, yes, also a bit of a hack. you can mutate each `u.series.bands` def and give it new series indices. i was considering introducing `u.setBand()` or similar to make it slightly more formal.

**Comment by stephanme** [comment]
Thanks. This helped to fix it.
