### ISSUE TITLE
expose a way to use a custom/external microTask impl

### ISSUE THREAD

**Issue by maxhq** [leeoniya/uPlot#439]
The use of a Promise for `microTask()` prevents user code from catching any errors that might occur in the function passed to `microTask()` - i.e. `commit()`.
This happens e.g. if the `data` Array contains less entries than what `opts.series` define. 

The problem can easily be shown by this code:
```javascript
// User code with Promise.catch()
new Promise((resolve, reject) => {
  // microTask()
  Promise.resolve().then(
    // code passed to microTask() throws some error:
    () => { throw new Error("Test error") }
  )
})
.catch(e => console.error("Caught via Promise.catch()", e)) // not called

// User code with try-catch
try {
  // microTask()
  Promise.resolve().then(
    // code passed to microTask() throws some error:
    () => { throw new Error("Test error") }
  )
}
catch(e) { console.error("Caught via try-catch", e) } // not called
```
I cannot think of an easy solution other than turning uPlot itself into a Promise. But it's late and I'm tired and there might be an easy solution :)

**Comment by maxhq** [comment]
Just for the record: this is a fantastic piece of software and in my 20+ years as a developer I have rarely seen modules as efficient, pure, well thought of and fun to use as uPlot. Thank you!

**Comment by leeoniya** [comment]
> Just for the record: this is a fantastic piece of software and in my 20+ years as a developer I have rarely seen modules as efficient, pure, well thought of and fun to use as uPlot. Thank you!

thanks! glad you're enjoying it :)

> I cannot think of an easy solution other than turning uPlot itself into a Promise. But it's late and I'm tired and there might be an easy solution :)

unfortunately, i'm far from an event loop expert. i thought maybe this might help, but i don't think it does: https://github.com/feross/queue-microtask/issues/2#issuecomment-529726146

**Comment by maxhq** [comment]
> unfortunately, i'm far from an event loop expert. i thought maybe this might help, but i don't think it does: [feross/queue-microtask#2 (comment)](https://github.com/feross/queue-microtask/issues/2#issuecomment-529726146)

I tried it but you are right, it doesn't help: obviously `Window.queueMicrotask()` is already defined so I cannot alter it.

What whould be really helpful is if you allowed for configuration of `microTask()` e.g. via options so that `commit()` (https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L1591) would use a custom function.

**Comment by leeoniya** [comment]
> What whould be really helpful is if you allowed for configuration of microTask() e.g. via options

:100: , feel free to PR this. (plz leave the builds out of the PR for easier review, i'll build post-merge)

**Comment by leeoniya** [comment]
hey @maxhq 

if you still need this, please open a PR. i'm gonna close this out for now as i don't plan to add it since this is the only request i've encountered since switching to async batching.
