### ISSUE TITLE
How to use uPlot with NejtJS

### ISSUE THREAD

**Issue by coditori** [leeoniya/uPlot#443]
Hi, I just saw the react sample and it works fine but with next I got this error "navigator is not defined", dynamic import could not help me either.

**Comment by leeoniya** [comment]
think you gotta wait until mount and init uPlot in a useEffect hook?

https://github.com/vercel/next.js/discussions/11027

**Comment by coditori** [comment]
@leeoniya Yes because we need to access uplot constructor

**Comment by leeoniya** [comment]
i'm not familiar with nextjs. does this solve your issue?
