### ISSUE TITLE
How to always display series points (even when zoomed out)

### ISSUE THREAD

**Issue by kaspar030** [leeoniya/uPlot#447]
I have a series that essentially draws some points over another series when certain events happened.

I'd like to have those points to be shown at all zoom levels, so I can zoom out, quickly scan where these events happen, then zoom back in on those. Unfortunately no data points are drawn after zooming out past a certain level.

Is this level configurable somewhere? Preferably per-series?

**Comment by leeoniya** [comment]
set `series.points.space: 0`:

https://github.com/leeoniya/uPlot/blob/a2ba0a7fd7d2901a14d93bdeaee23ae154b01a60/demos/points.html#L48-L55

**Comment by kaspar030** [comment]
That's what I was looking for. Thanks for the quick reply!

And big thanks for uPlot in general! :+1: :+1:
