### ISSUE TITLE
How to prevent native zoomin in uPlot where setSelect fires

### ISSUE THREAD

**Issue by zefirka** [leeoniya/uPlot#448]
Hi @leeoniya. 

I was pretty sure that at some point next code works: 

```ts
hooks.setSelect.push((u: UPlot) => {
    // do something with calculated from-to points of X scale
    u.setSelect({width: 0, height: 0, top: 0, left: 0}, false);
});
```
But I rolled back to version `1.4.x` (at this time I started working with uPlot) and found out that this didn't work. So I have question: how can I prevent default zoom when I'm selecting some range in chart? Let's say I should just catch up selection range and fire event for external usage which should fetch new data and redraw whole chart. If let chart default zooming then It could be a blinking when chart renders zoomed paths and after a second comes new render which can a little bit differ from uPlot's zoom view.

**Comment by leeoniya** [comment]
you're looking for this:

https://github.com/leeoniya/uPlot/blob/a2ba0a7fd7d2901a14d93bdeaee23ae154b01a60/demos/zoom-ranger-grips.html#L145
