### ISSUE TITLE
Plotting high / low band and separate line series

### ISSUE THREAD

**Issue by benmccann** [leeoniya/uPlot#45]
Is it possible to plot a high / low band and a separate line?

**Comment by leeoniya** [comment]
i'm not sure what you mean.

the high/low band does not require anything besides two adjacent series. it's independent of everything else.

**Comment by benmccann** [comment]
So if a high / low band is:
```
			let data = [
				gold[0],	// time
				gold[4],	// low
				gold[3],	// high
				gold[1],	// close
			];
```

Then would a high / low band + a separate series be the following?
```
			let data = [
				gold[0],	// time
				gold[4],	// low
				gold[3],	// high
				gold[1],	// close
				voo[1],	// vanguard s&p 500 close
			];
```

**Comment by leeoniya** [comment]
right.

adjacent series that are `band: true` are grouped and plotted as bands. `gold[1]` has no special meaning, it's and independent series as well.

**Comment by benmccann** [comment]
Ahhh, that's a helpful clarification. I didn't realize that. Thanks!

I'll leave this open in case you end up wanting to track it to add any docs, but feel free to close as well

**Comment by leeoniya** [comment]
since this has a demo comitted already & linked from readme, it's unlikely to be overlooked when time comes for docs.
