### ISSUE TITLE
Fill color below 0

### ISSUE THREAD

**Issue by damianoporta** [leeoniya/uPlot#451]
Hello
i need to create an chart like this: demos/add-del-series.html with just one line. 
Can we set two different fill colors, one for positive area and one for negative area?

**Comment by leeoniya** [comment]
yes, you have to use gradients for stroke and/or fill:

https://leeoniya.github.io/uPlot/demos/gradient-fill.html
https://leeoniya.github.io/uPlot/demos/gradient-stroke.html
