### ISSUE TITLE
uPlot much slower in macOS Big Sur than Linux / macOS Mojave

### ISSUE THREAD

**Issue by gerhat** [leeoniya/uPlot#452]
Running some uPlot benchmarks, I noticed significant performance delta between Chrome 88 in macOS Big Sur and Chrome 87 in Linux Mint 20 or macOS Mojave.

Here are the scenarios and the times in **ms**:
| OS | 1 graph / 50 curves / 1K points | 4 graphs / 10 curves / 1K points | 10 graphs / 10 curves / 1K points | 100 graphs / 10 curves / 1K points |
| :-- | -------------------------------: | --------------------------------: | ---------------------------------: | ----------------------------------:|
linux mint 20 | 63.70 | 83.06 | 152.51 | 962.18
macOS Mojave  | 26.07 | 48.21 | 65.43 | 791.08
macOS Big Sur | 486.68 | 411.47 | 1026.82 | 9860.96

Do you have any idea why this might be the case?

It worths mentioning that ECharts/SVG does not suffer from this performance impact.
ECharts/Canvas presents similar degradation.

**Comment by leeoniya** [comment]
> ECharts/Canvas presents similar degradation.

interesting! certainly seems like either a platform or chrome bug if it affects both libs. maybe try opening a chrome bug with details and let them investigate. unfortunately, i won't be much use here.

**Comment by leeoniya** [comment]
would be curious to see Firefox and Safari numbers on the same machines.

**Comment by gerhat** [comment]
I believe it is OS related. Even Safari (which I guess gets full access to the hardware) suffers at the 4th scenario (100 graphs / 10 curves / 1K points)

**Firefox**
OS | 1 graph / 50 curves / 1K points | 4 graphs / 10 curves / 1K points | 10 graphs / 10 curves / 1K points | 100 graphs / 10 curves / 1K points |
:- | ------------------------------: | -------------------------------: | --------------------------------: | ---------------------------------: |
macOS Mojave | 82.00 | 90.00 | 196.00 | 1630.00
macOS Big Sur | 520.00 | 415.00 | 1040.00 | 10283.00


**Safari**
OS | 1 graph / 50 curves / 1K points | 4 graphs / 10 curves / 1K points | 10 graphs / 10 curves / 1K points | 100 graphs / 10 curves / 1K points |
:- | ------------------------------: | -------------------------------: | --------------------------------: | ---------------------------------: |
macOS Mojave | 20.00 | 36.00 | 66.00 | 624.00
macOS Big Sur | 21.00 | 25.00 | 81.00 | 4283.00

**Comment by gerhat** [comment]
Here is the chromium issue I opened: https://bugs.chromium.org/p/chromium/issues/detail?id=1177629

**Comment by leeoniya** [comment]
gonna close this, since nothing actionable here for uPlot.
