### ISSUE TITLE
How to hide points?

### ISSUE THREAD

**Issue by liujiajun** [leeoniya/uPlot#454]
Thanks for the great library!

I have a question - how do I hide the dots shown on the lines? I guess there is a simple solution, but looked up the demos and docs to no avail.

Thank you!

**Comment by leeoniya** [comment]
hey @liujiajun 

`series.points.show: false` or `series.points.space: Infinity`

all the options are listed here:

https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L551

**Comment by liujiajun** [comment]
Thank you for the prompt reply :-)
