### ISSUE TITLE
Center the chart with a pivot point

### ISSUE THREAD

**Issue by damianoporta** [leeoniya/uPlot#456]
Hello @leeoniya again! thank you so much for your support of these days.

I made this chart:
![Schermata del 2021-02-12 15-51-47](https://user-images.githubusercontent.com/7131996/107783507-a0efa700-6d4a-11eb-87a4-79120840ceae.png)

The blu line has been drawn by me.

My series has these points [50, 150, -41, 2, 80, 10] as you can see the first one is **50** i would like to use this first point as pivot point, like the **0**
Is that possible?

I know that i can do that rescaling the points around zero, but maybe there is a different way to do that avoiding additional computations.

Thank you very much!

**Comment by leeoniya** [comment]
you should do it in the data.

while you might be able to tweak enough of scale and axis settings to shift the axis & grid, subtracting 50 from every value is super cheap and a lot less complicated than trying to avoid it.

probably relevant demo:

https://leeoniya.github.io/uPlot/demos/y-shifted-series.html

**Comment by damianoporta** [comment]
@leeoniya thank you!
ok i will reduce the data points using a simple map: `points.map(element => element - (difference_between_first_point_and_zero))`

Thanks

**Comment by leeoniya** [comment]
if you're concerned about performance, you should avoid callback-style loops.

```js
let data = [1,2,3];

let offset = data[0];

let shifted = Array(data.length);

for (let i = 0; i < data.length; i++)
    shifted[i] = data[i] - offset;
```
