### ISSUE TITLE
Jupyter widget

### ISSUE THREAD

**Issue by sohailsomani** [leeoniya/uPlot#457]
Hi Leon,

Here is a preliminary Jupyter widget that might be useful to some uPlot users: https://github.com/sohailsomani/uplot_jupyter_widget

It isn't well tested but I figured others might find it useful.

**Comment by leeoniya** [comment]
neat, thanks!

i added it to the readme: https://github.com/leeoniya/uPlot#third-party-integrations

**Comment by zhibor** [comment]
@sohailsomani [sohailsomani/uplot_jupyter_widget](https://github.com/sohailsomani/uplot_jupyter_widget) doesn't exist any more. did you rename it? could you kindly update the doc with the new link? much appreciated!
