### ISSUE TITLE
Parse datetime from JSON 

### ISSUE THREAD

**Issue by Jay27D** [leeoniya/uPlot#458]
I am currently making a web app based on Blazor.
The main problem I'm having at the moment is to parse the date time to uPlot in a way that can be recognized. Long story short, I'm parsing a json object (read as a string) to the script using IJSruntime. In the script I parse it to an object to be able to get the keys  dynamically and pass those to uPlot for the legend. So far, I managed to plot all the data with a simulated "time" which is basically a series of natural numbers. Obviously, the length is the same as the the length of the data arrays. 
Now, I'm getting the date as a string array and when I print it out to the console this is what I get:

    [Thu Oct 15 2020 15:26:24 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:25 GMT+0200 (Central 
    European Summer Time), Thu Oct 15 2020 15:26:26 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:27 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:28 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:29 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:30 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:31 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:32 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:33 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:34 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:35 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:36 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:37 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:38 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:39 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:40 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:41 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:42 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:43 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:44 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:45 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:46 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:47 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:48 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:49 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:50 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:51 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:52 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:53 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:54 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:55 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:56 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:57 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:58 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:26:59 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:00 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:01 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:02 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:03 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:04 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:05 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:06 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:07 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:08 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:09 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:10 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:11 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:12 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:13 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:14 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:15 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:16 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:17 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:19 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:20 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:21 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:22 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:23 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:24 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:25 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:26 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:27 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:28 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:29 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:30 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:31 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:32 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:33 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:34 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:35 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:36 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:37 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:38 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:39 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:40 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:41 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:42 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:43 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:44 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:45 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:46 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:47 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:48 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:49 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:50 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:51 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:52 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:53 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:54 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:55 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:56 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:57 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:58 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:27:59 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:28:00 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:28:01 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:28:02 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:28:03 GMT+0200 (Central European Summer Time), Thu Oct 15 2020 15:28:04 GMT+0200 (Central European Summer Time), …]

I then assigned the time the following way (obj is the JSON object containing the data): 

     let time = obj.Time.Date.map(x => new Date(x.replace(/\//g, "-")));
     console.log(time);
     var data = [time]

I then included tzDate in the options this way:
    
    const opts = {
        width: gWidth,
        height: gHeight,
        tzDate: ts => uPlot.tzDate(new Date(ts)),
        plugins: [
            wheelZoomPlugin({ factor: 0.75 })
        ],
        scales: {
            x: {
                time: false, 
            }
        },
        series: seriesStr,
    };

And finally, I plot using the following line:

    let u = new uPlot(opts, data, document.getElementById("targetGraph1"));

I also tried removing the time:false line but I can't seem to figure out a way to make it work. How is the data supposed to be parsed to uPlot? Also, is there any documentation about it on git? 
Also.... is there any way to view the date time at an angle? (for better readability) 

Thank you very much in advance!

**Comment by leeoniya** [comment]
> The main problem I'm having at the moment is to parse the date time to uPlot in a way that can be recognized

using `new Date()` to parse date strings on the client is not recommended, since it works unreliably and differently in most browsers [1]. if possible, you should return unix timestamps from your datasource. if you _must_ parse on the client, and `new Date()` parses properly for you, you can convert them to unix timestamps like this:

```js
let time = obj.Time.Date.map(x => (new Date(x.replace(/\//g, "-"))).getTime() / 1e3);
```

> Also.... is there any way to view the date time at an angle? (for better readability)

see how this demo rotates x labels: https://leeoniya.github.io/uPlot/demos/box-whisker.html

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

**Comment by leeoniya** [comment]
also, you should not need `tzDate` unless you want to display time in a timezone that's different than the browser's.
