### ISSUE TITLE
Is it possible to get mouse events for series?

### ISSUE THREAD

**Issue by gerhat** [leeoniya/uPlot#460]
I would like to run a custom function when the user clicks on a series. Is there any way I can achieve this?

**Comment by leeoniya** [comment]
is this different than https://github.com/leeoniya/uPlot/issues/239?

**Comment by gerhat** [comment]
It's different because #239 is about clicking on a point. I want to be able to click anywhere on the curve and make it appear as selected.

I saw the `tooltips-closest.html` example. Thank you.

**Comment by leeoniya** [comment]
the curves are interpolated by canvas, so it's not possible to hover the actual strokes. maybe if uPlot ever gets a slower svg backend it can be done easily, but there are no near-term plans for this.

**Comment by leeoniya** [comment]
i should clarify that it's possible, but not if you want Safari support: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/isPointInStroke

**Comment by gerhat** [comment]
Thank you @leeoniya it helps. I will check it.

**Comment by Nouran96** [comment]
> 

Where should this work ? I tried to add this code into the ready hook but it always logs false
`
u.over.addEventListener("mousemove", (e) => {
	const rect = over.getBoundingClientRect();
	const isPointInStroke =
		u.ctx.isPointInStroke(
			e.offsetX,
			e.offsetY
		);
	console.log(isPointInStroke);
});
`
