### ISSUE TITLE
Question: Render series on different time grid with gaps

### ISSUE THREAD

**Issue by zefirka** [leeoniya/uPlot#461]
Hi @leeoniya 

This is mostly question, not a feature request. But I'm really stuck into this.

When I was implementing chart rendering from different data sources I faced with next trouble. I have a data sources which generate data on grid by interval of 15 seconds and 30 seconds so I have next raw data:  

```
Line 1: data = [1, 2, 3, 4, 5, 6, 7], timestamps: [0, 15, 30, 45, 60, 75, 90]
 Line 2: data = [10, 20, 30, 40], timestamps: [0, 30, 60, 90]
```

As I understand uPlot requires single timeline for every series so I can easily convert raw data to:  

```js
const data = [
  [0, 15, 30, 45, 60, 75, 90],         // timeline
  [1, 2, 3, 4, 5, 6, 7],               // serie 1 (15 sec)
  [10, null, 20, null, 30, null, 40],  // serie 2 (30 sec)
];
```
 
 and switch `spanGaps: true`. And it works well. But troubles begin when in my data source appearing really `NULL` values which means that at that timestamp I have actual `null` and I should to render gaps at that timestamp.

```
 Line 1: data = [1, 2, 3, 4, 5, 6, 7], timestamps: [0, 15, 30, 45, 60, 75, 90] 
 Line 2: data = [10, null, 30, 40], timestamps: [0, 30, 60, 90]
```

And when I convert it to uPlot `AlignedData` I come to problem that I can’t just switch `spanGaps: true` because I can’t differ nulls for spanning gaps between them and nulls which I want to show as gaps.

```js
data: [
  [0, 15, 30, 45, 60, 75, 90], // timeline
  [1, 2, 3, 4, 5, 6, 7],       // serie 1 (15 sec)
  [
    10, 
    null, // <- span gap
    null, // <- render gap
    null, // <- span gap
    30,
    null, // <- span gap
    40,
   ],                          // serie 2 (30 sec)
]
```

The only solution I came up with is to interpolate all values into these nulls where I should span gaps, remember original data (for tooltip and `cursor.dataIdx`) and don’t replace these nulls which I want to show as gaps and switch `spanGaps: false`. 

So question is about what do you think about that? Maybe I didn’t understand fundamental restrictions of uPlot about single timeline for all data lines or I am right? If I’m right, have you thought about adding new special data type to differ nulls-as-empty-data from nulls-as-gaps-in-grid?

**Comment by leeoniya** [comment]
we just went through this in grafana ;)

you should use `undefined` for alignment artifacts and `null` where you want to show gaps. and leave `spanGaps: false`.

`uPlot.join()` will do this for you. see https://github.com/leeoniya/uPlot/blob/master/demos/align-data.html

**Comment by zefirka** [comment]
Hi there @leeoniya !

I've been through this issue last days and now I have some additional questions. There are cases when given approach doesn't work. For example map values to percents. For this calculations I should know the sum of all series on given X-point:

```
[1, 1, 1]      [25, 25, 25]
[1, 1, 1]  ->  [25, 25, 25] 
[2, 2, 2]      [50, 50, 50]
```
But if some y-value is `undefined` then I can't count the sum. So I need something more than `uPlot.join` which just align data on single timeline and replace missing data with `undefined`, I need real y-values which will be rendered on series in place of `undefined`s. As I understand `uPlot/paths` doesn't calculate y-values of missing data, just get next point's position and stroke line between two non-undefined and non-null points. 

I know that there are stacks and percents in Grafana, also there is highlighting nearest line by y-value in legend-in-tooltip . What are you planning to do with stacks on different time grid (as in example in subject)? Maybe you have some tricks what can be done with uPlot to handle stacks (or percents). My solution is about to really interpolate missing data (e.g. `[1, undefined, 3] -> [1, 2, 3]`), cache original data (for proper `findDataIdx` and legend-in-tooltip) and it sounds really memory expensive, but I can't find any other solutions.

**Comment by leeoniya** [comment]
> What are you planning to do with stacks on different time grid (as in example in subject)?

i haven't thought about it too much yet, but it's sure to come up soon :)

i hate stacked charts to begin with, so figuring out how to stack unaligned datasets is the next level of crazy. what you outlined seems like the logical path -- interpolating across undefined regions and adjusting the original values to stack based on those interpolations. that's what i would do as well.

if you fancy drawing the paths yourself, you can also take a look at Flot's fillBelow code, which i think does even more expensive geometric/shape stacking: https://github.com/whatbox/jquery.flot.fillbelow/blob/master/jquery.flot.fillbelow.js

not applicable to unaligned data, but maybe useful: https://leeoniya.github.io/uPlot/demos/stacked-series.html
