### ISSUE TITLE
Dynamically set series options

### ISSUE THREAD

**Issue by zac-yang** [leeoniya/uPlot#462]
Hi, thanks for the great library! I've been exploring how we might migrate our (much slower) recharts/d3 implementation over. Is there any way to set series options after init, beyond `show` & `focus` exposed in `setSeries()`?

In particular, we'd like to be able to set `points.show` to allow user toggling of line markers.

Tried using `delSeries()` / `addSeries()` but that seemed to break many things in between.

**Comment by leeoniya** [comment]
> In particular, we'd like to be able to set points.show to allow user toggling of line markers.

`series.points.show` can be specified as a function, which can return true/false dynamically, so you can implement an external toggle that calls `.redraw()` afterwards.

https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L565

**Comment by zac-yang** [comment]
Thanks @leeoniya! Managed to figure it out, cheers
