### ISSUE TITLE
Ranger out of boundaries

### ISSUE THREAD

**Issue by damianoporta** [leeoniya/uPlot#465]
Hello 
I need to create a chart like this one: https://leeoniya.github.io/uPlot/demos/zoom-ranger-grips.html
I think it has a bug because the ranger does not stay properly within its boundaries.

Do we have a correct demo for it? I need to create a candlestick chart with a ranger like that.
Thanks

**Comment by leeoniya** [comment]
> I think it has a bug because the ranger does not stay properly within its boundaries.

yes, there is some clamping missing to limit the drag ranges. i won't be able to get to fixing it till late next week. if you'd like to submit a PR with a fix, i will review it.

**Comment by damianoporta** [comment]
@leeoniya I think we just need to fix the update function (https://github.com/leeoniya/uPlot/blob/master/demos/zoom-ranger-grips.html#L102-L105). checking:

1. if newLft is < 0 
2. if newLft + newWid > uRanger.bbox.width

is `uRanger.bbox.width` the correct wait to retrieve the width of the ranger?
Inspecting the uRanger of the demo, the width is 725px, is that correct?

**Comment by leeoniya** [comment]
yep, fixed.
