### ISSUE TITLE
The problem of large value display

### ISSUE THREAD

**Issue by dukelec** [leeoniya/uPlot#467]
In the first figure, the Y-axis value is incomplete.
In the second figure, the X-axis value overlaps. (first number: 47,495,000)

![Screenshot_2021-03-10_17-05-32](https://user-images.githubusercontent.com/4454365/110607810-90561380-81c6-11eb-9590-a15aa5215d97.png)

Could you optimize these two issues? Thank you.

**Comment by leeoniya** [comment]
there are several ways to fix this. when i expect large values, i usually use `axis.values` to reformat them, e.g. 47,495,000 -> 47,495K. another option for x is to increase `axis.space` to decrease the grid density and spread the values further apart. for y values, you can increase `axis.size`. if you want to make axis size automatic you can see this example: https://leeoniya.github.io/uPlot/demos/axis-autosize.html

**Comment by dukelec** [comment]
Thank you very much for your reply, I added the following axes configuration and both problems are solved.
Although I am not sure what the fullDim and cycleNum do.

```
    axes: [
        {
            space(self, axisIdx, min, max, fullDim) {
                return Math.max(min.toFixed(3).length * 8, max.toFixed(3).length * 8);
            },
        }, {
            size(self, values, axisIdx, cycleNum) {
                if (!values) // avoid null value during init
                    return 40;
                return Math.max(values[0].length * 8, values[values.length-1].length * 8) + 8;
            },
        }
    ],
```

**Comment by leeoniya** [comment]
> The fullDim should be the width of the actual plot area ( ≈ opts.width - Y axis value string width).

also minus padding. it's the css pixel width of the area occupied by the grid (plotting area).

> The return value of the space function should be the width between grids

it's technically the _minimum_ spacing you need, since the ticks still need to be "nice", so uPlot will ensure that it picks the best available tick increment with at least the space you return.

> so there should be no need for fullDim to participate in the calculation, right?

you may choose to base the decision on the avg tick density you expect, with knowledge of how you're formatting your ticks, etc. you don't _need_ to use it :)
