### ISSUE TITLE
Scaling an entire uPlot chart proportionally

### ISSUE THREAD

**Issue by chrisdalke** [leeoniya/uPlot#469]
I'm looking for a way to setup a "presentation mode" which would scale a visualization proportionally on large screens. I've tried using `transform: scale(...)` to scale a fixed-size container, which preserves the layout and relative sizes of all components. With uPlot this doesn't work well because it breaks the mouse coordinate calculations.

I've thought about a few ways to do this:
1) Manually apply a scaling factor to every uPlot configuration option: font size, stroke, paddings, etc. 
2) Use `transform: scale(...)` to apply a scale to the entire visualization. Add a `scale` factor to the uPlot config which would multiply the canvas resolution and any mouse coordinates.

Do you have any thoughts on the simplest way to do this? Is there currently any type of logic for scaling factors on Retina displays that could be hijacked to support this? I recognize this is a bit of an edge case 😀

**Comment by leeoniya** [comment]
i guess let's get the obvious out of the way: why not use `u.setSize()`?

https://leeoniya.github.io/uPlot/demos/resize.html

**Comment by chrisdalke** [comment]
I'm trying to scale proportionally, which looks different than responsive sizing: I'd like to display the entire thing at a scale (e.g. 2x), as if the browser was zoomed in.

I might have better named this issue "Rendering a uPlot chart inside a container with a CSS transform", because it seems like that's the most feasible option. Here's an example codepen: https://codepen.io/chrisdalke/pen/WNomELr

As an example of a library that plays nicely `transform: scale`, see https://github.com/react-grid-layout/react-grid-layout:
```
// If parent DOM node of ResponsiveReactGridLayout or ReactGridLayout has "transform: scale(n)" css property,
// we should set scale coefficient to avoid render artefacts while dragging.
transformScale: ?number = 1,
```

I'm looking for your input:
1) Am I heading in the right direction or do you see a better method to accomplish this scaling?
2) If the CSS transform method is the most promising, would a configuration option for this belong in uPlot?
3) Is the above something you'd accept a PR for? It seems like this would involve a config parameter for `transform`, and use of that parameter anytime uPlot initializes the canvas or gets raw mouse positions.

**Comment by leeoniya** [comment]
i think there's more to this than cursor position. to get crisp rendering of a CSS-transformed chart, you would also need to weave a per-instance `devicePixelRatio` through to everywhere that currently uses a global `pxRatio`. Chart.JS currently has an option like this: https://www.chartjs.org/docs/latest/general/device-pixel-ratio.html

feel free to explore this in a PR, but if it gets too hairy, i reserve the right say that the "tedious" route is the recommended one.

**Comment by chrisdalke** [comment]
Got it, thanks for the suggestions. I'll play around with overriding the `pxRatio` and mouse calculations, but like you said it might get a bit hairy. I'll open a PR or another issue if I'm able to sort out an elegant solution.
