### ISSUE TITLE
Change cursor options during runtime

### ISSUE THREAD

**Issue by Andro172** [leeoniya/uPlot#470]
It would be useful to change cursor drag property during runtime, especially setScale prop. That way we can control if we want to zoom or just show selected range.

something like this maybe:

```
self.setDrag = function setDrag(dragOps) {
      assign(drag, dragOps)
      
      if (dragOps.setScale) {
	      hideSelect()
      }
      
      commit()
}
```

**Comment by leeoniya** [comment]
i think there are a number of ways to do this already without introducing a new API.

can you provide a more detailed description of what you mean by "during runtime"? do you mean while dragging, or just post-init?

it looks like i missed listing this demo in the demo index, but it pretty much does what i think you're looking for: https://leeoniya.github.io/uPlot/demos/cursor-bind.html

**Comment by Andro172** [comment]
just post init,i think i got what i need, thanks for reply :D

**Comment by leeoniya** [comment]
:+1:
