### ISSUE TITLE
fmtDate formats 100 milliseconds as 099

### ISSUE THREAD

**Issue by GlennMatthys** [leeoniya/uPlot#472]
When formatting a timestamp with milliseconds, if milliseconds = 100 then it gets formatted as `099` instead of `100`:

![image](https://user-images.githubusercontent.com/31989842/111290970-fb7c6b80-8646-11eb-96bf-d2a44e12ed38.png)

JSFiddle: https://jsfiddle.net/gb58mux6/

**Comment by leeoniya** [comment]
hmm... :thinking:

**Comment by leeoniya** [comment]
damn float math! should be fixed now, thanks for reporting!

you can also set `opts.ms: 1` and pass data directly in millisecond timestamps.
