### ISSUE TITLE
Allow other Github members to edit the Wiki

### ISSUE THREAD

**Issue by GlennMatthys** [leeoniya/uPlot#473]
Perhaps change the Wiki security settings so that other Github members can contribute documentation? https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by leeoniya** [comment]
done, though i'd prefer PRs to https://github.com/leeoniya/uPlot/blob/master/docs/README.md for actual docs and leave the wiki for integration examples and FAQ type stuff.
