### ISSUE TITLE
Wheel zoom plugin issue after setData()

### ISSUE THREAD

**Issue by denyaalt** [leeoniya/uPlot#475]
Hi,

After setData(), the **xRange**, **xMin**, **xMax** variables (of the **wheelZoomPlugin** function) contain values for the old content.
And when the wheel is scrolled, the display slides out.

How can we update **xRange**, **xMin**, **xMax** for the new data?

Thanks.

**Comment by leeoniya** [comment]
i'm assuming you're using `.setData(data, false)` to avoid auto-scaling?

you can add a `setData` hook that resets or adjusts those variables as needed.

**Comment by denyaalt** [comment]
I have sketched an [Example](https://playcode.io/751791). 
Press UPDATE DATA and scroll with the mouse wheel on the chart.
I added a setData hook, but the **u.scales.x/y.min/max** values do not change after setData, see the console.
```
setData: u => {
	xMin = u.scales.x.min;
	xMax = u.scales.x.max;
	yMin = u.scales.y.min;
	yMax = u.scales.y.max;

	xRange = xMax - xMin;
	yRange = yMax - yMin;

	console.log('xMin='+xMin+', xMax='+xMax+', yMin='+yMin+', yMax='+yMax+', xRange='+xRange+', yRange='+yRange);
},
```

**Comment by leeoniya** [comment]
> I added a setData hook, but the u.scales.x/y.min/max values do not change after setData, see the console.

yes, you're right. the `setData` hook fires before the scales are auto-ranged. if you're okay with the zoom resetting after setData(), then you can sync this way in the plugin: https://jsfiddle.net/ujhzLtdy/4/

if you need to maintain the same zoom window after setData(), then more work is needed.

> P.S. And please tell me how to reset the zoom from the js code (similar to a double click)?..

you can set the `x` scale to the data limits (see demo above).

```js
function scaleReset() {
  let lastIdx = u.data[0].length - 1;

  u.setScale('x', {
    min: u.data[0][0],
    max: u.data[0][lastIdx],
  });
}
```

**Comment by denyaalt** [comment]
Great! Problem solved!
