### ISSUE TITLE
Question: Major tick grid lines

### ISSUE THREAD

**Issue by sohailsomani** [leeoniya/uPlot#477]
Is there a way to set "major" ticks on the y axis to be divisible by 50 and perhaps have the stroke for that horizontal grid line be twice the normal thickness?

The furthest I got was `drawOrthoLines` but I couldn't see anything obvious there and I didn't see anything in the demos either. I can probably do this with a plugin but I figured I was missing the obvious way to do this.

Thanks!

**Comment by leeoniya** [comment]
yeah, there's no major / minor delineation in uPlot, you can use the `drawAxes` hook to draw additional thicker lines over those axis splits you consider to be "major". the spits locations are cached in `axis._splits`. another thing you can do is skip generating tick values and drawing ticks at the "minor" splits. you can do this via `axis.filter`, `axis.ticks.filter` and `axis.grid.filter`.

**Comment by sohailsomani** [comment]
Sounds good, thanks!

**Comment by leeoniya** [comment]
btw, filters is how log scales draw their "major/minor" distinctions internally, and i think it works quite well:

https://leeoniya.github.io/uPlot/demos/log-scales2.html

![image](https://user-images.githubusercontent.com/43234/112096926-285fdf80-8b6d-11eb-9b1f-2c92d631eb57.png)

**Comment by sohailsomani** [comment]
Yes I did see the log code thanks, in my case I'd not want to filter out any of the y values and just bold the value on the axis or give the grid line some extra thickness. I will give the `drawAxes` hook a shot, seems the way to go.
