### ISSUE TITLE
Export opts/getIncrs

### ISSUE THREAD

**Issue by zefirka** [leeoniya/uPlot#479]
Hi @leeoniya. We have faced with case where data values grow over `1e18 - 1e19` (it still precise for JavaScript), but default numeric `incrs` are in range from `1e-16` to `1e16`. Can I suggest small PR which exports `getIncrs` as static method of uPlot. It's really helpful function and it would be convenient to use it from uPlot and don't reimplement it. Or, as an option, just increase default `numIncrs` range to 19 or 20. 

Are you ok with that?

**Comment by leeoniya** [comment]
> it still precise for JavaScript

it's precise to display in isolation, but it's imprecise to calculate small incremental ticks using huge values. i'm not fundamentally opposed to exposing it, but the precision is often not there to properly calculate ticks at certain zoom levels or data densities.

```
1e16 + 1 === 1e16
true
1e15 + 1 === 1e15
false
```

exposing the increment generator won't save you from this.

you will be much happier if you reduce huge values to some sensible precision then divide them and simply label the axes "in quadrillions".

**Comment by zefirka** [comment]
Sound cogently, I forgot about `Number.MAX_SAFE_INTEGER`. I'm closing issue
