### ISSUE TITLE
Isolate series option?

### ISSUE THREAD

**Issue by oscgonfer** [leeoniya/uPlot#480]
Hi,

First of all, congratulations on this great library.

I've been trying to find a way to hide all series but one, or in other words, to isolate it, and then add series on-click on the legend entry or something similar.
Is it possible?

**Comment by leeoniya** [comment]
thanks!

is this same as https://github.com/leeoniya/uPlot/issues/404?

**Comment by oscgonfer** [comment]
Exactly! Sorry I missed it.Enviado desde mi smartphone Samsung Galaxy.
-------- Mensaje original --------De: Leon Sorokin ***@***.***> Fecha: 29/3/21  17:32  (GMT+01:00) Para: leeoniya/uPlot ***@***.***> Cc: oscgonfer ***@***.***>, Author ***@***.***> Asunto: Re: [leeoniya/uPlot] Isolate series option? (#480) 
thanks!
is this same as #404?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/leeoniya/uPlot/issues/480#issuecomment-809477560",
"url": "https://github.com/leeoniya/uPlot/issues/480#issuecomment-809477560",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
