### ISSUE TITLE
Grouping candles by timeframe at OHLC chart

### ISSUE THREAD

**Issue by mixartemev** [leeoniya/uPlot#481]
If I have ohcl-data every 1s, how can I render 1m candles?

**Comment by leeoniya** [comment]
you have to pre-aggregate your data and call setData() to update. see the histogram example: https://leeoniya.github.io/uPlot/demos/latency-heatmap.html

**Comment by mixartemev** [comment]
Cool, thanx! Then second question:
New candle adds to plot once at 1m, last candle updates every 1s (from websocket).
I don't want to set all data ( = redraw all candles) every second. I want to redraw only last candle at plot every 1s, and redraw whole plot only when adds new candle every 1m. Is there such possibility?

**Comment by leeoniya** [comment]
no, there's no such API. there might be in the future: https://github.com/leeoniya/uPlot/issues/62.

you don't need to re-aggregate everything of course, you can add to your data and only recalc the last bin.

there's very little reason to hyper-optimize the redraw for any reasonable amount of candlesticks that still look like candelsticks. the rendering perf is probably 100x faster than what you need to for 1hz redraws; here's 3,600 points at 60hz which uses only 20% cpu on my mid-range laptop: https://leeoniya.github.io/uPlot/demos/sine-stream.html
