### ISSUE TITLE
Can I make charts like this?

### ISSUE THREAD

**Issue by Feduch** [leeoniya/uPlot#486]
Hi!

Can I make charts like this?

On the diagram, there will be many different events like a cloud. The intervals can be for a month, a year.

![изображение_2021-04-05_123738](https://user-images.githubusercontent.com/5888590/113560455-b4611500-960b-11eb-9681-1e5044de215a.png)

**Comment by leeoniya** [comment]
you can draw whatever you need to on the chart canvas, including annotations like you show. uPlot only provides a way to get the proper coordinates on the chart and hooks to access its rendering cycle. it's up to you to use those to draw anything additional you need. see the Drawing demos here: https://leeoniya.github.io/uPlot/demos/index.html
