### ISSUE TITLE
Accessing points within an X/Y select box

### ISSUE THREAD

**Issue by thomasbroderick** [leeoniya/uPlot#488]
I see in the x-y axis ranging demo that there is a ready hook to create a 2D selection.  If I wanted to get access to all the chart points that fall inside of that select box, is there a pre-built hook (or plugin) that exists to do that?

**Comment by leeoniya** [comment]
you would use the `setSelect` hook, convert the selection box left/right coordinates to min and max x data indices, and top/bottom coordinates to y scale values, then accumulate from your data array between those x indices filter those within the y min/max values.
