### ISSUE TITLE
Closest tooltip demo doesn't show a tooltip

### ISSUE THREAD

**Issue by hmillison** [leeoniya/uPlot#496]
I'm trying to figure out how to write a plugin to show the closest tooltip when there are multiple series in a graph, but when I look at the closest tooltip demo (https://leeoniya.github.io/uPlot/demos/tooltips-closest.html), i'm never seeing the tooltip come up.

It seems like `setSeries` is always called with `null`, which is consistent with the behavior i'm seeing locally when trying to build this.

Is this a regression in uPlot or does this demo need to be updated to use a new approach?

**Comment by leeoniya** [comment]
yeah this looks like i broke it by skipping the `<td>` creation when `legend.live: false`, but there's a bunch of stuff that relies on accessing the `<tr>` via the cell's `.parentNode`.

i'll need to either create those empty `<td>` again, or keep a direct reference to the `<tr>`s, too.

**Comment by hmillison** [comment]
Thanks for the quick update @leeoniya
