### ISSUE TITLE
Load uPlot in Firefox with Angular

### ISSUE THREAD

**Issue by unocelli** [leeoniya/uPlot#498]
Hi,
I would like to integrate it in [FUXA ](https://github.com/frangoteam/FUXA) project but I have a problem.
In FUXA I'm using angular and I insert the uPlot control in a SVG foreignObject, the insertion is dynamic and works fine in chrome but not in Firefox and I would like to ask you if you have an idea why.
I attach a test project which reproduces the problem [angu6-app.zip](https://github.com/leeoniya/uPlot/files/6332145/angu6-app.zip)

in any case thanks...uPlot is amazing!

**Comment by leeoniya** [comment]
i've never used `foreignObject` in svg and have never worked with angular.

for me to be any help at all, you'll have to make a runnable, stripped down example in jsfiddle or codepen, using only JS, HTML, CSS and SVG that reproduces the issue.

**Comment by unocelli** [comment]
sorry, my mistake, I found the error in my component...I've been too impatient

**Comment by leeoniya** [comment]
btw, FUXA looks really neat. my team at Grafana is working on something very similar, cause most SCADA interfaces and software is a pile of slow/antiquated junk :+1:
