### ISSUE TITLE
_setSize trigger a setLegend event throught updateCursor during _commit

### ISSUE THREAD

**Issue by Martichou** [leeoniya/uPlot#499]
Hey there !

I'm not sure if this is an issue, but I noticed that the legend get reseted each time a `setSize` is called on the graph (for responsive by example). As I'm not sure what is the intended way for this, I report it as an "issue". 

My use case is that the legend will stick to the lastest value when not hovered. Like shown here :
![Screenshot 2021-04-22 223905](https://user-images.githubusercontent.com/23138751/115782263-c1c42080-a3bb-11eb-8bfe-0aa1afa2532b.png)

However when resizing (or scrolling on mobile), the legend got reseted each time which cause some visual artifact.
This behavior is fixed on my side during test by setting `shouldSetLegend` to false in `_setSize` and adding a check in the updateCursor function (here https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.esm.js#L4055) :
`if (idxChanged && shouldSetLegend) {
			legend.idx = idx;
			setLegend();
		}`

The code logic is :
`_setSize => commit => _commit => updateCursor => setLegend`

Thanks for your time and this pretty cool lib 💯

**Comment by leeoniya** [comment]
hey @Martichou thanks for the report.

i think in 99% of `.setSize()` cases the cursor is gonna be hidden (left/top coords are set to `-10, -10`), so we can probably bail on doing both cursor and legend updates using a similar check to the one in setData:

https://github.com/leeoniya/uPlot/blob/095e103e7c1c6c07dbfb202708329caadde9f7e9/dist/uPlot.esm.js#L2858-L2859
