### ISSUE TITLE
dynamic updates

### ISSUE THREAD

**Issue by wlentz** [leeoniya/uPlot#5]
Thanks for this great library!

Is it possible to support dynamic updates like the following?
http://dygraphs.com/tests/dynamic-update.html

**Comment by leeoniya** [comment]
it's possible but will require some thought. it's easy to do without worrying about perf for 1000 displayed datapoints at 1s updates but not so easy if it has to work well at 60 updates/sec at 100,000 displayed datapoints with continuous re-scaling.

i'm hoping that this thread [1] leads to some more dicussion about this.

[1] https://news.ycombinator.com/item?id=21209886

**Comment by leeoniya** [comment]
@wlentz this has been implemented.

see https://leeoniya.github.io/uPlot/demos/stream-data.html

there is still more optimization to do regarding labels which currently live in the DOM and are destroyed/recreated on every update, but if your update interval >= 250ms apart, then the perf difference should be negligible. i plan to tackle lable rendering optimizations next in #16.

**Comment by leeoniya** [comment]
cc @seanlaff

**Comment by leeoniya** [comment]
the label rendering optimizations are now done.
