### ISSUE TITLE
Gradient line

### ISSUE THREAD

**Issue by Feduch** [leeoniya/uPlot#501]
Hi!

In this screenshot very good!

![Скриншот_Выберите область_20210423221446](https://user-images.githubusercontent.com/5888590/115919617-bdfad180-a481-11eb-8232-21b986e5a5ba.png)

In this screenshot true 
![Скриншот_Выберите область_20210423222116](https://user-images.githubusercontent.com/5888590/115920047-52fdca80-a482-11eb-89ac-35eb782532e8.png)

But in this screenshot wrong color, I am waiting #0ACEF9. Is it bug?

![Скриншот_Выберите область_20210423221512](https://user-images.githubusercontent.com/5888590/115919613-bcc9a480-a481-11eb-888b-2c797f646735.png)

My options:

```
series: [
          {},
          {
            label: "Temperature",
            width: 1,
            stroke: (u, seriesIdx) => {
               return scaleGradient(u, 'y', 1, [           
                [0, "#0ACEF9"],
                [46, "#FFE663"],
                [60, "#F9440A"],
              ])
            },
          },
        ],
```

**Comment by leeoniya** [comment]
looking at your first image, the gradient you're specifying is yellow-green at the 40°, which is the correct color in the bottom chart.

why are you expecting #0ACEF9 at 40°?

**Comment by Feduch** [comment]
I want to paint colors with such segments:

from 0 to 46 #0ACEF9
from 46 to 60 #FFE663
from 60 to any #F9440A

**Comment by leeoniya** [comment]
to get sharp transitions, you have to create hard stops. see this demo:

https://github.com/leeoniya/uPlot/blob/095e103e7c1c6c07dbfb202708329caadde9f7e9/demos/gradient-stroke.html#L78-L87
