### ISSUE TITLE
"TypeError: _splits is null" when using "incrs" with thin plot

### ISSUE THREAD

**Issue by iamlouk** [leeoniya/uPlot#503]
Hello,

First of all, thank you very much for your work and this library. I tried implementing something specific to my problem but it turns out your library has better performance!

__When I use the `incrs` property on the options of an Axis and the Plot is thin, this happens:__

```
Uncaught TypeError: _splits is null
    drawAxesGrid http://localhost:5000/build/bundle.js:24336
    drawAxesGrid http://localhost:5000/build/bundle.js:24290
    _commit http://localhost:5000/build/bundle.js:24493
    _commit http://localhost:5000/build/bundle.js:24493
    commit http://localhost:5000/build/bundle.js:24448
    setScale http://localhost:5000/build/bundle.js:24568
    _setScale http://localhost:5000/build/bundle.js:24658
    autoScaleX http://localhost:5000/build/bundle.js:23800
    _init http://localhost:5000/build/bundle.js:25447
    uPlot
```

Here is an example that fails using the most up to date Version from NPM and uplot@1.6.7:

```js
const n = 1000;
const xData = [];
const yData = [];
for (let i = 0; i < n; i++) {
    xData.push(i);
    yData.push(Math.sin(i * 0.01));
}

const opts = {
    width: 100, // Change this and it works!
    height: 200,
    scales: { x: { time: false }, y: {} },
    axes: [
        { incrs: [1, 10, 100, 200, 500] }, // Change this and it works!
        {
            scale: 'y',
            grid: { show: true },
            labelFont: 'sans-serif'
        }
    ],
    series: [
        {},
        {
            scale: 'y',
            width: 1,
            stroke: 'black'
        }
    ],
    cursor: { show: false },
    legend: { show: false, live: false }
};

const wrapper = document.querySelector('#plot-wrapper');

let uplot = new uPlot(opts, [xData, yData], wrapper);

```

Changing the width and/or removing `incrs` fixes the problem, but the combination causes this problem.

Best regards!

**Comment by leeoniya** [comment]
this happens when uPlot cannot find a suitable increment that maintains the defined minimum tick spacing (`axis.space`), if you decrease this, it also works: https://jsfiddle.net/0krf43sg/. you can also add smaller increments to your array.

instead of crashing, uPlot should just skip rendering the ticks and grid if proper splits cannot be calculated for an axis.

**Comment by leeoniya** [comment]
pushed a commit that skips axis rendering in this situation.
