### ISSUE TITLE
How use path with spline() and render without rounding where there are no values?

### ISSUE THREAD

**Issue by Feduch** [leeoniya/uPlot#504]
Hi!

How use path with spline() and render without rounding where there are no values?

spline
On this graph, it seems that an event occurred below zero, but in fact it was equal to 0 in this interval.

![Скриншот_Выберите область_20210427111128](https://user-images.githubusercontent.com/5888590/116209511-a9049380-a74a-11eb-94cd-6801c68d3d5a.png)

linear
![Скриншот_Выберите область_20210427111102](https://user-images.githubusercontent.com/5888590/116209513-a99d2a00-a74a-11eb-86c1-41fe6c0fd146.png)

How can display a graph similar to the example below using spline?

![изображение_2021-04-27_113059](https://user-images.githubusercontent.com/5888590/116210963-09e09b80-a74c-11eb-85ef-7973ca395a17.png)

**Comment by leeoniya** [comment]
looks like Apex's algorithm is based on Chartist.js: https://github.com/apexcharts/apexcharts.js/blob/a6e4ca79f81e86c16bc6fcb9a0377a8a86e70df0/src/charts/Line.js#L553-L599

another related discussion: https://github.com/apache/echarts/pull/13314

i will take a look these soon.

if you would like to try making another smooth pathBuilder to compare, based on the above links, that would great. the code for the current smooth pathBuilder is here, for reference: https://github.com/leeoniya/uPlot/blob/master/src/paths/spline.js

**Comment by leeoniya** [comment]
@Feduch can you give me this dataset for testing?

**Comment by Feduch** [comment]
@leeoniya  ok, I'll try to get similar data as in the screenshot above
