### ISSUE TITLE
Axis labels not showing?

### ISSUE THREAD

**Issue by oscgonfer** [leeoniya/uPlot#508]
Hey,

Recently I have realised that I can't make labels show up, except for axis 0.

In example [axis-control.html](https://github.com/leeoniya/uPlot/blob/master/demos/axis-control.html#L69) I think this is reproduced. I can manage to plot x axis (axis 0 let's say) but not any other.

Am I missing something?

**Comment by guanicoe** [comment]
ok so it's not only me. Looking at the examples only the x axis has its label showing.

**Comment by guanicoe** [comment]
I download version 1.6.7 and the labels display correctly. Guess we'll have to wait for the next version. Hopefully it's just a simple fix

**Comment by leeoniya** [comment]
interesting. looks like i broke this 5 days ago on `master` when fixing https://github.com/leeoniya/uPlot/issues/503.

the official 1.6.8 release should be okay. i usually don't update the version in `package.json` before releases, but probably should.

**Comment by guanicoe** [comment]
so I can download 1.6.8? or is A.6.9 out?

**Comment by leeoniya** [comment]
this bug was only recently introduced on master. 1.6.8 should not be affected (it's been out for 20 days)

**Comment by oscgonfer** [comment]
Great! 

Got it working on my side too! Thanks :)
