### ISSUE TITLE
Values on axis and legend displayed with comma instead of dot

### ISSUE THREAD

**Issue by guanicoe** [leeoniya/uPlot#509]
Is there a reason that decimals use commas instead of dots on the axis? 

![Capture](https://user-images.githubusercontent.com/62290334/116615974-58ed2300-a93c-11eb-8507-c00f4d5fc82c.PNG)

It's also the case in the legend.

Is it my config or default in the lib?

**Comment by leeoniya** [comment]
it gets tge default from your browser's Intl object, so it would be odd if those differed. European decimals are commas.

what does this do in your case? what's the locale?

https://github.com/leeoniya/uPlot/blob/master/src/utils.js#L199
