### ISSUE TITLE
Hide legend marker and use colored legend label instead?

### ISSUE THREAD

**Issue by shengyan** [leeoniya/uPlot#514]
Hi.

Is it possible to add an `showMarker`  option to control the legend marker? 
The left chart use the original legend, the right one show the expected effect which looks better.

![original legend](https://user-images.githubusercontent.com/5512484/117957940-1caebf00-b34d-11eb-90f6-09569ebdbb23.png) ![proposed legend](https://user-images.githubusercontent.com/5512484/117957946-1e788280-b34d-11eb-835f-d329ac29f740.png)

Actually, it is pretty simple to implement this option. Please take a look at this [change](https://github.com/shengyan/uPlot/commit/f6c5810ef6a2ffef326b5d17ed29d78deb3c5aa9#diff-ad6d196bc8d38207d186017fc5c2c52660db3a546ccfdfe167fd7ad0c727cdee).

**Comment by leeoniya** [comment]
thanks, seems pretty straightforward. i'm considering moving all marker-related options under `legend.markers`, so maybe `legend.markers.show`. one thing to consider is whether we need to give control to users which color is used for text. your diff uses stroke(), but if there is no stroke it should use fill(), but if fill has transparency (which is usually true), then that becomes weird and hard to read. i guess in that case the user has to provide a `legend.fill` or `legend.stroke` option :thinking: 

https://github.com/leeoniya/uPlot/blob/69fb492b7f0069c5ef910f0cec5091964f2ccd78/dist/uPlot.d.ts#L253-L272

**Comment by shengyan** [comment]
Since legend color almost always identical to stroke color, I would suggest keep using `stroke()` or `fill()`. Maybe we can fix the  transparency problem by converting `rgba` to `rgb`? 
```js
text.style.color =
  legend.stroke(self, i) ||
  legend.fill(self, i).replace(/^rgba\(((,?\s*\d+){3}).+$/, 'rgb($1)');
```

**Comment by leeoniya** [comment]
try it out: https://github.com/leeoniya/uPlot/commit/b7f5a93cee5afc7f34ccd9dcba0b7966ce662446

**Comment by shengyan** [comment]
Work great for me.

A small bug? If there are no `width` and `stroke()`, then the default `width = 1` will be used, then the following code will return `null`, instead of `fill()`.
```js
text.style.color = s.width > 0 ? markers.stroke(self, i) : markers.fill(self, i);
```

**Comment by leeoniya** [comment]
if there's a line width, it's assumed there will be a stroke. the default stroke for markers is taken from series.stroke and assumes this condition anyways: https://github.com/leeoniya/uPlot/blob/b7f5a93cee5afc7f34ccd9dcba0b7966ce662446/src/opts.js#L351. i'm sure there are ways to screw this up, since there's a long fallback chain, but i think it will generally work as expected if the specified options make any sense.

**Comment by AnnEthan** [comment]
Hello, is there a property that controls the highlight or ash of a single legend? Like echarts has a selected attribute
