### ISSUE TITLE
Plugin & hooks documentations

### ISSUE THREAD

**Issue by temka1234** [leeoniya/uPlot#515]
Is there any hooks documentation to write own plugin?  

I want to make two things:  
* Ruler for signal (electrocardiogram) in Y and X directions. Ruler points mark by mouse clicks on graph area.
* Annotation points that can be dragged by user over chart line

**Comment by leeoniya** [comment]
can you provide some visual examples of what you're asking for? there are a lot of ways to implement this, so the details matter.

what does a signal ruler look like? is it inside kr outide the axis?

what do you mean by dragging annotation points? do you mean placing them via click? and then dragging them after they're placed?

**Comment by temka1234** [comment]
Something like this:

![bandicam 2021-05-13 19-30-19-797](https://user-images.githubusercontent.com/3648995/118156641-4685e580-b422-11eb-95fc-a78814739289.gif)

**Comment by leeoniya** [comment]
most of uPlot's documentation is simply reading the demo code samples -- fortunately or unfortunately.

for the above example you can find some relevant bits implemented below:

- see how the draggable/resizable overlay is done for the ranger plot: https://leeoniya.github.io/uPlot/demos/zoom-ranger-grips.html
- see one way to do Ctrl+drag annotation marking using `setSelect()` in https://leeoniya.github.io/uPlot/demos/cursor-bind.html

if you'd be interested in contributing a more developed annotation plugin, i'd be happy to help with the uPlot-specific bits, assuming you can do the core JS/SVG/HTML/CSS for it.

**Comment by temka1234** [comment]
Thanks for help and for lib, try to implement my features.  

I will think about more abstract annotations and come with some thoughts.
