### ISSUE TITLE
µPlot and Vue.js

### ISSUE THREAD

**Issue by Ka7i** [leeoniya/uPlot#518]
Hey there! 

I am currently working on the implementation of **µPlot** with **Vue.js 3.x**.
I saw that **µPlot** is compatible with the previous version of Vue. However, since my company decided to use the latest version I would like to know if the implementation for **Vue.js 3.x** is coming any time soon. If not, is there any workaround to implement it myself? 

Thank you very much in advance! 

J

**Comment by leeoniya** [comment]
if you are refering to the listed integration here: https://github.com/skalinichev/uplot-wrappers, it's best to ask @skalinichev , since i am not familiar with specifically what Vue needs. uPlot is very simple, plain javascript, and should be compatible with any web framework.

**Comment by Ka7i** [comment]
Thanks for the quick reply!
