### ISSUE TITLE
Graphical glitches between missing values 

### ISSUE THREAD

**Issue by mheiduk** [leeoniya/uPlot#523]
Hey,

we have chosen uPlot for its performance/small size and it works great, thanks!

Some thing I have noticed on missing values: https://geizhals.at/sony-playstation-5-825gb-weiss-a2374643.html
When you view the price history chart in large mode (click on the small one), you can see some "glitches" (blue line) between missing values:

![image](https://user-images.githubusercontent.com/291541/120340161-0a91c200-c2f6-11eb-9901-ea4e2be6bb05.png)

`spanGaps` is not enabled, we just use `stroke`, `width` and `points: { show: false }` for the series. My guess is that the line is trying to connect due to the other datapoint is beyond or above the last one not-nullish datapoint.

Any other guesses or explanations why this is happening?

EDIT: Using the newest release 1.6.10

Best,
Marc

**Comment by leeoniya** [comment]
> Any other guesses or explanations why this is happening?

nothing i'm aware of. i'll need to see the your and chart config.

please create a repro in a jsFiddle, e.g: https://jsfiddle.net/d5x60ocn/6/

**Comment by mheiduk** [comment]
Thanks for the fast reply!
Repro fiddle: https://jsfiddle.net/mheiduk/gnvqxzsb/2/

**Comment by leeoniya** [comment]
interesting, i'll take a look sometime this week.

your setup is clever, but not ideal. i would suggest implementing this using a horizontal stroke gradient with hard stops instead of multiple series. i think that may solve your issue:

https://leeoniya.github.io/uPlot/demos/gradient-stroke.html

**Comment by leeoniya** [comment]
ok, this is not bug. you're correct that there are invisible datapoints that are surrounded by null values, and the way gap clipping works results in these artifacts.

my recommendation is to omit null values and do this instead: https://jsfiddle.net/shoj1zpg/

```js
const data = [
  [
    1600300800,
    1601251200,
    1601856000,
    1602201600,
    1602720000,
    1603152000,
    1606953600,
    1609200000,
    1613520000,
    1613606400,
    1614038400,
    1616544000,
    1617062400,
    1617148800,
    1617235200,
    1617321600,
    1618272000,
    1618358400,
    1618444800,
    1619654400,
    1619740800,
    1619827200,
    1619913600,
    1620000000,
    1620086400,
    1620172800,
    1620259200,
    1620345600,
    1620432000,
    1620518400,
    1620604800,
    1620691200,
    1620864000,
    1620950400,
    1621036800,
    1621123200,
    1621209600,
    1621296000,
    1621382400,
    1621468800,
    1621555200,
    1621641600,
    1621728000,
    1621814400,
    1621900800,
    1621987200,
    1622073600,
    1622160000,
    1622246400,
    1622332800,
    1622419200
  ],
  [
    499,
    809.99,
    576,
    879.99,
    576,
    879.99,
    499.99,
    859.99,
    999,
    999,
    499,
    684.99,
    749,
    749,
    899,
    899,
    899,
    899,
    899,
    940,
    940,
    940,
    940,
    940,
    940,
    899,
    899,
    899,
    899,
    899,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935,
    935
  ]
];

const opts = {
  width: 800,
  height: 500,
  series: [
    {},
    {
      stroke: '#b3b3b3',
      width: 3,
      paths: uPlot.paths.stepped({align: 1}),
      points: {
      	show: true,
        stroke: '#059',
        fill: '#059',
      }
    },
  ],
};


let plot = new uPlot(opts, data, document.body);
```

**Comment by mheiduk** [comment]
thx for investigating, will try it next week.
