### ISSUE TITLE
uPlot.over is undefined

### ISSUE THREAD

**Issue by ePlayWebDev** [leeoniya/uPlot#524]
I'm trying some of your demos, but i notice that when you use a plugin (i.e. tooltips) this javascript error is raised up...
Hope you can help me

test.html:23 Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at init (test.html:23)
    at uPlot.iife.js:4335
    at Array.forEach (<anonymous>)
    at fire (uPlot.iife.js:4334)
    at _init (uPlot.iife.js:4374)
    at new uPlot (uPlot.iife.js:4391)
    at makeChart (test.html:165)
    at test.html:170

**Comment by leeoniya** [comment]
i'm not seeing this in any tooltip demos.

your browser may have a previous uPlot version cached. try doing a hard refresh:

https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#Google_Chrome

**Comment by ePlayWebDev** [comment]
I was using version 1.6.1 instead of 1.6.11
