### ISSUE TITLE
Is there any way to set only one of the maximum and minimum values？

### ISSUE THREAD

**Issue by aim-leo** [leeoniya/uPlot#526]
In my chart, I just want to limit the value of y-axis to be greater than 0, and I don't want to set the upper limit of y-axis. I hope it can be calculated dynamically. I first set min to 0, and then tried to set Max to null, or not to set max, but the line segments would not render.
Hope to get your reply, thank you for creating this magic project.

**Comment by leeoniya** [comment]
uPlot has very detailed controls over scale ranging, and sometimes they're a bit tricky to configure.

below is probably what you want. (here is another demo: https://leeoniya.github.io/uPlot/demos/soft-minmax.html).

i think for a simple/common case like you're asking, i think it would make sense to make `range: [0, null]` work the same as below.

https://jsfiddle.net/8fv0ju52/

```js
const data = [
  [1,2,3,4,5],
  [-30, 10, 12, 40, 100]
];

const opts = {
  width: 800,
  height: 500,
  scales: {
    x: {
      time: false,
    },
    y: {
      range: {
        min: {
          mode: 1,
          soft: 0,
          hard: 0,
        },
        max: {
          pad: 0.05
        }
      }
    }
  },
  series: [
    {},
    {
      stroke: '#059',
    },
  ],
};

let plot = new uPlot(opts, data, document.body);
```
