### ISSUE TITLE
Show point only for last data

### ISSUE THREAD

**Issue by nedy07** [leeoniya/uPlot#527]
I want to just show point just for idx1(last index), how can i achieve that?

```
              points: {
                    show(self, seriesIdx, idx0, idx1) {
                        console.log(seriesIdx, idx0, idx1);
                        return idx1;
                    }
                }
```

**Comment by leeoniya** [comment]
i actually added support for this just yesterday in https://github.com/leeoniya/uPlot/commit/a8639d922b4a87cbf1cac1f72a65c513ecbe926c :)

see how the orange series has its points filtered:

https://leeoniya.github.io/uPlot/demos/points.html

**Comment by nedy07** [comment]
@leeoniya thanks!, but how to get these features? I see that last release was 6 days ago.

**Comment by leeoniya** [comment]
next release will be in a few days, but you can download all files from here to test until then:

https://github.com/leeoniya/uPlot/tree/master/dist

**Comment by nedy07** [comment]
Thanks @leeoniya , working great for me!

Also, is this possible to 
- show text-value for this last point only , with some custom-font on canvas
- show "today" in x-axis for this point, along with a vertical line connecting the last point and "today" on x-axis

**Comment by nedy07** [comment]
@leeoniya like this, what i meant to say, -

Is this achievable ? with different "today" font-color?

<img width="72" alt="Screenshot 2021-06-11 at 8 07 41 PM" src="https://user-images.githubusercontent.com/74888988/121703756-c5893f00-caf0-11eb-90c9-c19c07e8d180.png">

**Comment by leeoniya** [comment]
you'll have to draw on the canvas yourself for this (probably using the `draw` hook). take a look at the Drawing section of the demos: https://leeoniya.github.io/uPlot/demos/index.html

**Comment by nedy07** [comment]
and for showing "today" ?

**Comment by leeoniya** [comment]
^^ same. see how "Time to draw" is rendered here: https://leeoniya.github.io/uPlot/demos/draw-hooks.html

**Comment by nedy07** [comment]
got it, thanks!

**Comment by nedy07** [comment]
@leeoniya curious to know when its going to release? Although I'm using `\dist` currently, but cannot able to push it to prod
