### ISSUE TITLE
How to rearrange the x-axis data

### ISSUE THREAD

**Issue by nedy07** [leeoniya/uPlot#528]
Currently, its showing like this -

<img width="337" alt="Screenshot 2021-06-11 at 1 14 46 PM" src="https://user-images.githubusercontent.com/74888988/121650343-1bd98c00-cab7-11eb-8308-416627e57e7b.png">

but I want to show only the first, middle and last data on the X-axis, how can i achieve that?

**Comment by leeoniya** [comment]
a few options.

you can use `axis.filter` to remove some tick values.

you can use `axis.grid.filter` to remove some gridlines.

you can adjust `axis.space` or `axis.incrs` to control grid & tick density.

you can use `axis.splits` and return competely custom tick & grid positions.

> but I want to show only the first, middle and last data on the X-axis, how can i achieve that?

you pobably dont want exactly start middle end. even if your time range is exactly jan1 - dec31, the middle timestamp between those won't land on a month boundary. you can use `axis.splits` and return exactly the timestamps you need to show, though.

**Comment by nedy07** [comment]
Thanks @leeoniya again!, Is there any example that uses `axis.splits` ?

And also one more thing, is there something to change the color of the x-axis font?

**Comment by leeoniya** [comment]
here is one that uses custom x splits:

https://github.com/leeoniya/uPlot/blob/master/demos/latency-heatmap.html

> And also one more thing, is there something to change the color of the x-axis font?

`axis.stroke`:

https://github.com/leeoniya/uPlot/blob/master/demos/axis-control.html

**Comment by nedy07** [comment]
Thanks @leeoniya , it worked! 

Also, i just want to show line for `x-axis` without showing all the `axis.grid` ,is this also configurable ?

**Comment by leeoniya** [comment]
you can toggle `grid.show` and `ticks.show` and then add box-shadow css `.u-over`.

it's not a perfect solution, but probably best for now: https://leeoniya.github.io/uPlot/demos/tooltips-closest.html

**Comment by nedy07** [comment]
@leeoniya ok, also can we change x-axis time months to lowercase like - `May` => `may` and add any custom font?

**Comment by leeoniya** [comment]
> ok, also can we change x-axis time months to lowercase like - May => may

https://github.com/leeoniya/uPlot/blob/a8639d922b4a87cbf1cac1f72a65c513ecbe926c/demos/months-ru.html#L33-L38

> and add any custom font?

`axis.font`, `axis.labelFont`

**Comment by nedy07** [comment]
Thanks, worked.
