### ISSUE TITLE
Clicking labels disables unrelated information across charts

### ISSUE THREAD

**Issue by mantielero** [leeoniya/uPlot#529]
In the example: https://leeoniya.github.io/uPlot/demos/sync-cursor.html

When I click over `CPU 1` label it hides: `CPU 1`, `RAM 1` and `TCP 1`. 

Is this the expected behaviour (maybe due to some configuration)? If so, how could I disable it?

**Comment by leeoniya** [comment]
it doesnt actually disable the other series. the hover/focus that is enabled in this demo also dims the legend labels, so when you actually toggle the hovered one, they all _look_ disabled in the legend, but they are not:

https://user-images.githubusercontent.com/43234/121691212-5bd74980-ca8c-11eb-9f49-65aeb54749f4.mp4

**Comment by leeoniya** [comment]
to disable the hover/focus behavior, you can remove the focus opts:

![image](https://user-images.githubusercontent.com/43234/121692968-46631f00-ca8e-11eb-8eab-fa1dfc1183b4.png)

**Comment by mantielero** [comment]
I am refering to this effect
![output](https://user-images.githubusercontent.com/1116064/121693229-39afec80-cac9-11eb-81b1-e103fae5282a.gif)

**Comment by leeoniya** [comment]
ah, these are just labels. the series is matched by index, so this is expected behavior in this case. if each graph represents the same 3 machines, you _may_ want machine 1 cpu, machine 1 ram and machine 1 tcp toggled together. so whether they're "related" is purely semantics.

in the above config you can set `cursor.sync.setSeries: false` to disable cross-chart series focus and toggle, and only retain the cursor position sync.

**Comment by mantielero** [comment]
So imagine that I want to split series among different graphs: CPU1-3 in first chart and CPU4-6 for second chart and I wanted to sync them.

My issue is that I want many sensed data (beyond 100). I want to split the data in several charts. I'd like that if a performed a temporal filter in one chart that occurs in all the charts.

**Comment by leeoniya** [comment]
> I'd like that if a performed a temporal filter in one chart that occurs in all the charts.

that will still work fine. the only thing `sync.setSeries: false` disables is legend toggling and hover focus.

**Comment by mantielero** [comment]
That is what I was looking for. Thanks a lot. Excellent library by the way.

**Comment by leeoniya** [comment]
glad it's working for you :+1:
