### ISSUE TITLE
How to get the point's height and width w.r.t canvas

### ISSUE THREAD

**Issue by abhisheknaiidu** [leeoniya/uPlot#530]
Is it possible to get the coordinates (width, height) with respect to the any point in axes.

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot/blob/a8639d922b4a87cbf1cac1f72a65c513ecbe926c/dist/uPlot.d.ts#L113-L114

one example of using it:

https://leeoniya.github.io/uPlot/demos/trendlines.html

**Comment by abhisheknaiidu** [comment]
Hey thanks @leeoniya for replying so quickly, and it worked, also btw great library! 👌🏼
