### ISSUE TITLE
Component breaking in Safari OS

### ISSUE THREAD

**Issue by abhisheknaiidu** [leeoniya/uPlot#531]
I made a component to render the uPlot charts, it's working fine in Firefox and Chrome but breaking in Safari, Any reasons?

**Comment by leeoniya** [comment]
i dont have any apple devices, so have no way to test it.

do the uPlot demos work for you?

are there any errors in the console?

**Comment by leeoniya** [comment]
since this is the first and only safari-specific issue reported, i'm closing this until further detail is provided. (screenshots, device/os/browser info, any console errors, jsfiddle or code i can run)

**Comment by apizzini** [comment]
@leeoniya i'm getting this issue too.

It's happening only in safari (i'm still on 13.1.1) and only with uPlot 1.6.13 (i've reverted to 1.6.12 and that fixed the issue).

JavaScript error looks to be: `TypeError: el.addEventListener is not a function. (In 'el.addEventListener(ev, cb, capt ? evOpts2 : evOpts)', 'el.addEventListener' is undefined)`

**Comment by leeoniya** [comment]
this fix works: https://github.com/leeoniya/uPlot/issues/538#issuecomment-870711531
