### ISSUE TITLE
Exact axis values auto-size?

### ISSUE THREAD

**Issue by tve** [leeoniya/uPlot#532]
uPlot is awesome! Thank you so much!

I'm working on auto sizing the axes, i.e., what the https://leeoniya.github.io/uPlot/demos/axis-autosize.html demo does. While "it's working" the results are sometimes rather underwhelming. Here is a screen shot when it's good:
![image](https://user-images.githubusercontent.com/39480/121822032-a7872000-cc51-11eb-9347-5e9f132f741c.png)
But here it sucks:
![image](https://user-images.githubusercontent.com/39480/121822045-c2f22b00-cc51-11eb-9efa-0dcf26062dc6.png)
I used the size function https://github.com/leeoniya/uPlot/blob/master/demos/axis-autosize.html#L109 with minor changes. Troubleshooting this I discovered:
- using `values[0].length * 8` really doesn't cut it in general, one should iterate through all the values and use `ctx.measureText` to get the correct size
- that size needs to be divided by `window.devicePixelRatio` 'cause uPlot needs CSS pixels
- the size returned by the `size()` function needs to include the tick size and the axis gap (why?)

With all that sorted out the labels actually start at exactly the correct pixel location. For performance, perhaps it would be worth caching the `ctx.measureText` results, I haven't looked whether it actually makes any difference, probably not.

It would be nice for the "axis auto-size" demo to include this stuff in its code, if not, perhaps at least this issue can help others figure it out faster than it took me...

NB: one of the issues I haven't solved is that I just use `self.ctx.measureText` in the size function and it happens that I use the same font for everything, but in general the ctx would need to be initialized.

**Comment by leeoniya** [comment]
yep, you're right. none of the demos are meant to have fully complete code, and they often strive for brevity so the general concept is demonstrated and not obscured by extra detail. if you'd like to PR your improvements that'd be great.

> NB: one of the issues I haven't solved is that I just use self.ctx.measureText in the size function and it happens that I use the same font for everything, but in general the ctx would need to be initialized.

generally i'd suggest using an externally-created ctx, setting its font, and calling measureText on it. typically this would be some util function that uses a static pre-initialized ctx, e.g. measureText(text, font).

> the size returned by the size() function needs to include the tick size and the axis gap (why?)

perhaps this is an artifact of the original axes implementation being dom-based with absolutely-positioned and css stylesheet-sized tick elements and tick margins. there was no way to assert these metrics besides expensive/fragile dom measuring readbacks. now that everything is on canvas, this makes lot less sense. though it's not completely absurd, considering that when axis.show is false, the full size of the axis disappears (including values, ticks, and gap). not sure whether changing axis.size to only refer to the tick label text would be just a different variant of confusing. (though i dont think axis.label and axis.labelSize are included in axis.size, so not 100% consistency there either). i'm open to being comvinced though, as i dont think either variant is ideal.

> For performance, perhaps it would be worth caching the ctx.measureText results, I haven't looked whether it actually makes any difference, probably not.

for something like 20hz+ streaming, caching this will be worthwhile, but at 1hz probably not. depends on how many axes and charts you have. profiling measureText is easy enough.

your FlexDash project is really neat. i have a local dashboard prototype myself that tries to do some small subset of Grafana but with very little UI ovehead. maybe one day it'll be mature enough to show ;)

**Comment by leeoniya** [comment]
pushed a commit that does this mostly right (it doesn't use an external ctx and set its font). hopefully this will save people time that run into this. thanks!

**Comment by leeoniya** [comment]
after further tweaking the new code looks like below. i had to add `self.ctx.font = axis.font[0];` to ensure the font metrics are available for measureText (i think this is what you were talking about). looks like it works with browser zooming as well.

https://github.com/leeoniya/uPlot/blob/1c9cae4e8106f041d68e2e510e19691f3579404b/demos/axis-autosize.html#L109-L129
