### ISSUE TITLE
Stepped graph rendering sometimes fail because of inaccurate gap logic

### ISSUE THREAD

**Issue by flyingmutant** [leeoniya/uPlot#535]
In `stepped()`, `inGap` is unconditionally set to `true`, even though `addGap` can leave the `gaps` unchanged:

https://github.com/leeoniya/uPlot/blob/883438687d8d00ecacee60e1810d4f4e5d086ab3/src/paths/stepped.js#L37-L43

This leads to `lastGap` being `undefined`:

https://github.com/leeoniya/uPlot/blob/883438687d8d00ecacee60e1810d4f4e5d086ab3/src/paths/stepped.js#L47-L61

Changing `inGap` assignment to

```js
inGap = gaps.length > 0;
```

fixes the issue, but I don't know if this is the best way to fix it.

**Comment by leeoniya** [comment]
can you please provide full dataset and options where this fails? or make jsfiddle?

thanks!

**Comment by flyingmutant** [comment]
Sorry, I can't make jsfiddle for this right now, and the data alone is not enough for this to trigger. The error looks like this:

```
Uncaught TypeError: Cannot read property '0' of undefined
    at uPlot.esm.js:1758
    at orient (uPlot.esm.js:1440)
    at Object.paths (uPlot.esm.js:1712)
    at uPlot.esm.js:3221
    at Array.forEach (<anonymous>)
    at drawSeries (uPlot.esm.js:3218)
    at uPlot.esm.js:3707
    at Array.forEach (<anonymous>)
    at _commit (uPlot.esm.js:3707)
```

With local variables being (note how `x1`, `prevXPos` and `firstXPos` are all the same):

![Screenshot from 2021-06-22 09-54-26](https://user-images.githubusercontent.com/73059/122878063-f878d180-d33f-11eb-8fed-94c3452d91c0.png)


It only happens (sometimes) when I zoom out after being zoomed in (zooming in/out fetches new data from the server). Zoom out code calls `setScale('x', ...)` with a big range, while the plot still has the data from the small range, and that causes the error (it happens *before* we have the data for the big range, but *after* the `setScale`, which is bound to the double-click).

Series options look like this:

```ts
u.addSeries({
  show: true,
  label,
  width: 1 / devicePixelRatio,
  stroke: color,
  fill: palette.rgba(color, 0.3),
  paths: uPlot.paths.stepped!({align: 1}),
});
```

**Comment by flyingmutant** [comment]
Hmm, maybe just using the combination of big-scale + small-data-with-nulls is enough to trigger this? I'll try to come up with a good reproducer once I have a bit more time for this (maybe on the weekend).

**Comment by leeoniya** [comment]
any updates?

**Comment by flyingmutant** [comment]
Sorry, I am a bit overworked now and didn't have time to create a good repro. Does my description of the problem make sense, though? `inGap` being true with `gaps` being empty does not seem like intended logic to me.

**Comment by leeoniya** [comment]
i did not repro this, but looking at the code, the only way that `addGap()` can leave gaps empty is if the null value occurs in the same x pixel (which would happen if you have a huge x range and very narrow data, as you said). the `inGap` flag is technically correct, since the last gap in the gaps array acts as an accumulator, but obviously this cannot work if we bail on zero-width gaps.

 i've adjusted `addGap()` to accept zero-width gaps and skip over them later in `clipGaps()`. hopefully that does it :crossed_fingers:
