### ISSUE TITLE
uPlot giving error and not working below iOS version 13

### ISSUE THREAD

**Issue by abhisheknaiidu** [leeoniya/uPlot#538]
Currently, not working in iOS mobile version below 13 and showing this - 

Some `MediaQueryList` or `el.AddListner` is causing problem.

<img width="782" alt="Screenshot 2021-06-24 at 3 00 36 AM" src="https://user-images.githubusercontent.com/55599878/123170916-b57e4180-d498-11eb-9696-49c92011b9d2.png">

`After consoling`:

<img width="969" alt="Screenshot 2021-06-24 at 3 16 39 AM" src="https://user-images.githubusercontent.com/55599878/123172342-a4cecb00-d49a-11eb-9d6a-5aba12310a8a.png">

**Comment by leeoniya** [comment]
also reported & explained here: https://github.com/grafana/grafana/issues/35594#issuecomment-864302938

long story short you can update safari to v14 or later, which has been available since Sept 2020 for all recent iOS and macOS versions.

or you can add some simple polyfill code that will solve this in your app like

```js
MediaQueryList.prototype.addEventListener = MediaQueryList.prototype.addEventListener || function(type, cb) { this.addListener(cb); }

MediaQueryList.prototype.removeEventListener = MediaQueryList.prototype.removeEventListener || function(type, cb) { this.removeListener(cb); }
```

(untested)

**Comment by abhisheknaiidu** [comment]
@leeoniya you mean like this - 

```js
MediaQueryList.prototype.addEventListener = MediaQueryList.prototype.addEventListener ?? function(type, cb) { this.addListener(cb); }

MediaQueryList.prototype.removeEventListener = MediaQueryList.prototype.removeEventListener ?? function(type, cb) { this.removeListener(cb); }

function on(ev, el, cb, capt) {
	MediaQueryList.addEventListener(ev, cb, capt ? evOpts2 : evOpts);
}

function off(ev, el, cb, capt) {
	MediaQueryList.removeEventListener(ev, cb, capt ? evOpts2 : evOpts);
}
```

as el is MediaQueryList only

**Comment by abhisheknaiidu** [comment]
Working by adding like this - 
```js
	console.log(el, ev)
	if (el.addEventListener) {
		el.addEventListener(ev, cb, capt ? evOpts2 : evOpts)
	  } else {
		el.addListener(cb)
	  }
```

Is there any way to add this without changing in the `\dist` file

**Comment by leeoniya** [comment]
you should not need to patch on() and off().

just execute the polyfill code before loading uPlot.

**Comment by abhisheknaiidu** [comment]
@leeoniya what exactly you mean by this `you should not need to patch on() and off()`, could you give some snippet example.

Also, so currently I'm using this dist folder as a main file and changing to this, so will it be a good thing for future use or will it might break sometime? 
take about this -

> Working by adding like this -
> 
> ```js
> 	console.log(el, ev)
> 	if (el.addEventListener) {
> 		el.addEventListener(ev, cb, capt ? evOpts2 : evOpts)
> 	  } else {
> 		el.addListener(cb)
> 	  }
> ```
> 
> Is there any way to add this without changing in the `\dist` file

**Comment by leeoniya** [comment]
i was able to test this now and a working polyfill for Safar < 14 is this one:

```js
let oMatchMedia = window.matchMedia;

window.matchMedia = (query) => {
  let mql = oMatchMedia(query);

  if (!mql.addEventListener) {
    mql.addEventListener = (evName, handler) => {
      mql.addListener(handler);
    };
    mql.removeEventListener = (evName, handler) => {
      mql.removeListener(handler);
    };
  }

  return mql;
};
```

**Comment by Venryx** [comment]
> i was able to test this now and a working polyfill for Safari < 14 is this one: [...]

The above worked for me!

Note that, if you want the polyfill to only be used in cases where it's needed, you can wrap the code block above like this:
```js
if (window.matchMedia("").addEventListener == null) {
  let oMatchMedia = window.matchMedia;
  window.matchMedia = (query)=>{
    let mql = oMatchMedia(query);
    if (!mql.addEventListener) {
      mql.addEventListener = (evName, handler)=>mql.addListener(handler);
      mql.removeEventListener = (evName, handler)=>mql.removeListener(handler);
    }
    return mql;
  };
}
```
