### ISSUE TITLE
is there anyway to start the next point from the given date instead of plotting on the literal time scale.

### ISSUE THREAD

**Issue by nedy07** [leeoniya/uPlot#540]
Currently, it just draws a line when there's no time given, 

for example let’s say we have 3 dates => 1,2,10
So graph it is plotting as - 
`1 - 2 -  -  -  -  -  -  -  -  - 10`

expected behaviour - 
`1 -  -  -  - 2 -  -  -  - 10`

**Comment by leeoniya** [comment]
you can set `scales.x.distr: 2`, which is an ordinal distribution
