### ISSUE TITLE
Dynamically change labels

### ISSUE THREAD

**Issue by MartijnHarmenzon** [leeoniya/uPlot#545]
We have radio buttons which dynamically update the data set.
Now I also want to update the labels. In my example the series label is "foo", I want it to become "bar".
And the axis labels are "x foo" and "y foo" which I want it to become "x bar" and "y bar".
How can we achieve this?

I created a codepen:
https://codepen.io/martijnharmenzon-the-looper/pen/MWmwYNJ?editors=1011

**Comment by leeoniya** [comment]
you have to reach in and touch the dom and initialized axes: https://codepen.io/leeoniya/pen/qBmNRxy?editors=1010

```js
function setXLabel(u, label) {
  let legendLabels = u.root.querySelectorAll(".u-legend .u-label");
  legendLabels[0].textContent = u.axes[0].label = u.series[0].label = label;
}

const radio1 = document.getElementById('radio1');

radio1.addEventListener('change', () => {
  setXLabel(u1, 'foo');
  u1.setData(data1);
});

const radio2 = document.getElementById('radio2');

radio2.addEventListener('change', () => {
  setXLabel(u1, 'bar');
  u1.setData(data2);
});
```

or you can re-create the plot.

**Comment by MartijnHarmenzon** [comment]
Thanks a lot @leeoniya!
