### ISSUE TITLE
Adjust precision for legend

### ISSUE THREAD

**Issue by johanjeppsson** [leeoniya/uPlot#550]
Is there a way to set the precision of the legend? As far as I can tell, this is always shows 3 decimal places, which causes small values to be rounded to zero. I've found examples (e.g. #437 ) to change the formatting of the x-axis using the "values" argument, but this does not appear to affect the legend. Is it possible to format the value that is displayed in the legend on mouse over in the same way?

An example of what I mean from one of the demo examples:
![legend_precision](https://user-images.githubusercontent.com/20884523/126471758-bc1a110f-aa17-4439-911f-d7d330435b4d.png)

**Comment by leeoniya** [comment]
sure, DIY your own formatting via the `series.value` callback.

**Comment by johanjeppsson** [comment]
Thanks, that works! I see now that this was covered in the [basics](https://github.com/leeoniya/uPlot/tree/master/docs#basics) section of the docs; I just searched for the wrong keywords. Sorry!
