### ISSUE TITLE
Zoom ranging with grips Demo memory leak

### ISSUE THREAD

**Issue by lticadler** [leeoniya/uPlot#551]
In the zoom ranging with grips demo is a small memory leak with event listeners.
![image](https://user-images.githubusercontent.com/58069494/126640600-7626287f-5cbc-48a9-8efc-4a7a2baccf2f.png)

In bindMove 2 listeners are added but in mouseup only one is removed:
```
				on("mousemove", doc, _onMove);
				on("mouseup", doc, e => {
					off("mousemove", doc, _onMove);
				});
```

I suggest something like this:
```
      on('mousemove', doc, _onMove);
      const onMouseUpFnc = () => {
        off('mousemove', doc, _onMove);
        off('mouseup', doc, onMouseUpFnc);
      };
      on('mouseup', doc, onMouseUpFnc);
```

**Comment by leeoniya** [comment]
oops! thanks! :pray:
