### ISSUE TITLE
When x scale is set to distr:2 the series points are always displayed

### ISSUE THREAD

**Issue by kchudoba** [leeoniya/uPlot#553]
Normally the small dots (circles) representing data points disappear when there are too many of them (too close to each other).
This is great but it doesn't work ANYMORE when scale x is set to distr:2 
With an older version of uPlot it worked perfectly, so some recent change must have affected it. Would be great if this could be fixed.

**Comment by leeoniya** [comment]
i cannot confirm this. the following works as expected for me: https://jsfiddle.net/ve60da51/1/

there were some improvements to the point visibility logic in https://github.com/leeoniya/uPlot/releases/tag/1.6.12, but none that affected `distr: 2` specifically.

please provide your data and config, and which specific release (or commit) changed the behavior for you.

```js
let data10 = [
  Array.from({length: 10}, (v, i) => i),
  Array(10).fill(10),
];

let data1000 = [
  Array.from({length: 1000}, (v, i) => i),
  Array(1000).fill(10),
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
      distr: 2,
    },
  },
  series: [
    {},
    {
      stroke: '#059',
    },
  ],
};

let plot10 = new uPlot(opts, data10, document.body);
let plot1000 = new uPlot(opts, data1000, document.body);
```

![image](https://user-images.githubusercontent.com/43234/126838684-fe68c094-65b7-4dd5-a824-0b9b91236633.png)

**Comment by kchudoba** [comment]
My x-scale config :
```
	scales: {
		x: {
			distr: 2,
		},
```
when time is set to false, it works, but since the x-series are timestamps, and there is no data on weekends, it doesn't look very good. 
Setting point space to a very high number seems to kind of work, but I don't really understand the space value - and it seems to need adjustment depending on the scale of the x-values (distance between each x).

The version where it worked "out-of-the-box" for me was v1.1.2 (didn't use or update to a newer version before)

**Comment by leeoniya** [comment]
please provide your full config and dataset, as i asked and showed above, so i can run your code and see the issue myself and debug it.

**Comment by leeoniya** [comment]
ok, i think i got it breaking in my demo by turning off `time: false` : https://jsfiddle.net/mtku94cg/

```js
let now = Math.floor(Date.now() / 1e3);
let hr = 3600;

let data10 = [
  Array.from({length: 10}, (v, i) => now + i * hr),
  Array(10).fill(10),
];

let data1000 = [
  Array.from({length: 1000}, (v, i) => now + i * hr),
  Array(1000).fill(10),
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      distr: 2,
    },
  },
  series: [
    {},
    {
      stroke: '#059',
    },
  ],
};

let plot10 = new uPlot(opts, data10, document.body);
let plot1000 = new uPlot(opts, data1000, document.body);
```

![image](https://user-images.githubusercontent.com/43234/126869885-782cbf17-123a-46a7-bca7-93a5bd9aec54.png)

**Comment by leeoniya** [comment]
fixed now, thanks for reporting :+1:

**Comment by kchudoba** [comment]
Worked like a charm! Thank you for all your awesome work!
