### ISSUE TITLE
svelte

### ISSUE THREAD

**Issue by WarShoe** [leeoniya/uPlot#556]
Hi!

I am trying to use uPlot in Svelte, but there are some style issues. The sections `<div class="u-over">` and `<div class="u-under">` are placed before and after the plot. On the attached screenshot the selected "u-over" section is definitely misplaced.

And the second problem is that `max-width` style parameter is ignored. How can I control the plot size?

I would love to give a try to **uPlot** in my app, but it looks that **Plotly** has a  better compatibility with Svelte...

Here is the relevant **Svelte** code for reference, it is very simple.
```
<div id='plot'></div>
<style>
    #plot{
        max-width: 400px;
    }
</style>
```

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/6560253/127789227-cc3c548b-3a2f-4268-bc70-0350d6ddbf33.png">

**Comment by leeoniya** [comment]
make sure you include uPlot's css file:

https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.min.css

**Comment by cloudlena** [comment]
For reference, a very basic way of using `uPlot` with Svelte is the following abstraction component:

```svelte
<script lang="ts">
	import 'uplot/dist/uPlot.min.css';
	import uPlot, { type Options, type AlignedData } from 'uplot';

	export let opts: Options;
	export let data: AlignedData | undefined;

	let chartDiv: HTMLElement;

	$: {
		if (targ) {
			new uPlot(opts, data, targ);
		}
	}
</script>

<div bind:this={targ} />
```
