### ISSUE TITLE
How to draw the title on canvas left-top corner?

### ISSUE THREAD

**Issue by ileadu** [leeoniya/uPlot#558]
To save the left and right space around the title.
<img width="1084" alt="截圖 2021-08-08 下午11 55 07" src="https://user-images.githubusercontent.com/237095/128638076-5f9d388e-9bea-42dd-8ae9-9479e72c858f.png">

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillText
I studied this, but i don't know where i add them to work well.
I need to create a plugin ??

**Comment by leeoniya** [comment]
you can add a `draw` hook that uses `fillText()` or just use some CSS to re-position the title.

example of both: https://jsfiddle.net/np69zayx/
