### ISSUE TITLE
Error in iOS 12.4.1

### ISSUE THREAD

**Issue by denyaalt** [leeoniya/uPlot#559]
Hi,
An error occurs immediately after loading the script in iOS 12.4.1 (uPlot-1.6.14/uPlot.iife.js)

TypeError: el.addEventListener is not a function. (In 'el.addEventListener(ev, cb, capt ? evOpts2 : evOpts)', 'el.addEventListener' is undefined)

Stack:
on@/js/uPlot.iife.min.js:604:22
setPxRatio@/js/uPlot.iife.min.js:530:5
/js/uPlot.iife.min.js:611:12
global code@/js/uPlot.iife.min.js:4912:2

**Comment by leeoniya** [comment]
uPlot assumes you are using a recent browser version. iOS 12.4.1 was released August 26, 2019.

you have to polyfill `matchMedia` for Safari versions < 14: https://github.com/leeoniya/uPlot/issues/538#issuecomment-870711531

**Comment by denyaalt** [comment]
The point is, older iPhone versions (4/5/6) are not updated to iOS 14.

**Comment by leeoniya** [comment]
i understand.

out of the box, uPlot does not include polyfills for old browsers. if you need this, then the code above can be used. i have neither the time nor the desire to troubleshoot and support Apple's policy bundling of Hardware + iOS + Safari updates.

**Comment by denyaalt** [comment]
I will use your code, thanks for the solution!
