### ISSUE TITLE
Special case single data point in Nearest Non-Null Demo

### ISSUE THREAD

**Issue by lticadler** [leeoniya/uPlot#560]
Found a special case in your nearest non-null demo https://leeoniya.github.io/uPlot/demos/nearest-non-null.html

If there is only one data point in a series this point is **never** hovered.

E.g.
```
data = [
    [ 1629340002, 1629340004, 1629340006 ],
    [ null,       15,         null ]
]
```

This why I modified the dataIdx function a bit at the end. If only one neighbor is found choose it.
``` js
          // If found left and right neighbor choose the smallest delta
          if (nonNullLft !== hoveredIdx && nonNullRgt !== hoveredIdx) {

            if (lftDelta <= rgtDelta) {            //
              if (lftDelta <= hoverProximityPx)    //
                hoveredIdx = nonNullLft;           //  Code in your demo
            }                                      //
            else if (rgtDelta <= hoverProximityPx) //
              hoveredIdx = nonNullRgt;             //

          }
          else if (nonNullLft !== hoveredIdx && lftDelta <= hoverProximityPx)
            hoveredIdx = nonNullLft;
          else if (nonNullRgt !== hoveredIdx && rgtDelta <= hoverProximityPx)
            hoveredIdx = nonNullRgt;
```

**Comment by leeoniya** [comment]
> Code in your demo

is it?

https://github.com/leeoniya/uPlot/blob/9344e3faa8668777860f5a0edbcc1ebce59a7468/demos/nearest-non-null.html#L156-L163

i replaced `data2` in my demo with your example and commented out the unused opts.series, and it seems to work as intended.

```js
data = [
    [ 0, 1, 2 ],
    [ null,       15,         null ]
]
```

**Comment by leeoniya** [comment]
nvm, you're right. there's some pretty stupid logic in there :facepalm:

https://github.com/leeoniya/uPlot/blob/9344e3faa8668777860f5a0edbcc1ebce59a7468/demos/nearest-non-null.html#L130-L133

**Comment by leeoniya** [comment]
hopefully fixed now. also found a regression from recent hover optimizations that would fail to update the rendered hovered point when the data was flat and the y value did not change.
