### ISSUE TITLE
dark mode colour gets overruled; letters & charts stay black

### ISSUE THREAD

**Issue by xq369** [leeoniya/uPlot#561]
[dark mode.zip](https://github.com/leeoniya/uPlot/files/7013666/dark.mode.zip)
got solved in this modified 1.6.13 version

**Comment by leeoniya** [comment]
grid, axes ticks and labels are drawn on canvas, not in the DOM. so you need to adjust their color using chart options in javascript.

see https://leeoniya.github.io/uPlot/demos/line-paths.html
