### ISSUE TITLE
Force timezone different than UTC?

### ISSUE THREAD

**Issue by atay** [leeoniya/uPlot#563]
Hi,

I've been trying to force timezone on the page. I put:
```
tzDate: ts => uPlot.tzDate(new Date(ts * 1e3), 'UTC'),
```

and it works fine, no matter what timezone is set in the browser, the time axis is identical. But if I change `UTC` to `Europe/Warsaw`, then the chart is ok only when the browser has same timezone. If the timezone of the browser is different, then the axis is shifted few hours. Any ideas how can I force uPlot to use `Europe/Warsaw` timezone, no matter what are browser TZ settings?

**Comment by leeoniya** [comment]
that's strange. does this demo work for you?

https://leeoniya.github.io/uPlot/demos/timezones-dst.html

in either case, i'll need your data to verify if and what is not working.

**Comment by atay** [comment]
@leeoniya you're right, it works fine.

I just tried to test different timezones using Firefox browser extensions and they messed up, showing different results for the plot. Instead I just changed the timezone of my OS and it works fine
