### ISSUE TITLE
Angular cli build Cannot find name `GapsRefiner`

### ISSUE THREAD

**Issue by jamie0walton** [leeoniya/uPlot#564]
With Angular core 12.2 I got an error.

    Error: node_modules/uplot/dist/uPlot.d.ts:797:10 - error TS2304: Cannot find name 'GapsRefiner'.
    797   gaps?: GapsRefiner;

Replacing this with

    gaps?: Series.GapsRefiner;

Allowed the build to work without error. Thanks for the great work.

**Comment by leeoniya** [comment]
thanks!

**Comment by whtrbit** [comment]
@leeoniya Are you going to publish the changes to npm? I see it's in the master but not in `1.6.15` tag.

**Comment by leeoniya** [comment]
there are still some things i want to get into the next release, so it'll likely be mid to end of next week.
