### ISSUE TITLE
How to synchronize mouse wheel zoom/drag with zoom ranger

### ISSUE THREAD

**Issue by marc3lsk** [leeoniya/uPlot#566]
https://jsfiddle.net/3r5ap0kd/5/ here I combined two demos, https://leeoniya.github.io/uPlot/demos/zoom-ranger.html and https://leeoniya.github.io/uPlot/demos/zoom-wheel.html

Currently, the mouse wheel operations are not synced with zoom ranger. How could synchronization like this be achieved?

**Comment by leeoniya** [comment]
change the x clamping to use uRanger's min/max:

```js
[nxMin, nxMax] = clamp(nxRange, nxMin, nxMax, uRanger.scales.x.max - uRanger.scales.x.min, uRanger.scales.x.min, uRanger.scales.x.max);
```

and something like this under `u.batch(...)`:

```js
uRanger.setSelect({
  left: uRanger.valToPos(nxMin, 'x'),
  width: uRanger.valToPos(nxMax, 'x'),
});
```

https://jsfiddle.net/zsvebgj5/

hopefully you can finish the rest ;)
