### ISSUE TITLE
Disproportion between the chart and its legend

### ISSUE THREAD

**Issue by whtrbit** [leeoniya/uPlot#567]
I'm looking for some help in order to modify (or maybe fix) the behavior of the [timeline typed chart](https://leeoniya.github.io/uPlot/demos/timeline-discrete.html).

I've used your example to test my dataset and I think I might've spotted the bug.
To better explain the problem let me use some trivial dataset as an example. Let's suppose we only have one serie with three values in it. Of course, first array will contain three timestamps to build the x-axis (all with equal period of time between each other; just like in your example).
As we can expect, we will only see two ranges on the screen divided in the half. The third value becomes the final edge (the end) of the chart so it's not visible.
So far so good. Everyting renders correctly.
The problem occurs when using the legend. When hovering over the dataset we can see that the value changes in the one-third and the second-third of the range (not in the middle).

Could you please help me fix it?

With regards, whtrb!t.

**Comment by whtrbit** [comment]
Why was the issue closed? Can you tell me what's wrong with it?

**Comment by leeoniya** [comment]
see linked commit for the required changes :)

`Time` in the legend will still behave the way it did previously and it's not too clear what to show there anyways unless you switch to a table style legend and show the start time for device state.

you can use CSS to hide the time in the legend. showing the time at the cursor can be done with a it of hacking if that's something you want to work through.

[1] https://leeoniya.github.io/uPlot/demos/time-periods.html

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot/commit/8dfe012c8366c410a48a49515bc6411d6e15cb9f updates the demo to show time at cursor in the legend.

**Comment by whtrbit** [comment]
Thank you @leeoniya

**Comment by leeoniya** [comment]
:+1:
