### ISSUE TITLE
Question: how to remove secondary grid lines in log plot

### ISSUE THREAD

**Issue by gerhat** [leeoniya/uPlot#575]
I would like to be able to reduce the horizontal grid lines in a log plot.

My intention is to go from this:
<img width="920" alt="log-full" src="https://user-images.githubusercontent.com/11447903/132006699-924b7b3e-0d84-4a36-999c-35ae75e1cb45.png">

to this:
<img width="919" alt="log-min-ticks" src="https://user-images.githubusercontent.com/11447903/132006704-9262de3b-fbae-4d69-8358-8c583a630e02.png">

Using `splits: [1.0e-1, 1.0, 1.0e1, 1.0e2, 1.0e3]` gives the desired result.

Since the values given to `splits` are the same as the ones marked by uPlot in the first image, I was wondering if there is a way to take these values from uPlot directly, instead of calculating them again in the `splits` function.

**Comment by leeoniya** [comment]
use axis filters:

```js
axes: [
  {},
  {
    filter: (u, splits) => splits.map(s => Number.isInteger(Math.log10(s)) ? s : null),

    grid: {
      filter: (u, splits) => splits.map(s => Number.isInteger(Math.log10(s)) ? s : null),
    },
    ticks: {
      filter: (u, splits) => splits.map(s => Number.isInteger(Math.log10(s)) ? s : null),
    },
  }
],
```

**Comment by gerhat** [comment]
Thank you very much!
