### ISSUE TITLE
How do I fix the number of ticks in axes??

### ISSUE THREAD

**Issue by JunjaK** [leeoniya/uPlot#579]
The chart I want make is chart can add series, axes dynamically.
Everything is good. but there is some problem.

Like below picture,
![image](https://user-images.githubusercontent.com/30404630/133029144-d6844550-d3ed-4f83-a25f-86ef311caa66.png)
The number of ticks in axes are different, and  It makes reduce readability.

I already tried to use `axes.splits` but something wrong like this (align and value look ugly)..
![image](https://user-images.githubusercontent.com/30404630/133030383-6b84b2f0-7f7b-41b6-b430-384001d48a7b.png)

Is there any good solution to fix the number of ticks
( like 10 tick - 10, 20, 30, 40, 50..., 100  and value can change dynamically)

**Comment by leeoniya** [comment]
there is nothing like Flot's cross-axis tick alignment option `alignTicksWithAxis` [1], which only works for 2 axes in that library.

> I already tried to use `axes.splits` but something wrong like this (align and value look ugly)..

this is the correct option to use. can may also need to adjust `scale.range` option if you want to ensure the same number of ticks on all axes. it's not an easy problem. can you provide a jsfiddle of your example? and also an image/example of what you expect in the bottom chart?

> Is there any good solution to fix the number of ticks ( like 10 tick - 10, 20, 30, 40, 50..., 100 and value can change dynamically)

what should happen when you zoom to a range of 45-55? one tick?

[1] https://www.flotcharts.org/flot/docs/API/#customizing-the-axes

**Comment by JunjaK** [comment]
I made sample chart of my chart project. 
The chart project I made can add axes, series dynamically.
so data are random.
http://jsfiddle.net/haring157/otq0rehn/109/

and I will test `what should happen when you zoom to a range of 45-55? one tick?` you said
Thanks a lot for your comment!

**Comment by JunjaK** [comment]
and This one is wrong version of fixed tick chart I made.
http://jsfiddle.net/haring157/5x0m3vhq/10/

**Comment by JunjaK** [comment]
and This one is wrong version of fixed tick chart I made.
http://jsfiddle.net/haring157/5x0m3vhq/10/
ps. The fiddle I uploaded use some api that applied http, so fiddle url must be http (not https)

**Comment by leeoniya** [comment]
thanks, does this example help?

https://jsfiddle.net/6tfo49xz/1/

```js
let data = [
  [0, 1, 2, 3, 4],
  [10, 20, 30, 40, 50],
  [0.1, 0.7, 1.2, 3.5, 7],
  [-300, -253, -20, 10, 100],
];

let redSplits = null;

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    }
  },
  axes: [
    {},
    {
      scale: "red",
      stroke: "red",
      values: (u, splits) => {
        redSplits = splits;
        return splits;
      },
    },
    {
      scale: "blue",
      stroke: "blue",
      side: 1,
      grid: { show: false },
      splits: u => redSplits.map(s =>  u.posToVal(u.valToPos(s, 'red'), 'blue')),
    },
    {
      scale: "magenta",
      stroke: "magenta",
      side: 1,
      grid: { show: false },
      splits: u => redSplits.map(s =>  u.posToVal(u.valToPos(s, 'red'), 'magenta')),
    }
  ],
  series: [
    {},
    {
      label: "Data 1",
      scale: 'red',
      stroke: "red",
    },
    {
      label: "Data 2",
      scale: 'blue',
      stroke: "blue",
    },
    {
      label: "Data 3",
      scale: 'magenta',
      stroke: "magenta",
    }
  ],
};

let u = new uPlot(opts, data, document.body);
```

**Comment by JunjaK** [comment]
Thank you so much for your comment.
As you mentioned in issue #178, there is a problem with the value, but It can be fixed the number of ticks.

![image](https://user-images.githubusercontent.com/30404630/133366897-14b7a8ab-8796-409e-9bc6-55c9b117b06b.png)


I think I need to find a way to tune the value.

Thank you again for taking the time to find the way to solve problem.

**Comment by leeoniya** [comment]
btw, you can also check out https://github.com/leeoniya/uPlot/blob/master/demos/nice-scale.html

which does some maxTicks control and re-scaling.
