### ISSUE TITLE
Bug with a double question mark

### ISSUE THREAD

**Issue by denyaalt** [leeoniya/uPlot#584]
Hi,
I found a bug with a double question mark "??" (_opts.mode ?? 1_)

Android 8/9 - uPlot.iife.min.js
msg:"Uncaught SyntaxError: Unexpected token ?", line:2, col:15438, stack:"SyntaxError: Unexpected token ?"

`	function uPlot(opts, data, then) {
		const self = {
			mode: opts.mode ?? 1,
		};
`

**Comment by leeoniya** [comment]
previous discussion: https://github.com/leeoniya/uPlot/issues/554#issuecomment-920352529

the native browsers on older android versions are effectively non-upgradeable -- you have to use Chrome, Firefox, Opera etc to use a "modern" browser on those systems. if you need to support older browsers, i suggest either adding Babel to your toolchain or pin the uPlot version to a prior release.

sorry about doing this in a patch release rather than a point release, but uPlot has never abstained from using widely-deployed features for the sake of old browser compat.

**Comment by laurenbarker** [comment]
>sorry about doing this in a patch release rather than a point release

The update being in a patch release would be my only complaint.

In case anyone else runs into jest test failures from this, you can specify a custom "transformIgnorePatterns" in your config to have some of your "node_modules" files transformed as is stated in the below error message.

**Error**
```
Unexpected token '?'
Jest encountered an unexpected token
Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
By default "node_modules" folder is ignored by transformers.
Here's what you can do:
• If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
• If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
• To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
• If you need a custom transformation specify a "transform" option in your config.
• If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/configuration
For information about custom transformations, see:
https://jestjs.io/docs/code-transformation
Details:
/.../node_modules/uplot/dist/uPlot.cjs.js:2341
    mode: opts.mode ?? 1,
                     ^
SyntaxError: Unexpected token '?'
```

**Fix**
```js
// jest.config.js
module.exports = {
  ...
  // https://jestjs.io/docs/configuration#transformignorepatterns-arraystring
  transformIgnorePatterns: ["node_modules/?!uplot"]
}
```

**Comment by denyaalt** [comment]
There are many users who have old smartphones.
It is very bad practice to add features that do not work on older smartphones...

**Comment by leeoniya** [comment]
i guess it's that time of the year to have "that conversation" again.

@denyaalt first, please understand that i appreciate [the issues you have opened](https://github.com/leeoniya/uPlot/issues?q=is%3Aissue+author%3Adenyaalt+) in the past here, which have allowed me to improve the project for you and for others.

with that said...

> There are many users who have old smartphones. It is very bad practice to add features that do not work on older smartphones...

your contributions to open source appear to pretty much end there.

- you pay nothing to use uPlot
- you have contributed no code to this project
- your public profile shows you maintain no open source projects (never mind several high profile ones), nor provide free support or bug fixes to any others.

however, you seem to have a very strong opinion about how i should run uPlot and what browsers i need to support. that's an amazing lack of perspective, and, frankly, respect. before you lecture me on about supporting old tech, perhaps you can first finish working on https://github.com/leeoniya/uPlot/issues/474, or pick up another open issue here (just kidding, of course, i know this won't happen). i maintain this project solo, i have 3 sponsors that total perhaps $10/mo, for a lib used by numerous multi-million $ businesses that pay me [drum roll]....$0. nice gig, right?

let's talk about old browsers.

where in uPlot's readme, demos, docs, or source code do you see any statement about browser support? i'll save you some time: nowhere. the fact that it works _at all_ in anything older than browsers released 6 months ago can be considered pure luck. as a single human being, with a finite amount of time, i'm not about to start testing uPlot in every fly-by-night version of every browser on every platform. your 2015 TV has some built-in browser based on IE8 that will never be updated? that's truly unfortunate, but definitely your problem, and not mine.

> There are many users who have old smartphones. 

really? https://backlinko.com/browser-market-share

maybe, some of them should pay me to support them :shrug: 

i don't deliver uPlot to end users, i deliver it to developers. if _your_ users need old browser support, guess whose job it is to ensure that _your_ code and _your_ dependencies run through Babel with specific browser targets. the answer may _not_ surprise you!

so, for the record:

uPlot runs in browsers that i can reasonably test and have a significant market share \<today\>. this typically means several prior versions of evergreen browsers, which are updated and fixed continuously. literally anything else may or may not require polyfills and/or Babel. if you have specific browser targets, it's on you to guarantee this promise to your users.

**Comment by denyaalt** [comment]
Excuse me please...
I just wanted to suggest not to use the new ES2020 features that we can easily do without...
