### ISSUE TITLE
Improper font size scaling for data stream and Y axis auto setting

### ISSUE THREAD

**Issue by whtrbit** [leeoniya/uPlot#585]
I am currently testing live stream data based on [pxAlign example](https://leeoniya.github.io/uPlot/demos/pixel-align.html).
It works perfectly with Y range however the problem occurs when the scale is dynamic (no range is applied).
The font for both axes become smaller. The situation is even worse for 4K monitors.

Range defined (4K monitor):
<img width="309" alt="live data stream with defined range" src="https://user-images.githubusercontent.com/3809903/134665123-fbba1ecc-986b-473d-9a1a-503b7f8382aa.png">

Range not defined (4K monitor):
<img width="300" alt="live data stream" src="https://user-images.githubusercontent.com/3809903/134664989-9e15596a-f890-495b-9075-fb34d7f271a9.png">

**Comment by leeoniya** [comment]
i cannot reproduce this. are you certain you can repro this on current `master` with the exact code in the pxAlign demo minus these two lines?

https://github.com/leeoniya/uPlot/blob/3c003c3a6acc4037f46d007e7f377f4b7937704f/demos/pixel-align.html#L56-L57

**Comment by whtrbit** [comment]
I cannot reproduce it anymore. After I changed the strategy of updating the data (I use on-demand update with new reference of the array so my Angular component detects the change) the problem disappeared.
Also, I was using 1.16.5 version.
