### ISSUE TITLE
Incorrect x-axis scaling of the timeline chart on mobile devices

### ISSUE THREAD

**Issue by whtrbit** [leeoniya/uPlot#587]
I'm currently testing the behavior of [timeline chart](https://leeoniya.github.io/uPlot/demos/timeline-discrete.html).
I've tested it extensively on various devices and I think the error can only be observed on touch devices.
The screenshot show the misalignment in values in x-axis and legend.

<img width="752" alt="uplot_timeline_mobile_error" src="https://user-images.githubusercontent.com/3809903/135246729-aa497d88-ee16-4e03-9297-fa6c8cb2c8ef.png">

I've narrowed the problem to this line:
https://github.com/leeoniya/uPlot/blob/75516f6170888d50fad07f22e412324a25c04be2/demos/timeline-discrete.html#L308
The result of `posToVal` function is incorrect in context of what's rendered on the screen.

EDIT:
The cause might be not respecting `window.devicePixelRatio` at some point. On my 4K screen pixel ratio is `1.5`, on 1K screen it's `1`. Everything is ok when value `1`. Problems start when `1.5` or `2`.

**Comment by whtrbit** [comment]
The problem can be reproduced in Chromium based browsers when enabling eg.: iPad Pro device in devtools.

**Comment by whtrbit** [comment]
It might be Window.devicePixelRatio related.
Could you point me into the right direction in the source code?

**Comment by leeoniya** [comment]
yep, fixed now.

**Comment by whtrbit** [comment]
Awesome! Thank you.
