### ISSUE TITLE
Set selection programmatically

### ISSUE THREAD

**Issue by bokolob** [leeoniya/uPlot#589]
Hi, is there a way to do it?

I have a table (actually not a table, an example for simplicity) and a chart based on it. When user clicked somewhere in table I have to highlight corresponding points on chart.

**Comment by leeoniya** [comment]
setting the selection an highlighting points are two different operations, so i'm not sure what specifically you're asking for here.

setting the selection can be done via `.setSelect()`:

https://github.com/leeoniya/uPlot/blob/294c39d6443283746e613f3d147ebda69cd3c7c3/dist/uPlot.d.ts#L101-L102

you can set compute those coordinates using the `.valToPos()` API:

https://github.com/leeoniya/uPlot/blob/294c39d6443283746e613f3d147ebda69cd3c7c3/dist/uPlot.d.ts#L113-L114

the active hover points are shown from the cursor position, and the cursor can be set using `.setCursor()`:

https://github.com/leeoniya/uPlot/blob/294c39d6443283746e613f3d147ebda69cd3c7c3/dist/uPlot.d.ts#L76-L77

if you want to mark every point in the selected range, it's up to you to find them from you data and draw them manually on the canvas in a hook, e.g, `drawSeries`. (see various demos in this repo that draw from hooks).
