### ISSUE TITLE
Option to toggle off a series initially

### ISSUE THREAD

**Issue by silverwind** [leeoniya/uPlot#59]
Is there a option to have a series toggled off initially?

**Comment by leeoniya** [comment]
try `{show: false}`

**Comment by silverwind** [comment]
`show: false` does hide the line, but is not reflected in the legend:

<img width="109" src="https://user-images.githubusercontent.com/115237/70001870-b706b280-155e-11ea-9f68-68066cd9dc8a.png">

What I'm after is this initial status:

<img width="112" src="https://user-images.githubusercontent.com/115237/70001882-bf5eed80-155e-11ea-9f79-71ef4cae83b9.png">

Ideally, clicking on the legend should toggle the line again, but `show` prevents that.

**Comment by leeoniya** [comment]
this was a bug.

try `{show: false}` again.

**Comment by silverwind** [comment]
Thanks, working as expected now!
