### ISSUE TITLE
posToVal(): incorrect values for asinh scales with linear threshold

### ISSUE THREAD

**Issue by vthriller** [leeoniya/uPlot#590]
Steps to reproduce:
- take demos/tooltips.html
- set `scales.y` to `{distr: 4, asinh: 5}`
- see cursor tooltip show values that don't match grid ticks:
  ![image](https://user-images.githubusercontent.com/176062/135704808-c283ed5d-d449-4569-ad58-726af3bde88b.png)

**Comment by leeoniya** [comment]
hopefully fixed now :crossed_fingers: 

thanks for the report!
