### ISSUE TITLE
handle mouse events on axes

### ISSUE THREAD

**Issue by kriede** [leeoniya/uPlot#604]
I have a chart with three different vertical axes with independent scale.

I already know how to change the grid visibility and the order of the axes by clicking on dedicated buttons, so the user can chose for which axis the grid should be shown.

I can't find any mouse handler options for axes. Is it somehow possible to handle mouse click an the axes to trigger these changes?

**Comment by leeoniya** [comment]
i've added axis dom rects in the linked commit.

note that they **do not include axis labels**:

![image](https://user-images.githubusercontent.com/43234/139513097-34fe7ca1-205e-4133-9769-95f19322790a.png)

if you need to attach event listeners to them, or add css or classnames, you can use an `init` hook and querySelectorAll by index:

https://jsfiddle.net/40kgvx7o/1/

```js
const data = [
  [0.8,2,3,4,5],
  [-30, 10, 12, 40, 100]
];

const opts = {
  width: 800,
  height: 500,
  scales: {
    x: {
      time: false,
    },
  },
  series: [
    {},
    {
      stroke: '#059',
    },
  ],
  hooks: {
    init: [
      (u) => {
        let axesRects = u.root.querySelectorAll(".u-axis");
        
        u.axes.forEach((axis, i) => {
          axesRects[i].classList.add("scale-" + axis.scale);
        })
      }
    ]
  }
};

let plot = new uPlot(opts, data, document.body);
```

**Comment by kriede** [comment]
Thank you for your super fast support and changes to uplot! It solves my problem.
