### ISSUE TITLE
Demos broken in Safari 12 and 13 

### ISSUE THREAD

**Issue by samuel-git** [leeoniya/uPlot#607]
Great work with this library!

Older Safaris (and maybe other browsers) crash the javascript thread with ``TypeError: n.addEventListener is not a function``. Tested here: https://leeoniya.github.io/uPlot/bench/uPlot.html on Safari 12 MacOS Mojave and Safari 13 on MacOS Catalina.

This is the problematic line: https://github.com/leeoniya/uPlot/blob/cdc31b47b77fad5d0ad911e231b2892011b58e26/dist/uPlot.esm.js#L645

Called from here: https://github.com/leeoniya/uPlot/blob/cdc31b47b77fad5d0ad911e231b2892011b58e26/dist/uPlot.esm.js#L561
Without this line everything works fine, my guess is that the event listener on matchMedia(...) is not supported by older Safaris.
<img width="780" alt="grafik" src="https://user-images.githubusercontent.com/22152728/139668271-2fca33a7-3618-446c-adb0-50e8943a07b0.png">

Edit: Add screenshot and better error description

**Comment by leeoniya** [comment]
please search for previous issues before opening new ones: https://github.com/leeoniya/uPlot/issues?q=is%3Aissue+safari

the fix is to polyfill older browsers if you need support for them: https://github.com/leeoniya/uPlot/issues/538#issuecomment-870711531

**Comment by samuel-git** [comment]
Thanks for pointing me in the right direction and excuse my mistake. I would suggest writing something about polyfills in the readme when not included in the code as I am not the first person with this issue und these are relatively new Browsers which should support matchMedia() https://caniuse.com/matchmedia so this is not obvious.
