### ISSUE TITLE
Stale cursor.idx / legend.idx inside of plugin.setLegend

### ISSUE THREAD

**Issue by Stinger-au** [leeoniya/uPlot#609]
Hi, 

I have implemented a custom legend for my plot and it seems that self.cursor.idx and self.legend.idx have not been updated to the latest value inside of my setLegend plugin callback. I can fix my issue by wrapping everything inside of a setTimeout(,0), however I am wondering if this is intentional as it is a bit surprising. 

I have     "uplot": "^1.6.16" according to my package.json.

Great library btw - I am writing an app currently plotting ~3 mil points and the performance is very reasonable considering.

**Comment by leeoniya** [comment]
hmm...the legend index looks correct to me, but the cursor index lags behind:

https://jsfiddle.net/re0Lh84k/

```js
const data = [
  [0.8, 2, 3, 4, 5],
  [-30, 10, 12, 40, 100]
];

const opts = {
  width: 800,
  height: 500,
  scales: {
    x: {
      time: false,
    },
  },
  series: [{},
    {
      stroke: '#059',
    },
  ],
  hooks: {
    setLegend: [
      (u) => {
        console.log('u.legend.idx', u.legend.idx);
        console.log('u.cursor.idx', u.cursor.idx);
      }
    ],
  }
};

let plot = new uPlot(opts, data, document.body);
```

**Comment by leeoniya** [comment]
in the linked commit i pulled some of the cursor prop setting up ahead of the `setLegend` hook. can you try the `master` build and see if it works as expected?

**Comment by Stinger-au** [comment]
Apologies you were indeed right - my code I started with cursor.idx and had this issue so I switched to legend.idx, but I had missed one instance which was still referring to cursor.idx so had outdated data. 

Can confirm with the version I was using legend.idx was correct and cursor.idx was stale. In your master dist both now appear to be correct.

**Comment by leeoniya** [comment]
great :+1: 

i'm thinking of having these fire in the natural order as they happen in the code (setCursor -> setLegend). right now they're reversed, but i can't remember if this was intentional or just an artifact of the previous code structure. need to be careful not to break any use cases that may have relied on this. :thinking:
