### ISSUE TITLE
How can I add reference lines in uplot?

### ISSUE THREAD

**Issue by kriede** [leeoniya/uPlot#613]
Because of the high rendering performance I am using uPlot to visualize historical sensor data. Is there a way to add horizontal reference lines like for the recommended min/max values of a data series? With other libraries that's often straight forward, like the ReferenceLine tag in recharts, but I haven't found anything yet with uPlot. Any hints?

Example: The orange dotted lines are the lower and upper acceptable bounds at 7.0 and 7.4. This image is rendered with recharts, but I want to migrate to uplot.

![image](https://user-images.githubusercontent.com/9135655/140164981-ac3f8e42-ff1b-492f-b736-de95ed6508df.png)

(There's a layer in front of the chart with the actual, min and max value which is totally independent of the chart.)

**Comment by leeoniya** [comment]
it's DIY drawing on canvas with a few lines of code in a hook of your choosing.

if you need the lines above the grid but below the series, use the `drawAxes` hook, if you want them on top of everything use the `draw` hook.

some examples:

https://leeoniya.github.io/uPlot/demos/trendlines.html
https://leeoniya.github.io/uPlot/demos/draw-hooks.html
