### ISSUE TITLE
Zooming after addSeries and setData

### ISSUE THREAD

**Issue by jcommander** [leeoniya/uPlot#614]
Hallo, I have a chart that uses a multi-dropdown list to select which objects data should be shown
when you add a Object I use addSeries to add a Series and setData to add the Data.

Unfortunately, after adding a Series, the zooming doesn't work properly anymore, it seems to still zoom on the first Series, but if the other one start after the first ends, there's no chance to zoom to it, i've tried changing some Hooks and updating min,max but it didnt work
```
                    
                        setData: u => {
                        shouldSyncX = true;
                        shouldSyncY = true;

                        xMin = u.scales.x.min;
                        xMax = u.scales.x.max;
                        yMin = u.scales.y.min;
                        yMax = u.scales.y.max;

                        xRange = xMax - xMin;
                        yRange = yMax - yMin;

                        console.log("setdata");
                    },
```

ResetScale() doesnt work either:
```
function scaleReset() {
	let lastIdx = u.data[0].length - 1;

	u.setScale('x', {
		min: u.data[0][0],
		max: u.data[0][lastIdx],
	});
}
```

u.cursor seems correct but it seems to zoom in the direction of the first Series always.

**Comment by leeoniya** [comment]
can you please provide a simple jsFiddle that shows the issue? it's very tedious for me to try to figure out and reconstruct repros from partial code dumps. thanks!

example: https://jsfiddle.net/re0Lh84k/

**Comment by jcommander** [comment]
Hey,

very understandable, I've created a jsFiddle with the barebones of my Project. I use μPlot to display sensor data read from a database.
Try zooming in and out in the jsFiddle you will notice the Scales and Graphs fail to line up with the actual Data.

https://jsfiddle.net/vdhkyx7m/20/

<img width="652" alt="Screenshot1" src="https://user-images.githubusercontent.com/7689370/141114959-16c438fa-2df4-4887-a95d-34965deef383.png">

<img width="652" alt="Screenshot2" src="https://user-images.githubusercontent.com/7689370/141115111-8a16b766-75a3-4428-b6d5-4d75c4da46fc.png">

**Comment by leeoniya** [comment]
i think you're just forgetting `scale: "C"` in your `addSeries()` call, so it's probably auto-assigning the default `y` scale.

this works as expected, i think: https://jsfiddle.net/4y5qu0fL/
