### ISSUE TITLE
Vertical line chart?

### ISSUE THREAD

**Issue by Artemichi** [leeoniya/uPlot#615]
cant understand how to create a vertical chart

data = [
[1636287720,1636287725,1636287730,1636287735,1636287740],
[73.11,76.12,76.8,76.1,76.12]
]
smth like this one
![image](https://user-images.githubusercontent.com/55092560/140648000-69e78fa3-adcd-4b13-a585-313b8076e4b4.png)

**Comment by leeoniya** [comment]
see https://leeoniya.github.io/uPlot/demos/scales-dir-ori.html
