### ISSUE TITLE
Custom background drawing hook

### ISSUE THREAD

**Issue by mkurtzsd** [leeoniya/uPlot#616]
Are there currently any hooks for doing any custom drawing prior to the series and axis being drawn? I need to draw some "red, yellow, green" ranges on the graph. I can easily get the bounding box (bbox) and context (ctx) from my uPlot instance; but I'm not sure how I can draw to the context in the correct sequence without some type of hook that would allow me to do that. I've attached an image that shows very simply what I need to do
![RangeChart](https://user-images.githubusercontent.com/7508755/141405799-d7093a6f-3952-40e2-85fa-a1c546d8c172.png)
.

**Comment by leeoniya** [comment]
you'll want to use either `drawClear` (before anything is drawn) or `drawAxes` (after axes and grid are drawn). remember to wrap your drawing code with `ctx.save()` and `ctx.restore()`.

see https://leeoniya.github.io/uPlot/demos/draw-hooks.html

**Comment by mkurtzsd** [comment]
Leon,

Works perfectly. Thanks for the help.

-Mike
