### ISSUE TITLE
ordering of items in legend

### ISSUE THREAD

**Issue by wothke** [leeoniya/uPlot#618]
nice tool :-) I missed a small feature that I just hacked in, for use on my page here:
https://www.wothke.ch/websid_filter/ 

The idea is maintain the ploting order of the different data series but to reverse the order in which they are
listed in the legend so as to better match them to the curves in the plot. (in my case successive data series
in the plot always appear further to the left and should be obscured by the earlier curves).

I just changed:
			let row = placeTag("tr", LEGEND_SERIES, legendEl, legendEl.childNodes[i]);
to:
			let row = placeTag("tr", LEGEND_SERIES, legendEl, legendEl.childNodes[legend.reverse ? 1 : legendEl.childNodes[i]]);

which addressed my need nicely. Let me know in case there already is some existing feature to achieve the same effect
or feel free to add a respective feature :-)

**Comment by leeoniya** [comment]
really cool project! i'm a fan of chiptunes :)

for legend item re-ordering i'd recommend using CSS's `order` property [1] for specific ordering. if you just need to reverse the display order, you can pair it with some `flex-direction` magic: https://jsfiddle.net/ohtg03yw/

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/order

random links:

http://www.8bitpeoples.com/ (all tunes are free for 192kbps MP3 and $5.00 for higher bitrates)

Trash80 - Icarus
https://www.youtube.com/watch?v=m7sEkhBvREA
Trash80 - Robot Sneakers
https://www.youtube.com/watch?v=s1HLtFfwihU
