### ISSUE TITLE
Order axis just by days without hours between

### ISSUE THREAD

**Issue by Mecanik** [leeoniya/uPlot#619]
Greetings! Thank you for this amazing library.

I'm in a bit of a pickle, trying to get rid of google charts... however I cannot get the result I want. I checked the demos, tries bits and pieces, still the same (or broken) result.

My current result is:

![image](https://user-images.githubusercontent.com/12122357/141755429-283b891c-3508-4061-840e-122e89b4d4a0.png)

I would like to have the data shown by days only, without the hours between, for example "2021-11-13", 2021-11-14", 2021-11-15",  etc.

Could you please point me in the right direction?

**Comment by leeoniya** [comment]
https://jsfiddle.net/eyuvfphw/

```js
let now = Math.round(Date.now() / 1e3);
let day = 24 * 3600;

const data = [
  [now - 3 * day, now - 2 * day, now - 1 * day, now],
  [-30, 10, 12, 40, 100],
];

const opts = {
  width: 800,
  height: 500,
  axes: [
    {
      // set axis tick increments to only 24h
      incrs: [day],
      // use static template for every tick
      values: '{YYYY}-{MM}-{DD}'
    }
  ],
  series: [
  	{},
    {
      stroke: 'blue',
      fill: "rgb(0,0,255, 0.1)",
    },
  ],
};

let plot = new uPlot(opts, data, document.body);
```
