### ISSUE TITLE
Automatic focus when the plot Initial loading?

### ISSUE THREAD

**Issue by hxse** [leeoniya/uPlot#623]
I have constantly updating data. When the data update, the chart is reloaded.
But each reloaded will cause the cursor to lose focus.
so, how to focus the cursor when reload.

**Comment by leeoniya** [comment]
i don't understand what you mean by "lose focus".

does this demo work as you expect? https://leeoniya.github.io/uPlot/demos/stream-data.html

**Comment by leeoniya** [comment]
closing until additional info is provided
