### ISSUE TITLE
Incorrect point position  in y-axis for one element in array

### ISSUE THREAD

**Issue by whtrbit** [leeoniya/uPlot#624]
I've spotted there is an issue in case of data series with only one element.

![image](https://user-images.githubusercontent.com/3809903/143498696-22847f72-d89e-4099-90eb-7508060018e9.png)

Your generic legend shows `0` as well. I've tested it with different values and the resut is the same.
Everything works fine with two elements.

**Comment by leeoniya** [comment]
there are a bunch of examples with one datapoint here appear to work correctly: ​https://leeoniya.github.io/uPlot/demos/no-data.html

please make a runnable demo. e.g. https://jsfiddle.net/8g7joe61/

**Comment by whtrbit** [comment]
https://jsfiddle.net/qbpLevk7/
The relevant part is when we call `setScale` for x-axis. `min` and `max` must be the same to reproduce.
I'm not sure if this is a bug though.
I already fixed that in my example by removing `setScale` as I actually don't need it.

**Comment by leeoniya** [comment]
i think this will be the same discussion as https://github.com/leeoniya/uPlot/issues/620. basically, how should uPlot draw a 0-range chart? 🤯
