### ISSUE TITLE
Different colors for bars

### ISSUE THREAD

**Issue by pcbt** [leeoniya/uPlot#626]
Hi,

Is there a way to set the stroke and fillcolor according to the value? 
I have this chart:
![2021-11-29 16_32_30-StrokesPlus](https://user-images.githubusercontent.com/8384926/143877336-7be8d626-9966-4638-b4d3-077697e7b5d8.png)
with these data:
![2021-11-29 16_36_28-StrokesPlus](https://user-images.githubusercontent.com/8384926/143877573-ef75dc46-e936-4b92-b5c4-6a4303df0598.png)

and I want to stroke and fill the 3th point with blue since it's type is different.

I tried to do it with "BarsPathBuilderDisplay" but it didn't help.

Thanks in advance.

**Comment by leeoniya** [comment]
> I tried to do it with "BarsPathBuilderDisplay" but it didn't help.

this should work, as shown in [1] [2].

can you make a jsfiddle of your attempt?

[1] https://leeoniya.github.io/uPlot/demos/multi-bars.html
[2] https://github.com/leeoniya/uPlot/blob/62adada4739e6545964fc38ee3bc55ac77f5d258/demos/multi-bars.html#L207-L224

**Comment by pcbt** [comment]
Hi,

Here is the jsfiddle:

https://jsfiddle.net/pcbtce/pcgo6xyz/3/

If I remove "disp" option from BarsPathBuilderOpts it works.

**Comment by leeoniya** [comment]
ah, yeah. it currently assumes you're also providing `disp.x0` and `disp.size`, so crashes when these are absent. e.g.

https://github.com/leeoniya/uPlot/blob/62adada4739e6545964fc38ee3bc55ac77f5d258/src/paths/bars.js#L68
https://github.com/leeoniya/uPlot/blob/62adada4739e6545964fc38ee3bc55ac77f5d258/src/paths/bars.js#L74

i need to add a couple `if`s in there, and it will work.

**Comment by pcbt** [comment]
thanks a lot

**Comment by leeoniya** [comment]
pushed a couple commits that make your fiddle work. thanks!
