### ISSUE TITLE
Question: is it possible to hide tooltips while zooming?

### ISSUE THREAD

**Issue by gerhat** [leeoniya/uPlot#627]
I would like to be able to hide the tooltips while dragging to zoom. 
I am using a tooltip plugin implementation similar to this demo: https://leeoniya.github.io/uPlot/demos/tooltips.html

In options I have:
```javascript
cursor: {
  drag: {
    x: true,
    y: true,
  },
},
```

I was trying to find out how I can get a `isDragging` event inside the tooltip plugin, but wasn't able to discover how.

**Comment by leeoniya** [comment]
it's not documented, but is `u.cursor.drag._x` and `u.cursor.drag._y`, though from testing does not seem to get reset at the end of drags or properly set at init: https://jsfiddle.net/4xrap3bv/

there may be a specific purpose for not resetting it, cause other synced plot instances read these variables from the emitter to see what it was doing. i'll have to test any changes to this carefully.

**Comment by gerhat** [comment]
Thank you  @leeoniya.
I saw about `u.cursor.drag._x` and `u.cursor.drag._y` in this issue: https://github.com/leeoniya/uPlot/issues/246 

Is there a workaround for getting the raw `dragstart``dragend` mouse events maybe? Like this issue: https://github.com/leeoniya/uPlot/issues/298

**Comment by leeoniya** [comment]
> Is there a workaround for getting the raw dragstart dragend mouse events maybe? Like this issue: #298

yep, you can definitely use `cursor.bind` to add your own pass-through handlers for `mousedown` and `mouseup` events. you do the same with `mousemove`, but that's likely not needed.

https://github.com/leeoniya/uPlot/blob/40fdfa17eb17f2d1f5fbd6d1b03621c00779f36b/dist/uPlot.d.ts#L425-L434

**Comment by gerhat** [comment]
Thank you for your input @leeoniya I got what I needed using the following code:
```javascript
const tooltipsPlugin = (shiftX = 3, shiftY = -1) => {
  let seriestt: (HTMLDivElement | undefined)[] = []
  let isDragging = false
  
  const init = (u: uPlot, opts: uPlot.options) => {
    const { over } = u

    seriestt = opts.series.map((s, i) => {
      if (i === 0) {
        return undefined
      }
      
      const tt = document.createElement('div')
      tt.className = 'u-tooltip'
      tt.style.pointerEvents = 'none'
      tt.style.position = 'absolute'
      tt.style.background = s.stroke as string
      tt.style.color = 'white'
      tt.style.display = s.show ? 'block' : 'none'
      over.appendChild(tt)
      return tt
    })  
 
    over.addEventListener('mousedown', () => {
      isDragging = true
    })

    over.addEventListener('mouseup', () => {
      isDragging = false
    })
  }

  const setCursor = (u: uPlot) => {
    const { idx } = u.cursor
    const { over } = u

    seriestt.forEach((tt, seriesIdx) => {
      const xVal = u.data[0][idx || 0]
      const yVal = u.data[seriesIdx][idx || 0]

      if (isDragging) {
        tt.style.display = 'none'
      } else {
        tt.style.display = 'block'
        tt.textContent = `${xVal}, ${yVal}`
      }
    })
  }
}
```
