### ISSUE TITLE
Bind click doesn't work for cursor

### ISSUE THREAD

**Issue by pcbt** [leeoniya/uPlot#629]
Hi,

Click bound is not working, am I doing somethong wrong? 

Here is the fiddle:
https://jsfiddle.net/pcbtce/4w260r1v/59/

KR

**Comment by leeoniya** [comment]
yep, you're right. uPlot doesn't actually use `click` internally, except for legend. so the value of having it in `bind` is not entirely clear. i think i added it just for uniformity but forgot to hook it up:

https://github.com/leeoniya/uPlot/blob/40fdfa17eb17f2d1f5fbd6d1b03621c00779f36b/src/uPlot.js#L2905-L2916

**Comment by leeoniya** [comment]
looking more at the code, now i remember: the `click` bind has always been specifically for intercepting legend item clicks. yes, this is absolutely not obvious, but the whole `bind` api is meant specifically for intercepting of event handlers that uPlot binds on its own, and was not intended to be a replacement for `addEventListener`. so for your case, just do something like `u.over.addEventListener("click")` in an `init` hook.
