### ISSUE TITLE
Question: How can i select multiple regions of data?

### ISSUE THREAD

**Issue by ondrados** [leeoniya/uPlot#630]
I would like to select multiple regions of data alongside axis x, so in the end i have some array of selected regions like this:
 `[[755, 1200], ...]` or even like this `[[750, 751, ..., 1199, 1200], ...]`

![image](https://user-images.githubusercontent.com/39186938/144717059-e8189fcd-89c3-4ac2-8ab4-9e73e8e55001.png)

I have followed this [demo](https://leeoniya.github.io/uPlot/demos/cursor-bind.html) but I was only capable of getting something what resembling a selection in pixels not in data.

Can someone purpose some approach how to do that? or even some code snippet?
I don't have a very good understanding of the internal architecture so I don't know how this can be achieved.

For starters, it would help me to get the selection in data and not in pixels.

Thanks in advance

PS I really appreciate your work!

**Comment by leeoniya** [comment]
> For starters, it would help me to get the selection in data and not in pixels.

the API you need to _draw_ the highlighted regions on canvas is `u.valToPos(value, 'x', true)`. this will get you the canvas x coordinate for a specific value along the `x` scale. are you also asking how to interactively select these regions?

https://jsfiddle.net/5hqgo0mw/

![image](https://user-images.githubusercontent.com/43234/144723005-75d9ce12-cf9f-470c-a66b-207688d634a5.png)

```js
const data = [
  [0, 1, 2, 3, 4],
  [-30, 10, 12, 40, 100],
];

const opts = {
  width: 800,
  height: 500,
  scales: {
    x: {
      time: false,
    }
  },
  hooks: {
    // draw atop axes & grid, but under series
    drawAxes: [
      u => {
        let left, right;
        
        u.ctx.save();
        u.ctx.fillStyle = 'rgba(255,0,0,0.1)';
        
        left = u.valToPos(0.5, 'x', true);
        right = u.valToPos(1, 'x', true);
        
        u.ctx.fillRect(
          left,
          u.bbox.top,
          right - left,
          u.bbox.height,
        );
        
        left = u.valToPos(2, 'x', true);
        right = u.valToPos(3, 'x', true);
        
        u.ctx.fillRect(
          left,
          u.bbox.top,
          right - left,
          u.bbox.height,
        );
        
        u.ctx.restore();
      }
    ],
  },
  series: [
    {},
    {
      stroke: 'blue',
      fill: "rgb(0,0,255, 0.1)",
    },
  ],
};

let plot = new uPlot(opts, data, document.body);
```

**Comment by ondrados** [comment]
Thanks for quick response.

Yes I want to interactively select these regions whit some `shiftKey` or something. 

High-level overview of my functionality is that user select some regions of this signal and then these regions will be used for some computation in the backend - so i want to get some binary mask of this signal (binary mask is easy to get with known regions).

**Comment by leeoniya** [comment]
it's pretty much just incorporating the above strategy into that `cursor.bind` demo:

https://github.com/leeoniya/uPlot/commit/8379a771ef2e853236edf1b8349e229c07474d3f
