### ISSUE TITLE
Disposing

### ISSUE THREAD

**Issue by xbaha** [leeoniya/uPlot#631]
Hello and thank you for the amazing library!
I have a page where my charts pull data every xx minutes,
I am thinking of 2 options, 
1. dispose of the current chart then recreate a new one.
2. refresh the current chart data.

Please advise if there is a right way to dispose the current chart, and also, how do I refresh the current chart's data?

Thank you.

**Comment by asimsedhain** [comment]
I just started using this library a few weeks ago, so might want take my words with a grain of salt.

You can dispose of the chart using the [destroy](https://github.com/leeoniya/uPlot/blob/40fdfa17eb17f2d1f5fbd6d1b03621c00779f36b/dist/uPlot.d.ts#L68) method.

As for refreshing the data, I am using the [setData](https://github.com/leeoniya/uPlot/blob/40fdfa17eb17f2d1f5fbd6d1b03621c00779f36b/dist/uPlot.d.ts#L71) method. I followed this [example](https://github.com/leeoniya/uPlot/blob/master/demos/stream-data.html) which shows how to dynamically stream data.

Hopefully that helps. And someone please correct me if I am wrong.

**Comment by xbaha** [comment]
That worked!
Thank you so much...

**Comment by leeoniya** [comment]
yep, `u.setData()` is the correct API to use. thanks @asimsedhain :+1: 

definitely try to avoid destroying the chart unless you have data layout or other options changes.
