### ISSUE TITLE
Bar does not get drawn if there is only one sample

### ISSUE THREAD

**Issue by islandsvinur** [leeoniya/uPlot#632]
When there is a single data sample, a bar does not get drawn. This is similar to line graph that does not draw a line segment if there is only one data sample.

To reproduce, disable all charting libraries except uPlot in the [Multi Bars demo](https://leeoniya.github.io/uPlot/demos/multi-bars.html):

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/869756/144984097-a182be7b-c255-46bb-9c9b-6e631725d097.png">

Note that the GroupedBarsPlugin does print the bar values.

**Comment by islandsvinur** [comment]
Did some debugging, discovered that `getValPct` can produce `NaN` if `val`, `scale._min` and `scale._max` are all 0. That `NaN` gets pushed up all the way to `canOffs` in `drawAxesGrid`, which then fails to draw ...

If I ensure `getValPct` always produces a number (i.e. add `|| 0`), the bar does get drawn (with the wrong offset, but it's something).

**Comment by leeoniya** [comment]
hmm, yeah this looks like a bug in `distr: 2`.

also affects candlestick when you zoom down to just one: https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html

**Comment by leeoniya** [comment]
fixed in linked commit (you might need to tweak the bars plugin a bit)

thanks for reporting :+1:

**Comment by islandsvinur** [comment]
Works like a charm, thanks for fixing!
