### ISSUE TITLE
Disable Click Event on Legend

### ISSUE THREAD

**Issue by xbaha** [leeoniya/uPlot#633]
When the chart has 1 series only, it's pointless to have it toggled to hidden, Is there a way to disable the mouse click event on the legend toggling this series off/on?

**Comment by leeoniya** [comment]
the easiest way is to to set `pointer-events: none;` on the legend label: https://jsfiddle.net/pz4g2hw5/

you can also use `cursor.bind.click` to provide your own click proxy that does not invoke the original handler (see discussion in https://github.com/leeoniya/uPlot/issues/629)
