### ISSUE TITLE
Question: How can i apply the click event to the bubble plot?

### ISSUE THREAD

**Issue by uheaji** [leeoniya/uPlot#636]
![Screenshot_3](https://user-images.githubusercontent.com/74044253/145721053-0e67e35c-d2fd-4d4f-9bce-ed46eca15a23.jpg)

When I click one bubble in this bubble plot, 
I would like to implement a click event that puts the values corresponding to that bubble in a variable.
but i don't know how to do it, so I'm asking you this question. 

Thank you.

**Comment by leeoniya** [comment]
something like this in `opts` would work:

```js
hooks: {
  init: [
    u => {
      u.root.addEventListener('click', e => {
        let hoveredSeriesIdx = u.cursor.idxs.findIndex(v => v != null);

        if (hoveredSeriesIdx != -1) {
          let hoveredDataIdx = u.cursor.idxs[hoveredSeriesIdx];
          let seriesOpts = u.series[hoveredSeriesIdx];
          let facetsData = u.data[hoveredSeriesIdx];

          console.log(seriesOpts.label);

          facetsData.forEach((data, facetIdx) => {
            console.log(data[hoveredDataIdx]);
          });
        }
      });
    }
  ]
}
```

**Comment by uheaji** [comment]
Thank you for your quick response 😄
