### ISSUE TITLE
seriesBarsPlugin does not format x-axis values as time

### ISSUE THREAD

**Issue by tomaszs** [leeoniya/uPlot#638]
When a seriesBarsPlugin is used:

```
const opts = {
					title: 'withPlugin',
					width:  800,
					height: 400,
					axes: [ {} ],
					series: [{}],
					plugins: [
						seriesBarsPlugin({
							ori: 0,
							dir: 1,
						}),
					],
				};

				let u = new uPlot(opts, [
					[1546300800,1546387200]
				], document.getElementById('a'));
```

The graph shows raw values of time (DOES NOT FORMAT IT):

Preview:

![fdfds](https://user-images.githubusercontent.com/834977/146176552-7a4bcda2-420e-4c25-9eaf-5542587e147b.jpg)

Compared when [seriesBarsPlugin](https://leeoniya.github.io/uPlot/demos/multi-bars.html) is removed, values of time are properly formatted:

```
const opts = {
					title: 'withoutPlugin',
					width:  800,
					height: 400,
					axes: [ {} ],
					series: [{}]
				};

				let u = new uPlot(opts, [
					[1546300800,1546387200]
				], document.getElementById('b'));
```

Preview:

![fdsfdfsd](https://user-images.githubusercontent.com/834977/146176724-b681d7fd-e4e8-43bc-aba2-0c7b6f6b4e4b.jpg)

How to make seriesBarsPlugin format x-axis values as time rather than showing raw data?

Minimal reproduction HTML code: https://gist.github.com/tomaszs/4c0ca50cf43e9f52fc07a7fc10caeed8

**Comment by leeoniya** [comment]
seriesBarsPlugin is not really _meant_ for time. it is meant for showing labeled groups or categories, like most barcharts:

https://www.google.com/search?q=bar+chart&source=lnms&tbm=isch

the x values are simply labels and will not auto-skip or auto-format. if you want the values formatted as time, you can do this yourself by setting `scales.x.time: true` and providing a template string for `axes[0].values`, like `{YYYY}-{MM}-{DD}`.

or you can implement your own `axis.values` formatter that uses `uPlot.fmtDate()` as done in the tooltip demo [3].

all that being said, if you simply want a timeseries trend rendered as bars, you should just use the `uPlot.paths.bars` pathBuilder [4].

[1] https://github.com/leeoniya/uPlot/blob/af312d693a32ee7e7575a53ac940fa4cc0c625c2/demos/grouped-bars.js#L243
[2] https://github.com/leeoniya/uPlot/blob/af312d693a32ee7e7575a53ac940fa4cc0c625c2/demos/grouped-bars.js#L208
[3] https://github.com/leeoniya/uPlot/blob/af312d693a32ee7e7575a53ac940fa4cc0c625c2/demos/tooltips-closest.html#L63
[4] https://leeoniya.github.io/uPlot/demos/line-paths.html
