### ISSUE TITLE
setScale is unsuccessful

### ISSUE THREAD

**Issue by hxse** [leeoniya/uPlot#639]
I want to setScale in draw hook, but is unsuccessful.
Code example:
https://jsfiddle.net/1qo4dj0h/

**Comment by leeoniya** [comment]
> I want to setScale in draw hook

generally you should not do this since it will likely result in an infinite loop of `draw -> setScale() -> draw -> setScale()...`

if you describe in more detail what you are trying to achieve, then i can probably provide better advice.

but if you still think you need this, then...

```js
  hooks: {
    draw: (u) => {
      u.setScale("x", {
        Min: 1,
        Max: 3
      })
    },
  }
```

should be 

```js
  hooks: {
    draw: [
      u => {
        u.setScale("x", {
          min: 1,
          max: 3
        })
      },
    ]
  }
```

**Comment by hxse** [comment]
Thanks
