### ISSUE TITLE
Reinitialize tooltips after addSeries / delSeries

### ISSUE THREAD

**Issue by gerhat** [leeoniya/uPlot#641]
Is there any way to reinit the tooltips when adding / removing series?

I combined the [add-del-series](https://leeoniya.github.io/uPlot/demos/add-del-series.html) and [tooltips](https://leeoniya.github.io/uPlot/demos/tooltips.html) demos to the fiddle below in order to showcase the problem.
https://jsfiddle.net/oLcuyr6x/13

<img width="1302" alt="tooltips_for_added_series_not_showing" src="https://user-images.githubusercontent.com/11447903/147534212-ed83420c-23f1-4f53-b770-6acad0766c35.png">

**Comment by leeoniya** [comment]
hmm, i could add `addSeries` and `delSeries` hooks that can be used by plugins to update the state in their closures.

internally `addSeries()` just delegates to `initSeries()`, so i guess it would also fire during initial chart creation for each series, but i think that can be discerned from post-creation by checking `u.status` for `0` or `1`. :thinking: 

https://github.com/leeoniya/uPlot/blob/3ae0ff005d15b2361c7545b65757620687cbee52/src/uPlot.js#L934-L942

**Comment by gerhat** [comment]
@leeoniya hooks would be great! Thank you so much!

**Comment by leeoniya** [comment]
added in attached commit.

something like this seems to work: https://jsfiddle.net/jLngfxav/

**Comment by gerhat** [comment]
@leeoniya thank you for the fix and the fiddle. Will there be a new release to npm including these hooks?

I liked the `setLegend` suggestion, but I have to use `setCursor` because I need to change the `z-index` of the tooltip closest to the cursor so that it's not hidden when there are many curves with similar values.

**Comment by leeoniya** [comment]
> because I need to change the z-index of the tooltip closest to the cursor so that it's not hidden when there are many curves with similar values.

you should still be able to use `setLegend` via proximity-testing, just set `alpha: 1` and use `setSeries` hooks:

https://github.com/leeoniya/uPlot/blob/ca036c817701d47a94f1d1c7c1b443f77a5c0e52/demos/focus-cursor.html#L50-L57
