### ISSUE TITLE
axis borders

### ISSUE THREAD

**Issue by kpkalwa** [leeoniya/uPlot#643]
The axis line not drawn when using two different line chart on same chart. One to represent on left other one on right.
The right axis line is not drawn only tick marks for the values are present as shown in screenshot below
![image](https://user-images.githubusercontent.com/10389768/147925302-e0af7e38-7796-4182-b90c-c72881eab3be.png)

**Comment by leeoniya** [comment]
are you asking about the hz gridlines that extend from the ticks or a vertical line at the axis edge?

uplot's axes don't draw lines at the edges. you can take a look at https://github.com/leeoniya/uPlot/issues/547 for some ways to do this. in addition to what's mentioned in that issue, uPlot now also adds `<div class="u-axis">` elements over each axis, so you can set set the css border style of these, too.

**Comment by kpkalwa** [comment]
No looking for the vertical line on other side of the axes for multiple axis chart

**Comment by kpkalwa** [comment]
The pull request with the axis border has been raised. Review and close the enhancement if the properties is added as per library standards

**Comment by leeoniya** [comment]
this is now implemented. i ended up rendering the borders on canvas to match the rest of the axis drawing code.

axis borders are disabled by default, but you can enable them with `axis.border.show: true` and configure other options to control color, width, etc.
