### ISSUE TITLE
Synced key selection defaults to full-scale when below cursor.drag.dist threshold

### ISSUE THREAD

**Issue by Stinger-au** [leeoniya/uPlot#645]
I have an app with a navigation chart similar to your [Zoomranger XY demo](https://leeoniya.github.io/uPlot/demos/zoom-ranger-xy.html) and the issue I have is actually present on this demo. When the drag threshold is not met (i.e. you have started a drag to zoom but are still too close to the mousedown location) the selection on the synced plot goes to fullscale. I would prefer this not to happen - ideally the selection should revert to the existing selection before the drag started. This would keep the selection visible as the indication of the current viewing window for the main plot.

What would the best way to get this functionality? Currently I sync my nav chart selection to match the main chart axes whenever I get a setScale hook event on my main chart, but I am not sure anything will fire when I get a invalid drag selection.

**Comment by leeoniya** [comment]
looks like this was regressed in 1.6.10 by https://github.com/leeoniya/uPlot/commit/4065fa98f036c3ba3882cc64c2d9ea741f0da72b.

i'll have to investigate further if this is something that should be fixed in the demo or in the lib.

**Comment by leeoniya** [comment]
should be fixed now. please try latest `master` and see if it works as you expect.

**Comment by Stinger-au** [comment]
Hi,

Can confirm it's fixed, thankyou - Although I had a hell of a time debugging what eventually turned out to be a caching issue :s
