### ISSUE TITLE
Browser Snap

### ISSUE THREAD

**Issue by kpkalwa** [leeoniya/uPlot#646]
I was using version 1.16.7 for over a 6 months. Due to the feature avalibility in 1.16.18 I upgraded it to the latest version. 

In latest version the browser gets snapped "**Error: Status_breakpoint**".

Tried loading by clearing cache and even disabled all the extensions then also browser gets snapped.

**Comment by leeoniya** [comment]
what do you expect me to do with a bug report like this?

what is the last version where it worked?

make a jsfiddle that.i can debug..

we can re-open once that's done.
