### ISSUE TITLE
Auto-zoom does not work for values < 1e-10

### ISSUE THREAD

**Issue by olivren** [leeoniya/uPlot#657]
I am using uPlot to plot physical measurements of nanocomponents. Some of the datasets I have are very close to zero, below 1e-10. I found that around this threshold, the auto-zoom (automatic calibration of the y axis) does not work as expected: the plot line is partially or completely outside of the view.

I also found that if I compute the min and max of the dataset, and force the y axis calibration (using `range`), the plot displays correctly. It's not an ideal workaround though, because I would like to benefit from the y axis automatically adjusting when I change the visibility of other plots.

Here is an example with my workaround, just comment the `auto` and `range` settings to see the bug.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>uPlot bugreport</title>
    <link rel="stylesheet" href="uPlot/dist/uPlot.min.css">
    <script src="uPlot/dist/uPlot.iife.min.js"></script>
  </head>
  <body>
    <script>

      const data = [
        [...Array(61).keys()],
        [-1.31869e-11, -2.33299e-11, -3.31166e-11, -3.50622e-11, -3.91018e-11, -4.20137e-11, -4.4046e-11, -4.54435e-11, -4.65222e-11, -4.76008e-11, -4.87424e-11, -5.00099e-11, -5.13403e-11, -5.26707e-11, -7.43758e-11, -9.90512e-11, -1.04559e-10, -1.06542e-10, -1.17462e-10, -1.37704e-10, -1.7234e-10, -2.13291e-10, -1.93946e-10, -1.48644e-10, -1.28916e-10, -1.10578e-10, -6.26766e-11, -1.43299e-11, 4.20336e-12, 2.27367e-11, 3.97575e-11, 5.37533e-11, 6.62366e-11, 7.87198e-11, 9.95956e-11, 1.01506e-10, 6.9279e-11, 2.34912e-11, -3.20078e-11, -1.17756e-10, -2.60386e-10, -3.25076e-10, -2.14502e-10, -1.08675e-10, -7.68983e-11, -4.82006e-11, -1.4627e-11, 9.6851e-12, 1.83201e-11, 2.69552e-11, 3.38127e-11, 3.71154e-11, 3.86405e-11, 4.01657e-11, 2.73136e-11, 4.95753e-12, -1.40212e-11, -3.59917e-11, -1.03545e-10, -1.99257e-10, -2.39149e-10]
      ];
      
      let min = Math.min(...data[1]);
      let max = Math.max(...data[1]);
      const span = max - min;
      min = min - 0.1 * span;
      max = max + 0.1 * span;
      
      const opts = {
        title: "My Chart",
        class: "my-chart",
        width: 800,
        height: 600,
        padding: [null, null, null, 30],
        scales: {
          x: {
            time: false,
          },
          y: {
            // Comment these 2 lines to enable auto-zoom
            auto: false,
            range: [min, max],
          }
        },
        series: [
          {},
          {
            show: true,
            stroke: "red",
            value: (self, rawValue) => rawValue.toExponential(2),
          }
        ],
        axes: [
          {},
          {
            values: (self, ticks) => ticks.map(v => v.toExponential(2)),
          },
        ],
      };

      const uplot = new uPlot(opts, data, document.body);
    </script>    
  </body>
</html>
```

Also, thank you for uPlot! It allows me to generate self-contained html reports, by embedding uPlot on each report while still keeping them tiny. Awesome work!

**Comment by leeoniya** [comment]
there are definitely some safe-guards around extremely low and high values that prevent infinite loops due to numeric precision limits when [max-min < 1e-16](https://github.com/leeoniya/uPlot/blob/8125b7eacb00de5dd6759e27c661d3022e8b38b8/src/uPlot.js#L2021). i'll look into what specifically happens here, but until then i have a better work-around for you:

https://jsfiddle.net/mb2v90a5/

![image](https://user-images.githubusercontent.com/43234/152230481-f6d9e93d-860a-42e2-bbf7-2574c0829391.png)

```js
const data = [
  [...Array(61).keys()],
  [
    -1.31869e-11, -2.33299e-11, -3.31166e-11, -3.50622e-11, -3.91018e-11, -4.20137e-11, -4.4046e-11, -4.54435e-11,
    -4.65222e-11, -4.76008e-11, -4.87424e-11, -5.00099e-11, -5.13403e-11, -5.26707e-11, -7.43758e-11, -9.90512e-11,
    -1.04559e-10, -1.06542e-10, -1.17462e-10, -1.37704e-10, -1.7234e-10, -2.13291e-10, -1.93946e-10, -1.48644e-10,
    -1.28916e-10, -1.10578e-10, -6.26766e-11, -1.43299e-11, 4.20336e-12, 2.27367e-11, 3.97575e-11, 5.37533e-11,
    6.62366e-11, 7.87198e-11, 9.95956e-11, 1.01506e-10, 6.9279e-11, 2.34912e-11, -3.20078e-11, -1.17756e-10,
    -2.60386e-10, -3.25076e-10, -2.14502e-10, -1.08675e-10, -7.68983e-11, -4.82006e-11, -1.4627e-11, 9.6851e-12,
    1.83201e-11, 2.69552e-11, 3.38127e-11, 3.71154e-11, 3.86405e-11, 4.01657e-11, 2.73136e-11, 4.95753e-12,
    -1.40212e-11, -3.59917e-11, -1.03545e-10, -1.99257e-10, -2.39149e-10,
  ],
];

let mult = 1e10;

data[1] = data[1].map((v) => v * mult);

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
  },
  axes: [
    {},
    {
      values: (u, splits) => splits.map((v) => (v / mult).toExponential()),
    },
  ],
  series: [
    {},
    {
      label: 'input points',
      stroke: 'red',
      value: (u, v) => (v / mult).toExponential(),
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

**Comment by olivren** [comment]
Thanks. I thought about such workaround, but I am not comfortable fiddling with the values like this. I know the users who look at the reports expect to see precise values, and this multiplication and division roundtrip will introduce some imprecision. I was even asked to add an option to let the user see the raw data values instead of the shorter exponential display.

If I use a modified version of uPlot that removes this 1e-16 safe guard, what problem can I expect?

**Comment by leeoniya** [comment]
so, it's actually falling into here:

https://github.com/leeoniya/uPlot/blob/8125b7eacb00de5dd6759e27c661d3022e8b38b8/src/utils.js#L213

this was added to avoid situations where you have flat data but due to rounding errors you may end up with

```
1,
1,
1,
0.99999999999999999,
1,
1.00000000000000001,
```

without the this safeguard you'd get a graph that has a range of 0.99999999999999999 - 1.00000000000000001 instead of something more sane, like 0 - 2.

an easy work-around is to just implement your own `scale.range`, but functional rather than static like in your example.

```js
const data = [
  [...Array(61).keys()],
  [
    -1.31869e-11, -2.33299e-11, -3.31166e-11, -3.50622e-11, -3.91018e-11, -4.20137e-11, -4.4046e-11, -4.54435e-11,
    -4.65222e-11, -4.76008e-11, -4.87424e-11, -5.00099e-11, -5.13403e-11, -5.26707e-11, -7.43758e-11, -9.90512e-11,
    -1.04559e-10, -1.06542e-10, -1.17462e-10, -1.37704e-10, -1.7234e-10, -2.13291e-10, -1.93946e-10, -1.48644e-10,
    -1.28916e-10, -1.10578e-10, -6.26766e-11, -1.43299e-11, 4.20336e-12, 2.27367e-11, 3.97575e-11, 5.37533e-11,
    6.62366e-11, 7.87198e-11, 9.95956e-11, 1.01506e-10, 6.9279e-11, 2.34912e-11, -3.20078e-11, -1.17756e-10,
    -2.60386e-10, -3.25076e-10, -2.14502e-10, -1.08675e-10, -7.68983e-11, -4.82006e-11, -1.4627e-11, 9.6851e-12,
    1.83201e-11, 2.69552e-11, 3.38127e-11, 3.71154e-11, 3.86405e-11, 4.01657e-11, 2.73136e-11, 4.95753e-12,
    -1.40212e-11, -3.59917e-11, -1.03545e-10, -1.99257e-10, -2.39149e-10,
  ],
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
    y: {
      range: (u, dataMin, dataMax) => {
        let delta = dataMax - dataMin;
        let yPad = delta * 0.1;
        return [dataMin - yPad, dataMax + yPad];
      },
    },
  },
  axes: [
    {},
    {
      values: (u, splits) => splits.map((v) => v.toExponential()),
    },
  ],
  series: [
    {},
    {
      label: 'input points',
      stroke: 'red',
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

since this is the first time someone has opened an issue about it, i'm going to assume that this case is fairly atypical and leave the behavior in place, though it would be useful to expose control over this guard value in the `uPlot.rangeNum()` util function and in the `scale.range` config object.

> I know the users who look at the reports expect to see precise values, and this multiplication and division roundtrip will introduce some imprecision. I was even asked to add an option to let the user see the raw data values instead of the shorter exponential display.

i can understand not wanting to have `.toExponential`, as this strips out way too much precision in many cases, but to insist on _exact_ values is a bit absurd when the variability of the data is 10x that of the raw values even when rendered via `.toPrecision(6)`. :shrug:

**Comment by olivren** [comment]
Your solution works like a charm! Thanks a lot!
