### ISSUE TITLE
event and api naming conventions

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#66]
> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

it would be good to outline some general conventions for uniformity, keeping in mind that i have an affinity for terse names. a two-letter prefix may work for general disambiguation / namespacing:

series - sr
scales - sc
axes - ax
legend - lg
label/title - lb
cursor - cr
annotation - an
point - pt
marker - mk
selection - sl
value - va

with this, a cursor move event would be `crmove` and series toggle would be `srtoggle`.

for the imperative API side, the current `.toggle()` would change to `srtoggle()`. a change that's against js conventions but more uniform would be `.setScale()` -> `.scset()`. however this would shorten possible future things like `.setCursor()` to `.crset()`, and could emit an event with a 1:1 name match.

thoughts?

cc @silverwind @jeancharles-roger @danyalejandro @alextarrell

**Comment by silverwind** [comment]
Can't say I'm a fan of those two-letter abbreviations, it would make me look up those in documentation all the time because I can't remember such things. I do agree some consistent casing is needed, either camelcase `cursorMove` or all lowercase `cursormove`. I think most if not all DOM events are in the latter format, so I guess I'd prefer that for event names. For configuration properties, I think my preference is to camelcase them all.

**Comment by leeoniya** [comment]
so i've been mulling this over and here's my current thinking.

i'd like to reduce the amount of API surface / methods, because this will be a never-ending expansion of methods that tweak one thing or another. instead, i want to try doing a declarative-type API that mimics the original opts instead of multiple args.

- `.setScale(key, {min: max:})` (instead of the current `.setScale(key, min , max)`)
- `.setSeries(i, {show: false, focus: true})` (instead of the current `.toggle()` and `.focus()` )
- `.setCursor({left, top})` (instead of the current `.moveCursor(left, top)` )
- `.setAxis(i, {...})`
- etc...

the events handlers (i'll probably rename them to `hooks`) will also lose some granularity. e.g. calling `.setCursor({left, top})` will result in all `setCursor: [(self, ..args) => {}]` hooks firing with `..args` being the original args passed to the method. to avoid creating new objects, if the hook is triggered implicitly rather than by external method call, then `...args` will include the matching mutable sub-state, e.g. `self.cursor`.

/brain dump

**Comment by leeoniya** [comment]
this is now done. take a look at the `tooltips.html` diff for API adjustments:

https://github.com/leeoniya/uPlot/commit/bb2a23aabf99724e806e717bbab07549dfca65b2#diff-726893fe0f5471adf7d2372e701101ff
