### ISSUE TITLE
setSeries is not called if cursor.focus.prox is not defined

### ISSUE THREAD

**Issue by tobemo** [leeoniya/uPlot#662]
I was trying to recreate [tooltips-closest.html](https://github.com/leeoniya/uPlot/blob/master/demos/tooltips-closest.html) to learn how to detect which data points are clicked. It seems that the hook `setSeries` can be used to detect what series is clicked on and the hook `setCursor`  can be used to detect the timestamp. 

`setCursor` works fine but `setSeries` only works when, in the plot options, `cursor.focus.prox` is defined.
Is this expected behaviour?

[Minimal working example](https://jsfiddle.net/yw8m679z/11/), currently this logs null for series_idx, uncomment lines 66-70 for it to work.

As a side note: Is this the best way to detect what data points are clicked? Clicking empty space also registers a click event, which can be handled easily enough but maybe there is another way?
#239 proposes another approach but at first glance it no longer works.

Thanks in advance

**Comment by leeoniya** [comment]
> setCursor works fine but setSeries only works when, in the plot options, cursor.focus.prox is defined. Is this expected behaviour?

yes, this is by design.

> https://github.com/leeoniya/uPlot/issues/239 proposes another approach but at first glance it no longer works.

if you read further down in that thread, you just need to adjust to use the new `u-` prefixed css classes, and it works fine:

https://jsfiddle.net/fxey3875/

**Comment by tobemo** [comment]
ok, thank you,

In case anyone stumbles upon this:
My mistake regarding #239 is that I did not implement **both** suggestions made by gerhat.
[Updated version.](https://jsfiddle.net/m0th2ypf/12/)
