### ISSUE TITLE
Not enough space for bars to render

### ISSUE THREAD

**Issue by whtrbit** [leeoniya/uPlot#663]
Hey Leon,
I am currently testing charts with `bars` paths strategy -> `bars {align: 0}` and `bars {align: 1}` from this [example](https://leeoniya.github.io/uPlot/demos/line-paths.html).
There is an issue with available space for the bars to render.
In case of `align: 0` the first and the last bar is splitted in half.
![image](https://user-images.githubusercontent.com/3809903/154698489-8f7e98a3-4b54-44f8-808a-f336399d9a77.png)
In case of `align: 1` is even worse because the last bar is not shown at all.
![image](https://user-images.githubusercontent.com/3809903/154699275-9251d91b-49dd-4443-839e-cf6660f67172.png)

Is there a way to make all the bars fit the plot?

**Comment by leeoniya** [comment]
> Is there a way to make all the bars fit the plot?

you'll have to manually expand the x scale range by some amount.

the pathBuilders are simply rendering styles and do not and cannot affect the scales in any way. when you have time along x, the bar widths are meaningless (in one view they can be 27h wide and when zoomed in they will be 5s wide, and you can pass options to manually customize their pixel widths), only their _positions_ mean something.

when you have bars that are categorical, i have a demo for that: https://leeoniya.github.io/uPlot/demos/multi-bars.html

you can see the range expansion being done by a wrapper that also handles the bar distribution and sizing logic:

https://github.com/leeoniya/uPlot/blob/fe14dfd907db8d50c108f048b89eadf1fb0d8ff4/demos/grouped-bars.js#L215-L234

**Comment by whtrbit** [comment]
Thanks for the tips!
In the end, I've decided to expand the plot by adding `null` data points at the beginning and the end of data series.
For time, I've reduced first time point by 23:59:59 and extended the last one with 23:59:59 which works fine for both my aggregations -> daily, and monthly.
