### ISSUE TITLE
Is it possible to move a plot to a different element?

### ISSUE THREAD

**Issue by tobemo** [leeoniya/uPlot#664]
I would like to have setup where there is one large main plot and multiple smaller subplots. The smaller subplots show different datasets and the larger main plot facilitates analysis. The behavior I'm looking for is that by clicking a subplot it gets 'copied' to the main plot.

Right now the best I've come up with is to first destroy the main plot, once a subplot is clicked, and then call the uPlot constructor again but this time with a different html element.

I noticed that the constructor can accept a function as the target. Could this somehow be used?

Thanks in advance

**Comment by leeoniya** [comment]
> Right now the best I've come up with is to first destroy the main plot, once a subplot is clicked, and then call the uPlot constructor again but this time with a different html element.

that's how i would do it for 99% of cases. destroy & re-create is the most straightforward solution.

> but this time with a different html element.

why a different element? wouldn't you use the same element each time?

i assume you're doing

```js
let mainDiv = document.getElementById("main_plot");

let mainPlot = new uPlot(opts, data, mainDiv);

// then onclick
mainPlot.destroy();
mainPlot = new uPlot(newOpts, newData, mainDiv)`
```

**Comment by tobemo** [comment]
> why a different element? wouldn't you use the same element each time?
Yes, my bad, I meant a new data set.

Thanks for your help and thanks for this library!
