### ISSUE TITLE
Incorrect use of method of a class

### ISSUE THREAD

**Issue by c-smile** [leeoniya/uPlot#665]
https://github.com/leeoniya/uPlot/blob/e0ddd8737e24912c967c86160e799f655998ad81/src/utils.js#L250

This construct
```
const fmtNum = new Intl.NumberFormat(navigator.language).format;
```
will lead to  `format()` method call with `null` as `this` and that is wrong.

**Comment by leeoniya** [comment]
i suppose it should be?

```js
const numFormatter = new Intl.NumberFormat(navigator.language);
export const fmtNum = numFormatter.format.bind(numFormatter);
```

**Comment by c-smile** [comment]
I would rather do it this way:
```JS
const numFormatter = new Intl.NumberFormat(navigator.language);
export const fmtNum = val => numFormatter.format(val);
```
format is a native method and may not support bind - that is a gray area of different JS implementations - better (more reliable) to do it as the above.

**Comment by leeoniya** [comment]
sounds good. feel free to PR, btw.
