### ISSUE TITLE
Cursor sync and manually setting scale

### ISSUE THREAD

**Issue by kpbieber** [leeoniya/uPlot#666]
I adapted the mousewheel zoom plugin to  be a panning plugin (wheelScrollPlugin), and have multiple graphs on one page that have the sync function enabled on their cursors. That sync works great for the built-in click/drag and doubleclick zoom behavior, but seems to miss my manual setScale action. I thought I remembered reading at one point that firing the setScale function manually may not actually fire associated hooks, and was wondering if this was expected behavior or not.

I am continuing to look in to it, because I think my understanding of the API may be out of date (I don't remember this SyncPubSub interface at all). Ultimately the behavior I want is that when I have graphs set on the same sync key, they should always have their x scales match. 

```
export function wheelScrollPlugin(opts) {
    let factor = opts?.factor || 3;

    let xMin, xMax, yMin, yMax, xRange, yRange;

    function clamp(nRange, nMin, nMax, fRange, fMin, fMax) {
        if (nRange > fRange) {
            nMin = fMin;
            nMax = fMax;
        }
        else if (nMin < fMin) {
            nMin = fMin;
            nMax = fMin + nRange;
        }
        else if (nMax > fMax) {
            nMax = fMax;
            nMin = fMax - nRange;
        }

        return [nMin, nMax];
    }

    return {
        hooks: {
            ready: u => {
                xMin = u.scales.x.min;
                xMax = u.scales.x.max;
                yMin = u.scales.y.min;
                yMax = u.scales.y.max;

                xRange = xMax - xMin;
                yRange = yMax - yMin;

                let over = u.over;
                let rect = over.getBoundingClientRect();

                // wheel drag pan
                over.addEventListener("mousedown", e => {
                    if (e.button == 1) {
                    //	plot.style.cursor = "move";
                        e.preventDefault();

                        let left0 = e.clientX;
                    //	let top0 = e.clientY;

                        let scXMin0 = u.scales.x.min;
                        let scXMax0 = u.scales.x.max;

                        let xUnitsPerPx = u.posToVal(1, 'x') - u.posToVal(0, 'x');

                        function onmove(e) {
                            e.preventDefault();

                            let left1 = e.clientX;
                        //	let top1 = e.clientY;

                            let dx = xUnitsPerPx * (left1 - left0);

                            u.setScale('x', {
                                min: scXMin0 - dx,
                                max: scXMax0 - dx,
                            });
                        }

                        function onup(e) {
                            document.removeEventListener("mousemove", onmove);
                            document.removeEventListener("mouseup", onup);
                        }

                        document.addEventListener("mousemove", onmove);
                        document.addEventListener("mouseup", onup);
                    }
                });

                // wheel scroll zoom
                over.addEventListener("wheel", e => {
                    e.preventDefault();
                    u.batch(() => {
                        var diff = (u.scales.x.max - u.scales.x.min) * factor*e.wheelDelta*.0001
                        u.setScale("x", {
                            min: u.scales.x.min+diff,
                            max:  u.scales.x.max+diff,
                        });

                        // u.setScale("y", {
                        //     min: nyMin,
                        //     max: nyMax,
                        // });
                    });
                });
            }
        }
    };
}

```

**Comment by leeoniya** [comment]
> I thought I remembered reading at one point that firing the setScale function manually may not actually fire associated hooks, and was wondering if this was expected behavior or not.

it should fire hooks on that instance, but it will not publish sync events to other instances. the reasoning for this is that manually-invoked API methods should be magic-free. it is often undesirable to always sync every manual API and then provide some additional way to opt of it. the assumption is that manual API calls can replicated on all instances if such a thing is needed. the `uPlot.sync` global registry is the way to iterate all other plot instances in the same-keyed sync group and do what you need to.

https://github.com/leeoniya/uPlot/blob/190134aa844cfa2a0c052e72501240efc6031ced/demos/sync-cursor.html#L87

**Comment by kpbieber** [comment]
Thank you as always, this is working great.
`over.addEventListener("wheel", e => {
                    e.preventDefault();
                   u.batch(()=>{
                    var diff = (u.scales.x.max - u.scales.x.min) * factor*e.wheelDelta*.0001
                    var range = {
                        min: u.scales.x.min+diff,
                        max:  u.scales.x.max+diff,
                    }
                    var plots = uPlot.sync(u.cursor.sync.key).plots
                    plots.forEach(p=>{
                        p.setScale("x",range )
                    })
                   })
                });`

**Comment by leeoniya** [comment]
```
                    plots.forEach(p=>{
                        p.setScale("x",range )
                    })
```

you may want to exclude self. `(p != u) && p.setScale("x", range );`
