### ISSUE TITLE
Any way to set the total height including legend?

### ISSUE THREAD

**Issue by gerhat** [leeoniya/uPlot#676]
Setting the `height` in options excludes the title and legend, as documented in [uPlot.d.ts](https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L345). Is there any way to include it?

**The issue**
I am trying to fit uPlot (and the legend) in a resizable container but since I cannot know the height of the legend until rendered, I am using the `draw` hook to get notified about the legend height when drawing completes. Once the `draw` hook is fired, I am setting the new `height` to uPlot which causes the `draw` hook to get called again. In certain zoom levels I am getting into an infinite loop.

Can you think of any way to avoid this?

Ideally, I would like to set the height of the container to uPlot and have the library decide how to size its internal components (canvas, title, legend).

**Comment by leeoniya** [comment]
> Can you think of any way to avoid this?

you can set up a ResizeObserver during init that watches for title and legend changes, and adjusts the plot dims using `u.setSize()`:

https://jsfiddle.net/52upwLnz/2/

```js
const opts = {
  title: "Foo",
  width: 600,
  height: 300,
  scales: {
    x: {
      time: false,
    },
  },
  series: [
    {},
    {
      stroke: "red",
    },
    {
      stroke: "blue",
    },
  ],
};

const bootDom = (u, init) => {
  let adjHeight = opts.height;

  const myObserver = new ResizeObserver(entries => {
    for (let entry of entries)
      adjHeight -= Math.floor(entry.contentRect.height);

    u.setSize({ width: opts.width, height: adjHeight });
  });

  const extras = u.root.querySelectorAll('.u-legend, .u-title');

  extras.forEach(box => {
    myObserver.observe(box);
  });

  document.body.appendChild(u.root);
  init();
};

let data = [
  [0, 1, 2],
  [35, 71, 20],
  [90, 15, 70]
];

let u = new uPlot(opts, data, bootDom);
```
