### ISSUE TITLE
Pass instance as first argument to callbacks

### ISSUE THREAD

**Issue by silverwind** [leeoniya/uPlot#68]
I generally don't like dealing with `this`. Mainly because of its interaction with arrow/non-arrow functions and secondly because tooling like linters can not statically determine which functions are bound and which are not, so they can not warn on a unused `this`.

Would it make sense to instead pass the current instance as the first argument to all callbacks? E.g. `(uPlot, left, right, idx)` for `cursormove` for example.

**Comment by leeoniya** [comment]
agreed.

**Comment by leeoniya** [comment]
i made this change for init() and event listeners.

not sure if the same should be done for all callbacks accepted in the opts like `value`, `values`, `ticks` and `space`. probably?

**Comment by silverwind** [comment]
I'm leaning towards having it everywhere for consistency, even thought it does make the examples a bit longer, so 

```js
value: rawValue => rawValue.toFixed(2) + "MB",
```

would become

```js
value: (uPlot, rawValue) => rawValue.toFixed(2) + "MB",
```

**Comment by alextarrell** [comment]
Could it be the last parameter instead? I feel that's somewhat more commonplace in JS-land and would also not be a breaking change.

**Comment by leeoniya** [comment]
@alextarrell 

> Could it be the last parameter instead?

this requires a high degree of confidence that function signatures are perfect and makes it impossible to non-awkwardly add more params to the existing methods without breaking changes.

> I feel that's somewhat more commonplace in JS-land

i don't feel this way at all. do you have some examples of popular libs that do this?

> and would also not be a breaking change.

before v1.0, every commit can be breaking; i don't make the rules, but someone smart did :rofl:

**Comment by alextarrell** [comment]
Ah seems most of the examples I had in mind were for passing a custom this into the callback, not within the callback itself. You raise all valid points and I have no interest to argue them. I'm just happy this library exists at all. It's the only one I've found that can handle what I'm throwing at it data-wise and for that I'm thankful.

**Comment by leeoniya** [comment]
this is now done with the exception of `.tzDate` - i'll probably leave it as-is, since it's sufficiently different from other function-taking opts and hooks.

what ultimately convinced me was building out https://leeoniya.github.io/uPlot/demos/pad-scale.html
