### ISSUE TITLE
uplot.setSeries(null, {show: true}) doesn't work

### ISSUE THREAD

**Issue by zefirka** [leeoniya/uPlot#680]
Hi @leeoniya 

According [to this typings](https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L82-L84) next code should work

```js
uplot.setSeries(null, {show: true})
```

as well as `uplot.setSeries(null, {focus: true})`. But if we [see at the implementation](https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L2150-L2151), we can find that it will not work (cuz of `s` will be `undefined`). 

So is it a bug, or the wrong typing? If it's a bug, I can try to fix it.

**Comment by leeoniya** [comment]
should be fixed, now. try it out.

**Comment by zefirka** [comment]
Yep, it works. Can you publish plz?

**Comment by leeoniya** [comment]
want to track down and fix this one first: https://github.com/leeoniya/uPlot/issues/683
