### ISSUE TITLE
image as X axis caption

### ISSUE THREAD

**Issue by tmueller** [leeoniya/uPlot#685]
Hi leeoniya,

thanks for providing such a great chart library 👍 

Is it possible to place images on the x axis values instead of strings? Maybe even inline HTML? Or is there a programmatical way to do so?

**Comment by leeoniya** [comment]
you can definitely draw whatever you need to on the uplot `<canvas>` yourself by using the cached `axis._splits`. do you have an example picture of what you're looking to achieve?

**Comment by tmueller** [comment]
Thanks for answering. I'm trying to achive something similar to this:
![uPlot](https://user-images.githubusercontent.com/177675/162970451-11ab72b9-9264-4e39-bbcb-7ffd0df13f27.png)

Cannot really find `axis._splits`. Any hints where to look?

**Comment by leeoniya** [comment]
maybe something like this if you want to use the DOM: https://jsfiddle.net/0qkL9y6x/

you can instead use `u.ctx` inside the `drawAxes` hook to draw on the canvas and simply omit the `drawClear` hook since everything will be cleared automatically. it's probably more efficient to do this, since you're not creating and destroying dom elements each time.

![image](https://user-images.githubusercontent.com/43234/163054782-74dbd195-c651-415b-8582-ed4628380539.png)

```js
let data = [
  [0, 100, 200, 300, 400],
  [7, 8, 9, 10, 11]
];

let opts = {
  width: 600,
  height: 300,
  scales: {
    x: {
      time: false,
    }
  },
  axes: [
    {
      // disable tick value rendering
      values: () => [],
    }
  ],
  series: [
    {},
    {
      stroke: "red",
    }
  ],
  hooks: {
    drawClear: [
      u => {
        // remove all axis marks
        let xAxisBox = u.root.querySelectorAll('.u-axis')[0];
        xAxisBox.textContent = "";
      }
    ],
    drawAxes: [
      u => {
        let xAxisBox = u.root.querySelectorAll('.u-axis')[0];
        let xSplits = u.axes[0]._splits;

        xSplits.forEach(split => {
          let mark = document.createElement("div");
          mark.classList.add('axis-mark');
          mark.style.left = `${u.valToPos(split, 'x')}px`;
          xAxisBox.appendChild(mark);
        });
      }
    ]
  }
};

let u = new uPlot(opts, data, document.body);
```

```css
.axis-mark {
  border-radius: 50%;
  width: 30px;
  height: 30px;
  background: pink;
  position: absolute;
  transform: translateX(-50%);
  opacity: 0.5;
}
```

**Comment by tmueller** [comment]
Thanks a million. Will try and report back.

**Comment by leeoniya** [comment]
btw, if you're drawing on canvas you want to use `u.valToPos(split, 'x', true)`. the `true` part will return properly scaled and offset canvas coords instead of dom/css coords.

**Comment by tmueller** [comment]
Went for the DOM strategy. Works really well, thanks for providing a solution :)

![uPlot](https://user-images.githubusercontent.com/177675/163063119-8d47a480-5061-456c-bf8a-3f0e0834c6ce.png)
