### ISSUE TITLE
Line segment missing after the tables join

### ISSUE THREAD

**Issue by jkmnt** [leeoniya/uPlot#686]
I've tried to plot two series with non-aligned x'es and joined them with uPlot.join to produce
combined data object. There are nulls present in data and they are significant, so spanGaps: true.
One point (with undefined value, produced by join) remain disconnected from it's finite neighbours.

There is the minimum code to reproduce the problem (just the single serie).
IMHO the the points 3 and 5 (vals 30, 40) should be connected but they not.

uPlot 1.16.9 release.

```js
let data = [
    [42000,71999,77999,78000,79800,92400,98400],
    [10,20, null,30, undefined,40, undefined]
];

let opts = {
    title: "My Chart",
    id: "chart1",
    class: "my-chart",
    width: 1400,
    height: 600,
    scales: {
        x: {
            time: false,
        }
    },
    series: [
        {},
        {
            show: true,
            spanGaps: false,
            stroke: "red",
        }
    ]
};
```

**Comment by jkmnt** [comment]
changing the data[0][3] to the 78033 (was 78000) makes the segment visible as expected.
_some 32 elements buckets ?_

**Comment by leeoniya** [comment]
fiddle: https://jsfiddle.net/fd2o8urz/

> changing the data[0][3] to the 78033 (was 78000) makes the segment visible as expected. some 32 elements buckets or bitmaps?

this looks like a bug in the intertwined decimation & gap detection logic. maybe something here:

https://github.com/leeoniya/uPlot/blob/5815eba9774eb7ec1c869869d0313d3abcb8e150/src/paths/linear.js#L76

the wrapping check `if (x == accX) {` makes sure we're still accumulating in/min/max/out for the same x pixel, which is likely true for the `77999,78000` case but false for `77999,78033` case.

coincidentally, i was gonna experiment with decoupling the decimation and pathbuilding from gap detection in https://github.com/leeoniya/uPlot/issues/684 to make bugs like this easier to reason about. i'll try to take a closer look at this soon.

**Comment by leeoniya** [comment]
as a work-around you might want to first quantize the x values of all your series to multiples of 100.

**Comment by jkmnt** [comment]
thank you, the workaround works. my x'ses are in fact are time seconds and flooring them to the minute is acceptable.
