### ISSUE TITLE
Using y-axis splits/values to Map y-axis labels

### ISSUE THREAD

**Issue by dbii** [leeoniya/uPlot#687]
I have old code that did mapped y-axis values using split/values to an alternate version (like mapping things from 0.25 and 0.5 to 1/4" and 1/2") under version 1.0.9 of uPlot that you helped with about 2 years ago: https://jsfiddle.net/0e2xtpwv/4/ (which is broken, since the JS/CSS uplot versions are out of date, but I can map to my saved version if you want).

I am upgrading to the current uPlot, and have upgraded most of the code (e.g. mainly tooltips, switching from the old legendAsTooltipPlugin to tooltipPlugin) but splits/values for the y-axis fail. Part of it is that axes.split => axes.splits sometime in th past, but when I do that the y-axis labels blow up. I looked for an example of the current way to do this, but couldn't find one. I have forked the original jsfiddle and updated it so you can see what it has (note the tooltip mapping is slightly off so the y-value in it is off a little, but you can see the y-axis is really off, and disappears if you change split to splits for the y-axis).

https://jsfiddle.net/sfdzLgex/11/

**Comment by leeoniya** [comment]
hey @dbii 

a few things have been tweaked. the `axis.splits` signature is a bit different. (it's also plural "s", not singular "split"):

```js
      splits: (u, axisIdx, scaleMin, scaleMax) => {
      	// filter splits to visible y-scale range
        return ySplits.filter(s => s >= scaleMin && s <= scaleMax);
      },
```

the format of `axis.values` for time formatting is also different:

https://github.com/leeoniya/uPlot/blob/02100dd02819d02dc477e5c5fbc2cfa75b1bd53e/docs/README.md?plain=1#L359-L368

i think the rest is mostly the same.

here's what it looks like with the `axis.splits` update:

https://jsfiddle.net/se4d50xh/1/
