### ISSUE TITLE
`cursormove` firing on all synced charts

### ISSUE THREAD

**Issue by silverwind** [leeoniya/uPlot#69]
https://codesandbox.io/s/uplot-sync-cursormove-0nw2y

In this example, I have synced two charts and registered `cursormove`. It fires two times, once for each chart, resulting in my toolltip positioned on the last initialized chart while the mouse cursor is actually over the left chart in this example:

<img width="272" src="https://user-images.githubusercontent.com/115237/70379925-f6a11600-1933-11ea-8eb7-757ecd70c356.png">

While it's technically correct that the uPlot cursor did move on all charts, I'd like to either restrict the callbacks to only the chart where the mouse cursor is currently over or alternatively identify the currently hovered chart. Any suggestions?

(The demo seems to be a bit wonky, if it does not work, try editing and saving it)

**Comment by leeoniya** [comment]
can you please move over to using jsFiddle or Codepen, for the sake of my laptop's fans, and battery life. oh, and also so i don't need to repeatedly "try editing and saving it".

**Comment by silverwind** [comment]
JsFiddle: https://jsfiddle.net/1je5v483/3/

**Comment by leeoniya** [comment]
with deps in `<script>` tags: https://jsfiddle.net/m3ynozh1/

**Comment by silverwind** [comment]
One possible solution is to track the active plot via separate `mousemove`:

https://jsfiddle.net/silverwind/rekxsjpq/1/

Thought not totally happy with it because of the wasteful extra events, but otherwise acceptable I guess.

**Comment by leeoniya** [comment]
i'm trying to understand the use case where you have cursor sync but don't want the values displayed in the other plots (in which case you'd make separate opts and overlays for each instance).

are you just interested in syncing zoom & toggle?

i was considering adding `move:true/false` to the sync config but decided that move was always implicit `true`.

**Comment by leeoniya** [comment]
also, you can cheaply track activePlot on `mousenter` rather than `mousemove`.

**Comment by silverwind** [comment]
I have multiple side-by-side sparkline style chart and the intention is that the tooltip follows only the current chart. The syncing is more of a nicety so the highlight dot renders on the other charts too, totally not necessary.

So I guess you can leave this as-is. From a uPlot perspective, the cursor on the other charts *did* actually move, so I guess it is technically correct to fire it.

**Comment by leeoniya** [comment]
> While it's technically correct

you mean, the best kind of correct? 😉

**Comment by silverwind** [comment]
Did that, thanks: https://jsfiddle.net/silverwind/rekxsjpq/6/
