### ISSUE TITLE
get plotting area width in pixels

### ISSUE THREAD

**Issue by vinnitu** [leeoniya/uPlot#690]
hello

uplot.bbox.width - is float value, but how to get integer value? just use Math.trunc() or maybe exist more elegant ang properly method?

**Comment by leeoniya** [comment]
i cannot recall my own ancient wisdom why i round to the 0.5px -- it's more precise than either `Math.floor()` or `Math.ceil()`.

https://github.com/leeoniya/uPlot/blob/1b8d313deb745ea533630959e6ee3f9accc1b994/src/uPlot.js#L724-L727

it got added in a commit long ago that also did a bunch of other refactors: https://github.com/leeoniya/uPlot/commit/c224ce4935cbeacb3fe14b9d9e24cac9b7071796

`Math.trunc()` should be fine. do you have specific case when the float is problematic :thinking: ?

hilariously, i did not know this function existed and have always used `~~value` to do this :D

**Comment by vinnitu** [comment]
I want request decimated history data with actual width in pixels (bins).

**Comment by leeoniya** [comment]
:+1: makes sense
