### ISSUE TITLE
Fixed/sticky the position of the y-axis 

### ISSUE THREAD

**Issue by 13panda10** [leeoniya/uPlot#696]
<img width="182" alt="Screenshot 2022-05-18 084604" src="https://user-images.githubusercontent.com/37309415/168975083-ffcc1747-c62a-428f-a0aa-07eb2603cb47.png">

**Comment by 13panda10** [comment]
Hi, 

I am trying to implement the chart so that the y-axis remains fixed when scrolling horizontally to see all data within the y-values when in mobile responsive mode. Is this possible?

**Comment by leeoniya** [comment]
you'll want touch panning for mobile screens, like https://leeoniya.github.io/uPlot/demos/zoom-touch.html
