### ISSUE TITLE
properly embedding

### ISSUE THREAD

**Issue by vinnitu** [leeoniya/uPlot#697]
Glory to Ukraine!

I  want to properly embedding uplot to parent container.

What it the right way if we known width and height of parent?
And I need legend table under chart.

Help please.

**Comment by leeoniya** [comment]
> I want to properly embedding uplot to parent container.

the constructor accepts the container dom element, but height will only include canvas height, and exclude the legend and title height, so you may need to subtract.

a table legend example is here (see `series.values`): https://leeoniya.github.io/uPlot/demos/time-periods.html
