### ISSUE TITLE
Very slow rendering when chart width is less than 353

### ISSUE THREAD

**Issue by LimonSea** [leeoniya/uPlot#698]
here's a rendering of 100 lines with 361 points per line，when width is 352px:
![image](https://user-images.githubusercontent.com/45709930/169445740-1f07217d-4b8c-42b2-aac5-9215a7415a29.png)
![image](https://user-images.githubusercontent.com/45709930/169445529-20884abc-2dd7-4509-bcce-6866b5bbb509.png)
and when width is 353px:
![image](https://user-images.githubusercontent.com/45709930/169446038-295d5068-dd28-43c7-8d51-ed29b600a933.png)
![image](https://user-images.githubusercontent.com/45709930/169446056-a6ddb1e7-ef4c-4a84-9270-8c948c90a5a6.png)
Not sure what caused it, but such scenarios are very important to us, looking forward to your reply, thank you!

**Comment by leeoniya** [comment]
you have not provided enough information for me to help you.

the time ticks on your x axis do not look like anything uPlot will generate in its default config. i'm guessing it is some custom tick gen function that you have added.

please provide your exact config and your data.

**Comment by LimonSea** [comment]
> Thanks a lot for the reply, I have attached the demo. You can view it by modifying the width of line 36783 of App.js. However, the render time within the codesendbox is not obvious, but the somatosensory time is still different. 
Looking forward to your reply. Thank u.❤️
↓
https://codesandbox.io/s/uplot-demo-vc9fj3?file=/src/App.js

**Comment by leeoniya** [comment]
thanks. there is a lot going on in that code, so unfortunately i won't be able to tell you where the problem is. i copied your data and made a simple example with default options, which renders fast for me with 300px width: [100-line.zip](https://github.com/leeoniya/uPlot/files/8740421/100-line.zip). if you are able to reproduce the problem with a simple demo, then i can help investigate further.

![image](https://user-images.githubusercontent.com/43234/169535775-5c9a4011-606b-4f8e-b69f-6fde3ebbeb89.png)

**Comment by LimonSea** [comment]
> thanks. there is a lot going on in that code, so unfortunately i won't be able to tell you where the problem is. i copied your data and made a simple example with default options, which renders fast for me with 300px width: [100-line.zip](https://github.com/leeoniya/uPlot/files/8740421/100-line.zip). if you are able to reproduce the problem with a simple demo like the one i attached, then i can help investigate further.
> 
> ![image](https://user-images.githubusercontent.com/43234/169535775-5c9a4011-606b-4f8e-b69f-6fde3ebbeb89.png)

Thank you very much, I compared the options and found that when `ms` is not set, adding the following two options will cause this problem. 
`
fmtDate: () => uPlot.fmtDate('{HH}:{mm}:{ss}'),
tzDate: (ts) => new Date(ts),
`
![image](https://user-images.githubusercontent.com/45709930/170412174-85b4abf3-2583-4cf0-9ed9-344144a7315b.png)

Thanks for the demo that helped me find the solution! (*≧∪≦)
