### ISSUE TITLE
Error with single data point chart

### ISSUE THREAD

**Issue by silverwind** [leeoniya/uPlot#70]
Check this simple example: https://jsfiddle.net/silverwind/bafcx3qs/1/

It has two data points and works. Now change `data` to just `[[1575900426],[1]]` and uPlot throws an `m is undefined` error. Can this error be avoided in uPlot?

**Comment by leeoniya** [comment]
> Can this error be avoided in uPlot?

i guess an *error* could be avoided by simply drawing nothing but the grid and axes.

after #10 we can show a datapoint without the line.

either that or someone will need to show me a what a 1-point line chart looks like.

**Comment by silverwind** [comment]
I'd render a single pixel 😉. If that's too much work, a requirement for a minimum of 2 data points would also work with me.

**Comment by leeoniya** [comment]
i'll add it to the docs
