### ISSUE TITLE
1.6.20版本编译无法通过

### ISSUE THREAD

**Issue by chenmengyu** [leeoniya/uPlot#702]
在vue@2.5.2的vue-cli的项目中使用uplot@1.6.20。编辑报如下错误信息，我记得我几个月前使用还是正常的，于是我查看之前项目中的配置，发现使用的是uplot@1.6.19，于是我下载1.6.19版本，项目编译通过了。

in ./node_modules/uplot/dist/uPlot.esm.js

Module parse fa
iled: Unexpected token (160:17)
You may need an appropriate loader to handle this file type.
|
| const evOpts = {passive: true};
| const evOpts2 = {...evOpts, capture: true};
|
| function on(ev, el, cb, capt) {
[新建文本文档.txt](https://github.com/leeoniya/uPlot/files/8821912/default.txt)

**Comment by leeoniya** [comment]
Vue 2.5 was released in 2017, i don't actively support browsers and toolchains older than 1yr. you can try the links below.

https://github.com/vuejs/vue-cli/issues/4615

https://forum.vuejs.org/t/object-spread-operator-with-vue-cli/36651

https://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b
