### ISSUE TITLE
Weird line across the line chart

### ISSUE THREAD

**Issue by rem4ik4ever** [leeoniya/uPlot#703]
Hey there,

I'm running into a weird issue i'm not sure how to resolve. I have 2 time series and orange one is getting this weird bottom line across the chart. 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/3874496/171780033-d1390ddf-6552-4a37-b846-09f55610f0d7.png">

This is uplot running in react app. 

Any ideas what could be wrong?

**Comment by leeoniya** [comment]
probably out of order data? it needs to be sorted ascending by x.

**Comment by leeoniya** [comment]
![image](https://user-images.githubusercontent.com/43234/172313633-29606272-346a-4f2a-8326-4c048fd326fa.png)
