### ISSUE TITLE
Hide {year} from x-axis

### ISSUE THREAD

**Issue by alvinwoon** [leeoniya/uPlot#705]
Is there a way to hide the year overflowing from x-axis in the chart?

![image](https://user-images.githubusercontent.com/1026383/172847767-6ac77aae-c645-4da0-80a9-381424d06cd2.png)

**Comment by leeoniya** [comment]
if you dont need the charts to be zoomable, the easiest way to do it is to simply set `axis.values` to a static template string, like `{MM}/{DD}`, you'll also want to reduce `axis.size` to get rid if the extra padding reserved for year.

if you want to do something more complex, you'll have to provide a full formatting table for `axis.values` without the `\n{YYYY}` portions.

maybe helpful discussion: https://github.com/leeoniya/uPlot/issues/474

the full table is at the bottom of https://github.com/leeoniya/uPlot/tree/master/docs#axis--grid-opts

internally, it gets assembled here:

https://github.com/leeoniya/uPlot/blob/a8854465fe44248980a675656ca544823d4fd01c/src/opts.js#L136-L149
