### ISSUE TITLE
Unable to use `.setData` on typed arrays

### ISSUE THREAD

**Issue by ghostandthemachine** [leeoniya/uPlot#706]
We have been using the same version of uplot for a bit now and have just started seeing a new issue when using `setData`. We use typed arrays our data and now after calling `setData` with a typed array the uPlot instance seems to turn the data into an object. After going through with the debugger it appears to us that:

- The error begins in the call to `copy` from `setData` [here](https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L1072)
- The first iteration goes fine on the call to `copy` [here](https://github.com/leeoniya/uPlot/blob/a8854465fe44248980a675656ca544823d4fd01c/dist/uPlot.cjs.js#L537)
- Then on the second, recursive, iteration the `isArr` fails when the `o` value is the TypedArray [here](https://github.com/leeoniya/uPlot/blob/a8854465fe44248980a675656ca544823d4fd01c/dist/uPlot.cjs.js#L540)
- `isArr` is [just an alias](https://github.com/leeoniya/uPlot/blob/a8854465fe44248980a675656ca544823d4fd01c/dist/uPlot.cjs.js#L516) to `Array.isArray` 
- Which makes sense that it could fail because `Array.isArray(new Float32Array([0, 1, 2]))` is `false`

After some googling and stackoverflowing this seems to be the expected js behavior. I don't agree with it but here we are... We must have unintentionally been converting to standard arrays before b/c I don't see how calling `setData` could have worked otherwise. In any case, we'd really like to use our raw TypedArrays directly which I believe uPlot intends to support.

Is there something we should be doing differently to achieve this?

**Comment by leeoniya** [comment]
looks like i'll need to add handling for this in`copy()`.

will check out which of these methods is fastest: https://stackoverflow.com/questions/15251879/how-to-check-if-a-variable-is-a-typed-array-in-javascript

**Comment by leeoniya** [comment]
pushed a fix, try it out.

**Comment by ghostandthemachine** [comment]
Thank you @leeoniya! Will pull, test and give feedback

**Comment by rosejn** [comment]
While we're on this, might there be the possibility of having a no-copy option?  We specifically create immutable data arrays (without nils, as we've already interpolated for any missing values when querying from TimescaleDB) to hand to uPlot so this copy isn't even necessary.  I thought maybe we could just set uplot_obj.data, but there were some other internal vars (dataLen and data0 I think) that this bypasses so it didn't seem feasible as is.
