### ISSUE TITLE
Question: How to show grid only for existing data points?

### ISSUE THREAD

**Issue by alexey-milovidov** [leeoniya/uPlot#709]
If I have integer values of x: [1, 2, 3], how to prevent grid and ticks to be displayed for 1.25, 1.5, etc...?

**Comment by leeoniya** [comment]
you can provide your own array for `axis.incrs` that omits fractional divisors. something like `[1,2,5,10,20,25,50,...]`

the default one is generated here:

https://github.com/leeoniya/uPlot/blob/d3f5b59be236677ecb65ba280b73a786644ffe32/src/opts.js#L45-L58
