### ISSUE TITLE
Question: how to replace number formatter?

### ISSUE THREAD

**Issue by alexey-milovidov** [leeoniya/uPlot#710]
I want to use not a locale-default number formatter but something more custom.
For example, I want to display number 1234567890 as 1&thinsp;234&thinsp;567&thinsp;890 (with &thinsp).

**Comment by leeoniya** [comment]
`axis.values` is the setting that formats the raw tick values returned by `axis.splits`.

https://github.com/leeoniya/uPlot/blob/d3f5b59be236677ecb65ba280b73a786644ffe32/dist/uPlot.d.ts#L932

https://github.com/leeoniya/uPlot/blob/d3f5b59be236677ecb65ba280b73a786644ffe32/dist/uPlot.d.ts#L926

something like

```js
values: (u, splits) => splits.map(v => {
  // convert number to formatted string
  return v.toPrecision(3);
})
```
