### ISSUE TITLE
Possible to error correct historical data already plotted?

### ISSUE THREAD

**Issue by ty11111111** [leeoniya/uPlot#720]
My database updates once every minute for high quality data. Websocket is robust and realtime but not entirely 100% accurate.

If I'm updating the line chart with websocket feed, can I overwrite the historical data already plotted on the chart with data from my database if there is missing and/or incorrect data plotted? This historical data on chart updating would ideally occur as my database is updated once a minute.

**Comment by leeoniya** [comment]
i'm not sure what you mean. uPlot only accepts the full dataset, not incremental or partial. even if you stream data via websocket, it would be up to you to first accumulate and/or correct any incremental data before calling `u.setData()` with that full buffer.

**Comment by ty11111111** [comment]
Sure, I can see how I can call ws.onmessage() and nest nest the u.setData() per new ws message.

I found that websocket messages are not 100% reliable and accurate. That's why I set up a redundancy backup in my database that calls the api data slower than ws but highly accurate. 

So I can setdata() with newly received ws message and also correct previously plotted data with my database all in realtime without losing the chart?

This is one of the limitations of lightweight charts. If you add/update previous data, chart refreshes and .update()-ed data is lost.

**Comment by leeoniya** [comment]
> So I can setdata() with newly received ws message and also correct previously plotted data with my database all in realtime without losing the chart?

as mentioned above, `.setData()` always accepts the full data, if you need to append or correct prior data, you should do this in an external buffer prior to giving it to uPlot,
