### ISSUE TITLE
DOM warning

### ISSUE THREAD

**Issue by GitHubLionel** [leeoniya/uPlot#721]
Hi 

With almost all demos, I have a DOM warning : "Couleur attendue, mais « null » trouvé.". 
In English : "Colour expected but "null" found".
I try to find where is the cause of this message but with no success. It is when we add point, but where ?

Best regards,
Lionel

**Comment by leeoniya** [comment]
this is the first such report, and i cannot reproduce here.

you'll need to provide a lot more info about your env.

**Comment by GitHubLionel** [comment]
Hi,

Sorry, I am under Win7 with last Firefox.
The best demo to observe the warning is the stream data demo who add points continuously.
In the screenshot, you see the warning with the count is rising more and more (663 when I capture the screen, several thousand after one minute).
![DOM_Error](https://user-images.githubusercontent.com/73015867/180594725-11ec7d3f-1c55-4818-83b5-cf909072d04c.png)

**Comment by GitHubLionel** [comment]
Hi again, 
I found another precision : if you have only one graph, you don't have message. The problem come when you have several graphs in same time.

**Comment by leeoniya** [comment]
thanks, reproduced. will look into a fix soon.

**Comment by GitHubLionel** [comment]
Great, thank's
Lionel
