### ISSUE TITLE
How to differentiate click vs select (or dbl click) events.

### ISSUE THREAD

**Issue by lucianbaciu** [leeoniya/uPlot#723]
I have a normal chart, which select and zoom reset feature (dbl click). On simple click events, I'd like to disable the series that are close to the cursor. If I use u.root.addEventListener(), it will be called also on select and double click. Can I separate them?

Thank you!

**Comment by leeoniya** [comment]
i think you'll have to decide if you want to keep the double-click to reset zoom behavior or implement another or modified keybinding to do zoom reset. i'm not sure how you can nicely handle both click and doubleclick actions without some kind of timeouts/debouncing, though this can work too. there is a uPlot api `cursor.bind.*` [0][1] that allows you to override or proxy the default handlers. (disregard the `click` there; it's for the click event on the legend series, not a click in the plot area). the selection & zoom-in is hooked up with `mousedown`,`mousemove`, and `mouseup`, and the zoom reset is hooked up with `dblclick`.

i can help more if you decide what UI/UX route you'd prefer to take.

[0] https://leeoniya.github.io/uPlot/demos/cursor-bind.html
[1] https://github.com/leeoniya/uPlot/blob/f66eee24afdf29fc57da383f2d214db9483f49b5/dist/uPlot.d.ts#L430-L439

**Comment by lucian-baciu** [comment]
Thank you for the answer! For now I will put the feature on hold, or will use the right click instead. Thanks again!
