### ISSUE TITLE
Swith path to bar series

### ISSUE THREAD

**Issue by GitHubLionel** [leeoniya/uPlot#726]
Hi,

I often need to have bar and path series on the same plot and want to switch path to bar quickly. I know that there is a big plugin for bar but it  is complicated and to sophisticated for a basic drawing of bar. 
So I have added simple bar function in core, very small code but great feature :)
You only need two properties for the series :
- showAsBar : to switch path to bar
- fillBar : a colour if you want to fill the bar
Source and demo :
Code modified is bracketed with comment : /* ShowAsBar begin / and / ShowAsBar end */
[Bar.zip](https://github.com/leeoniya/uPlot/files/9200781/Bar.zip)
Best regards,
Lionel
The result : 
![bar](https://user-images.githubusercontent.com/73015867/181294351-2d6777a3-3ebb-44b1-83cc-5b431f674904.png)

**Comment by leeoniya** [comment]
> I often need to have bar and path series on the same plot and want to switch path to bar quickly. I know that there is a big plugin for bar but it is complicated and to sophisticated for a basic drawing of bar.

the bar demo that you might be referring to [1] is a very different type of chart, and is not intended for this case.

uPlot includes a bars path renderer, which you can see used here: https://leeoniya.github.io/uPlot/demos/line-paths.html

i am not entirely convinced that adding options to switch renderers on demand is a better solution that simply re-initializing the plot, but it's not difficult to accomplish this without any changes to the core, also:

https://jsfiddle.net/d6pkr3mn/1/

```js
let data = [
  [0, 1, 2, 3, 4, 5],
  [0, 1, 2, 3, 4, 5],
];

let linearBuilder = uPlot.paths.linear();
let barsBuilder = uPlot.paths.bars();

let asBars = false;

const opts = {
  width: 600,
  height: 200,
  scales: {
    x: {
      time: false,
    }
  },
  series: [{},
    {
      label: "Data 1",
      stroke: "blue",
      fill: "lightblue",
      paths: (...args) => asBars ? barsBuilder(...args) : linearBuilder(...args),
    },
  ],
};

let u = new uPlot(opts, data, document.body);

setInterval(() => {
  asBars = !asBars;
  u.redraw();
}, 1000);
```

[1] https://leeoniya.github.io/uPlot/demos/multi-bars.html

**Comment by GitHubLionel** [comment]
Hi,
Sorry, I did not understand the manipulation in the line path demo.
But this code is clear and do what I need.
This is just a suggestion, but it might be more intuitive if we simply have a property in the series that represent the path we want.
For example, the name could be : "pathtype". By default, it would be "linear" and we have choice between "linear", "bar", "spline", "cubic".
So we can change the representation simply by  change "pathtype" :)
`  series: [{},
    {
      label: "Data 1",
      stroke: "blue",
      fill: "lightblue",
      pathtype: "bar",
    },
  ]`
Best regards,
Lionel

**Comment by leeoniya** [comment]
each path builder also has different options which would need to be exposed on something like `pathOpts`. originally i wanted to keep the path builders separate so that they can be excluded in custom builds by simply commenting out these lines and re-compiling:

https://github.com/leeoniya/uPlot/blob/f66eee24afdf29fc57da383f2d214db9483f49b5/src/uPlot.js#L3098-L3102

i'm not sure there is a lot of value in having multiple ways of specifying path types, this is a very simple api:

```js
{
  label: "Data 1",
  stroke: "blue",
  fill: "lightblue",
  paths: uPlot.stepped({
    align: 1,
  })
},
```

**Comment by GitHubLionel** [comment]
Hi,
It's technical and for a simple user like me, go into the core code is not easy !
Maybe you can keep the 2 approaches : 
- modified the core and recompile
- have a series property paths with 2 fields : type and opts
{
  label: "Data 1",
  stroke: "blue",
  fill: "lightblue",
  paths: {
    "type": bar,
    "opts": { "align": 1, }
  }
},
