### ISSUE TITLE
Shared legend across uPlot charts

### ISSUE THREAD

**Issue by cabreraalex** [leeoniya/uPlot#729]
I have a set of uPlot charts with the same series people can interact with, but the legend is quite big and distracting to show for each one. It would be awesome if there could be one legend that shows the current selection of one chart, and changes as you hover on other charts. Is this possible with uPlot as is?

<img width="1179" alt="Screen Shot 2022-07-29 at 18 08 52" src="https://user-images.githubusercontent.com/4563691/181851822-09528ee7-b4c1-4cbc-8ce4-ec5a9dc0db0a.png">

**Comment by leeoniya** [comment]
no, it's not possible out of the box, but should be pretty easy to hook into uPlot's APIs to make a legend that works this way.

**Comment by cabreraalex** [comment]
I see, something like the tooltip example here to get the live selected data: https://github.com/leeoniya/uPlot/blob/master/demos/tooltips.html

Thanks a ton!

**Comment by leeoniya** [comment]
here's a quick hack that extracts all the legends and hides all but the one associated with the hovered plot. obviously would take more work to get cross-chart click toggling synced up, etc. but all generally do-able.

https://jsfiddle.net/uhp4Ld8a/3/

```css
.uplot:not(.faux) {
  display: inline-block;
}

.uplot.faux {
  width: 800px;
}

```

```js
let allLegends = document.createElement('div');
allLegends.classList.add('uplot', 'u-hz', 'faux');

const opts = {
  width: 400,
  height: 200,
  scales: {
    x: {
      time: false,
    }
  },
  series: [
    {},
    {
      label: "Data 1",
      stroke: "blue",
    },
    {
      label: "Data 2",
      stroke: "red",
    },
  ],
  hooks: {
    ready: [
      u => {
        let thisLegend = u.root.querySelector('.u-legend');
        allLegends.appendChild(thisLegend);

        u.over.addEventListener('mouseenter', e => {
          for (let legend of document.querySelectorAll('.u-legend')) {
            legend.style.display = legend === thisLegend ? "block" : "none";
          }
        });
      }
    ]
  }
};

let data = [
  [0, 1],
  [0, 1],
  [1, 0],
];

let u = new uPlot(opts, data, document.body);

let data2 = [
  [0, 1],
  [7, 13],
  [9, 11],
];

let u2 = new uPlot(opts, data2, document.body);

queueMicrotask(() => {
  document.body.appendChild(allLegends);
});
```

**Comment by cabreraalex** [comment]
Worked like a charm, thanks a ton! Hopefully this is helpful for people in the future:

<img width="1362" alt="Screen Shot 2022-08-08 at 08 33 46" src="https://user-images.githubusercontent.com/4563691/183418869-37dafd6d-a473-4863-bd84-7fb2d59f4b09.png">

**Comment by leeoniya** [comment]
there's a new `legend.mount` callback added in https://github.com/leeoniya/uPlot/commit/e028b3d694d300db3eb368a547763d7c8047d8db that might simplify this a bit: https://jsfiddle.net/bws0tjr2/1/

that commit also adds explicit legend DOM removal during `plot.destroy()` without assuming that it's a descendant of the plot root.
