### ISSUE TITLE
Unable to use addSeries and setData with mode: 2 data for scatter plot. [possible bug or incomplete implementation]

### ISSUE THREAD

**Issue by pthomaid** [leeoniya/uPlot#736]
I would like to have a scatter plot with buttons to add/delete series to the plot as in the jsfiddle below.
However, attempting to add a series using the corresponding button results in a script error within uPlot.

https://jsfiddle.net/oj4ruemy/

**Comment by kpkalwa** [comment]
Its the issue with mode 2 the value of facet is not synced for new series as default import assignment when you add new series through default addSeries function.

**Comment by leeoniya** [comment]
yes, likely an unintentional omission, will check it out over the weekend

**Comment by kpkalwa** [comment]
@leeoniya Thanks it resolved the issue
