### ISSUE TITLE
Doesn't show line when data includes extremely high peak

### ISSUE THREAD

**Issue by wjdwl002** [leeoniya/uPlot#737]
* Excuse me for English, not English mother tongue 😅

Hi, I'm developing a graph chart for monitoring some devices. My graph is to be monotonous most of time, but it occasionally includes extremely high or low error value due to the characteristics of devices.
My graph just doesn't show up when data includes extreme peak for just one second. It should at least show the rest values while the peak value doesnt have to show up 

Below is a graph when it's on normal state

![스크린샷 2022-08-11 오후 3 15 26](https://user-images.githubusercontent.com/72961728/184074657-d7f06582-8477-422a-9efa-d671558dcfc0.png)

Below is when i randomly inserted very high value. The whole graph just doesnt show up(while the point itself does). Also, when repeating zoom in and out, fixed max axis value just changes up to that peak value at some point.

![스크린샷 2022-08-11 오후 3 12 52](https://user-images.githubusercontent.com/72961728/184074649-4a8b9e6d-0c64-46c0-b61d-699df4ea0d42.png)
![스크린샷 2022-08-11 오후 3 12 58](https://user-images.githubusercontent.com/72961728/184074655-a756c337-525b-4234-88e5-f825c03e98b5.png)
![스크린샷 2022-08-11 오후 3 27 01](https://user-images.githubusercontent.com/72961728/184075864-8dd5dc4d-c924-4736-9883-a77801d96a30.png)

how to handle this kind of data?

**Comment by leeoniya** [comment]
this is a bug with Chrome's canvas2d implementation. i reported this issue a couple months ago but there has been no recent updates :(

https://bugs.chromium.org/p/chromium/issues/detail?id=1337313

you can work around this by using logarithmic scales (`distr: 3`) or pre-filtering your data.
