### ISSUE TITLE
Data stream chart loses its cursor hover value

### ISSUE THREAD

**Issue by rem4ik4ever** [leeoniya/uPlot#738]
Hey!
I'm using react-uplot and rendering continuous stream of data every 1 or 1/10 of a second. The issue I'm seeing is that hovering over the graph loses its label values and only shows when continue hovering, essentially not working when cursor is just placed on the graph. Expected behaviour is to see label values continue changing depending on where cursor is placed on the graph. 

Here is an example: 
https://user-images.githubusercontent.com/3874496/184164556-645c780b-6324-4a98-9303-f9bb25429fd4.mov

I wonder if anyone has any suggestions on how to achieve/fix that?

**Comment by leeoniya** [comment]
i do not maintain `react-uplot`, so if the following works for you, please open an issue in that repo.

https://leeoniya.github.io/uPlot/demos/stream-data.html
