### ISSUE TITLE
Inconsistent X-axis

### ISSUE THREAD

**Issue by kpkalwa** [leeoniya/uPlot#739]
HI @leeoniya 

I am using uplot in mode:2 

The x-axis ticks are formed at irregular intervals as shown in image below.
![image](https://user-images.githubusercontent.com/10389768/184652043-dfcc10ce-6187-4865-9fe6-945244033ba5.png)

Is there a way where i can enable only the days / hours in the x-axis if needed based on zoom the minutes and seconds kick into the action.

**Comment by leeoniya** [comment]
can you make a jsfiddle that results in the x ticks you're showing here? they look incorrect.

here's a mode: 2 fiddle that generates "nice" ticks: https://jsfiddle.net/mu52aqxr/

**Comment by kpkalwa** [comment]
@leeoniya 

I have made a js fiddle https://jsfiddle.net/x2djhspo/

Can you check when i add mode :2 the chart is not forming and even no error ? Not getting what exactly an issue is

**Comment by leeoniya** [comment]
> Can you check when i add mode :2 the chart is not forming and even no error ? Not getting what exactly an issue is

`mode: 2` is pretty different to `mode: 1` and scatter/unaligned datasets. none of the built-in pathBuilders are designed with scatter in mind, and expect ascending-x ordered data, though they can _technically_ render the dataset you're providing since it conforms to that mode: 1 requirement. i have pushed a commit in https://github.com/leeoniya/uPlot/commit/fe4cefc500e943813935811cf13d377713fcfe38 which makes this work. however, you will see other behavior in mode: 2 that is missing, like a different [rectangular] default zoom mode, and hover points disabled.

the data structure for mode: 2 is also different. instead of mode 1 `[x,y1,y2,y3]` it is `[null, [x1,y1], [x2,y2], [x3,y3]]`, since each dataset can be unordered and unaligned. there is no built-in hover detection, which requires a spatial index such as a quadtree, and you're usually expected to write your own pathBuilders. the demos which use mode: 2 do these things outside the core. i plan to integrate some of these ideas into uPlot v2, but this will not be soon. currently mode: 2 is mostly DIY.

also i see you're using `distr: 2` x scale. this will not work in `mode: 2` because ordinal scales cannot be used with scatter/unordered/unaligned data.

your data looks like mode: 1 data. do you have a specific reason why you're using `mode: 2` and `distr: 2`? your x ticks are inconsistent in the image above because `distr: 2` is a discontinuous scale, it will simply pull x labels from the data every 10th or 100th index and format them as time, so it will not be "nice".

https://jsfiddle.net/hkx6v2tz/2/

```js
let data = [
    null,
    [
        [
            1660107600417, 1660108955709, 1660111666293, 1660114376877, 1660117087461,
            1660119798045, 1660122508629, 1660125219213, 1660127929797, 1660130640381,
            1660133350965, 1660136061549, 1660138772133, 1660141482717, 1660144193301,
            1660146903885, 1660149614469, 1660152325053, 1660155035637, 1660157746221,
            1660160456805, 1660163167389, 1660165877973, 1660168588557, 1660171299141,
            1660174009725, 1660176720309, 1660179430893, 1660182141477, 1660184852061,
            1660187562645, 1660190273229, 1660192983813, 1660195694397, 1660198404981,
            1660201115565, 1660203826149, 1660206536733, 1660209247317, 1660211957901,
            1660214668485, 1660217379069, 1660220089653, 1660222800237, 1660225510821,
            1660228221405, 1660230931989, 1660233642573, 1660236353157, 1660239063741,
            1660241774325, 1660244484909, 1660247195493, 1660249906077, 1660252616661,
            1660255327245, 1660258037829, 1660260748413, 1660263458997, 1660266169581,
            1660268880165, 1660271590749, 1660274301333, 1660277011917, 1660279722501,
            1660282433085, 1660285143669, 1660287854253, 1660290564837, 1660293275421,
            1660295986005, 1660298696589, 1660301407173, 1660304117757, 1660306828341,
            1660309538925, 1660312249509, 1660314960093, 1660317670677, 1660320381261,
            1660323091845, 1660325802429, 1660328513013, 1660331223597, 1660333934181,
            1660336644765, 1660339355349, 1660342065933, 1660344776517, 1660347487101,
            1660350197685, 1660352908269, 1660355618853, 1660358329437, 1660361040021,
            1660363750605, 1660366461189, 1660369171773, 1660371882357, 1660374592941,
            1660377303525, 1660380014109, 1660382724693, 1660385435277, 1660388145861,
            1660390856445, 1660393567029, 1660396277613, 1660398988197, 1660401698781,
            1660404409365, 1660407119949, 1660409830533, 1660412541117, 1660415251701,
            1660417962285, 1660420672869, 1660423383453, 1660426094037, 1660428804621,
            1660431515205, 1660434225789, 1660436936373, 1660439646957, 1660442357541,
            1660445068125, 1660447778709, 1660450489293, 1660450489293, 1660451844585,
            1660457265753, 1660459976337, 1660462686921, 1660465397505, 1660468108089,
            1660470818673, 1660473529257, 1660476239841, 1660478950425, 1660481661009,
            1660484371593, 1660487082177, 1660489792761, 1660492503345, 1660495213929,
            1660497924513, 1660500635097, 1660503345681, 1660506056265, 1660508766849,
            1660511477433, 1660514188017, 1660516898601, 1660519609185, 1660522319769,
            1660525030353, 1660527740937, 1660530451521, 1660533162105, 1660535872689,
            1660538583273, 1660541293857, 1660544004441, 1660546715025, 1660549425609,
            1660552136193, 1660554846777, 1660557557361, 1660560267945, 1660562978529,
            1660565689113, 1660568399697, 1660571110281, 1660573820865, 1660576531449,
            1660579242033, 1660581952617, 1660584663201, 1660587373785, 1660590084369,
            1660592794953, 1660595505537, 1660598216121, 1660600926705, 1660603637289,
            1660606347873, 1660609058457, 1660611769041, 1660614479625, 1660617190209,
            1660619900793, 1660622611377, 1660625321961, 1660628032545, 1660630743129,
            1660633453713, 1660636164297, 1660638874881, 1660641585465, 1660644296049,
            1660647006633, 1660649717217, 1660652427801, 1660655138385, 1660657848969,
            1660660559553, 1660663270137, 1660665980721, 1660668691305, 1660671401889,
            1660674112473, 1660676823057, 1660679533641, 1660682244225, 1660684954809,
            1660687665393, 1660690375977, 1660693086561, 1660695797145, 1660698507729,
            1660701218313, 1660703928897, 1660706639481, 1660709350065, 1660712060649,
            1660714771233, 1660717481817, 1660720192401, 1660722902985, 1660725613569,
            1660728324153, 1660731034737, 1660733745321, 1660736455905, 1660739166489,
            1660741877073, 1660744587657, 1660747298241, 1660750008825, 1660752719409,
            1660755429993, 1660758140577, 1660760851161, 1660763561745, 1660766272329,
            1660768982913, 1660771693497, 1660774404081, 1660777114665, 1660779825249,
            1660782535833, 1660785246417, 1660787957001, 1660790667585, 1660793378169,
            1660793378169, 1660794733461,
        ],
        [
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91, -43.91,
            -43.91, -43.91, -43.91, -43.91, -43.91,
        ],
    ],
];

const opts = {
    mode: 2,
    ms: 1,
    width: 1200,
    height: 300,
    scales: {
        x: {
            //distr: 2,
        },
    },
    series: [
        {},
        {
            label: "xDwAdWobFtrPv",
            stroke: "#b4def2",
        },
    ],
};

let u = new uPlot(opts, data, document.body);
```

**Comment by kpkalwa** [comment]
The reason why i am using distr 2 is basically i want the Y axis to form at the first x point. See below in the chart
![image](https://user-images.githubusercontent.com/10389768/185411183-0e54eab4-8ee3-4cb8-adc6-655f96e7df66.png)

**Comment by leeoniya** [comment]
you are setting `distr 2` on the x scale in your fiddle. why would it affect the y scale? it would not make sense to have `distr: 2` on y axis anyways. if you want to control the y ticks, you should use y `scale.range`, and y `axis.splits`.

i don't understand what your final goal is so i cannot help you very well. but from your example data and images, you don't need `mode: 2` or `distr: 2`. :shrug:

**Comment by kpkalwa** [comment]
@leeoniya 

I am taking about the Initial Line along the Yaxis. THe one highlighted in Red should be formed by default if you see in the fiddle its not getting formed.

![image](https://user-images.githubusercontent.com/10389768/185651821-a44dabbc-1b49-4eaf-9a82-89cc7989e6f2.png)

https://jsfiddle.net/yfp93vaq/

**Comment by kpkalwa** [comment]
Can you reopen the issue ?

**Comment by leeoniya** [comment]
> I am taking about the Initial Line along the Yaxis. THe one highlighted in Red should be formed by default if you see in the fiddle its not getting formed.

ok, you should be able to get that working without `distr: 2` by overriding the default x:

`scale.range` - returns the min and max timestamps for the x axis
`axis.splits` - returns an array of timestamps where the ticks and gridlines should be drawn
`axis.values` - formats the raw splits array into the rendered tick labels

your range function will need to work out what "previous" time increment to snap to based on your data min/max and your desired splits density/increment.

**Comment by kpkalwa** [comment]
@leeoniya I have given min and max manually it did not worked see the fiddle
https://jsfiddle.net/peqrmo6y/1/
