### ISSUE TITLE
change opacity

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#740]
what is the best way to set opacity for the whole canvas? when the uplot drawings are overlapping with other parts, I am trying to find a way to increase or decrease the opacity of the uplot drawings on the fly. seems setAlpha is related, but didnt find a live sample on how to do that. thx

**Comment by leeoniya** [comment]
any reason not to just apply css `opacity` style to the canvas element or plot container?

**Comment by hz2018tv** [comment]
hmm. I tried changing the plot container opacity from 1.0 to 0.4 then to 0.0, the plot is still transparent, but washed out as the value decreases till disappeared with 0.0. it seems that the plot is always behind the container (z-index?). and the plots went along with the container when I dragged the container. 

also tried the u.ctx.globalAlpha one, but didnt seem to make a difference. maybe I didnt do it right. could you make one of your demos to show this? like adding +/- buttons where we can click to increase/decrease the opacity of the whole plot? 

Thx!

**Comment by leeoniya** [comment]
can you make an example image of what you're trying to accomplish? i don't really understand why css opacity does not work.

**Comment by hz2018tv** [comment]
the contain code is like this

<div id="chartdialog" title="chartinfo" style="opacity:1.0;background-color:#FFFFFF">
   <div id="chartlegendbar"></div>
   <div id="chartinfo"></div>
</div>
1.png is when opacity=1.0, and 2.png is opacity=0.4, and 3.png is opacity=0.0

when I drag the container, the plot goes with it, so I assume the container is above the numbers behind it. I want to find a way to increase / decrease the plot so the numbers behind it can be seen or hidden.

![1](https://user-images.githubusercontent.com/44717154/185762083-d8278fd3-31e4-4dae-9bbe-c854c039ee6c.png)
![2](https://user-images.githubusercontent.com/44717154/185762090-5130774a-2643-4bc5-8b4d-50cf4e80fff6.png)
![3](https://user-images.githubusercontent.com/44717154/185762096-2eef9360-9ba0-4125-b974-737b90fc1f6a.png)

**Comment by leeoniya** [comment]
the canvas has a transparent background. so any area that does not have bars drawn will not be affected by css opacity.

if you want the canvas background to be white you should be able to add `.uplot canvas { background: rgba(255,255,255,1); }` (or any < 1 alpha) to your styles and it will occlude everything behind it.

**Comment by hz2018tv** [comment]
adding .uplot canvas { background: rgba(255,255,255,1); } to style works !. how to set the opacity dynamically? I want to add +/- buttons to adjust it so that the numbers are shown as needed on the fly. thx

**Comment by leeoniya** [comment]
https://jsfiddle.net/8L7hk2q9/

```html
<button id="alpha_inc">opacity +</button>
<button id="alpha_dec">opacity -</button>
```

```css
body {
  background: pink;
}

.uplot canvas {
  background: white;
}
```

```js
let data = [
  [0, 1, 2, 3, 4, 5],
  [0, 1, 2, 3, 4, 5],
];

const opts = {
  width: 600,
  height: 200,
  scales: {
    x: {
      time: false,
    }
  },
  series: [
    {},
    {
      label: "Data 1",
      stroke: "blue",
      fill: "lightblue",
    },
  ],
};

let u = new uPlot(opts, data, document.body);

let opacity = 1;

document.querySelector("#alpha_inc").addEventListener('click', () => {
  if (opacity < 1)
    u.root.style.opacity = opacity += 0.2;
});

document.querySelector("#alpha_dec").addEventListener('click', () => {
  if (opacity > 0)
    u.root.style.opacity = opacity -= 0.2;
});
```
