### ISSUE TITLE
Dynamically Add Scale and Axis

### ISSUE THREAD

**Issue by MarvinSt** [leeoniya/uPlot#741]
I need to dynamically add new signals to the graph at runtime, this is working fine for a default y scale and axis, but I would like to be able to let the end user configure the min/max and top/bottom (in %) of each signal on the given plot. For this to work, I would need to be able to add a new axis and scale for each signal I add to the plot.

I.e. currently, I do the following to add new data:
`chart.setData(chart.data.push(signal.y))`

Likewise, I would like to be able to add a new scale, i.e. 
`chart.addScale(newkey, { ...scale settings... })`
`chart.addAxis({ ... axis settings... })`

Is there any method available to achieve this currently? Or would I need to re-generate the plot each time I am adding a new signal?

The objective is that if we for example have a signal with min/max set to -5/+5 and a top of 100% and bottom of 50%, the signal going from -5 to +5 will be mapped from 50% to 100% on the "normalised" graph. Yet, I need the axis of the signal to display the original range of -5 to +5.

**Comment by leeoniya** [comment]
> but I would like to be able to let the end user configure the min/max and top/bottom (in %) of each signal on the given plot

you'll have to re-init the plot for this. i was actually reluctant to even implement the addSeries() API, but what convinced me was that in a high frequency streaming scenario you can have 100 possible sensors but only 10 active ones report values every 100ms while others are silent, so you need to be able dynamically add/remove series without full re-init.

for cases like you're describing, when a human user needs to manually configure chart settings, it's simple and more than fast enough to just do a full re-init -- that's exactly what we do in Grafana. even on manual series visibility toggle when using Grafana's custom legend we don't bother using the `.setSeries({show: false})` APIs that uPlots native legend uses.

**Comment by MarvinSt** [comment]
Thanks for the insights, the addSeries API is indeed not of any use if more details need to be added to the plots. Regenerating the plot from scratch is fine as it happens occasionally indeed. So indeed, the problem is solved.
However, I may have another requirement in which it is maybe useful to update some settings dynamically without regenerating the graph. I’ll open a separate issue as it is not fully related.
