### ISSUE TITLE
Advanced Y-Shifted Series

### ISSUE THREAD

**Issue by MarvinSt** [leeoniya/uPlot#742]
For the project I am working on, I would need to plot various signals with different physical units (velocity, acceleration, rotational velocity, angles, etc), for visibility reasons these signals are y shifted. Each signal is shifted by the user cover a certain part of the plot specified by a top and bottom % and the scale is defined using min / max. If desired, (partial) overlap is also possible. I am able to calculate the “equivalent” ranges for a given top/bottom/min/max value set. However, this leads to the ticks being drawn beyond the region of interest and causes unnecessary overlap, so I would like to prevent the axes drawing beyond my min/max values and not extend the full height of the graph.
I’ve looked at the example of y shifted series, but my problem is slightly different.

I think the best solution in my case would be if there were a dedicated top/bottom parameters for the axis object. Would something like this be a possible extension for this library? It is a pretty common feature in data analysis tools in my industry and would make it a lot easier to realize what I’m looking for. 

Alternatively, is there a way to prevent the axes from drawing beyond certain values?

Thanks!

**Comment by MarvinSt** [comment]
Example of what I’m trying to accomplish:
![](http://www.virtualr.net/wp-content/gallery/2870/atlas-overlay.png)

**Comment by leeoniya** [comment]
first, allow me to propose an alternate solution: use multiple charts, combine the legend, and sync the cursor. this way you dont have to do all sorts of crazy shifting and scale math.

take a look at how the `Inverted Log10 Y Scale` demo is constructed using two plots: https://leeoniya.github.io/uPlot/demos/log-scales2.html. there's also a new `legend.mount` API on `master` that lets you detach the legend out of the plot container with fewer html hacking (and it will still get auto-removed on `u.destroy()`). https://github.com/leeoniya/uPlot/commit/e028b3d694d300db3eb368a547763d7c8047d8db, https://github.com/leeoniya/uPlot/issues/729#issuecomment-1218704150

if you still insist on doing Y shifting, you should be able to generate only the ticks you need using `axis.splits` or filter the drawn ticks/lines/tick-labels in `axis.filter`, `axis.grid.filter` and `axis.ticks.filter`.

**Comment by MarvinSt** [comment]
Yes, I understand it can be separated into different plots and that simplifies things, but this will not allow for (partial) overlap. It is not a big deal, but I was hoping to implement a workflow where a user can select a signal and move it up/down and scale it easily. In that case, having top/down attributes which can be updated on the fly with mouse drag events would be ideal.
