### ISSUE TITLE
tooltip: how can the tooltip be drawn when the plot is created?

### ISSUE THREAD

**Issue by tve** [leeoniya/uPlot#744]
I'm using an adapted version of the basic tooltip plugin and one of the difficulties I'm facing is that when the plot is drawn and the cursor happens to be in the plot area the tooltip is not drawn because no SetCursor callback is invoked. I tried to draw the tooltip using a draw or read callback but at that point u.cursor doesn't have useful information.

This situation can be observed in the basic tooltip demo: bring up the demo, observe the tooltip working, keep the cursor within the plot and refresh the browser using F5. The page gets redrawn, the cursor is within the plot, but the tooltip is not shown. You have to move the cursor for the tooltip to show.

The use-case is that in some cases I have to re-create the uPlot when new data arrives and that can happen relatively frequently and this causes the tooltip to disappear on data update which is not a good user experience. Is there a work-around?

**Comment by leeoniya** [comment]
this turned out to be a bit of a rabbit hole after my initial attempt at adding this to the tooltip demo didnt quite work as i expected. so had to make some changes to the core as well in the linked commit. (see updated demo)

**Comment by tve** [comment]
Thanks for the prompt fix! This does not address the situation where the cursor is inside the chart on initial draw, e.g., place cursor inside the demo chart and hit F5? I surmise there's no way to get the current cursor position in JS other than through an event when it moves?

**Comment by leeoniya** [comment]
> I surmise there's no way to get the current cursor position in JS other than through an event when it moves?

right, none that i've found at least.
