### ISSUE TITLE
Click events on line stroke not only points

### ISSUE THREAD

**Issue by Nouran96** [leeoniya/uPlot#745]
According to this issue #460 , you mentioned that there is a way using isPointInStroke canvas method.

Where should this work ? I tried to add this code into the ready hook but it always logs false
```
u.over.addEventListener("mousemove", (e) => {
	const rect = over.getBoundingClientRect();
	const isPointInStroke =
		u.ctx.isPointInStroke(
			e.offsetX,
			e.offsetY
		);
	console.log(isPointInStroke);
});
```
I tried to draw a custom line on the canvas in the draw hook, and with some calculations I managed to reach it. But the series lines are not reachable at all like they are in a different stack than that of the new drawn line.

**Comment by leeoniya** [comment]
you gotta grab the Path2D from the series cache ;)

https://jsfiddle.net/2u4sjybn/

```js
let data = [
  [0, 1],
  [0, 100],
];

const opts = {
  width: 800,
  height: 400,
  title: "Trendlines",
  scales: {
    x: {
      time: false,
    },
  },
  series: [
    {},
    {
      width: 3,
      label: "Data 1",
      stroke: "red",
      fill: "rgba(255,0,0,0.1)",
    },
  ],
  hooks: {
    init: [
      (u) => {
        let pxRatio = devicePixelRatio;

        u.over.addEventListener("mousemove", (e) => {
          let res = u.ctx.isPointInStroke(
            u.series[1]._paths.stroke,
            u.bbox.left + e.offsetX * pxRatio,
            u.bbox.top + e.offsetY * pxRatio
          );

          console.log(res);
        });
      },
    ],
  },
};

let u = new uPlot(opts, data, document.body);
```

**Comment by Nouran96** [comment]
@leeoniya Yeah that's great thanks. But Is there a way to make the series ID dynamic ? To trigger the setSeries or to know which series is the cursor on ?
