### ISSUE TITLE
Gaps function is not firing

### ISSUE THREAD

**Issue by jonachehilton** [leeoniya/uPlot#747]
Hello, I have a use case that is very similar to the `Insert gaps when adjacent points > delta` example in the [missing data demo](https://leeoniya.github.io/uPlot/demos/missing-data.html).

For testing purposes, I added the following gaps function to each of the series options:
```javascript
gaps: (u, seriesIdx, idx0, idx1, gaps) => {
  console.log('cannot see this in the console')
  return gaps
}
```

However, I am not seeing any logs in the console, which leads me to believe that the function is not firing. Is there something else I need to be doing?

Cheers

**Comment by leeoniya** [comment]
working okay for me: https://jsfiddle.net/76ubwsty/1/

**Comment by leeoniya** [comment]
closing for now, let's re-open once you have a jsfiddle that shows the issue.

**Comment by jonachehilton** [comment]
My apologies, I was using an older version of uPlot, which did not have the gaps functionality
