### ISSUE TITLE
zooming/scaling question

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#748]
img1:  the starting drawing
![Screenshot1](https://user-images.githubusercontent.com/44717154/188296832-2c729cf9-67c5-4564-81db-0f1c1783901f.png)
img2: the zoomed part after a segment is selected by mouse.
![Screenshot2](https://user-images.githubusercontent.com/44717154/188296777-68d54f2e-76fd-459f-9db6-6a854f5ef9dd.png)

what caused some of the drawings be cut off at the top? seems some y-axis scaling problem. thx

**Comment by leeoniya** [comment]
quite impossible to say with the limited info you've provided. please make a fiddle that shows the issue. example: https://jsfiddle.net/76ubwsty/1/

**Comment by leeoniya** [comment]
i'm only aware of line widths getting clipped at the edges of the scale range, which looks like maybe your first image (see below). i don't know what's going on in your second image, but i assume you're setting the scale range to be smaller than the y data limits in your view. we can re-open once you have simplified code that exhibits the issue.

https://jsfiddle.net/9krb5ncL/

![image](https://user-images.githubusercontent.com/43234/188688401-182e0362-633f-4fa6-8dd1-146d35806668.png)

```js
let data = [
  [0, 1, 2, 3],
  [0, 0, 1, 1],
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
    y: {
      range: [0, 1],
    }
  },
  series: [
    {},
    {
      width: 5,
      label: "Data 1",
      stroke: "red",
      fill: "rgba(255,0,0,0.1)",
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

**Comment by hz2018tv** [comment]
thanks. that part is integrated into a more complicated plugin. will definitely come back here once I can isolate it out.
