### ISSUE TITLE
Just Thanks

### ISSUE THREAD

**Issue by brendanmatkin** [leeoniya/uPlot#754]
No issue - just wanted to say this is my new favourite plot library. 

* SUPER fast - easily the fastest non webgl one I've used.
* Easy to use - as you mention, the docs are WIP. But even without super detailed docs it was still easier & faster to get a test of my data working than most of the other libs out there (with cute & fancy docs)
* No fluff - it just lets me plot my data cleanly and efficiently and leaves me in control of the rest. 

Nice work it's very appreciated! Small sponsorship sent.

**Comment by leeoniya** [comment]
thanks! glad it's working well for you :)
