### ISSUE TITLE
Set color on existing series

### ISSUE THREAD

**Issue by jmthomas** [leeoniya/uPlot#757]
Someone asked something similar in #182 but it looks like the implementation changed such that the only way is to delete and add the series. I can't really do this in my application because I'm streaming live data. I was hoping to do something like:

      this.graph.series[index].stroke = 'green'

Where of course `this.graph` is the reference to uPlot. This results in the error `s.stroke is not a function`. It's a little confusing to me because previously I was saving and restoring colors to my color list for use in future graph items.

**Comment by leeoniya** [comment]
for a stroke to be dynamic you can define it as a callback and your callback can return whatever it needs to on any redraw.

https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.d.ts#L728

**Comment by jmthomas** [comment]
Ok I was able to get this to work with something like the following:

        this.graph.addSeries(
          {
            stroke: (u, seriesIdx) => {
              return this.colors[this.colorIndex]
            },
          }

Where `this.colors` is an array of color names. However the legend color does not change. I thought they were linked?

**Comment by jmthomas** [comment]
I tried adding this to my chart options based on what I thought you were doing in the source but it had no effect:

        legend: {
          markers: {
            stroke: (u, seriesIdx) => {
              // let s = u.series[seriesIdx];
              return this.colors[this.colorIndex]
            },
          },
        },

**Comment by jmthomas** [comment]
@leeoniya That did the trick! I'm glad this was something more complex because my Javascript-fu isn't very high and I didn't want to waste your time.

I'll argue this came up in ticket #182 but yeah it's not probably typical. I just wanted to provide the ability to change the colors in the plot to suite user preferences.

Thanks so much for such an amazing library.

**Comment by leeoniya** [comment]
> I'll argue this came up in ticket https://github.com/leeoniya/uPlot/issues/182 but yeah it's not probably typical.

haha, oops :)

> I just wanted to provide the ability to change the colors in the plot to suit user preferences.

since this happens infrequently (typically only during config and not during actual operation), it's fast and easy to just `u.destroy()` and re-init the plot. this also covers all cases of config changes. we do this in Grafana and i'd recommend this route instead of trying to do anything more custom/imperative.

> Thanks so much for such an amazing library.

:+1:

**Comment by jmthomas** [comment]
I appreciate the help. Wouldn't `u.destroy()` remove the series and the stored data? I mean you could do this at initialization like you said but you'd lose anything currently on the plot correct? Or is there another way to rebuilt the plot while keeping the data and just redrawing / layout?

**Comment by leeoniya** [comment]
just keep the data externally in `this.data` and re-provide it when re-initializing the plot, right?
