### ISSUE TITLE
App crash with some axes range

### ISSUE THREAD

**Issue by Loori-R** [leeoniya/uPlot#760]
App crash with some axes range.
At first, I thought the problem was the number of decimal places, but it's not.
<br/>
Fox example:
```javascript
options = {
  ...otherOptions,
  scales: {
    y: {
      range: [99999999.99999996, 100000000.00000004] // not work
      // range: [0.9999996, 1.0000004] // work
      // range: [0.0009999999999999996, 0.0010000000000000005] // work
    }
  }
};
```
<br/>
Result:
<img width="400" src="https://user-images.githubusercontent.com/29711459/197722986-56284eda-4d8f-4d7f-a9c7-460f02fab562.png"/>

Reproduced in the example:
https://codesandbox.io/s/objective-dawn-37k0ex?file=/src/index.js

**Comment by leeoniya** [comment]
i think handling scenarios like this will be an endless game of whack-a-mole, these are all clearly float math errors. i'm not sure if uPlot should arbitrarily decide to round to some amount of decimal places to account for this. my current recommendation is to ensure your scale range isn't nonsense for your specific use case.

if you have a concrete proposal for how `[99999999.99999996, 100000000.00000004]` should work _generically_, i'm open to suggestions! how do we know it's a float error and not a real data range :shrug:? uPlot has some guards in its autoranger when dataMin == dataMax, but if you manually supply an invalid scale range (or infinitesimal one like this), there aren't any guards.

maybe useful:
https://github.com/leeoniya/uPlot/blob/4805a2e002e914ff7b6a67a4666b014ab67b49fd/src/utils.js#L306-L317

**Comment by Loori-R** [comment]
If range is not supplied manually, uPlot still stops working: https://codesandbox.io/s/hardcore-kare-xn0ve0?file=/src/index.js

uPlot stops working when drawing time series with small difference between time series values comparing to the average series value. E.g. if `abs(avg(values)) > (range.max - range.min) * 1e10`. 

I'm not sure how best to process this, but "Aw, Snap!" the page crashed - not the best option.
Perhaps, if there are no other ideas, it is worth throwing an exception and stopping processing.

**Comment by leeoniya** [comment]
the version in your sandbox is pretty ancient (1.6.13 is from Jun 16, 2021). the current `master` doesnt crash [1] since https://github.com/leeoniya/uPlot/commit/c801838d4611eec62a532b5b728c72ee8a5cf4d0, but that's not a fix, it's just incidental.

[1] https://jsfiddle.net/ntjhfeak/1/

**Comment by leeoniya** [comment]
fixed in linked commit for built-in auto ranger (there was already as-flat logic in there for tiny ranges < 1e-9).

you can still crash it by manually returning nonsense from a user-defined `scale.range` function, but i'm going to leave this as-is.
