### ISSUE TITLE
Time series data

### ISSUE THREAD

**Issue by kpkalwa** [leeoniya/uPlot#762]
I have a scenario where i need to plot the data for the 1 hour Let say from 11:00 AM to 12:00PM but the data in the system is only for 30 minutes assume till 11:30AM. But i need the x axis to be formed till 12:00PM with no points.

Currently the x axis is forming till 11:30 is there any config i can pass on where the axes is formed till 12:00 AM nothing butt one hour on axes scale.

I am attaching a fiddle link where i have created a data for 30 mins to chart but i need chart to be formed for 1 hour
https://jsfiddle.net/b5xrazmv/3/

**Comment by leeoniya** [comment]
i assume you only mean for the default (zoomed out) view? when you zoom it's okay to respect the exact zoom range?

**Comment by kpkalwa** [comment]
Yes i  need it for initial view , Zoom range is okay with respect to zoom view

**Comment by leeoniya** [comment]
you can grow the range like this: https://jsfiddle.net/1xfz29Lt/

```js
  scales: {
    x: {
      range: (u, min, max, scaleKey) => {
        let xData = u.data[0];
        let len = xData.length;

        if (min == xData[0] && max == xData[len - 1]) {
          return [min, max + 60 * 5];
        }

        return [min, max];
      }
    }
}
```

**Comment by leeoniya** [comment]
btw, you can also set `opts.ms: 1` if your x is always milliseconds, and then skip the `/ 1000` stuff. you don't need `time: true` either, since that's the default.

**Comment by kpkalwa** [comment]
Thanks for the help

I want to do back fill i need to do it similar fashion for min value setting ?

**Comment by leeoniya** [comment]
yes, range min can be expanded in same way. your data backfill will have to be done with `.setData(dataWithBackfill, false)`.

`false` will prevent an additional scale reset.

**Comment by kpkalwa** [comment]
Will write a data modification to fill in the values. 

Thanks for the help @leeoniya
