### ISSUE TITLE
Incorrect # of plot-columns in stacked bars

### ISSUE THREAD

**Issue by alejandrokewazian** [leeoniya/uPlot#763]
Hey, man. 

In your [bars-grouped-stacked.html](https://github.com/leeoniya/uPlot/blob/master/demos/bars-grouped-stacked.html) example, you have
```
const data = [
	["Group A", "Group B", "Group C"],
	[1, 2, 3],
	[3, 2, 1],
	[5, 9, 3],
];
```
which corresponds to
![image](https://user-images.githubusercontent.com/83082534/200895370-146d3bb9-7b9d-44e0-ac96-a3d5ebe12f12.png)
where the bottom fig is _stacked_. 

But when adding a 4th (... nth) column (say, Group D), something weird happens. Given
```
const data = [
	["Group A", "Group B", "Group C", "Groupd D"],
	[1, 2, 3, 10],
	[3, 2, 1, 10],
	[5, 9, 3, 10],
];
```
we'd expect to see a 4th column also appear on the bottom fig ... but it doesn't:
![image](https://user-images.githubusercontent.com/83082534/200896431-e02e5e11-a90f-46c9-aa15-1b3edb6b0b4d.png)

The name 'Group D' does appear in the x-axis, but no corresponding stacked bars. 

Anyway, I made a change to your _grouped-bars.js_ file [locally], i.e., this:
```
if (stacked)
	barsPctLayout = [null].concat(distrOne(u.data.length - 1 - ignore.length, u.data[0].length));
```
to this:
```
if (stacked)
	barsPctLayout = [null].concat(distrOne(u.data[0].length - ignore.length, u.data[0].length));
```
which seemed to fix the issue (examples with 4 columns ... and more):
![image](https://user-images.githubusercontent.com/83082534/200913054-1c11789f-dea9-442b-92e3-a0c2a007073c.png)

![image](https://user-images.githubusercontent.com/83082534/200911162-4d522322-9791-4a45-b17e-8f0203ee2768.png)
...
![image](https://user-images.githubusercontent.com/83082534/200911416-a310baa0-a5de-43bd-b344-989de63e47af.png)

Don't know if I'm missing something or whatnot. But `u.data.length - 1 ` would always limit the stacked columns to the length of the Y-series collections in _data_, where instead we would want them to follow the length of the X-series or data[0] -- `u.data[0].length` . 

Anyway, apologies if this passes stupidity for profundity.

**Comment by leeoniya** [comment]
yeah, nice catch.

> Anyway, apologies if this passes stupidity for profundity.

definitely not. there was a bunch of other nonsense logic in there that's fixed by linked commit. also properly fixes several edge cases that are added to the demo: https://leeoniya.github.io/uPlot/demos/bars-grouped-stacked.html

there is still the stacked hover rect issue that's described in https://github.com/grafana/grafana/issues/57110#issuecomment-1286316184 and fixed in https://github.com/grafana/grafana/pull/57711
