### ISSUE TITLE
should `i` be relative to the internal flattened array?

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#77]
right now the public API is split into `x` and `y` sections, but internally they're merged to keep the loops uniform, with just a sprinkling of `if (i ==0)` branching to split off `x`.

the public API accepts `i` that is against the internal flattened array, but this is not terribly intuitive, especially since uPlot goes to additional lengths to make it look like the internals match the externals, e.g.

https://github.com/leeoniya/uPlot/blob/589d1dd2a17d7fdc33aef176b837678131b460c2/src/Line.js#L174

this can probably be improved.

i've considered dropping the x/y and simply making the lists flat but it results in awkwardness elsewhere. e.g. `x` is required, but if nothing needs to be customized for the x axis, you need to provide options that start with null: `axes: [null, {values}]`. also, there can be multiple x axes (let's say different units), then what?

i guess one route can be to attach an extra required property to each option item in a flat list, eg. `dir: 'x'`, but that's not great either.

considerations:

- data[0] is always the x-series data and there can only be a single x series
- there could be multiple x axes (alt units)

if we simply disallow multiple x axes, then this whole situation becomes easier. we can use flat lists and simply say that data[0], series[0] and axes[0] are all `x`, everything else is `y`, and then we just use a flat `i` as we do now and everything becomes logically aligned. yes, there will be `axes: [null, {}, {}]` but it's easy to reason about.

**Comment by leeoniya** [comment]
multiple x axes can actually be quite useful, especially when comparing 2 time periods, or group-segmenting another axis:

![XBDhQ](https://user-images.githubusercontent.com/43234/71398734-06cd1c80-25e7-11ea-9f2f-da899162c20f.png)
![088297df-5acb-4974-872b-d3cc775a1be8_chart-legacy](https://user-images.githubusercontent.com/43234/71398735-06cd1c80-25e7-11ea-8e0f-5de01b7d24ad.png)
![36106056-4351e246-0fe4-11e8-95e9-970c904e9a57](https://user-images.githubusercontent.com/43234/71398736-06cd1c80-25e7-11ea-9162-4cbd2fc739e4.png)

**Comment by leeoniya** [comment]
here's what a flattened uniform structure would look like that allows `i` to be logically consistent (with multiple x axis support).

modifying the default y axis or y series would require `null` or `{}` placeholders for the skipped default `x`.

technically, the axes order doesnt matter s long and we can treat the first encountered `side: 2` axis as the default x and `side: 3` as the default y.

there's no such option for `series` if we want to stay sane and follow the order of `data`.

```js
{
  data: [
    [1,2,3,4],
    [47,22,13,4]
  ],
  series: [
    null,
    {},
  ],
  axes: [
   null,
   {side: 3}
  ],
  scales: {
    x: {},
    y: {},
  }
}
```

**Comment by thinhlm** [comment]
Have you a sample demo for this? thanks.

**Comment by leeoniya** [comment]
a sample demo of what?

**Comment by thinhlm** [comment]
> a sample demo of what?

 multiple x-axes like [image](https://user-images.githubusercontent.com/43234/71398735-06cd1c80-25e7-11ea-8e0f-5de01b7d24ad.png)

**Comment by thinhlm** [comment]
> a sample demo of what?

multiple x-axes like image.
I want to render a chart with 2 lines. But they have different x.

**Comment by leeoniya** [comment]
chart 2: https://leeoniya.github.io/uPlot/demos/time-periods.html
