### ISSUE TITLE
How to: custom xticks and xticklabels

### ISSUE THREAD

**Issue by GittyGenie** [leeoniya/uPlot#770]
Can't figure out how to do the following matlab-style customization.  Say I have a plot with 100 elements in the x series.  I want to have the x-ticks only at a set of custom positions, such as [1,5,10] and I want the x-tick labels at these three positions be something like ['a','b','c']. What's the most straightforward way to do this?

**Comment by leeoniya** [comment]
you would set `axis.splits: [1,5,10]` and `axis.values: ['a','b','c']`

**Comment by GittyGenie** [comment]
Worked great, thank you!
