### ISSUE TITLE
lower y axis grid line and label not showing for negative decimals

### ISSUE THREAD

**Issue by adamsonjesse** [leeoniya/uPlot#771]
I noticed that if you have a chart with decimals that is using negative number, the lowest Y gird line does not show up on even values, you have to go a tiny bit past it to get it to show up, here is my fiddle:

https://jsfiddle.net/jesseadamson/7hnq3jts/24/

You can swap out the commented line to see what I mean. So if you have the y range: [-0.6, 1.6], then the lowest grid/axis line does not show up but if you have range: [-0.600000001, 1.6], then it does. Since the auto range uses even numbers, it also has this funky look when set to auto.

**Comment by leeoniya** [comment]
<img width=200 src="https://user-images.githubusercontent.com/43234/206026805-8fe244de-af12-424b-9263-0220f96a8606.png">

**Comment by leeoniya** [comment]
hopefully fixed by linked commit :crossed_fingers:

**Comment by adamsonjesse** [comment]
Awesome, thanks! You're a machine!

**Comment by leeoniya** [comment]
> You're a machine!

you've obviously never met some of my co-workers :rofl:

**Comment by leeoniya** [comment]
i'm testing some more and this isn't a full fix :(, will need more work...

**Comment by adamsonjesse** [comment]
No worries, rounding numbers in JS seems like a gnarly rabbit hole that I am going to have to go down too but I have been putting it off... https://stackoverflow.com/questions/11832914/how-to-round-to-at-most-2-decimal-places-if-necessary

**Comment by leeoniya** [comment]
i think https://github.com/leeoniya/uPlot/commit/9fc7bb4881c43eef11677661ad92b4320d7f8a13 does it.

basically you have to round to a reduced precision at the intermediate steps, too. i tested with these, where the string is my expected output:

```js
console.log('-0.6', incrRound(-0.6, 0.1));
console.log('-0.6', incrRound(-0.6, 0.2));
console.log('-0.7', incrRound(-0.7, 0.1));
console.log('-0.8', incrRound(-0.7, 0.2));

console.log('-0.6', incrRoundUp(-0.6, 0.1));
console.log('-0.6', incrRoundUp(-0.6, 0.2));

console.log('-0.6', incrRoundDn(-0.6, 0.1));
console.log('-0.6', incrRoundDn(-0.6, 0.2));

console.log('-0.7', incrRoundDn(-0.7, 0.1));
console.log('-0.8', incrRoundDn(-0.7, 0.2));

console.log('-0.7', incrRoundUp(-0.7, 0.1));
console.log('-0.6', incrRoundUp(-0.7, 0.2));
```
