### ISSUE TITLE
How can i remove cursor line

### ISSUE THREAD

**Issue by Duc-Developer** [leeoniya/uPlot#772]
Hello Leeoniya,
How can i remove this line when i hover in chart
![dsfasdfsad](https://user-images.githubusercontent.com/66018863/206087390-90b21c61-286c-4572-b5c5-e054b32c1ad4.jpg)

**Comment by leeoniya** [comment]
it's all CSS, so you can override it:

https://github.com/leeoniya/uPlot/blob/9fc7bb4881c43eef11677661ad92b4320d7f8a13/src/uPlot.css#L106-L114

**Comment by Duc-Developer** [comment]
oh, thanks man!

**Comment by leeoniya** [comment]
> Is there any other way besides overriding by styles?

no, you'll have to set/unset styles in a setCursor or setLegend hook. it's unlikely that this will be added to the core because the performance of potentially updating cursor DOM styles on every mousemove is likely to be miserable.
