### ISSUE TITLE
canvas scaling?

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#773]
Have a question. i.e

in html
```
<div id="plot1"></div>
```
in js
```
 u = new uPlot(opts, data, document.getElementById("plot1"));
```
the above combo work just fine. the normal plot size is 100x100, if I want to "scale" the whole plot into a smaller 60x60 div , like
```
<div id="plot1" width="60" height="60"></div>
```
,  the plot does not show up. how should we do that? thanks.

**Comment by hz2018tv** [comment]
in the plot init, we can set the width/height in the opts, can we change them on the fly, say, by resizing the window with a mouse? thx

**Comment by leeoniya** [comment]
there is a `u.setSize({width: ..., height:...})` API.

demo: https://leeoniya.github.io/uPlot/demos/resize.html

if you need to resize to a container element, you will probably want to use a https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

**Comment by hz2018tv** [comment]
the demo looks like what I am looking for. I will check out the resizeobserver. Thanks!
