### ISSUE TITLE
[v1.7.0 PSA/RFC] give me a reason not to always include zero when y auto-scaling

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#776]
uPlot v1.7.0 is coming in the next few months.

mainly, it will bring changes to how the default numeric tick selection and y-auto-ranging works. i will try my best to make this upgrade seamless, but internally it's actually a significant refactor that will take into account axis splits settings into auto-scaling algo.

so while i'm ripping up the scaling logic, i'm tempted to improve it in other ways as well.

currently, if your y-data like this: `250_000, 250_010, 250_000`, you'l get a chart that looks like this: `_/\_`, and a y axis range of something like `249_990 - 250_020`. while this maximizes the vertical available space for the data, it's actually very misleading, like bar charts that don't start at zero [1], and stacked area charts [2].

if my data range fluctuates by 0.1% of the absolute values, i don't want to see mountains in my chart, and i shouldn't have to set soft limits to avoid this. that's what 863fb22d4e352449a291253f17004ae024799977 aims to do. however, i now don't see a reason for there to be an arbitrary cut-off; most of the time, i dont want to see 1% fluctuations as mountains either, or even 10%.

a [maybe controversial] side effect of this change will be that you will not be able to "zoom" further into a y scale by _only_ dragging x. you can still y-zoom deeper by doing a rectangular zoom or explicit y zoom (if enabled).

so my request is for users to provide any feedback and/or counter-arguments for this behavior change.

i want auto-ranging to do this by default: https://jsfiddle.net/gm3hw7q4/
![image](https://user-images.githubusercontent.com/43234/208561804-ca169bfd-064a-4d08-86c7-0d3f3e01ca6e.png)
not this, which it does currently:
![image](https://user-images.githubusercontent.com/43234/208561549-6827dcdb-0d8f-4ff4-9214-c0597c27f0e5.png)

```js
let data = [
  [0, 1, 2, 3],
  [1000, 1010, 1000, 1010],
  [1000, 1100, 1000, 1100],
  [1000, 1115, 1000, 1115],
  [1000, 700, 1000, 700],
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
    y: {
      auto: false,
      range: [0, 2000],
    },
  },
  series: [
    {},
    {
      label: "1%",
      stroke: "red",
      fill: "rgba(255,0,0,0.1)",
    },
    {
      label: "10%",
      stroke: "blue",
    },
    {
      label: "11.5%",
      stroke: "magenta",
    },
    {
      label: "30%",
      stroke: "green",
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

[1] https://medium.com/loud-updates/what-happens-when-bar-charts-dont-start-with-zero-7db04221417e
[2] https://leeoniya.github.io/uPlot/demos/stacked-series.htmluPlot v1.7.0 is coming in the next few months.

**Comment by tve** [comment]
You mean, I won't have to set a 0 minimum on all my charts anymore???? 💯 

What is the algorithm really? To always include 0 somewhere along the y axis? E.g. what if all values are negative?

I assume if I set the axis bounds explicitly then I can get anything I want, right? E.g. think of a temperature graph for normal ambient temperatures with a Y axis in Kelvin. Would be awkward to start at 0 and your argument doesn't really apply.

**Comment by leeoniya** [comment]
> What is the algorithm really?

heh, i'm still trying to figure that one out :)

certainly open to suggestions!

> To always include 0 somewhere along the y axis? E.g. what if all values are negative?

the default auto-ranging already has a sticky 0 if you cross it when adding the padding % to the raw data min or max. if all vals are negative then 0 is at the top edge of the plot. when it's mixed pos/neg, it will already be in view, but not very stable, it would be good to have it be stable, like vertically centered.

i think my biggest question is about how much padding to add. what's shown above is kinda:

```js
let dy = dataMax - dataMin;
let yMin = 0;
let yMax =  2 * (dataMin + dy/2);
```

but this doesn't work very well in terms of a consistent look. e.g. a data range of 900-1000 will have a y range of 0-1900 but 100-1000 will be 0-1100.

another strategy is `yMin = 0; yMax = dataMax * (1 + padding)`, this is similar to what happens now. where padding default is `0.1`. but this strategy will mean we have a y range of 0 - 1100 for our 900-1000 data range. if you fill that, you'll have most of the plot solid red, which maybe isn't great either, but maybe okay:

![image](https://user-images.githubusercontent.com/43234/208579519-98e1a754-f16f-48c9-a10d-516440e3eab5.png)

doesn't look good when the fluctuation is minimal (+/- 10):

![image](https://user-images.githubusercontent.com/43234/208579847-5429a6d2-416f-493e-a000-0f6fedad643a.png)

> I assume if I set the axis bounds explicitly then I can get anything I want, right?

yes

> E.g. think of a temperature graph for normal ambient temperatures with a Y axis in Kelvin. Would be awkward to start at 0 and your argument doesn't really apply.

kelvin is a good one to keep in mind. but if you're still expecting a "human" C of F range, then it might make sense to still have a 273.15K baseline that's always in view. so maybe an additional setting for this that defaults to 0, but can be configured with some other static offset.

**Comment by TPU22** [comment]
In my opinion, this would be a massive mistake. At least 95% of my plots leverage the current "proper" auto-scaling that maximizes the vertical space. If I want to include zero in the scale range, I will add it manually. Why would having zero be something special, other than in the bar charts? Look at R, Matlab and Python plotting libraries. All they use a similar auto-scaling uPlot currently employs by default (the _jumps_ are there), and for a good reason.
Not to mention that dragging X would disable recaling the Y fit, as you mentioned. UPlot is very snappy and intuitive right now, and this change would steer it certainly to clumsier and old-fashioned direction.

By the way, what was done in the autoscale algorithm in 1.6.23? I had to revert to 1.6.22 because 1.6.23 does not anymore maximize the vertical space anymore with data with certain scale (the plotting calls being the same), but rather adds padding both below and above the actual data ranges. Should I fill a separate bug?

**Comment by leeoniya** [comment]
yeah, the more i think about it the more cases there are when having always having 0 would not be good. this probably means i'll revert https://github.com/leeoniya/uPlot/commit/863fb22d4e352449a291253f17004ae024799977 as well.

> Should I fill a separate bug?

please do.

**Comment by danekasper** [comment]
90% of my use cases are for sensors that are relative values and zero is not important to viewing data. Not against changing default behavior, as long as the current can be kept via an easy flag.

**Comment by leeoniya** [comment]
thanks, people!
