### ISSUE TITLE
How to configure multi axes with custom range?

### ISSUE THREAD

**Issue by Duc-Developer** [leeoniya/uPlot#778]
Hi leeoniya,
Is this possible if I configure each y-axis with a different range? I can't use scales: **{y: {auto: true}}** because for my purposes I want the axis display to be separate from the series. In auto mode, when hide/show the series it also hide/show the corresponding y-axis.

I see you have instructions for configuring scales like this, if I choose type Range = Range.Function. This function only returns MinMax = [min: number | null, max: number | null]. It doesn't seem to be enough for me to configure the range for each axis.

![image](https://user-images.githubusercontent.com/66018863/209516059-385ca28d-e15c-4bb5-b813-eb4a4e85721d.png)

**Comment by leeoniya** [comment]
you need to use a different scale for each axis, like `y`, `y2`, etc. then each scale can have a fixed range like a function or a min/max tuple. then each axis and series should have the scale keys:

```js
{
  scales: {
    y:  {range: [  0, 125]},
    y2: {range: [-20, 400]},
  },
  axes: [
    {},
    {scale: 'y'},
    {scale: 'y2'},
  ],
  series: [
    {},
    {scale: 'y'},
    {scale: 'y2'},
  ]
}
```
