### ISSUE TITLE
Tooltip marker is offset from plotted point

### ISSUE THREAD

**Issue by tve** [leeoniya/uPlot#779]
The markers set by the tooltip plugin are offset by a pixel or two to the upper-left. This can be see in the [Tooltips plugin (basic)](https://leeoniya.github.io/uPlot/demos/tooltips.html) demo:
- open the demo
- magify the plot by a few steps
- hover around a point and observe carefully how the point not just fills in but also expands to the top-left

Here's a screen shot where I stopped execution while the tooltip was up and then changed the color on the ".u-cursor-pt" element. (Hmm, I guess this is really in the core of uPlot 'cause the tooltip doesn't place that .u-cusrsor-pt, I'm just not managing to reproduce the issue in the demos that don't have a tooltip.)

![image](https://user-images.githubusercontent.com/39480/209576546-5c5c6bef-bb7b-46ff-9747-8d18c4e2467f.png)

Firefox 107.0.1 (64-bit) Arch Linux and Vivaldi 5.6.2867.40 Arch Linux.

**Comment by leeoniya** [comment]
> (Hmm, I guess this is really in the core of uPlot 'cause the tooltip doesn't place that .u-cusrsor-pt, I'm just not managing to reproduce the issue in the demos that don't have a tooltip.)

unfortunately this will forever be a game of whack-a-mole as it requires aligning dom elements with canvas-rendered stuff. there's rounding at different stages for perf and float-math-precision reasons, dealing `devicePixelRatio` / zoom, fractional pixel anti-aliasing, stroke widths of lines and points, etc. it also varies between browsers and platforms.

https://github.com/leeoniya/uPlot/commit/76341638995a5397b1bd533a25023672edc1433f improves it somewhat in my testing, but it can never be perfect; there are simply too many variables in play here.
