### ISSUE TITLE
Excessive padding on the left when tick is disabled

### ISSUE THREAD

**Issue by florentbr** [leeoniya/uPlot#782]
Removing the tick on the Y axis ` ticks: {show: false}` shifts the label to the right but fail to update the spacing.
This leaves an excessive gap in front of the labels even with the padding set to 0 `padding: [0, 0, 0, 0]`.

To reproduce:
https://jsfiddle.net/20smofvx/2/

**Comment by leeoniya** [comment]
axes are statically sized by default, so if you have short values you'll have white space. you can adjust them down via e.g. `axis.size: 50`. you can also size them dynamically via callbacks and your own tick label measurement logic: https://leeoniya.github.io/uPlot/demos/axis-autosize.html
