### ISSUE TITLE
Legend Spacing / Position

### ISSUE THREAD

**Issue by adamsonjesse** [leeoniya/uPlot#784]
I am trying to decrease the space between the legend and the chart to pack more charts closer together vertically. I noticed I could move the legend up in CSS by just adding:

.u-legend {
  margin-top: -25px !important;
}

But this messes up the click for enable/disable on the series. See fiddle here, when I move it up 25px then the click is below the button:

https://jsfiddle.net/jesseadamson/z5v47tge/20/

Is there a better way to do this or do you have any suggestions?

**Comment by leeoniya** [comment]
when you do it via margin you're simply moving the dom element behind `.u-wrap`, which makes it unclickable.

![image](https://user-images.githubusercontent.com/43234/211605784-74b200b9-e71a-4e81-8b55-a945c9d49f29.png)

you can/should instead remove the legend padding (in css) and set axis options which reduce its height (in js):

https://jsfiddle.net/tg80as7y/1/

![image](https://user-images.githubusercontent.com/43234/211607149-dbfa8d77-e7de-4d17-a060-e18db70adc0d.png)

you can also get rid of axis ticks, if you want to squeeze further. and/or reduce font size.

https://jsfiddle.net/tg80as7y/2/

![image](https://user-images.githubusercontent.com/43234/211607461-8193a30f-cb99-4c3b-91db-95976d67cf6d.png)

**Comment by adamsonjesse** [comment]
Awesome thanks! Perfect, those axes options were mainly what I needed:
  axes: [
  	{
    	size: 20,
      gap: 5,
      ticks: {
      	size: 0,
      }
    },
  ],
