### ISSUE TITLE
Center series (line path) when values are constant [0, 0] for the whole x (time) axis 

### ISSUE THREAD

**Issue by DeanDK** [leeoniya/uPlot#789]
Version: 1.6.23

Imagine we have following mock data (first item is time range on x axis):

`[
    [1617177790260, 617177790905],
    [0, 0],
    [0, 0],
    [0, 0],
    [0, 0],
]`

This will produce following result:

![Screenshot 2023-01-25 at 16 30 49](https://user-images.githubusercontent.com/25985367/214605316-c1050950-dffa-467e-9ecf-f7fd83890498.png)

As you can see, series is drawn on the x-axis, so sometimes it might seem like there is no data, while there actually is, but line is placed at the minimum y-axis value.

Is it possible to change the y-axis grid values and place series path to the center of the chart ? 

max y value - 1
center - 0 (where the line is drawn)
min y value - 1

I forked the project and did some small change locally to get this

![Screenshot 2023-01-25 at 16 37 54](https://user-images.githubusercontent.com/25985367/214606735-f2fc2982-2f5d-4f0f-9341-bf4b1c779bca.png)

I hope you get better idea now, even thought in this case y-axis value are from 100 to -100, while they should be from 1 to -1.

This is the change I did (only commented line is changed)

![Screenshot 2023-01-25 at 16 47 02](https://user-images.githubusercontent.com/25985367/214609045-53b4b6da-0d38-4516-9c2d-75de1e0c1c2a.png)

Is it possible to center series path when data is constant 0 ? This actually works with all other constants, both negative, positive, decimals etc, only 0 is drawn on the x axis.

**Comment by leeoniya** [comment]
you can customize the ranging function of each scale to do whatever you want.

https://jsfiddle.net/n7rpb69q/

```js
const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
    y: {
      range: (u, dataMin, dataMax) => {
        if (dataMin == 0 && dataMax == 0)
          return [-100, 100];
        return uPlot.rangeNum(dataMin, dataMax, 0.1, true);
      },
    }
  },
  series: [
    {},
    {
      stroke: 'blue',
    },
  ],
};

let plot1 = new uPlot(opts, [[0, 1, 2], [0, 1, 2]], document.body);
let plot2 = new uPlot(opts, [[0, 1, 2], [0, 0, 0]], document.body);
```

![image](https://user-images.githubusercontent.com/43234/214681099-7b8adcd4-1856-4c69-9dde-0b69472f2f12.png)
