### ISSUE TITLE
Line is not appearing

### ISSUE THREAD

**Issue by benmccann** [leeoniya/uPlot#79]
I'm finally getting around to trying to migrate one of my apps to uPlot. Unfortunately the line isn't appearing and I'm not getting any errors in the Chrome debug console, so I'm not quite sure what I'm doing wrong if anything. The hover and tooltip are working though. Do you have any ideas you'd be able to share?

http://plnkr.co/edit/UGKhW6mkaG3lmOniPnYz?p=preview

**Comment by ldstein** [comment]
I believe if you remove `band` from the series config, the line will appear.

```
          {
            label: 'UPLT',
            color: 'red',
            fill: 'rgba(0, 255, 0, 0.2)',
            value: (u, v) => fmtUSD(v, 2),
            band: true, // Remove this
          }
```

**Comment by leeoniya** [comment]
yep :)

i'd also recommend applying the baseline CSS reset, since uplot's css kinda assumes this.

https://github.com/twbs/bootstrap/blob/bd278341989e115e95fe29bc4738b440087f6d75/dist/css/bootstrap-reboot.css#L8-L24

maybe i should bake the `box-sizing: border-box;` rule into uplot's css, since stuff might get misaligned without it.

**Comment by leeoniya** [comment]
@benmccann also, if you end up using uPlot for financial plotting, i'd welcome a plugin contribution from you which draws OHLC markers at the data points, similar to what's done in the draw-hooks demo:

https://leeoniya.github.io/uPlot/demos/draw-hooks.html

**Comment by benmccann** [comment]
Thanks @ldstein! I hadn't caught that I'd accidentally copied that line from the example I was following

@leeoniya is the only line I need from the CSS `*,*::before,*::after { box-sizing: border-box; }`? That does make things look better. It'd be cool if it could apply just to the uPlot elements and not the whole page. I haven't tried embedding this in my webpage yet, but am not sure if it might make other elements on my page display differently

**Comment by leeoniya** [comment]
> It'd be cool if it could apply just to the uPlot elements and not the whole page.

yeah, for sure, it would be namespaced to `.uplot`, like everything else.

**Comment by benmccann** [comment]
Cool. Thanks for the CSS update! It's a bit easier to setup and get going now :-)
