### ISSUE TITLE
Cursor data point selection

### ISSUE THREAD

**Issue by simon-jouet** [leeoniya/uPlot#792]
Hi,

First of thanks for the library, it's great and performance-wise it's night and day with pretty much everything else I have tried!

So I'm trying to show some line plots of some sensor data, the data displayed is in the same time frame but the readings are not time aligned. Following the doc and api I have used `Uplot.join` and made the series use spanGaps. So far so good and it shows the series.

The issue i'm having is with the cursor and trying to read the values; most of the time the series selected and displayed in the legend is nowhere near where my cursor is. For instance in the screenshot above I'm trying to read the data point of the purple line but it keeps focusing the blue and green lines.

![image](https://user-images.githubusercontent.com/832495/215782498-39f405fa-791f-4bfa-a26e-91cf4d62b0d5.png)

So I have two questions that are quite related:

1. Is there any way at the moment to use the distance to the series as an indicator on why data point to select?
2. Is there any way to show in the legend the closest point for all the series instead of only the series with an exact match?

I have read the API and checked most of the demos but I have very likely missed some things.

Thanks a lot.

**Comment by leeoniya** [comment]
this shows how to scan left/right of the hovered index to show the one with data: https://leeoniya.github.io/uPlot/demos/nearest-non-null.html

you don't need to do the multi-value legend if you don't care about the differing timestamps for each series hovered datapoint, but then your legend will show the value of the hovered (joined) index. this might be sufficient.

https://leeoniya.github.io/uPlot/demos/timeline-discrete.html manipulates `legendTimeValueEl.textContent` directly to show the exact time at the cursor position, regardess of whether it lands on a data index.

you can probably hack something together that only shows the point of the nearest series and hides the rest.

take a look at the setSeries/focus hook here: https://leeoniya.github.io/uPlot/demos/tooltips-closest.html

**Comment by simon-jouet** [comment]
That's great thanks @leeoniya I will have a look at all of that I think the nearest non null will be the answer to what I was mostly looking for. Sorry I had checked the examples but I missed those.

Thanks again
