### ISSUE TITLE
Conditional background shading

### ISSUE THREAD

**Issue by csianglim** [leeoniya/uPlot#794]
I'd like to perform conditional shading on my chart with 4 series, based on a 5th series with on/off boolean values (e.g. yellow if 0, none if 1).

![image](https://user-images.githubusercontent.com/7519832/216387277-f885bdd4-4bc2-4cfd-9ebe-fa3e7f844f4a.png)

I went through the demos and the closest option that I can think if is to use bands, but seems like that would involve some calculations to set up the low/high band values, where:

- low band = min across all 4 series
- high band = max across all 4 series if on/off = on
- high band = min across all 4 series if on/off = off

Is there a simpler way to do shading instead of creating these bands?

**Comment by leeoniya** [comment]
two options:

1. if you don't need the series to be toggle-able or in the legend, you can omit it from the `opts.series` array, but still keep it in your data (at the end). you can then use a `drawClear` or `drawAxes` hook to just custom-render directly onto the blank canvas. something like this is done for the interpolated markers in https://leeoniya.github.io/uPlot/demos/tooltips-closest.html.
  https://github.com/leeoniya/uPlot/blob/1e4ea5427100f81750a93c1ab9f5b78d3c0bf116/demos/tooltips-closest.html#L153-L181
2. if you want it rendered as an actual series, with legend interaction/values, you can do the same custom rendering in user-defined `series.paths`. though these are drawn in order, so if you put it as series[5], it will be drawn on top of everything else. you may want to move it to series[1] position so the shaded regions draw first.
