### ISSUE TITLE
axis direction

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#795]
how to flip the direction of one axis? e.g. y axis has range [0,40], by default, it starts from left lower corner (0) and goes up to 40, how to make it start from left upper corner (0) and come down to 40? thx.

**Comment by leeoniya** [comment]
`scale.dir: -1`

see https://leeoniya.github.io/uPlot/demos/scales-dir-ori.html

**Comment by hz2018tv** [comment]
that did it. thanks!
