### ISSUE TITLE
How does trendlines update his location

### ISSUE THREAD

**Issue by zChanges** [leeoniya/uPlot#796]
This dome  trendlines.html
Click the canvas to get the current closest data point and update the position of the line. What should I do? 
DrawSeries is hooks. How can I update the previous line after clicking

<img width="862" alt="image" src="https://user-images.githubusercontent.com/16421725/216574754-15d5d0d0-5955-4d78-862c-01199c8ba77f.png">

**Comment by leeoniya** [comment]
`u.redraw()`

example: https://github.com/leeoniya/uPlot/issues/765#issuecomment-1329116984

**Comment by zChanges** [comment]
can solve my problem, thank you very much
