### ISSUE TITLE
multi charts arrangement/gridding

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#797]
Say, I have 4 squre charts c1/c2/c3/c4, each is of 20x20, I want to combine them into a bigger one, idealy seamlessly. I can choose to arrange them like C1 C2 C3 C4 in one row or C1 C4 on one row and C3 C2 on the row below. each sub chart still maintains its own ops like ori/dir/etc. Kind of like the grid from echarts. Any thoughts? Thanks.

**Comment by leeoniya** [comment]
i'm not sure what you're asking. uPlot creates a single chart. you can make 4 uPlot charts or 40 uPlot charts and arrange them however you like.

people do this in very different ways with very different requirements, so it's not possible to provide a solution that will work with all frameworks (React, Angular, Vue, Svelte, Solid, etc).

> idealy seamlessly

> Kind of like the grid from echarts

you have not provided any links or examples to demonstrate what you mean with these statements. seamless like turning off axes and padding on some of the charts in the 2x2 grid? how would you know the value ranges?

**Comment by hz2018tv** [comment]
https://echarts.apache.org/en/option.html#grid

**Comment by leeoniya** [comment]
here's why this is not a great idea. on a mobile device they don't stack. and if you want them to stack, then you need to basically re-implement CSS grid or flexbox layout models in JS. what if you wanted to resize one of the panels by dragging? probably this is not supported by echarts grid. it's very easy to create something like this as a uPlot wrapper with the full flexibility of CSS.

if you want something more powerful for dashboarding arrangement, take a look at https://gridstackjs.com/. uPlot should not be in the business of creating flexible/dynamic layouts outside each chart.

![image](https://user-images.githubusercontent.com/43234/218226166-e134e4d6-0484-41a8-9e9a-0d712b8ad545.png)

**Comment by hz2018tv** [comment]
got it.  will check out the  https://gridstackjs.com/. thx!

**Comment by hz2018tv** [comment]
"it's very easy to create something like this as a uPlot wrapper with the full flexibility of CSS."   could you provide some ref/links to this?

**Comment by leeoniya** [comment]
something like this (incomplete): https://jsfiddle.net/rfevL1qo/4/. hopefully that helps.

![image](https://user-images.githubusercontent.com/43234/218233463-fb05a6db-6bc5-428d-8b81-aecd4f1bd361.png)

```js
const grid = GridStack.init({
  disableOneColumnMode: true,
  float: false,
});

grid.on('added', (event, items) => {
  items.forEach((item, i) => {
    let contentItem = item.el.querySelector('.grid-stack-item-content');
    let { width, height } = contentItem.getBoundingClientRect();
    let u = new uPlot({
      width,
      height: height - 50,
      ...sharedOpts
    }, charts[i].data, contentItem);
  });
});

grid.on('resize', (event, items) => {
  console.log(items);
});

const sharedOpts = {
  scales: {
    x: {
      time: false
    }
  },
  series: [
    {},
    {
      stroke: "red"
    },
  ],
};

let charts = [
  {
    opts: {},
    data: [
      [0, 1],
      [-1, -2],
    ],
  },
  {
    opts: {},
    data: [
      [2, 3],
      [-3, -4],
    ],
  },
  {
    opts: {},
    data: [
      [4, 5],
      [-5, -6],
    ],
  },
  {
    opts: {},
    data: [
      [6, 7],
      [-7, -8],
    ],
  },
];

grid.batchUpdate(true);
grid.addWidget({ x: 0, y: 0, w: 5, h: 5 });
grid.addWidget({ x: 5, y: 0, w: 5, h: 5 });
grid.addWidget({ x: 0, y: 5, w: 5, h: 5 });
grid.addWidget({ x: 5, y: 5, w: 5, h: 5 });
grid.batchUpdate(false);
```

**Comment by hz2018tv** [comment]
wow, quick and neat! thanks for the sample! 

I looked at the gridstackjs briefly, it does provide lots of possiblities. but I havent seen any seamless arrangements, there seems always a gap between sub charts. will take a closer look at these libs. 

this scientific project produces 4 square heatmaps (20x20) from 4 diff sources, sometimes we need to combine (seamlessly) those heatmaps to have a bigger view, we do want/hope to use uplot for this because uplot is used to draw almost every single chart in the project and we love the performance.
