### ISSUE TITLE
Anyway to zoom streaming chart currently it doesn't do anything

### ISSUE THREAD

**Issue by ananth-kimshuka** [leeoniya/uPlot#801]
```js
const opts1 = {
  title: "RE111",
  ...getSize(),
  ms: 1,
  scales,
  cursor: { drag: { x: true, y: true, uni: 50 } },
  series: [
    {},
    {
      stroke: "red",
    },
  ],
};
```

**Comment by leeoniya** [comment]
you can definitely do it, the question is exactly how you want it to behave. there are 3 different streaming examples on the demo page [1], and it is not clear which one you are interested in. each would need different accommodations for zooming.

[1] https://leeoniya.github.io/uPlot/demos/stream-data.html
