### ISSUE TITLE
How to highlight the current column

### ISSUE THREAD

**Issue by 17839359913** [leeoniya/uPlot#802]
当使用堆叠柱状图的时候，hover某个柱子的时候，高亮这一行柱子的同时，如果高亮当前这一个柱子。
如图中框内的珠子加一个高亮色
![image](https://user-images.githubusercontent.com/22956606/219617041-8ab9237b-a154-4213-b122-5936059ff84c.png)

**Comment by leeoniya** [comment]
see `columnHighlightPlugin` in https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html

**Comment by 17839359913** [comment]
Thank you very much for your reply。
I've got it done in the same way as columnHighlightPlugin。
The bright red bead is rendered in the u-under。
I won't re-render canvas。
Is this the right way?

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/22956606/220022566-4be7d91e-402a-48a2-b597-725c587f109a.png">

**Comment by 17839359913** [comment]
Thank you very much for your reply。
I have a problem。
The position of some points calculated by the valToPos method will have a deviation of 1px。
At first I thought it was a matter of decimals。But it is not. The problem may be an integer。
<img width="585" alt="image" src="https://user-images.githubusercontent.com/22956606/220841055-5719eed3-c07d-41c2-8a90-75b4fc9c62c4.png">

**Comment by leeoniya** [comment]
the bar and grid/axis renderers round the output of valToPos so that the rendering stays sharp instead of rendering lines and bar edges on fractional pixel boundaries. you may need to also round the output of valToPos in your code to make the alignment match.

it looks like the left side is also off by the same amount, so you can probably fix this by Math.floor() or similar.

**Comment by 17839359913** [comment]
Thank you very much for your reply。
It seems that because of the reason of translation, it's OK to change it to left

**Comment by 17839359913** [comment]
![image](https://user-images.githubusercontent.com/22956606/221126021-8e1cf0eb-b576-467d-89c1-10a124528edb.png)

**Comment by 17839359913** [comment]
Is there any way to make the x-axis uneven?

**Comment by leeoniya** [comment]
can you explain or provide an example?
