### ISSUE TITLE
x axes extends beyond the canvas

### ISSUE THREAD

**Issue by zChanges** [leeoniya/uPlot#804]
The x-axis goes beyond the canvas.  How to set the offset
<img width="451" alt="image" src="https://user-images.githubusercontent.com/16421725/224007498-1361490d-6764-4ca9-bd7d-0d28c0a589ac.png">

**Comment by leeoniya** [comment]
you can set `opts.padding` to be larger on the right side, or do more advanced things to increase it dynamically:

https://leeoniya.github.io/uPlot/demos/axis-autosize.html

you can also use `axis.filter` to skip the last label.

**Comment by zChanges** [comment]
solved my problem thanks a lot
