### ISSUE TITLE
Cursor position is wrong

### ISSUE THREAD

**Issue by Duc-Developer** [leeoniya/uPlot#806]
Hi Leeoniya,
I use 1 chart with quite a few data points. When I point my mouse to show the data point's tooltip, it seems to be showing quite far from where it is. Is there a way the pointer works most accurately, or reduce its error rate?
![Untitled](https://user-images.githubusercontent.com/66018863/225198334-75a9b101-6553-4b2b-94db-c05445e1de79.png)

**Comment by leeoniya** [comment]
by default uPlot will find the nearest index in the data relative to the cursor position.

you can customize this behavior (like proximity testing) using `cursor.dataIdx` option [1] to return a `null` index for each series that you don't want hovered.

[1]
https://github.com/leeoniya/uPlot/blob/915fc81633595ccb04e9d9c425dff82cea8f12dc/demos/nearest-non-null.html#L54-L89

**Comment by Duc-Developer** [comment]
Hi @leeoniya, thanks for your feedback
![Untitled](https://user-images.githubusercontent.com/66018863/226271316-f68fedb4-9e59-4111-b506-1336cb8039c4.jpg)
But what I really want to do here is reduce the distance error of the cursor. For any data type (null or not), I want to check how far is the distance from my cursor to the nearest point, and I won't show the tooltip if that distance is too large than expected. I noticed that the hoveredIndex parameter is always rounded to the nearest index, so I have no control over what I want to do.

**Comment by leeoniya** [comment]
you have to measure it:

https://jsfiddle.net/gsoft1y7/

```js
let data = [
  [0, 1, 2, 3],
  [10, 50, 25, 100],
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
  },
  cursor: {
    dataIdx: (u, seriesIdx, hoveredIdx, cursorXVal) => {
      let dx = Math.abs(u.valToPos(cursorXVal, 'x') - u.valToPos(u.data[0][hoveredIdx], 'x'));

      // hover when < 30px       
      return dx < 30 ? hoveredIdx : null;
    },
  },
  series: [
    {},
    {
      stroke: 'red',
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

you can also optimize this by pre-calculating and caching `pxPerVal` for a given scale range and chart size, and then doing simple math with `cursorXVal` and `u.data[0][hoveredIdx]` instead of `.valToPos()`, but it's probably not worth the added code/complexity.
