### ISSUE TITLE
What are the ways to lock and unlock by clicking the button outside the canvas

### ISSUE THREAD

**Issue by 17839359913** [leeoniya/uPlot#807]
What are the ways to lock and unlock by clicking the button outside the canvas？
This is very important for me. Thank you very much

**Comment by 17839359913** [comment]
like this
lock and unlock by clicking the lock button
<img width="952" alt="image" src="https://user-images.githubusercontent.com/22956606/227489064-8c843c7b-0a7c-4a3f-acb1-6f28d9a73205.png">

**Comment by 17839359913** [comment]
Is there any way to make axes render outside of canvas？
because when I move the mouse into the canvas, I want to add a transparency gradient to the canvas.But this will affect axes

**Comment by leeoniya** [comment]
> lock and unlock by clicking the lock button

you can add css `pointer-events: none` to the uplot wrapper `u.root` (see below)

> when I move the mouse into the canvas, I want to add a transparency gradient to the canvas.But this will affect axes

you can use `u.over` or `u.under` div elements which only cover the plotting area (see below)

https://jsfiddle.net/scj6ptLx/

```html
<link rel="stylesheet" href="https://leeoniya.github.io/uPlot/src/uPlot.css">
<script src="https://leeoniya.github.io/uPlot/dist/uPlot.iife.js"></script>

<button id="lock">Lock/Unlock</button>
```

```js
let data = [
  [0, 1, 2, 3],
  [10, 50, 25, 100],
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
  },
  series: [
    {},
    {
      stroke: "red",
    },
  ],
  hooks: {
    init: [
      (u) => {
        u.over.addEventListener("mouseenter", (e) => {
          u.under.style.background = "linear-gradient(#e66465, #9198e5)";
        });
        u.over.addEventListener("mouseout", (e) => {
          u.under.style.background = "none";
        });
      },
    ],
  },
};

let u = new uPlot(opts, data, document.body);

let locked = false;

document.getElementById("lock").addEventListener("click", (e) => {
  u.root.style.pointerEvents = !locked ? "none" : "auto";
  locked = !locked;
});
```

**Comment by 17839359913** [comment]
I know what you mean
But I want to add transparency to the drawing area instead of u.under
Because I want to add a transition effect to cursor. alpha
But I didn't find the corresponding API

**Comment by leeoniya** [comment]
do you have a demo that visually shows the effect you're trying to achieve?

**Comment by 17839359913** [comment]
> do you have a demo that visually shows the effect you're trying to achieve?


https://user-images.githubusercontent.com/22956606/227852648-7a1d76c2-c052-44e9-9c7b-a47b4339e457.mov

**Comment by 17839359913** [comment]
The transparency changes are delayed and gradual

**Comment by 17839359913** [comment]
I achieved this by completely covering a layer of div on canvas. I don't think this is a good way, and it will bring additional rendering pressure

**Comment by leeoniya** [comment]
> I achieved this by completely covering a layer of div on canvas

what does this code look like? 🤔 

> The transparency changes are delayed and gradual
> I don't think this is a good way, and it will bring additional rendering pressure

as stated in the readme, uPlot will [never support transitions or animations](https://github.com/leeoniya/uPlot#non-features) in the core (for performance reasons).

**Comment by 17839359913** [comment]
> > > I achieved this by completely covering a layer of div on canvas
> > 
> > 
> > what does this code look like? 🤔
> > > The transparency changes are delayed and gradual
> > > I don't think this is a good way, and it will bring additional rendering pressure
> > 
> > 
> > as stated in the readme, uPlot [will never support transitions or animations](https://github.com/leeoniya/uPlot#non-features) in the core (for performance reasons).
> 
> Cover canvas with my own div，What you see is not a canvas, but a div in the same location as the canvas，Can you understand what I mean？



> > lock and unlock by clicking the lock button
> 
> you can add css `pointer-events: none` to the uplot wrapper `u.root` (see below)
> 
> > when I move the mouse into the canvas, I want to add a transparency gradient to the canvas.But this will affect axes
> 
> you can use `u.over` or `u.under` div elements which only cover the plotting area (see below)
> 
> https://jsfiddle.net/0ax8sdpq/
> 
> ```
> <link rel="stylesheet" href="https://leeoniya.github.io/uPlot/src/uPlot.css">
> <script src="https://leeoniya.github.io/uPlot/dist/uPlot.iife.js"></script>
> 
> <button id="lock">Lock/Unlock</button>
> ```
> 
> ```js
> let data = [
>   [0, 1, 2, 3],
>   [10, 50, 25, 100],
> ];
> 
> const opts = {
>   width: 800,
>   height: 400,
>   scales: {
>     x: {
>       time: false,
>     },
>   },
>   series: [
>     {},
>     {
>       stroke: "red",
>     },
>   ],
> };
> 
> let u = new uPlot(opts, data, document.body);
> 
> // chart locking for mouse events
> let locked = false;
> 
> document.getElementById("lock").addEventListener("click", (e) => {
>   u.root.style.pointerEvents = !locked ? "none" : "auto";
>   locked = !locked;
> });
> 
> // background hover
> u.over.addEventListener("mouseenter", (e) => {
>   u.under.style.background = "linear-gradient(#e66465, #9198e5)";
> });
> 
> u.over.addEventListener("mouseleave", (e) => {
>   u.under.style.background = "none";
> });
> ```

What I want is to be able to lock or unlock by clicking a button outside or by clicking on the plotting area. 
If I do this, there's a problem
Unable to unlock or lock by clicking on the plotting area.
Can you understand what I mean

**Comment by 17839359913** [comment]
> a big reason to use uPlot is for performance. if you need animations/transitions and are going to make performance much worse to achieve this, you should probably use another library that has these features and will simplify your code.

Thank you very much
