### ISSUE TITLE
x-axis line spacing

### ISSUE THREAD

**Issue by florentbr** [leeoniya/uPlot#810]
The spacing between two lines of text on the x-axis is currently hard coded with the [`lineMult`](https://github.com/leeoniya/uPlot/blob/02222d4500115aac23ddef89c3382d9a4dca153f/src/opts.js#L491) constant :

```javascript
const font      = '12px system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"';
const labelFont = "bold " + font;
export const lineMult = 1.5;		// font-size multiplier
```
It gives too much spacing on a tight layout:

![Screenshot_20230320_215603](https://user-images.githubusercontent.com/918557/226464315-773a0349-a598-4ef2-ae4a-65573b2e44ee.png)

https://jsfiddle.net/pLmvf463/4/

It's be great if this styling property was available in the x-axis options.

**Comment by leeoniya** [comment]
now exposed as `axis.lineGap: 1.5`

looks like you forgot to match your y `axis.ticks.width` ;)

![image](https://user-images.githubusercontent.com/43234/226485321-64c46e06-12c4-4d8e-8ba2-8cc2d16887c5.png)

**Comment by florentbr** [comment]
Thanks, that was fast.
I would have exposed  it as `axis.lineHeight` since the equivalent CSS property is named [`line-height`](https://www.w3.org/WAI/WCAG22/Techniques/css/C21).

**Comment by leeoniya** [comment]
i've always been iffy about using height/width terminology since orientation of axes or text rotation can be different. while this instance is mostly unambiguous, i chose to stick with the existing pattern of using `gap` for space-between type things.

**Comment by florentbr** [comment]
That makes sense, thanks for the explanation.
