### ISSUE TITLE
how to delay blur when focus ? 

### ISSUE THREAD

**Issue by yongchaoo** [leeoniya/uPlot#812]
like this:

https://user-images.githubusercontent.com/26200085/226866692-68ca76be-80b3-406a-a852-7a11aa2a7424.mov

when hover one bar, current one highlight, other bars delay seconds to blur. how to config?

I add  focus
```
 const [focused, setFocused] = useState(false);

 cursor: {
            bind: {
              mouseenter: () => {
                return () => {
                  const timer = setTimeout(() => {
                    setFocused(true);
                    timer && clearTimeout(timer);
                  }, 360);
                };
              },
            },
          },
```
and change options
```
options = {
  focus: {
        alpha: focused ? 0.3 : 1,
   },
}
```
then destroy and redraw the chart,  it works, but  the chart shake，not stable.

https://user-images.githubusercontent.com/26200085/226870711-e94267a6-f62d-4be0-ad87-f46551091983.mov

**Comment by leeoniya** [comment]
there is too much going on here. please make a jsfiddle that reproduces this issue. i cannot debug small parts of code that do not work.
