### ISSUE TITLE
Span gaps and add manually gaps

### ISSUE THREAD

**Issue by konsalex** [leeoniya/uPlot#814]
Hey folks, 

We are using uPlot to display multiple line charts together. Currently we used `snapGaps` for each of the series we added, as it was quite frequent that we had a bit of time misalignment and we wanted to display a line chart without any gaps.

The issue we face now is that we want to actually display a gap if the `delta` is bigger than expected.

As a simple example:

| Time     | 1 | 2 | 3    | 4    | 5    | 6 | 7 |
|----------|---|---|------|------|------|---|---|
| Series 1 | 1 | 1 | 1    | 1    | 1    | 1 | 1 |
| Series 2 | 1 | 1 | 1    | 1    | null | 1 | 1 |
| Series 3 | 1 | 1 | 1    | 1    | 1    | 1 | 1 |
| Series 4 | 1 | 1 | null | null | null | 1 | 1 |
| Series 5 | 1 | 1 | 1    | 1    | 1    | 1 | 1 |

In the example data, the desired state would be:
* all the series and their points are connected
* if we have more than 2 consecutive timestamps with `null` value, then add a gap 

Tried to write a custom `gap` [based on this example](https://leeoniya.github.io/uPlot/demos/missing-data.html), but then the `snapGaps` stops working. Is there any straight-forward way to achieve this?

**Comment by leeoniya** [comment]
what you're asking for is the _inverse_ of what that example does. you want to remove gaps that are too small rather than add gaps when there's too much x delta. something like this works:

https://jsfiddle.net/fyLwzgec/

```js
let _ = null;

let data = [
  [0, 1, 2, 3, 4, 5, 6],
  [1, 1, 1, 1, 1, 1, 1],
  [2, 2, 2, 2, _, 2, 2],
  [3, 3, _, _, _, 3, 3],
];

const ungapper = (u, sidx, idx0, idx1, nullGaps) => {
  let xData = u.data[0];
  let yData = u.data[sidx];

  // min px distance for gap retention
  const minGapPx = 2 * (
    Math.round(u.valToPos(xData[1], 'x', true)) -
    Math.round(u.valToPos(xData[0], 'x', true))
  );

  return nullGaps.filter(([fromPx, toPx]) => toPx - fromPx > minGapPx);
};

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
    y: {
      range: [0, 5]
    }
  },
  series: [{},
  {
    stroke: "red",
    gaps: ungapper,
  },
  {
    stroke: "green",
    gaps: ungapper,
  },
  {
    stroke: "blue",
    gaps: ungapper,
  },
  ],
};

let u = new uPlot(opts, data, document.body);
```

**Comment by konsalex** [comment]
Thanks for the prompt response @leeoniya
