### ISSUE TITLE
Uneven gap in the bar chart

### ISSUE THREAD

**Issue by 17839359913** [leeoniya/uPlot#815]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/22956606/229714531-4b39127b-d83c-4090-b804-7ed04f0e9044.png">

In some cases, the gap of the bar chart is not uniform, with an error of 0.5px。
Is this a known problem?

**Comment by leeoniya** [comment]
this is because uPlot generally prefers crisp edges rounded to pixel boundaries.

you can turn this off globally or on a per-series basis:

https://github.com/leeoniya/uPlot/blob/1697833479862f8ae0a446b880fa39237a793fc9/dist/uPlot.d.ts#L369-L370

https://github.com/leeoniya/uPlot/blob/1697833479862f8ae0a446b880fa39237a793fc9/dist/uPlot.d.ts#L862-L863

**Comment by 17839359913** [comment]
Thank you very much.
May I ask for your advice?
Can you tell me the reason for the ambiguity?

**Comment by leeoniya** [comment]
> Can you tell me the reason for the ambiguity?

i dont understand your question. what is ambiguous here?

**Comment by 17839359913** [comment]
I have a new problem where the first and last points are always rendered in half. Is there any way to solve this problem?
<img width="778" alt="image" src="https://user-images.githubusercontent.com/22956606/230529517-fa98326f-ce94-474a-9f9d-b9381b709085.png">

**Comment by leeoniya** [comment]
you can expand the time range a little. uPlot will not expand the time range automatically.

https://jsfiddle.net/0bvks7cw/1/

```js
let data = [
  [0, 1, 2, 3, 4, 5, 6],
  [1, 2, 3, 4, 3, 2, 1],
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
      range: (u, from, to) => {
        let pad = (to - from) * 0.05;
        return [from - pad, to + pad];
      },
    },
  },
  series: [
    {},
    {
      stroke: "red",
      fill: "#ff000020",
      paths: uPlot.paths.bars(),
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

**Comment by 17839359913** [comment]
Thank you very much.

**Comment by 17839359913** [comment]
I have a new question. If you move the mouse quickly, hook.setSeries will execute very frequently, and the transparency of the series will change frequently, feeling very jittery. Is there any way to add interception? Just like useDebounce

https://user-images.githubusercontent.com/22956606/230562637-16499639-660a-4cf1-b13a-19034834853a.mov

**Comment by leeoniya** [comment]
no, not currently: https://github.com/leeoniya/uPlot/issues/787

**Comment by 17839359913** [comment]
But this is really very performance intensive. If there are 100 series, it is very important to me

**Comment by leeoniya** [comment]
what solution do you suggest?
