### ISSUE TITLE
Display directional data

### ISSUE THREAD

**Issue by newinnovations** [leeoniya/uPlot#817]
Many thanks for your excellent work. Most of the things I wanted to achieve I have been able to find out using the many examples and responses to the issues.

Now I want to display something that I could not figure out how to approach. I have some time series data of measurements that may be related to wind speed and direction. The wind information I have in two time series, one for speed (m/s) and the other the direction (0-360).

In the graph I would like to include the wind information using arrows/vectors. Longer vectors with higher speeds, in the direction of the wind. Preferably with colors indicting speed as well.

The following sketch below shows the idea.

![image](https://user-images.githubusercontent.com/8201694/230564613-8638054a-f8f5-454e-bbb0-feb09ad6a851.png)

Would this be possible to achieve with uPlot and if so, how should I approach this?

**Comment by leeoniya** [comment]
you can write a custom renderer that draws directly to `u.ctx` with a custom-defined `series.paths`. the series data can be whatever your renderer understands, such as `[[7,320],[25,270],...]`. in the renderer you should use `u.valToPos(value, 'x', true)` to get the pixel coords on canvas.

give the series a custom scale, such as `wind`. since the data format is custom, uPlot won't be able to determine a range for this scale, so set `scale.auto` to false and pre-define with `scale.range: [-100, 1000]` so you get 1000mph padding on top, and 100mph padding below.

do you have some realistic sample data you can attach?

**Comment by newinnovations** [comment]
Thanks for your quick response. Glad to know it is feasible.

The first eye-opener for me is that I can, and should, provide speed and direction in a single series array.

I will collect the actual wind speed and direction data and attach it here asap. Hopefully tomorrow.

**Comment by leeoniya** [comment]
> The first eye-opener for me is that I can, and should, provide speed and direction in a single series array.

this isn't strictly necessary. uPlot will ignore anything in the data that is not declared in the series array. so you can stick any extra data arrays at the end, as long as your renderer knows where to pull them from. this is probably more efficient since you dont need wrapping arrays for every wind datapoint:

```js
let data = [
  [0, 1, 2, 3, 4],  // timestamps
  [34, 25, 15, 40], // wind speeds
  [270, 95, 0, 30], // wind dirs
];

let opts = {
  width: 800,
  height: 400,
  scales: {
    wind: {
      auto: false,
      range: [-100, 1000],
    }
  },
  series: [
    {},
    {
      label: "Wind",
      scale: "wind",
      paths: (u, seriesIdx, fromIdx, toIdx) => {
        let series = u.series[seriesIdx];

        let times = u.data[0];
        let speeds = u.data[1];
        let dirs = u.data[2];

        u.ctx.save();

        for (let i = fromIdx; i <= toIdx; i++) {
          // do whatever Math.atan2() calcs with times[i], speeds[i], dirs[i]
          let xPx = u.valToPos(times[i],     'x', true);
          let yPx = u.valToPos(speeds[i], 'wind', true);

          // draw/stroke/fill on u.ctx here
          // ------------------------------
        }

        u.ctx.restore();
      },
    },
  ]
};
```

**Comment by newinnovations** [comment]
Thanks for your great help. As promised here is some actual data.

For the signal under study that may or may not depend on the wind I have included the temperature (°C) in data[1]. The wind speed (meters/sec) in data[2] and direction (degrees) in data[3]. The file is JSON.

[temp-wind.txt](https://github.com/leeoniya/uPlot/files/11182815/temp-wind.txt)

In regular graphs the data looks like this:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/8201694/230711344-df15bb14-32d2-40ea-b6c4-ec19d9ae4f51.png">

<img width="353" alt="image" src="https://user-images.githubusercontent.com/8201694/230711374-2e2f95a8-e255-4f77-aaee-dc54a5d4a5e5.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/8201694/230711394-da62c360-9e5c-4c5a-b636-3cf300d665a2.png">

**Comment by leeoniya** [comment]
i did a bit of a different take on it, but i'm sure you can continue from here. https://jsfiddle.net/qd8ne4kf/

![image](https://user-images.githubusercontent.com/43234/230734518-bb1429d3-707d-41d1-83e7-c81889501d24.png)

```js
let opts = {
  width: 800,
  height: 400,
  scales: {
    y2: {
      range: [0, 30],
    }
  },
  axes: [
    {},
    {
      label: "Temp °C",
      stroke: "orangered",
    },
    {
      scale: 'y2',
      label: "Wind m/s",
      stroke: "purple",
      side: 1,
      grid: {
        show: false,
      }
    }
  ],
  series: [
    {},
    {
      label: "Temp °C",
      stroke: "orangered",
    },
    {
      label: "Wind m/s",
      stroke: "purple",
      scale: 'y2'
    },
    {
      label: "Wind dir °",
      stroke: "blue",
      auto: false,
      paths: (u, seriesIdx, fromIdx, toIdx) => {
        let series = u.series[seriesIdx];

        let times  = u.data[0];
        let speeds = u.data[2];
        let dirs   = u.data[3];

        u.ctx.save();

        u.ctx.beginPath();

        for (let i = fromIdx; i <= toIdx; i++) {
        	if (speeds[i] == null) continue;

          let xPx = u.valToPos(times[i],   'x', true);
          let yPx = u.valToPos(speeds[i], 'y2', true);

          let len = 15;
          let theta = dirs[i] * (Math.PI / 180);
          let dx = len * Math.cos(theta);
          let dy = len * Math.sin(theta);

          u.ctx.moveTo(xPx, yPx);
          u.ctx.lineTo(xPx + dx, yPx + dy);
        }

        u.ctx.strokeStyle = series.stroke();
        u.ctx.stroke();

        u.ctx.restore();
      },
    },
  ]
};

let u = new uPlot(opts, data, document.body);
```

**Comment by newinnovations** [comment]
Great! Indeed I should be able to build on this. Very much appreciate your ideas on showing the wind data combined with the actual data.
