### ISSUE TITLE
Any way to do event callbacks?

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#82]
Hello,

I'm currently trying to use this project to power a signal labeling tool.

Our users work on time-series obtained from a web-service. The data plotted needs to be re-downloaded on every zoom or pan action.

Is there any feature thast lets me add a callback on zoom / pan to change the plot data?

Thank you

**Comment by leeoniya** [comment]
you can use the `setScale` hook:  https://jsfiddle.net/m9bp4k68/

```js
const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    }
  },
  series: [
    {},
    {color: "red"}
  ],
  hooks: {
    setScale: [
      (u, key) => {
        if (key == 'x')
          console.log("zoomed!");
      }
    ]
  }
};

const data = [
  [ 1, 2, 3, 4, 5, 6, 7, 9,10],
  [40,43,60,65,71,73,40,22,20],
  [30,23,35,27,11,13,30,32,30],
  [15,13,39,17,21,53,10,11,13],
];

let u = new uPlot.Line(opts, data, document.body);
```

**Comment by leeoniya** [comment]
i think this is addressed. let me know if there's anything else.
