### ISSUE TITLE
Move legend table rows under tbody element for scrollable legend

### ISSUE THREAD

**Issue by acdc2019** [leeoniya/uPlot#820]
Hi @leeoniya 
Thank you very much for this library. I have a requirement to plot about 20-50 time series data with the legend stacked to the right.
I have been able to move the legend to the right but it takes up too much space vertically.
![image](https://user-images.githubusercontent.com/55312259/232021331-190ce5e2-2649-4c62-aca2-e0b7b1272343.png)

Is it possible to move the legend table u-series rows inside tbody element so that the table can be made vertically scrollable using overflow-y CSS ?

I am currently doing it using the init hook but would be nice to include it in the library.

```ts
init: [
      (u: uPlot) => {
        // Move legend to right
        u.root.classList.add('rgt-leg');

        // Get all the u-series elements
        const rows = u.root.querySelectorAll('.u-series');
        // Get the legend table
        const table = u.root.querySelector('.u-legend');
        // Create a tbody element
        const tbody = document.createElement('tbody');
        tbody.classList.add('u-legend-body');
        // Move the tbody element inside the table
        table?.appendChild(tbody);

        // Move each u-series element under the tbody element
        rows.forEach((row, _i) => {
          const parent = row.parentNode;
          parent?.replaceChild(tbody, row);
          tbody.appendChild(row);
        });
      },
    ],
```
```css
.u-legend-body {
  height: 250px;
  width: 200px;
  overflow-y: auto;
}
```
![ScrollableLegend](https://user-images.githubusercontent.com/55312259/232023709-54c3cded-868f-4d9f-926a-0460863480a6.gif)

```html
<table class="u-legend u-inline">
  <tbody class="u-legend-body">
    <tr class="u-series">
    <tr class="u-series">
    <tr class="u-series">
    <tr class="u-series">
	...
  </tbody>
</table>
```

**Comment by leeoniya** [comment]
:+1: sounds reasonable, will add this in the next few days.
