### ISSUE TITLE
auto y-range on full x-range when zooming

### ISSUE THREAD

**Issue by florentbr** [leeoniya/uPlot#823]
I'm trying to setup the library to compute the y-range on the full x-range and not the selected/zoomed x-range.
This is to keep the same y-range when the view is horizontally zoomed or panned.

The `scale.y.auto` provides the `viaAutoScaleX` option to skip the auto scaling once the data is loaded.
The issue is that the calculated `serie.max/serie.min` are cleared by [`resetYSeries`](https://github.com/leeoniya/uPlot/blob/02222d4500115aac23ddef89c3382d9a4dca153f/src/uPlot.js#L1255) before `scale.y.range(...)` is called:

```js
scales: {
    y: {
        auto: (u, viaAutoScaleX) => viaAutoScaleX,
        range: (u, lo, hi) => {
            if (lo == null) {
                lo = Infinity;
                hi = -Infinity;
                for (let s of u.series) {
                    if (s.show) {
                        lo = Math.min(lo, s.min);  // fails since s.min has been cleared
                        hi = Math.max(hi, s.max);  // fails since s.max has been cleared
                    }
                }
            }
            return [ lo * 1.1, hi * 1.1 ];
        }
    }
}
```
https://jsfiddle.net/zwe7aksq/

Would it be possible to expose the auto-calculated min/max of each serie for the full range or at least the previous values ?

**Comment by leeoniya** [comment]
can you just cache the full scale range in some user-defined scale prop?

https://jsfiddle.net/1qaj6oru/

```js
y: {
  auto: (u, viaAutoScaleX) => viaAutoScaleX,
  _range: null, // full range cache
  range: (u, lo, hi, scaleKey) => {
    let sc = u.scales[scaleKey];

    if (lo == null)
      [lo, hi] = sc._range;
    else
      sc._range = [lo, hi];

    return [lo * 1.1, hi * 1.1];
  },
}
```

**Comment by leeoniya** [comment]
> The issue is that the calculated serie.max/serie.min are cleared by [resetYSeries](https://github.com/leeoniya/uPlot/blob/02222d4500115aac23ddef89c3382d9a4dca153f/src/uPlot.js#L1255) before scale.y.range(...) is called:

i have a vague plan to split `scale.auto` from its current dual-purpose role as "should uplot autoscale" and "should uplot find min/max limits" to pass to `scale.range()`. something like `scale.scan()` + `scale.auto()`. probably the same for `series.auto()` and `series.scan()`.

**Comment by florentbr** [comment]
> can you just cache the full scale range in some user-defined scale prop?

Can't use `u.scales` for caching since it's no longer correct if one serie is enabled/disabled by the user.
One solution would be to disable the auto scaling, but it requires to rewrite the existing min/max function since it's not accessible: 

```js
  function set_bounds(serie, data) {
    if (data) {
      let i = 0;
      for ( ; i < data.length && data[i] === undefined; i++) ;
      let lo = data[i] ?? Infinity;
      let hi = data[i] ?? -Infinity;
      for ( ; i < data.length; i++) {
        let v = data[i];
        if (v < lo) lo = v;
        else if (v > hi) hi = v;
      }
      serie.lo = lo;
      serie.hi = hi;
    }
  }

  const opts = {
    plugins: [{
      hooks: {
        setData: u => {
          for (let i = u.series.length; --i; )
            set_bounds(u.series[i], u.data[i]);
        },
      }
    }],
    scales: {
      x: { distr: 1, time: true, },
      y: {
        auto: false,
        range: (u, lo, hi, k) => {
          lo = Infinity;
          hi = -lo;
          for (let s of u.series) {
            if (s.show && s.scale === k) {
              lo = min(lo, s.lo);
              hi = max(hi, s.hi);
            }
          }
          return [ min(0, lo * 1.06), max(1, hi * 1.06) ];
        },
      },
    },
```

**Comment by leeoniya** [comment]
as i mentioned above: 

> your version is a bit more dynamic with `if (s.show) {`, but your demo only has one series in it, so not sure how critical that bit is. if you need that you can just do your own full range caching per-series on user-defined `series._range` prop rather than `scale._range` prop and achieve something closer to your example.

**Comment by florentbr** [comment]
> as i mentioned above:
> 
> > your version is a bit more dynamic with `if (s.show) {`, but your demo only has one series in it, so not sure how critical that bit is. if you need that you can just do your own full range caching per-series on user-defined `series._range` prop rather than `scale._range` prop and achieve something closer to your example.

To do my own caching, I need to get the values first (series min/max). I can't since they are either not yet set in `hooks.setData()` or cleared in `y.range()`. That's the whole point of this ticket.

**Comment by leeoniya** [comment]
https://jsfiddle.net/rspb1hxf/

```js
{

  let opts = {
    ...{ width: 600, height: 300 },
    cursor: {
      x: true,
      y: false,
      drag: { y: false, setScale: true, },
    },
    scales: {
      x: { distr: 1, time: false, },
      y: {
        auto: (u, viaAutoScaleX) => viaAutoScaleX,
        range: (u, lo, hi, scaleKey) => {
          let sc = u.scales[scaleKey];

          if (lo == null) {
            lo = Infinity;
            hi = -Infinity;
            for (let i = 1; i < u.series.length; i++) {
              let s = u.series[i];
              if (s.show) {
                let [_lo, _hi] = s._range;
                lo = Math.min(lo, _lo);
                hi = Math.max(hi, _hi);
              }
            }
          }
          else {
            for (let i = 1; i < u.series.length; i++) {
              let s = u.series[i];
              s._range = [s.min, s.max];
            }
          }

          let dy = hi - lo;
          return [lo - dy * 0.1, hi + dy * 0.11];
        },
      }
    },
    series: [
      {},
      { label: "Serie1", stroke: "blue", _range: null },
      { label: "Serie2", stroke: "red", _range: null },
    ]
  };

  let data = [[0, 1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200, 300, 400, 500]];

  let u = new uPlot(opts, data, document.body);
}
```

**Comment by florentbr** [comment]
I tried that last week. The issue remains if a serie is turned off by default:
https://jsfiddle.net/9scmaz16/

**Comment by leeoniya** [comment]
then pre-scan the data in an `init` hook to set `series._range`, ignoring any `series.show`.

i don't want to introduce more complexity to the scale scanning / ranging prior to the bigger upcoming refactor.

**Comment by florentbr** [comment]
That's pretty much what i did in my second comment.
I wish i could call [`function getMinMax(data, _i0, _i1, sorted)`](https://github.com/leeoniya/uPlot/blob/02222d4500115aac23ddef89c3382d9a4dca153f/dist/uPlot.iife.js#L210), but unfortunately it's buried in a closure.
