### ISSUE TITLE
Syncing charts with SetSeries enabled does not consider the series name

### ISSUE THREAD

**Issue by hensou** [leeoniya/uPlot#824]
First of all, thanks for your work on this library!

Currently we have the following scenario:

- **ChartA** with series **Sx**
- **ChartB** with series **S1, S2**
- **ChartC** with series **S1, S2, S3**

All charts are synced and with `setSeries: true`.

The problem is that whenever we hide series **S1** in either **ChartB** or **ChartC**, the **ChartA** also hides its **Sx** series.
The same happens if we hide **Sx** on **ChartA**, the series **S1** on both **ChartB and ChartC** gets hidden.

Now the question is: **Is it possible to make `setSeries` take into account the name of the series as opposed to only consider the index?**

At first I thought of implementing the sub event and compare the series at the respective index on both charts (sender and receiver).
And I already implemented the `sync.filters.sub` but couldn't figured out how to get the current chart object from the sub event since it's signature is this:

```typescript
sub: (type: string, client: uPlot, x: number, y: number, w: number, h: number, i: number) => void;
```

Is it possible to achieve this behaviour with the current implementation? Or would it necessary to add something like the receiving chart object to the pub/sub filters?

If further implementation is needed I could help with a PR.

**Comment by leeoniya** [comment]
hmm, for this i might need to add a third callback to `sync.match` called `matchSeries` that accepts a publisher instance, subscriber instance, and publisher's seriesIdx and returns a subscriber's seriesIdx.

https://github.com/leeoniya/uPlot/blob/1697833479862f8ae0a446b880fa39237a793fc9/dist/uPlot.d.ts#L508

**Comment by leeoniya** [comment]
added, see new demo in https://leeoniya.github.io/uPlot/demos/sync-cursor.html

![image](https://user-images.githubusercontent.com/43234/235319134-9671f935-43df-481e-9c71-74c135a6e68f.png)

https://github.com/leeoniya/uPlot/blob/8fb9510d16fe63dfd5952bbf63b03944f6968fdd/demos/sync-cursor.html#L277-L336

**Comment by hensou** [comment]
Thank you @leeoniya, it works perfectly.
