### ISSUE TITLE
Hook into drawing to downsample 

### ISSUE THREAD

**Issue by KyleBsingh** [leeoniya/uPlot#825]
I have a use case, where I want to show multiple series (usually around the same x-axis timeframe), but the density of these series are unknown. For example: a series could have 1000 points in some timeframe, while another series could have 1,000,000.

Is it possible to hook into the draw mechanism to limit the amount of points drawn per series? E.g when fully zoomed out, only 1000 points are drawn for each series (so downsampled), but when fully zoomed in you would be able to see full granularity.

**Comment by leeoniya** [comment]
i think for this case you'll want to downsample externally, do `new uPlot(opts, lowResData)` and customize uPlot's zoom behavior to do `u.setData(highResData, false) + u.setScale('x', {min: zoomedFrom, max: zoomedTo})` inside the `setSelect` hook. if you give me some sample data and your downsampling function e.g. `(rawData, fromIdx, toIdx, numPoints) => resampledData` i can make an example for you.
