### ISSUE TITLE
Support for user-defined formatting of time values

### ISSUE THREAD

**Issue by mbj4668** [leeoniya/uPlot#83]
Hi,

By setting tick formatters in 'values' in an axis, I can show timestamps in 24h format.  But the selected "Time" is always printed in 12h format with am/pm.  I would like to print that in 24h format as well.

I added an option 'timeSeriesVal', by changing this line in Line.js:

```js
const _timeSeriesVal = timeSeriesVal(tzDate);
```

to:

```js
const _timeSeriesVal = opts.timeSeriesVal ? opts.timeSeriesVal(tzDate) : timeSeriesVal(tzDate);
```

and with this I can pass my own formatting function.  I'm not sure this is the right way to do it though; specifically I'm not sure the name of this option is correct / descriptive.

**Comment by leeoniya** [comment]
you can change the formatting templates by providing a custom `axis.values` config. the default one is essentially this:

```js
values: [
  [3600 * 24 * 365,    "{YYYY}",               7,   "{YYYY}"                    ],
  [3600 * 24 * 28,     "{MMM}",                7,   "{MMM}\n{YYYY}"             ],
  [3600 * 24,          "{M}/{D}",              7,   "{M}/{D}\n{YYYY}"           ],
  [3600,               "{h}{aa}",              4,   "{h}{aa}\n{M}/{D}"          ],
  [60,                 "{h}:{mm}{aa}",         4,   "{h}:{mm}{aa}\n{M}/{D}"     ],
  [1,                  "{h}:{mm}:{ss}{aa}",    4,   "{h}:{mm}:{ss}{aa}\n{M}/{D}"],
],
```

just change `{h}` to `{H}` or `{HH}` and drop the `{aa}`

the full list of abbreviations is in the source:

https://github.com/leeoniya/uPlot/blob/bc8cc24bd9176e023f33f2019e1ea5d22b62cf9e/src/fmtDate.js#L63-L106

**Comment by leeoniya** [comment]
oops, sorry, i just re-read your question. one sec...

**Comment by leeoniya** [comment]
ok, `series.value` can now be a template string and will respect `opts.tzDate`.

**Comment by mbj4668** [comment]
Thanks for the quick reply and the fix; the new format string works fine!

And thanks for this great project!  I stumbled upon it yesterday and have started to experiment w/ my data sets.  Seems to work perfectly!  I just need to figure out a way for the user navigate the data; I have one sample per second (from ~8 different Y-series), and each set is anything between 2 hours to 3 days.  2 hours can be handled in one chart w/ panning but w/o scrolling, but for the larger sets I will need some kind of scrolling, I think.

**Comment by leeoniya** [comment]
i was planning on making a demo similar to this:

http://dygraphs.com/gallery/#g/range-selector

there's nothing built in but i think there's enough api to make this without too much effort using 2 charts with the same data but different scale ranges and some ui sprinkled on.

i might need to add the ability to disable zoom without disabling selection and make a new "select" hook. i havent really thought about it much yet.

**Comment by mbj4668** [comment]
That would be perfect!

**Comment by leeoniya** [comment]
closing this issue in favor of #87 to stay on topic. i've added some more thoughts/concerns there. let me know what you think.
