### ISSUE TITLE
how to remove legend and tooltip?

### ISSUE THREAD

**Issue by dolev146** [leeoniya/uPlot#830]

**Comment by leeoniya** [comment]
to disable the legend, set `legend.show: false`. there is no tooltip in uPlot.

**Comment by dolev146** [comment]
thank you a lot!!!
added this to the options and it worked

```
  legend: {
    show: false
  },
```
full option object
```
const options = {
  width: 400,
  height: 300,
  // the answer 
  legend: {
    show: false
  },
  // ^^^^
  scales: {
    x: {
      time: false,
      range: [-0.5, 5.5]
    },
    y: {}
  },
  axes: [{}],
  series: [
    {},
    {
      stroke: "blue"
    }
  ]
};
```

**Comment by dolev146** [comment]
![image](https://github.com/leeoniya/uPlot/assets/62290677/4a7763c4-f17f-41d2-bea9-c4148a5631ea)

**Comment by dolev146** [comment]
when hovering we have a cross, sorry for my bad English I meant removing the cross

**Comment by leeoniya** [comment]
all the options are documented here:

https://github.com/leeoniya/uPlot/blob/91b459fbcb86d39d1e7dfafd16ee5db9872987f7/dist/uPlot.d.ts#L531-L539
