### ISSUE TITLE
Bug: Cursor crosshairs renders on new plot on top left corner

### ISSUE THREAD

**Issue by DeadP4xel** [leeoniya/uPlot#834]
Hi there,

We are using uPlot in a React project (with React uPlot) and we are very excited about it because we could do a lot of
our own customisation using plugins. Thanks for the great library!

Now we wanted to implement a function to retrieve live data (via polling) and update the data array at regular
intervals. Since we always add some data to the data array and remove the same amount of data from the beginning of the
array, since we want to have a fixed interval length to display, and since it is not an option for us to keep growing
the array due to the large amount of data. We now have two options using React uPlot (uPlot wrappers):

1. we can trigger uPlot's setData to be used, which will adjust the data of the plot. However, this leads to the problem that
   Scales-xMin is not corrected, making it possible to zoom out of the plot. The missing data creates a gap at the beginning. Is there a way to adjust the x-range of the plot in a hook afterwards to avoid this problem?
2. we can have a new plot object created. However, we then have the problem that there is a cursor crosshair (horizontal
   and vertical) at the top left of the canvas coordinate 0,0, which we find very annoying (see screenshot). We cannot
   explain how this happens. The cursor focus stays there until the cursor enters the plot area. Is there a way to avoid this without having to set crosshair x and y to false in the cursor options? Finding a solution to this would probably be the better method for us.

Our uPlot cursor config:

```
cursor: {
	show: true,
	drag: {
		x: false,
		y: false
	},
	focus: {
		prox: 15
	},
	sync: {
		key: "channels",
		setSeries: false,
		match: [matchSyncKeys, matchSyncKeys],
		filters: {
			pub: () => isSynced
		}
	},
	bind: {}
}
```

![Screenshot 2023-05-31 185416](https://github.com/leeoniya/uPlot/assets/7443226/8695159d-7a8d-45ae-974f-f632a58abd26)

Thanks in advance!

**Comment by leeoniya** [comment]
> Scales-xMin is not corrected, making it possible to zoom out of the plot. The missing data creates a gap at the beginning. Is there a way to adjust the x-range of the plot in a hook afterwards to avoid this problem?

can you make a jsfiddle that shows the issue using only uPlot without React or wrappers (like https://jsfiddle.net/0bvks7cw/1/) ? i have a streaming demo that does what you're describing and it works okay (first example): https://leeoniya.github.io/uPlot/demos/stream-data.html

> However, we then have the problem that there is a cursor crosshair (horizontal
and vertical) at the top left of the canvas coordinate 0,0, which we find very annoying (see screenshot). We cannot
explain how this happens. 

i've seen this occasionally, but also find it hard to reproduce (e.g. none of the demos in this repo seem to be affected), can you provide some runnable code that shows this consistently?
