### ISSUE TITLE
The "Dynamic data update / streaming" demo appears to stutter during operation

### ISSUE THREAD

**Issue by jinjilynn** [leeoniya/uPlot#835]
https://leeoniya.github.io/uPlot/demos/stream-data.html

How can we make the animation more smooth

**Comment by leeoniya** [comment]
that demo updates data every 100ms, you can update data or call setScale() as often as you need, just be aware that it's not free, performance-wise. see:

https://leeoniya.github.io/uPlot/demos/sine-stream.html

https://leeoniya.github.io/uPlot/demos/pixel-align.html
