### ISSUE TITLE
Bug: The crosshairs are drawn in the wrong position 

### ISSUE THREAD

**Issue by jinjilynn** [leeoniya/uPlot#838]
![image](https://github.com/leeoniya/uPlot/assets/12596042/933b56a6-b8bd-4dec-bf31-bca732f88e6d)

when my web page has been transform for the root element, the crosshairs can not been drawn properly

![image](https://github.com/leeoniya/uPlot/assets/12596042/10ce020e-7862-472f-86db-5ab739866a40)

**Comment by leeoniya** [comment]
duplicate of https://github.com/leeoniya/uPlot/issues/734

i'm not sure there's a cheap and simple way to support this. it's a rare enough case that the solution must be simple (must not modify a lot of the codebase) to be accepted.
