### ISSUE TITLE
Is there any isZoomed() property/check method?

### ISSUE THREAD

**Issue by zorgoz** [leeoniya/uPlot#839]
I have some charts that is updated in real-time. `setData` method that a second bool parameter that determines if the chart should be rescaled or not. That's nice with realtime data as it is advancing, however it is rescaled on update even if it is zoomed, and that is not so nice.
I would simply pass a check as second parameter, so that it rescales only if not zoomed. 
But I can't figure out how to determine if the chart is zoomed or not.

**Comment by leeoniya** [comment]
you can check `u.scales.x.min` and `u.scales.x.max` against `u.data[0].at(0)` and `u.data[0].at(-1)`
