### ISSUE TITLE
Proposal: svg implementation

### ISSUE THREAD

**Issue by jinjilynn** [leeoniya/uPlot#842]
may be you can add a 'type' field for initial opts, like type:"canvas" or type:"svg"

**Comment by leeoniya** [comment]
while it's possible to map some canvas path commands to svg (https://github.com/d3/d3-path) there are other major differences that cannot be directly translated, such as ctx.globalAlpha, ctx.clip, etc. and would require very significant work and would also be much slower. so this is not something that's likely to happen. if you need svg, there are many other libraries for svg plotting.
