### ISSUE TITLE
Does uplot support bar series stack?

### ISSUE THREAD

**Issue by zChanges** [leeoniya/uPlot#846]
echart:  https://echarts.apache.org/examples/zh/editor.html?c=bar-stack
Grouping like bar series stack
<img width="1476" alt="image" src="https://github.com/leeoniya/uPlot/assets/16421725/2fda41ee-0728-4d9b-8d16-4df27eadeaf4">

**Comment by leeoniya** [comment]
the core doesnt have stacking or bar groups, but does provide the basics for getting it done. however, it's not as simple as in other libs, but you can copy/paste the demo code:

https://leeoniya.github.io/uPlot/demos/bars-grouped-stacked.html

the full image of what you're showing has both grouping and stacking, which would probably be out of scope and/or difficult.

**Comment by zChanges** [comment]
> the core doesnt have stacking or bar groups, but does provide the basics for getting it done. however, it's not as simple as in other libs, but you can copy/paste the demo code:
> 
> https://leeoniya.github.io/uPlot/demos/bars-grouped-stacked.html
> 
> the full image of what you're showing has both grouping and stacking, which would probably be out of scope and/or difficult.

Want to achieve grouping and stacking how do I do it？

**Comment by leeoniya** [comment]
i don't think it is worth trying to get this working in uPlot because its data structure is not expressive enough to do this easily.

if you need this, i would recommend using ECharts or Chart.js: https://www.chartjs.org/docs/latest/samples/bar/stacked-groups.html
