### ISSUE TITLE
Pan and zoom a single axis when the cursor is over that axis

### ISSUE THREAD

**Issue by danielgoodell** [leeoniya/uPlot#847]
I figured out how to add panning and zooming using the mouse wheel to multi-axis plots. Now I would like to make it so that if the cursor is over an axis when the mouse wheel clicked or rotated it will pan and zoom only that particular y-axis. Therefore, I need some way to detect which axis the cursor is over. 

I can get the element the cursor is over using
```
document.elementFromPoint(e.clientX, e.clientY)
```

I'm not really sure how figure out which axis that element is associated with that since there doesn't seem to be any identifying information in it. Is there a way to do this? If not, maybe there is an alternative way to intuitively pan and zoom a single axis of a multi-axis plot.

**Comment by leeoniya** [comment]
the axes bounding divs are added to the DOM in the same order that they're defined in the opts. so they can be matched up by index from `document.querySelectorAll(".uplot .u-axis")`:

![image](https://github.com/leeoniya/uPlot/assets/43234/5a57d214-f290-4f1d-a403-2ded296cf56f)
