### ISSUE TITLE
Line disappears when there are relatively few datapoints

### ISSUE THREAD

**Issue by newinnovations** [leeoniya/uPlot#850]
This is related to my question #817.

I have a strange situation when I have few data points in relation to the wind data. When there is enough data things work ok:

<img width="833" alt="image" src="https://github.com/leeoniya/uPlot/assets/8201694/ab848d8e-0aa8-4307-88a0-0f2f316bb436">

When I zoom in and the wind data has much more data points than the main data, the line disappears:

<img width="828" alt="image" src="https://github.com/leeoniya/uPlot/assets/8201694/e8571550-9596-4fec-8256-bc9067bbf457">

Without the wind data the line shows fine:

![image](https://github.com/leeoniya/uPlot/assets/8201694/bda45f12-7f3e-4442-b9ff-fe64d085e67c)

Switch to dots instead of line also works:

![image](https://github.com/leeoniya/uPlot/assets/8201694/6b21c9b6-99c3-44cf-8501-1ee9d560a8ce)

Might this be a configuration issue?

**Comment by leeoniya** [comment]
what does your dataset look like? are you using `uPlot.join()`?

**Comment by newinnovations** [comment]
I combine the different data streams to have a common time base by inserting nulls. Then I give the data to uPlot:

```
const combined = combineSensorData(data, wind);
plot.setData(combined);
```

Dataset: `[ [timestamps], [sensor-data], [wind-speed], [wind-dir] ]`

[combined.zip](https://github.com/leeoniya/uPlot/files/11835979/combined.zip)

**Comment by leeoniya** [comment]
you should insert `undefined` ;)

`null` is an explicit gap, whereas `undefined` is an alignment artifact. this is what `uPlot.join()` does, and my recommendation is to use that.
