### ISSUE TITLE
Handle grouped bars in react

### ISSUE THREAD

**Issue by Fadi-Aldalati** [leeoniya/uPlot#851]
I'm using UplotReact and I'm adding the series conditionally based on what I want (line, bar, area or horizontal bar).
The bar object looks like this 

   
          {
            band: true,
            fill: chartColors[chartColorIndex],
            stroke: chartColors[chartColorIndex],
            paths: uPlot.paths.bars(),
          }

but the bars are overriding each other, they're not stacked nor grouped , any idea why?

**Comment by leeoniya** [comment]
neither stacking nor grouping is part of uPlot core. you can see that the demos here require additional logic:

https://github.com/leeoniya/uPlot/blob/master/demos/grouped-bars.js

https://github.com/leeoniya/uPlot/blob/master/demos/stack.js

**Comment by Fadi-Aldalati** [comment]
Using the additional logic in seriesBarsPlugin caused my code to have some problems in the following:

- All the series were forced to be bars even the one that were chosen as line chart 
- Changing chart scale is no longer working
- Zooming was disabled

Do I need to customize the function in order to make it work?

**Comment by leeoniya** [comment]
> Do I need to customize the function in order to make it work?

the way grouped bars are laid out on the x axis depends on x scale math. i think it will be tricky to get zooming to work here, but possible.

i don't think that zooming in these types of charts is necessary, since they never draw hundreds or thousands of bars. usually you have a few groups and a few bars per group.

**Comment by Fadi-Aldalati** [comment]
Can you please give me any tips on how to implement zooming cause I need it in my chart?

**Comment by YaminoYuki** [comment]
why this is closed .. I am facing the same problem :(

**Comment by Fadi-Aldalati** [comment]
I found a way that doesn't need so much work nor editing the current code in the seriesBarsPlugin function, you can pass the full data as a prop to the function and in the setSelect in hooks you can slice the data and set the new one and when zooming out you can set the whole data in the init hook on double click
`
    hooks: {
        init: [],
        setSelect:[],
   }
`

**Comment by Fadi-Aldalati** [comment]
I still have a weird behavior when resetting scale the bars are not being set as expected.

@leeoniya  Can please help me to know how the bars are being set on axis so I can customize the code as need?
