### ISSUE TITLE
two x-axes chart ?

### ISSUE THREAD

**Issue by kimthumb** [leeoniya/uPlot#854]
x1 = [1, 2, 3, 4, 5]
y1 = [1, 2, 3, 4, 5]

x2 = [1.2, 2.5, 3.8, 7.9]
y2 = [4.1, 3.4, 1.1, 3.5]

What if there are two x-axes?

This is not the case in the demo.

**Comment by leeoniya** [comment]
do you actually want two x axes, or you just need to plot datasets that are not x-aligned?

if you just need to plot un-aligned data, you should use `uPlot.join()` to align it: https://leeoniya.github.io/uPlot/demos/align-data.html

if you actually want a second x axis, look at https://leeoniya.github.io/uPlot/demos/time-periods.html
