### ISSUE TITLE
SyntaxError: Unexpected token (1935:31)

### ISSUE THREAD

**Issue by ile** [leeoniya/uPlot#855]
When using `require('uplot')` in Node.js I'm getting this error:

```
SyntaxError: Unexpected token (1935:31)
```

It points here: https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.cjs.js#L1967

(In my installed version the line seems to be 1935).

Maybe this isn't allowed: `opts?.alignGaps`?

**Comment by ile** [comment]
The reason seems to be package acorn, which is at version 7.4.1. I'll see if I can get it to update.

**Comment by leeoniya** [comment]
optional chaining has been supported by modern browsers since ~2020:

https://caniuse.com/mdn-javascript_operators_optional_chaining

**Comment by ile** [comment]
Yes. Browserify seems to be slow to update its dependencies.
