### ISSUE TITLE
How to set y-axis auto scaling with no fractional numbers?

### ISSUE THREAD

**Issue by ile** [leeoniya/uPlot#856]
Thanks for the great library. This is just a question, hope it's ok:

Is it possible to set the y axis so that it uses auto scaling, but it wouldn't print fractional numbers?

![image](https://github.com/leeoniya/uPlot/assets/433707/447db8bd-c4e7-4b79-af3c-e64a5676fdcb)

On this chart, it can still print the grids as they are, but it just wouldn't print those 272,5 and 267,5 numbers. So it would look like this:

![image](https://github.com/leeoniya/uPlot/assets/433707/4a357012-bf2b-41e4-9309-6c2ee8e42ec6)

**Comment by leeoniya** [comment]
what ticks/grid do you want to see when your data range is `{min: 264.5, max: 264.9}`

**Comment by ile** [comment]
Well, my data range wouldn't be like that. The data represents "the number of tasks", so it's always integers. 

That's why it feels strange to see floating point numbers when tasks can be anything like that. 

So, if there was a setting like `{ int: true }` that could help.

**Comment by ile** [comment]
I can also fork the library and do my own change.

**Comment by leeoniya** [comment]
you can control what tick multiples can be chosen by providing your own via `axis.incrs`: https://jsfiddle.net/duym25wh/1/
