### ISSUE TITLE
Series stroke at scale limits is clipped to half width when scale is explicitly ranged

### ISSUE THREAD

**Issue by zefirka** [leeoniya/uPlot#859]
See here: https://jsfiddle.net/Zeffirsky/k273abz8/11/ 

Even with padding set up, top and bottom series (which sticked to the top and bottom of scales) are going beyond chart and so series has different width. I see a workaround with playing scales min/max modifications, but it's really nasty path cuz possible there will be two axes with different scale range and so It will become really hard to find matching scale change to ensure axes grid will have the same values on same height.

Can we consider something like internal padding for chart or scales or something like this?

**Comment by leeoniya** [comment]
i think the series path clipping rect just needs to be expanded by half the `series.width` instead of using exactly `u.bbox`.

**Comment by leeoniya** [comment]
it already does this halfWidth expansion here if it sees the series values hitting the scale min/max, but maybe it's not hitting that condition?

https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L1521

**Comment by zefirka** [comment]
I looked into `uplot.series[number].min/max` and found out that there's null. Possibly that's the reason?

**Comment by leeoniya** [comment]
probably yes. e.g. if `auto: false` uplot will not scan the series data for min/max and will not cache those on the series objects.

i was actually planning on decoupling this scanning+caching from the follow-up auto-ranging by making `series.scan` and `scale.scan` and not only rely on `series.auto` and `scale.auto` for both things.

**Comment by leeoniya** [comment]
this works, though. hmm...

```js
  scales: {
    x: {
      time: false
    },
    y: {
      range: {
      	min: {pad: 0},
        max: {pad: 0},
      },
    }
  },
```

**Comment by leeoniya** [comment]
i think this is mostly a problem with explicitly setting scales, whether via cursor or via api. when you set the scales manually there's no reason for uPlot to scan the data for auto-ranging, so it skips this.

an easy way to avoid this is to unconditionally expand the stroke clipping region by half width. it would fix the flat-min or flat-max case but would have the not-so-great side-effect of the stroke going outside the grid area by halfWidth when the data limits are outside the y scale bounds. generally that's probably less-bad behavior than the current one.

**Comment by leeoniya** [comment]
hmm, not sure i like the unconditional approach. the alternative is to always scan the data. there will still be edge cases there, for example if you have a bunch of values at 0 and one value at -1 and your scale min is 0.

![image](https://github.com/leeoniya/uPlot/assets/43234/f42357ca-99fd-40ce-9335-52f5d5ffe2b9)

**Comment by zefirka** [comment]
@leeoniya can you release the fix?

**Comment by leeoniya** [comment]
this week

**Comment by zefirka** [comment]
🥺
👉 👈

**Comment by leeoniya** [comment]
sorry, will try today.

i'm on parental leave (not getting.much sleep 😅 🧟) and doing a release involves a couple hours of careful manual testing in uPlot demos and Grafana dashboards to make sure i didnt break anything!

**Comment by leeoniya** [comment]
https://www.npmjs.com/package/uplot/v/1.6.25

**Comment by zefirka** [comment]
Thanks a lot and my congrats!
