### ISSUE TITLE
How can I know when the chart is finish drawing?

### ISSUE THREAD

**Issue by Fadi-Aldalati** [leeoniya/uPlot#865]
Is there a way to know when the chart is finish drawing even if it's a work around ?

**Comment by Fadi-Aldalati** [comment]
Yes please, is there an example or something?
Thank you very much

**Comment by Fadi-Aldalati** [comment]
When I'm doing this 
`  hooks: {
      ready: [
        (u) => {
          console.log('Test');
        },
      ],
}
`
It's logging 3 times ,on the first 2 the chart's not finished but on the third it is , is this the expected behavior ?

**Comment by leeoniya** [comment]
> is this the expected behavior ?

no, it should only fire once, like it does here: https://jsfiddle.net/ysnL60e1/

can you make a jsfiddle that shows the the behavior you're seeing?
