### ISSUE TITLE
Hotizontal bar with labels beside each bar?

### ISSUE THREAD

**Issue by ile** [leeoniya/uPlot#868]
Sorry for a newbie question, but is this type of graph possible?

I suspect that it is possible otherwise, but the label placement may not be, as labels seem to be usually at the bottom of the graph.

![image](https://github.com/leeoniya/uPlot/assets/433707/390164e9-1e9b-4dc1-a988-e13104f98188)

**Comment by leeoniya** [comment]
some examples here:

**Comment by ile** [comment]
Ok, closing, I don't want to leave open issues for no good reason. 

I think my needs expanded a bit, I need also pie charts, which may be difficult with uPlot. So unfortunately I have to go with one of those 2MB libraries - I guess...
