### ISSUE TITLE
Include un-minified uPlot.min.css in dist/

### ISSUE THREAD

**Issue by backspaces** [leeoniya/uPlot#870]
I'd like to work with the uPlot css and the minified version is a bit of a pain for that. :)
So I've been grabbing the github version via:

> curl https://raw.githubusercontent.com/leeoniya/uPlot/master/src/uPlot.css

It can easily be out of sync from the uPlot in node-modules

Thanks.

**Comment by backspaces** [comment]
Actually, I'm wrong. I noticed if I wanted to edit uPlot css, vscode un-minifies it.
So I'll close this.

**Comment by leeoniya** [comment]
any reason you don't just _add_ css after loading the main file to override uplot defaults?

or if you're editing it anyways, just use your own modified copy of it. that css changes very infrequently anyways.
