### ISSUE TITLE
Question: How to change the plot data on zoom without triggering zoom callback?

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#88]
Thank you for your help in #82, it got me going. This is on the same topic.

I want to re-load the data range (with additional resolution) every time the plot is zoomed in, like this:

1. Initially display full data range (low-resolution)
2. When the user zooms-in, load and display the data for the zoomed-in range at higher resolution.

Example: https://jsfiddle.net/danyalejandro/93utgkbx/2

After #82 I do this setting a callback on **opts.hooks.setScale** that downloads the data for the zoomed range, and then calls **uplot.setData(newData)**.

However, setData() will trigger the zoom callback again, so it downloads the data twice.

Is this the right way to go about this? setData() has a second parameter that I couldn't figure out.

**Comment by leeoniya** [comment]
> setData() has a second parameter that I couldn't figure out.

https://github.com/leeoniya/uPlot/blob/e7acfc2642b284699a297b5ce5303ede738e8bcc/src/Line.js#L216

that's exactly the parameter you need :)

normally setData will auto-rescale to the full range of the new data. to prevent this, pass `false` as the second param. then it's up to you to call `setScale()` if necessary (in this case it isn't necessary).

**Comment by danyalejandro** [comment]
nailed it, thank you.

**Comment by henjoe** [comment]
Hi @danyalejandro  looking at your example, I wonder how you achieve to get the zoomed data? 
```
opt.hooks = {
                            setScale:[(u,key) => {
                                if (key === 'x' ) {
                                    console.log("Zoomed!")
                                    // Add logic here for getting the value of zoomed (how??)
                                    
                                }
                            }]
                        }
```

In your case you send you send an API request, but did you know the time range of the zoomed data? I actually stuck in here. 
Or maybe how you can get the zoomed data itself without calling an API? 

Thanks and regards,

**Comment by henjoe** [comment]
> Hi @danyalejandro looking at your example, I wonder how you achieve to get the zoomed data?
> 
> ```
> opt.hooks = {
>                  setScale:[(u,key) => {
>                     if (key === 'x' ) {
>                         console.log("Zoomed!")
>                         // Add logic here for getting the value of zoomed (how??)
>                                     
>                     }
>                 }
>  }
> ```
> 
> In your case you send you send an API request, but did you know the time range of the zoomed data? I actually stuck in here. Or maybe how you can get the zoomed data itself without calling an API?
> 
> Thanks and regards,

Done it using this trick:

```
opt.hooks = {
                            setScale:[(u,key) => {
                                if (key === 'x' ) {
                                    let startIndex = u.series[0].idxs[0];
                                    let endIndex = u.series[0].idxs[1];
                                    zoom_data = sliceArrayRange(u.data,startIndex,endIndex);                                   
                                }
                            }]
                        }


function sliceArrayRange(array: any[][], startIndex: number, endIndex: number): number[][]{
        let result = [[]]
        result =  array.map(subArray => subArray.slice(startIndex, endIndex + 1));
        return result
    }
```
