### ISSUE TITLE
[Query] showing last value at end

### ISSUE THREAD

**Issue by sreeramu** [leeoniya/uPlot#885]
Hello,
Is there is any way to achieve this functions with plugin.
![Screenshot 2023-10-26 at 11 36 59 PM](https://github.com/leeoniya/uPlot/assets/438259/4505e952-383d-45f7-bc21-a90370bb2396)

Need to display the last value of the line at the end of the chart.

Thanks.

**Comment by leeoniya** [comment]
yes it's possible, but probably needs extra logic to avoid overlap when the values are similar.

it is probably easier to just move the y axis to the right side.

you can also use the legend to display the most recent value when nothing is being hovered.

**Comment by leeoniya** [comment]
see the source of this demo: https://leeoniya.github.io/uPlot/demos/area-fill.html

**Comment by sreeramu** [comment]
Thanks , will close this issue.
