### ISSUE TITLE
How to find position of splits?

### ISSUE THREAD

**Issue by vinay2897** [leeoniya/uPlot#886]
I want to draw something at a particular split (tick) of x-axis but there is no datapoint at that timestamp. When datapoint exists it is simple to do with `valToPos`.

Is there something like `valToPos` but in this case `val` is not available instead we pass it a split value? Or some way to get a split's position

**Comment by leeoniya** [comment]
i'm not sure what you mean. valToPos() accepts arbitrary values, so you can pass any timestamp, it doesnt need to come from data.

**Comment by vinay2897** [comment]
> i'm not sure what you mean. valToPos() accepts arbitrary values, so you can pass any timestamp, it doesnt need to come from data.

my bad, didn't realize it works for any value
