### ISSUE TITLE
Hide drawing over axis

### ISSUE THREAD

**Issue by 3rdBlock** [leeoniya/uPlot#891]
Is there a way to stop drawings from overflowing into the axis?

![Screenshot 2023-04-07 235157](https://github.com/leeoniya/uPlot/assets/98533777/19012997-824e-4bd9-900b-77f961f11474)

https://leeoniya.github.io/uPlot/demos/draw-hooks.html

As you can see in your example, if you zoom to specific areas the stars are visible in the axis zone. This is an issue if you have panning and zoom controls as it constantly overflows (both sides) into the axis view.

**Comment by leeoniya** [comment]
in that demo, you can copy these lines into `drawPointsAsStars()`:

https://github.com/leeoniya/uPlot/blob/6221297595add587a2a877ea297eb0c5107d9928/demos/draw-hooks.html#L94-L96
