### ISSUE TITLE
About axes.y.splits

### ISSUE THREAD

**Issue by dingjunweibjkanyun** [leeoniya/uPlot#896]
<img width="672" alt="image" src="https://github.com/leeoniya/uPlot/assets/135958780/cf2f9103-dcc3-4e1a-af83-c3fd359af34a">

The prerequisite is that options.padding is [0,0,0,0]. In some cases, when the scaleMax returned by the split function is close to the maximum split line, it may be truncated.
Is there any way to avoid this problem？

**Comment by leeoniya** [comment]
the purpose of the non-zero padding is to avoid this. if you want y tick labels that are vertically centered on the tick marks and want to put a tick at the top edge of the plotting area, obviously you need extra padding to draw the top half of the tick label. otherwise you cannot render ticks at scales.y.max.

**Comment by dingjunweibjkanyun** [comment]
Padding may have style issues, business needs to pay attention to this padding
<img width="725" alt="image" src="https://github.com/leeoniya/uPlot/assets/135958780/748a51c3-f560-4f66-888e-bc59d7362986">


Is this possible?
When setting scaleMax, the largest split is calculated based on the algorithm of existing splits. If it is close to scaleMax, how can we adjust scaleMax appropriately?

**Comment by leeoniya** [comment]
the algorithm for auto-calculating yMax from dynamic data will be improved in the future to ensure that there is always a tick at the top edge of the plot. this means the padding will be even more important in the future. i dont have any advice for how to select ticks or yMax in a way that always prevents the top tick label from being clipped if your padding is 0. you can reduce the top padding to half your text height, which will help.
