### ISSUE TITLE
Shifted y series not support bar chart type

### ISSUE THREAD

**Issue by minhduc0802** [leeoniya/uPlot#897]
Hi leeoniya, when i use bar chart type in shifted y series, it just work at 1st series, it will wrong drawing at other index. 
1st index:
![Screenshot 2023-11-27 at 14 26 06](https://github.com/leeoniya/uPlot/assets/58297658/fbbfbe4e-579e-40a7-a53e-b2c349b710ef)
Wrong at other index:
![Screenshot 2023-11-27 at 14 26 26](https://github.com/leeoniya/uPlot/assets/58297658/58812745-c627-4f27-ba91-f2f934e23c36)

**Comment by leeoniya** [comment]
should be fixed now, thanks for reporting :)
