### ISSUE TITLE
Change bar color through setCursor hook with bars plugin

### ISSUE THREAD

**Issue by balthazar** [leeoniya/uPlot#898]
Hello,

I was wondering if there was a way I'm not seeing of modifying the color of a bar through the `setCursor` hook, but since the barsPlugin `dist.fill.values` is set upon initialization I haven't found a way to properly do it. The idea is to get a better hover effect compared to the one seen [here](https://leeoniya.github.io/uPlot/demos/bars-grouped-stacked.html)

I thought that [this piece](https://github.com/leeoniya/uPlot/blob/aea27cafd41acfb3ca77a97ec2092ebddf067de4/demos/grouped-bars.js#L136-L139) in a `drawClear` could possibly help, but it doesn't seem to have much effect since `barsColors` isn't used anywhere else.

Thanks and sorry if this was asked already, I tried looking through the issues without success

**Comment by leeoniya** [comment]
to stay fast, all of uplot's interactive bits and effects are done using DOM elements to avoid redrawing the canvas on rapid mousemove events.

the hover overlays are just cleverly re-using the dom hover point divs the way to dynamically set the point fill would be to use the `cursor.points.fill` option.

https://github.com/leeoniya/uPlot/blob/master/demos/grouped-bars.js#L174
https://github.com/leeoniya/uPlot/blob/master/demos/gradients.html#L118

if you're just looking to remove the point radius, you can override that using a css rule that targets `.u-cursor-pt`. i usually just use the `init` hook to query the uplot DOM and assign any static styles directly to each hover point div to avoid messing with extra stylesheets.

hope that helps!

**Comment by balthazar** [comment]
I see, so you're saying it's just better to stylize `.u-cursor-pt` and transform it in a rectangle that takes the whole bar space and do some CSS opacity/blend-mode rather than modifying the series colors?

**Comment by balthazar** [comment]
I think that mostly works, thanks! Getting an issue with multiple charts syncing (only connects 2 out of 3, sometimes none at all) probably something in `dataIdx` but I'll create another issue with demo if I can't figure it out 😄
