### ISSUE TITLE
How to have scrollable and smaller font in legends?

### ISSUE THREAD

**Issue by selvavm** [leeoniya/uPlot#909]
Hi,

I came to know recently while digging in Grafana source code about uplot and it is blazing fast. Thanks for the contribution.

I am creating a new grafana panel similar to XYChart but with sync enabled. I was not sure how to override the original XYChart so I am using `uplot-react`

Below is my options,
```
let series = [
    {
      label: "t",
      value: (u: any, v: any) => v == null ? "-" : v+"s",
    },
    {
      label: "CPU 1",
      values: (u, sidx, idx) => {
        if (idx==null)
          return {Sname: 'To be filled dynamically', Min: '--', Max: '--', Mean: '--', Std_dev: '--', Value: '--'};
        return {Sname: 'To be filled dynamically', Min: idx, Max: idx, Mean: idx, Std_dev: idx, Value: idx};
      },
      stroke: "red",
    },
    {
      label: "CPU 2",
      values: (u, sidx, idx) => {
        if (idx==null)
          return {Sname: 'To be filled dynamically', Min: '--', Max: '--', Mean: '--', Std_dev: '--', Value: '--'};
        return {Sname: 'To be filled dynamically', Min: idx, Max: idx, Mean: idx, Std_dev: idx, Value: idx};
      },
      stroke: "blue",
    },
  ]
  const brushOpts = {
    width: width,
    height: height*0.7,
    legend: {
        show: true
    },
    cursor: {
        y: false,
        points: {
            show: false,
        },
        drag: {
            setScale: false,
            x: true, 
            y: false,
        },
        sync: {
            key: 'moo',
            setSeries: true,
        },
    },
    scales: {
        x: {
            time: false,
        },
    },
    series: series,
    hooks: {
      init: [
        (u: any) => {
          u.over.ondblclick = e => {
            console.log("Fetching data for full range");

            u.setData(data);
          }
        }
      ],
      setSelect: [
        (u: any) => {
          if (u.select.width > 0) {
            let min = u.posToVal(u.select.left, 'x');
            let max = u.posToVal(u.select.left + u.select.width, 'x');

            // zoom to selection
            u.setScale('x', {min, max});

            // reset selection
            u.setSelect({width: 0, height: 0}, false);
          }
        }
      ],
    }
  }
```

I wanted to have tooltip similar to Grafana so I tried the [cursor-tooltip](https://leeoniya.github.io/uPlot/demos/cursor-tooltip.html) but it does not show the pop-up.

Anyway, I settled with showing the legends as a scrollable table as seen in Grafana. How can I acheive it? Also, I want the font to be smaller (Grafana style) such that there is more space for the chart. How can I achieve this?

![uplot_custom_panel](https://github.com/leeoniya/uPlot/assets/16543422/bd6186ee-5f74-40a6-b89e-6414f51e9f0c)

**Comment by leeoniya** [comment]
hey @selvavm ,

grafana does not use uPlot's legend, it creates its own from the dataframe fields and is rendered by the panel code into VizLayout container.

you may want to do the same thing if you want similar behavior and styling. example:

https://github.com/grafana/grafana/blob/a5957ba5557e92940db7f19ea5fe77b26ee7c75b/public/app/plugins/panel/histogram/Histogram.tsx#L348-L354
