### ISSUE TITLE
sub-second divisors lack a formatter

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#91]
I'm drawing low/high bands on plots made from API calls.

Sometimes, the low, high and close values are the same for specific data ranges, and this causes the plot to go blank, although the values are clearly there.

Example: https://jsfiddle.net/danyalejandro/93utgkbx/7/

Is this a bug? if not, any tips on what I can do to avoid this from happening on the uplot.opts side?

**Comment by leeoniya** [comment]
this is a bug but not with the bands.

the error it throws is a result of it not finding a formatter for the determined divisor along the x time scale (0.5s). there are currently no formatters defined for periods smaller than 1s:

https://github.com/leeoniya/uPlot/blob/d88fb3507aae57a4ad78346c31c2274ee46a7d42/src/opts.js#L118-L125

i'll add one more for sub-second periods which just appends `{fff}`:

https://github.com/leeoniya/uPlot/blob/d88fb3507aae57a4ad78346c31c2274ee46a7d42/src/fmtDate.js#L105

**Comment by leeoniya** [comment]
well, this is kind of fixed (it doesn't crash any more). but the minimum tick `space` needs to be much larger at these label widths.

you can either change `axis.space` to be a function which returns different minimum space values (in pixels) based on the scale's min/max values:

https://github.com/leeoniya/uPlot/blob/73f160245813ff552aad45000ba34ce088e77d14/src/Line.js#L662

or you can provide your own formatter array makes smaller labels that fit into the staticly-defined tick space:

https://github.com/leeoniya/uPlot/blob/73f160245813ff552aad45000ba34ce088e77d14/src/opts.js#L255

**Comment by leeoniya** [comment]
i've pushed some better defaults for second & sub-second formatters in 48a1479e4cae6612dad966590080c23985528549 so it's less horrible.

**Comment by danyalejandro** [comment]
Looks so much better now, thank you!
