### ISSUE TITLE
Add a way to clear selection

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#92]
I recently discovered that `.setSelect({ width: 0, height: 0}, false)` can clear a selection while trying to cancel a zoom-in operation from the setSelect hook (I'm trying to limit maximium zoom).

Is this the right way to do it? Maybe you could provide access to .hideSelect() if that's more appropiate?

**Comment by leeoniya** [comment]
`.setSelect({ width: 0, height: 0})` is the proper way to do it. if you're only zooming along the `x` axis, then `.setSelect({width: 0})` should be sufficient. whether you want to pass `false` to prevent the `setSelect` hook from firing is up to you. i don't want to expose more API methods than strictly necessary.
