### ISSUE TITLE
Support for oklch colors

### ISSUE THREAD

**Issue by alexey-milovidov** [leeoniya/uPlot#927]
https://oklch.com/

They are already supported in most browsers in CSS, and maybe supported on Canvas, but when I tried to use them for uPlot, it did not work.

Motivation: https://github.com/ClickHouse/ClickHouse/pull/60391

**Comment by leeoniya** [comment]
hmm, uPlot just passes the color strings straight to dom and canvas context. i dont recall having any kind of color parsing/processing 🤔

**Comment by leeoniya** [comment]
works okay: https://jsfiddle.net/bycp0efm/

**Comment by alexey-milovidov** [comment]
Thank you, this makes me confused - I will check again.

**Comment by alexey-milovidov** [comment]
My mistake. Everything works.
