### ISSUE TITLE
low/high bands with missing data not rendered properly

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#93]
Consider the following example:

https://jsfiddle.net/danyalejandro/93utgkbx/10/

It seems like the `null` value breaks low/high band plots. Is this something that could be fixed?

Thank you

**Comment by danyalejandro** [comment]
Another example of behaviour with null values:
![image](https://user-images.githubusercontent.com/1218608/72279609-58b40180-35eb-11ea-986d-759679cf0f04.png)

**Comment by leeoniya** [comment]
bands are currently drawn counter-clockwise as a single filled shape. to account for missing data in bands, there would have to be additional logic to draw them first to an offscreen canvas, apply clipping rectangles where the values are null, and then draw the result to the final canvas.

**Comment by danyalejandro** [comment]
Sounds like a lot of work.

Dygraphs was able to do this. Plot.ly would break the same way uPlot does right now (they do a similar thing), I made a work-around in Plot.ly by adding extra fake data around the plot holes to make low/high/close values equal and somehow make the hole *almost* invisible (an area with thickness 0). Maybe this could be done automatically when drawing the bands?

See artistic representation attached
![image](https://user-images.githubusercontent.com/1218608/72297918-d25ee600-3611-11ea-92aa-5475ec6c490c.png)

**Comment by leeoniya** [comment]
after a bit more research i think this can be done without a secondary canvas and just an additional Path2D with calls to ctx.save(), ctx.clip(), ctx.restore()

**Comment by leeoniya** [comment]
i think this is fixed now.

keep in mind that uPlot will always behave as if `high` bands are missing data wherever `low` bands are missing data. this is because it simply clears a full height rectangle through that missing x range of the low band.
