### ISSUE TITLE
Secondary sync demos not working

### ISSUE THREAD

**Issue by lucianbaciu** [leeoniya/uPlot#934]
Founding a bug in the latest versions of uPlot, I was trying to see how they work on the demos. Both secondary sync (time-ranger) demos are not working.

**Comment by dmccuskey** [comment]
i want to add 3 other demos not working - all are giving same error as OP:

- candlestick
- box & whisker
- draw hooks

thanks !

**Comment by mariusk** [comment]
Can confirm that lots of the demos (candlestick/OHLC charts and more as mentioned already) are not working.

**Comment by mariusk** [comment]
I dug into it a bit, and it is this construct (which inside a lot/all the failing demos) that is to blame:
```javascript
						uPlot.assign(opts, {
							cursor: {
								points: {
									show: false,
								}
							}
						});
```
If you remove/comment out the line `show: false` in the candlestick demo for instance, it works fine.

**Comment by leeoniya** [comment]
it's a bug if the demos don't work as-is.

it's related to new `cursor.points.one` setting. (not in any release yet).

i'll look at fixing it in the next couple days.

**Comment by leeoniya** [comment]
fixed
