### ISSUE TITLE
Is it possible to create stacked bar charts that are grouped by year ?

### ISSUE THREAD

**Issue by LCHXYZ** [leeoniya/uPlot#937]
I started using dygraphs some time ago without realizing that it's not maintained.

So I want to switch to µPlot. However before I do so I need to know if the following graph that I created with dygraphs could also be created with µPlot. A simple yes or no is all I need. Thanks in advance :)

![Graph](https://github.com/leeoniya/uPlot/assets/92049410/21606e8e-cb06-44ad-b336-3d3d5a309efd)

With zoom:

![Graph_zoom](https://github.com/leeoniya/uPlot/assets/92049410/c8eb227f-76be-4355-a79d-c2fc78b8f717)

**Comment by leeoniya** [comment]
probably you're looking for https://leeoniya.github.io/uPlot/demos/timeline-discrete.html ?
