### ISSUE TITLE
Can we render Multicolor Bar charts(each bar has different color) using uPlot?

### ISSUE THREAD

**Issue by H-For-Hitesh** [leeoniya/uPlot#945]
First of all thanks for the amazing library and I honestly appreciate your work. :)

I'm working on the following type of bar chart. 
![colorbar](https://github.com/leeoniya/uPlot/assets/124291730/fd694598-eece-4a68-81b7-791ade2cdd9f)

I was able to rendered this type of bar chart by creating data and series in the following way.

```
const practice2 = {data : [
    [0, 1, 2]
    [1, 0, 0, 0, 0, 0, 0],
    [0, 3, 0, 0, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 0],
  ],
  option: {
    width: 800,
    height: 400,
    scales: {
      x: {
        time: false,
        range: [-0.5,3]
      },
    },
    series: [
      {},
      {
        stroke: "red",
        fill: "red",
        paths: uPlot.paths.bars(),
      },
      {
        stroke: "blue",
        fill: "blue",
        paths: uPlot.paths.bars(),
      },
      {
        stroke: "green",
        fill: "green",
        paths: uPlot.paths.bars(),
      }
    ],
  }}
```
I feel this is a workaround and I am not sure if this is the right way of rending multicolor bar charts.

can you please guide me if there is any better way of doing this?
Thanks!

**Comment by leeoniya** [comment]
take a look at the first two examples here: https://leeoniya.github.io/uPlot/demos/multi-bars.html

you can provide `disp.fill` and `disp.stroke` callbacks to the bars pathbuilder that can do per-bar coloring.

https://github.com/leeoniya/uPlot/blob/e579947241a48c401a7a2c96f1815f44fd19173a/demos/multi-bars.html#L217-L234

**Comment by H-For-Hitesh** [comment]
Hi @leeoniya Thanks for the response. I understood the solution you suggested but it does not resolve the complete problem in my case. In this case I can render bar charts of different colour with different labels but I'm not able to select/deselect different colors in the metric legends(same goes for the demo which you have shared). Any solution on this is highly appreciated!

**Comment by H-For-Hitesh** [comment]
Added some images for your reference @leeoniya :)

![image](https://github.com/leeoniya/uPlot/assets/124291730/842cc822-1931-4cc5-bf48-8471f4815e15)
when Legend Selected
![image](https://github.com/leeoniya/uPlot/assets/124291730/b1c817fb-d3c5-4b92-93a2-b8158a88f47a)
when legend is not selected

**Comment by leeoniya** [comment]
uPlot's legend is series-based.

since there is only one series here, what you're looking for is a value-based legend. so probably you can make your own legend that would act as a data/value filter when clicked and use `u.setData(filteredData)` to update the plot with the "off" values removed.

**Comment by H-For-Hitesh** [comment]
Hi @leeoniya Thanks again for the response. I worked on the solution you suggested, this is working well. :)

**Comment by H-For-Hitesh** [comment]
Hi @leeoniya Regarding the same issue. Is there any way tooltip may work for similar bar chart. Checked the current tooltip plugin shared in demos. It works with series so there is single text for whole chart, Is there any way I can have a separate tooltip label for each bar?
