### ISSUE TITLE
Uplot allows for more plots than webgl based libs

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#95]
Just wanted to mention that uplot has an advantage over webgl based libs: you can only have a very limited number of webgl canvases per page (around a dozen).

My use case requires hundreds of plots per page so not only I appreciate the speed of uplot and low resource consumption, but the fact that even if other libs (ie plotly) offer webgl modes to achieve the same, they limit the number of plots per page.

Just a heads up on an important advantage of your lib.

**Comment by leeoniya** [comment]
thats a great point, actually.

this issue even calls out the Plotly scenario:

https://bugs.chromium.org/p/chromium/issues/detail?id=771792
