### ISSUE TITLE
How to get even spacing between axis ticks for arbitrary discrete values

### ISSUE THREAD

**Issue by lfeng2099** [leeoniya/uPlot#952]
Hello there! I try to plot some real time discrete values and need to display corresponding axis ticks with even spacing. The data I am dealing with can be consecutive integers but sometimes can have huge gaps such as 0, 1, 2, 305...1000. These discrete values represent some state machine states so I'd like to only show axis ticks related to these values and have even spacing between them since the magnitude of the values doesn't matter at all in this case. I tried to use the `splits` prop like this [0,1,2,300,405](let's say these five integers are the possible values my chart can receive); however, when rendered, the distance between axis tick 0 and axis tick 1 is very close to each other while tick 300 is far away. Thanks in advance!

**Comment by leeoniya** [comment]
related: https://github.com/leeoniya/uPlot/issues/894

you can def do it by customizing remapping your states into sequential y integers and customizing the y axis value formatter.

maybe take a look at

https://leeoniya.github.io/uPlot/demos/timeseries-discrete.html

**Comment by lfeng2099** [comment]
@leeoniya Hey thank you very much.
