### ISSUE TITLE
Drawing order for plugin drawing hooks

### ISSUE THREAD

**Issue by mariusk** [leeoniya/uPlot#953]
I've read through the issues related to drawing order before. The suggested method to have some control over this is by reordering series. In my own software I've built on the candlestick plugin example, and even rebuilt it so that the data series used for rendering the candle can appear anywhere in the data series (not always first, as assumed in the original plugin).

I also have other plugins that render things like indicator lines. I would like these to render on TOP of the candles, not below. But regardless of where in the series array I put my candlestick data, and regardless of the order of how the plugins get included, for some reason uPlot always insist on drawing the candles on top of everything else.

I've even looked into the uPlot source code related to series and plugin hooks (for drawing), and done some testing in getting control of the rendering order (so that I can render candles first, effectively making everything appear on top).

But I haven't been successful. If anyone have any clues on how to achieve some predictability with drawing order for multiple plugins as described, I'm all ears.

**Comment by leeoniya** [comment]
the plugin renders the candles in the `draw` hook, which fires last. if you want them drawn below regular series you can use `drawAxes` hook, which fires after axes and grid have been rendered, or the `drawClear` hook which fires before anything exists, so will render under the grid.

https://github.com/leeoniya/uPlot/blob/e579947241a48c401a7a2c96f1815f44fd19173a/demos/candlestick-ohlc.html#L235

**Comment by mariusk** [comment]
Excellent, thanks, that works. After moving it to the `drawAxes` hook some weirds points started appearing at the key values for the OHLC candles. Which was easily fixed by adding a `points: {show: false}` to the series definition for the OHLC prices series.
