### ISSUE TITLE
import uPlot.iife.min.js into js wrapper script.

### ISSUE THREAD

**Issue by sdzghsfhsfdh** [leeoniya/uPlot#955]
Hello,
I'm using uPlot on a small embedded device to visualize some live values. Because of that I'm strongly limited in resources and unable to use any framework or any server side code...
I just try to build a `js` wrapper class around the uPlot script just to simplify the usage.
In my project I have a flat structure of:
```
myplot.js
uPlot.iife.min.js
uPlot.min.css
index.html
```
My webserver serves the `index.html` which contains:
```html
<!DOCTYPE html>
<html>
	<head>
		<title id="title">Dashboard</title>
		<link rel="stylesheet" type="text/css" href="./uPlot.min.css" />
	</head>

	<body>
		<script type="module" src="./myplot.js">
			let obj = document.getElementById("plot");
			plot(obj);
		</script>
		<div>Hello World!!!</div>
		<div id="plot"></div>
	</body>
</html>
```
the `myplot.js` script contains:
```js
import uPlot from "./uPlot.iife.min.js"

export function plot(root) {
    let data = [[1, 2, 3, 4, 5], [1, 3, 2, 5, 4]];

    const opts = {
        width: 600,
        height: 300,
        scales: {x: {time: false}},
        series: [{label: "x"}, {label: "y", stroke: "red"}],
    };

    return new uPlot(opts, data, root);
}
```
Of course - this is an example implementation just to understand how the importing works - and finally it doesn't (or probably I just don't understand it).
When I try to import `myplot.js` into a `type="module"` script block when loading `index.html` into my browser I just get:
```shell
Loading module from “http://localhost:5000/js/js/uPlot.iife.min.js” was blocked because of a disallowed MIME type (“text/plain”)
```  

When I obmit the `type="module"` just get:
```shell
Uncaught SyntaxError: import declarations may only appear at top level of a module
```  

For me it is just unclear how I can wrap up uPlot in a javascript class.
I apologize if my question seems stupid - I just hope you can help me...

**Comment by leeoniya** [comment]
the `iife` build is not an esm module. to use native `import` you can use https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.esm.js

if you want it minified, you can try copy/pasting it into https://try.terser.org/ and fiddling with the Terser options
