### ISSUE TITLE
2 series or more cutting

### ISSUE THREAD

**Issue by Trystanlm** [leeoniya/uPlot#956]
Here is the broken chart with 4 sensors chart

![Capture d'écran 2024-05-30 15211855](https://github.com/leeoniya/uPlot/assets/145838082/3e9c2fc3-a0ef-48d7-af9d-9110d1290dc8)

Here is the work chart with only one sensor

![Capture d'écran 2024-05-30 152052](https://github.com/leeoniya/uPlot/assets/145838082/9878c479-bc29-4243-aeb1-9a87daeb5769)

**Comment by Trystanlm** [comment]
Ask me if u need to see my code

**Comment by leeoniya** [comment]
yes, and also the data

**Comment by Trystanlm** [comment]
const options = {
  width: 450,
  height: 200,
  hooks: {
    init: [
      u => {
        u.root.querySelector('.u-title').style.textAlign = 'left';
      }
    ]
  },
  scales: {
    x: {
      time: true
    },
    y: {
      auto: true,
      range: (self, min, max) => [min - 10, max + 10]
    }
  },
  axes: [
    {
      grid:
      {
        show: false
      },
      space: 50,
      incrs: [60 * 1000, 5 * 60 * 1000, 15 * 60 * 1000, 30 * 60 * 1000, 60 * 60 * 1000], // Different increments to find the best fit
      values: (u, vals) => vals.map(v => new Date(v).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }))
    },
    {
      grid:
      {
        show: false
      },
      space: 50
    }
  ]
};

**Comment by Trystanlm** [comment]
const rssiSeriesUplot = computed(() => {
  const data = [];
  const series = [];
  data[0] = metrics.value
    .filter(metric => {
      if (!clusterMode.value) {
        return metric.uuid === selectedSensor.value?.uuid;
      }

      return sensors.value.some(sensor => sensor.uuid === metric.uuid);
    })
    .map(metric => new Date(metric.time).getTime());
  if (!clusterMode.value) {
    data[1] = metrics.value.filter(metric => metric.uuid === selectedSensor.value?.uuid).map(metric => metric.rssi);
  }
  else {
    for (let i = 0; i < sensors.value.length; i++) {
      const sensorData = metrics.value.filter(metric => metric.uuid === sensors.value[i].uuid).map(metric => metric.rssi);
      data[i + 1] = sensorData;
    }
  }
  if (!clusterMode.value) {
    series.push({
      label: 'Heure',
      value: (u, v) => v !== null ? new Date(v).toLocaleDateString() + ' ' + new Date(v).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '--'
    },
    {
      label: selectedSensor.value?.serial,
      stroke: 'blue',
      width: 2
    }
    );
  }
  else {
    series.push({
      label: 'Heure',
      value: (u, v) => v !== null ? new Date(v).toLocaleDateString() + ' ' + new Date(v).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '--'
    });
    for (let i = 0; i < sensors.value.length; i++) {
      series.push({
        label: sensors.value[i].serial,
        stroke: color.value[i],
        width: 2
      });
    }
  }

  return [data, series];
});

**Comment by Trystanlm** [comment]
<UplotVue :data="rssiSeriesUplot[0]" :options="{...options, title: 'Rssi (dBm)', series: rssiSeriesUplot[1]}"/>

**Comment by leeoniya** [comment]
sorry, this is a lot of work to put together. can you make a runnable demo with your code and data in a jsFiddle? like https://jsfiddle.net/vmy4hfq8/

**Comment by Trystanlm** [comment]
i'm working with vue 3 and its hard to transcript it in a jsFiddle

**Comment by leeoniya** [comment]
> its hard to transcript it in a jsFiddle

do you think it is easier for me to transcribe your vue code? 🤔

**Comment by Trystanlm** [comment]
https://jsfiddle.net/L7ck0g82/ 

sorry for late that good !

**Comment by leeoniya** [comment]
thank you.

the problem is that your x array has duplicate timestamps (one dupe for each series). the x array needs to be the same length as the y arrays. if you original datasets look like `[[1,2,3],[50,30,50]], [[1,2,3],[-20,15,120]]`, you can use `uPlot.join()` to merge the datasets into a single table that uPlot expects, with a single, aligned x array.

in your example if i do `[...new Set(timestamps)]`, this removes the duplicates and makes it work as expected.

https://jsfiddle.net/em4uL2np/

some other drive-by advice: you can set `opts.ms: 1` which will properly handle millisecond timestamps rather than expecting unix (second) timestamps. or just divide all your timestamps by 1000 and skip this setting. this way you can omit the axis value formatting and `incrs` customization you're doing.
