### ISSUE TITLE
Problems with data

### ISSUE THREAD

**Issue by Trystanlm** [leeoniya/uPlot#957]
Hello i'm come back , the last help you give me was verry helpfull for the data format i haved but we change the periodicity of our reiceiving data and now the data dont have the same lenght : i let you see

https://jsfiddle.net/e9cgqh4p/2/

**Comment by leeoniya** [comment]
as mentioned in the previous issue:

> you can use `uPlot.join()` to merge the datasets into a single table that uPlot expects, with a single, aligned x array:  `[[1,2,3],[50,30,50],[-20,15,120]]`
