### ISSUE TITLE
Add new scale/axis to existing plot

### ISSUE THREAD

**Issue by sdzghsfhsfdh** [leeoniya/uPlot#958]
Hi, I want (during runtime) add a new data series to an existing plot (I just saw the example `add-del-series.html`). But these new data belong to an even new scale. I don't know while creating the Plot if I will need this additional scale or not (I even don't want to plot one if the belonging data are not appearing...).

How can I add a new scale to an existing plot during runtime?

**Comment by leeoniya** [comment]
you cannot add acales and axes at runtime. it's an unusual requirement. you can re-create the chart if this is something you need.

or you can define all the possible scales, and create additional axes ahead of time. the axes will auto-hide if there are no visible series on their scales.

**Comment by sdzghsfhsfdh** [comment]
I already found a workaround for my use case. Apologies for annoying questions...

**Comment by StefanoVuerich** [comment]
@sdzghsfhsfdh Hi what workaround did you find for this, I cannot find a way to add new axe at runtime
