### ISSUE TITLE
Offset y plot with max negative y scale value for fill bottom

### ISSUE THREAD

**Issue by mulgurul** [leeoniya/uPlot#960]
Hi, thanks for sharing a great library, most impressing.

This might not be an issue but a request if this is possible at all.
I have a need for creating a chart with a fixed scale, top -10 bottom -120
The series should be plotted so the the fill color is shown from -120 up to the series y value, so its kind of offset/shifted from zero
Heres an example with apexchart which unf. does not perform at all.
Is this possible with uPlot? Any hint how to obtain this would be highly appreciated, thanks.

Best regards, Peter

![Screenshot 2024-06-19 at 08 49 54](https://github.com/leeoniya/uPlot/assets/5803230/b77ce02c-3456-46e0-95ea-1e7fd2cc03cc)

**Comment by leeoniya** [comment]
`series.fillTo` should work for this:

https://github.com/leeoniya/uPlot/blob/e579947241a48c401a7a2c96f1815f44fd19173a/dist/uPlot.d.ts#L931-L932

**Comment by leeoniya** [comment]
https://jsfiddle.net/xp0uqadw/1/

![image](https://github.com/leeoniya/uPlot/assets/43234/92936677-8dce-4916-9084-1a44d7125019)

```js
let data = [
  [470_000, 480_000],
  [-20, -120],
  [-120, -20],
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
    y: {
      range: [-120, -10],
    }
  },
  series: [
    {},
    {
      label: "Scanning 1",
      stroke: "#0000ff",
      fill: "#0000ff30",
      fillTo: -120,
    },
    {
      label: "Scanning 2",
      stroke: "#00ff00",
      fill: "#00ff0030",
      fillTo: -120,
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

**Comment by mulgurul** [comment]
Great, this works exactly as needed:-)

Thank you so much for helping with the solution and even a fiddle.

Best regards from Peter
