### ISSUE TITLE
Hello, is there a property that controls the highlight or ash of a single legend? Like echarts has a selected attribute

### ISSUE THREAD

**Issue by AnnEthan** [leeoniya/uPlot#964]
I want to click on a legend, the other buttons are gray, so are the lines on the chart, click on the highlighted legend again and highlight all the Legends

**Comment by leeoniya** [comment]
there isn't dimming via legend click, but if you enable cursor focus then this also works in the legend during hover:

https://leeoniya.github.io/uPlot/demos/focus-cursor.html

**Comment by AnnEthan** [comment]
I've got it right here. Thank you

**Comment by AnnEthan** [comment]
![1720142079762](https://github.com/leeoniya/uPlot/assets/167418908/3ba065d9-4c46-4cc2-afbe-bf59db4e8fbc)
There is another problem on my side, that is, the Y-axis, the requirement is that only integers can be displayed. I asked it to display only integers through the values property in the axes, but can the y axes I marked in red be hidden
