### ISSUE TITLE
There is a requirement, that is, the Y-axis, which can only display integers. I made it display only integers through the values property in the axes, but can the y axes I marked in red be hidden

### ISSUE THREAD

**Issue by AnnEthan** [leeoniya/uPlot#965]
![1720142079762](https://github.com/leeoniya/uPlot/assets/167418908/2e44a71d-85e2-49dd-aab2-067928667dd1)

**Comment by leeoniya** [comment]
you can add some filters: https://jsfiddle.net/0f56tder/1/

```js
let data = [
  [0, 1],
  [0, 5],
];

const onlyInts = (u, splits) => splits.map(s => Number.isInteger(s) ? s : null);

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
  },
  axes: [
    {},
    {
      filter: onlyInts,
      grid: { filter: onlyInts },
      ticks: { filter: onlyInts }
    }
  ],
  series: [
    {},
    {
      label: "Scanning 1",
      stroke: "#0000ff",
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

or you can provide your own `axis.incrs` array that only contains integer increments.

or you can provide your own `axis.splits` function that only creates integer splits.

**Comment by AnnEthan** [comment]
![1](https://github.com/leeoniya/uPlot/assets/167418908/ab938f89-c9f2-46b3-a9c8-cab4458ceaaa)
I convert non-integers to Null through filter, but why does the orange region still have an axis

**Comment by leeoniya** [comment]
you forgot to filter `axis.ticks`, as shown above: `ticks: { filter: onlyInts }`

**Comment by AnnEthan** [comment]
thanks！！！
