### ISSUE TITLE
Syncing scales presumes a shared scale key

### ISSUE THREAD

**Issue by Qanpi** [leeoniya/uPlot#967]
Trying to sync the x-scales across two uPlot instances, as demoed in [sync-cursor](https://leeoniya.github.io/uPlot/demos/sync-cursor.html). 

When scaling/zooming, results in
> Cannot read properties of undefined (reading 'ori')

at line 
`let sori = src.scales[xKey].ori;`

This assumes that the scale key is identical across two instances. If it is, works perfectly. Just wondering if there is justification for this, or should this be `xKeySrc` instead of `xKey`?

**Comment by leeoniya** [comment]
hmm, that certainly looks unintentional :sweat_smile:,  it probably should be `xKeySrc`

**Comment by Qanpi** [comment]
Happens :) 

Should I PR this, or will you handle it? If the former, does there exist a formalized process for contributions? If the latter, when can we expect the patch to be released? 

On a side note, are there plans for implementing tests that would prevent these kinds of hiccups?

**Comment by leeoniya** [comment]
thanks, fixed.

> On a side note, are there plans for implementing tests that would prevent these kinds of hiccups?

this is quite niche. there are many unwritten tests for much more major things :)
