### ISSUE TITLE
wind direction improvement

### ISSUE THREAD

**Issue by kantigabgerundet** [leeoniya/uPlot#970]
@leeoniya thanks for this incredilble library.

I encountered a small issues in the [wind-direction demo ](https://leeoniya.github.io/uPlot/demos/wind-direction.html).
The directions didn't seem to be rendered correctly. This seems to fix it: 

```
let len = - 15;
                    let theta = dirs[i] * (Math.PI / 180);
                    let dx = len * Math.sin(-theta);
                    let dy = len * Math.cos(theta);
```

Here's a jsfiddle: 
https://jsfiddle.net/ce1ghjzu/

**Comment by leeoniya** [comment]
thanks, fixed.
