### ISSUE TITLE
multi charts zoomed simultaneously when click-drag to zoom one of them

### ISSUE THREAD

**Issue by RonnieLincoln** [leeoniya/uPlot#975]
When having multi uPlot instances thats share a same x series, it is helpful to simultaneously zoom in and out those charts.
How can I do that?

**Comment by leeoniya** [comment]
called cursor sync. examples:

https://leeoniya.github.io/uPlot/demos/sync-cursor.html

https://leeoniya.github.io/uPlot/demos/timezones-dst.html
