### ISSUE TITLE
Is the `points.show` TypeScript definition correct?

### ISSUE THREAD

**Issue by juliusv** [leeoniya/uPlot#976]
The `points.show` field for a series has a TS signature of:

```typescript
export type Show   = boolean | ((self: uPlot, seriesIdx: number) => HTMLElement);
```

(see https://github.com/leeoniya/uPlot/blob/91de800538ee5d6f45f448d98b660a4a658e587b/dist/uPlot.d.ts#L448)

However when I look at how it's actually used in uPlot:

https://github.com/leeoniya/uPlot/blob/91de800538ee5d6f45f448d98b660a4a658e587b/src/uPlot.js#L1603

...it gets more arguments passed internally, and I don't see why the return value would be an `HTMLElement`, since the return value is only used in a boolean context?

The return type of `HTMLElement` first made me think that you could return an HTML element that should be displayed instead of a normal circle, although I guess that wouldn't make much sense in a Canvas context anyway :) I guess my only option for showing something else than a circle is to use the approach from https://leeoniya.github.io/uPlot/demos/draw-hooks.html and draw custom paths on the Canvas?

**Comment by leeoniya** [comment]
the issue with the TS defs is that i re-use the options that go into the constructor and those that are exposed by the instance (or used internally). the former has multiple possible sigs, but the latter is usually a single sig / fn.

so, `show` will always be an fn after init. if it was defined as `false` during init, it's then converted to `() => false` so it has a single calling signature at runtime.

previously: https://github.com/leeoniya/uPlot/issues/595
