### ISSUE TITLE
Question: Show tooltip with data of the nearest non null points of all series

### ISSUE THREAD

**Issue by AdilRabbani** [leeoniya/uPlot#977]
Hi. I'm back with another question 😅 Apologies if this is already mentioned somewhere...I have data with gaps in it and I want to show a tooltip that can show the data for the nearest non-null point of all series. I went through the demo for the nearest non-null point (https://leeoniya.github.io/uPlot/demos/nearest-non-null.html) which actually accomplishes this but the data for the series is shown in the legend and i would like to show it on a custom tooltip i have. I have also created a fiddle which uses the nearest non-null example, shows a tooltip but currently shows `undefined` for the nearest non-null points 😞 

jsfiddle: https://jsfiddle.net/adilrabbani/zp21hjfk/

Can you suggest what is the best way to get the nearest non-null value of all series in a tooltip? :) Thanks!

**Comment by leeoniya** [comment]
the nearest idx for each series will be in the `u.cursor.idxs` array. use that instead of `u.cursor.idx` :)

**Comment by AdilRabbani** [comment]
Awesome! That was it! 🥳 Thanks for the quick reply.
