### ISSUE TITLE
adding and removing series with Y-axis

### ISSUE THREAD

**Issue by builder555** [leeoniya/uPlot#979]
I understand I can add series with `.addSeries()` method and delete with `.delSeries()`, however I'm wondering if it's possible to add series with its own Y axis and remove it, taking its Y axis with it as well? I haven't found a way to do it other than doing the `.destroy()` and then new `uPlot()` again.

**Comment by leeoniya** [comment]
uplot will auto-hide axes when therr are no series on their scales. so you can initially configure the additional axis and scale and add/remove series later that use this scale.
