### ISSUE TITLE
[Question] What’s the best way to extend two series without gaps?

### ISSUE THREAD

**Issue by diego-curti** [leeoniya/uPlot#981]
I have this two series:

![Screenshot from 2024-08-01 09-32-39](https://github.com/user-attachments/assets/16955d71-2731-4614-880e-f14b5a8009d9)

The red one have `null` values when the dashed has values and vice-versa.

However, the connection between the two series has gaps at the edges. So I would like to know the best way to connect the series without gaps between them:

> EDIT:  ideally meeting at the midpoint of each gap

![Screenshot from 2024-08-01 09-32-39](https://github.com/user-attachments/assets/337b143c-93a4-44e8-9bda-45edbb68f996)

I tried addressing the gaps by extending the given values. But this only works for the red line. Moreover, the trend follows the interpolation line between the edges of the red line, instead of following the trend between the last point of the red line and the first point of the dashed line.

![image](https://github.com/user-attachments/assets/b0d85018-7225-475c-9a66-b1e4fe25ae22)

> NOTE: this will be use with a lot of data so performance is an important factor

**Comment by leeoniya** [comment]
can you share the raw dataset for the first image? (before you uPlot.join() them or any other adjustments)

**Comment by diego-curti** [comment]
> can you share the raw dataset for the first image? (before you uPlot.join() them or any other adjustments)

Hi Leon! Thanks for replying so quickly.

I've created this [repro](https://jsfiddle.net/diegocurti/0hv32z5b/14/) for the first image

**Comment by leeoniya** [comment]
thanks!

i'm wondering if your data is structured this way naturally, or split into two series solely to achieve the different rendering style for specific regions? if it's the latter, have you considered/seen this demo?

https://leeoniya.github.io/uPlot/demos/gradients.html

it may be a bit easier to do this interpolation in a single series if you're okay with having a solid color rather than dashed.

**Comment by diego-curti** [comment]
Yes, the data is split into two series specifically for this purpose.

I've looked into the ["gradient"](https://leeoniya.github.io/uPlot/demos/gradients.html) demo and plan to give it a try, since it's possible to use another solid color instead of a dashed line.

However, if you think there could be an efficient way to achieve this with a dashed line, it would be great to know. Otherwise, you can close the issue.

Thanks Leon!

**Comment by diego-curti** [comment]
Finally I managed to resolve this issue by following the ["gradient"](https://leeoniya.github.io/uPlot/demos/gradients.html) demo and we'll stick to this solution, without using dashed line.
