### ISSUE TITLE
switch legend.live true/false & hide/unhide hooks 

### ISSUE THREAD

**Issue by kantigabgerundet** [leeoniya/uPlot#984]
Dear @leeoniya thank you so much for the help so far. Im currently trying to achieve two things:

1. Use a checkbox to switch the legend from live = true to live = false. Probably controversial but unfortunately this is something that can be quite helpful when users need to quickly share data from weather stations to alert each other. It kind of works but it would be great if the Time in the legend would disappear as when it does when setting it manually to false. 
2. Use a checkbox to hide and unhide the hooks 

I would be very grateful for some help. 

Here's the jsfiddle: https://jsfiddle.net/9604zfux/

**Comment by leeoniya** [comment]
the legend is fully in the DOM, so you can easily implement it by adding or removing css classes to the items you would like to temporarily hide.

```css
.u-series:nth-child(1) {
  display: none;
}

.u-series:nth-child(n + 1) .u-value {
  display: none;
}
```

![image](https://github.com/user-attachments/assets/810982c6-5533-4210-84aa-ab3295e1aa1a)

you may also be interested in this demo that renders the chart as a png, that might be a better alternative to manually screenshotting: https://leeoniya.github.io/uPlot/demos/svg-image.html

**Comment by kantigabgerundet** [comment]
Thank you very much! This helepd a lot!
