### ISSUE TITLE
Sort legend items by value

### ISSUE THREAD

**Issue by CrashLaker** [leeoniya/uPlot#99]
Hi all.

Is it possible to display de legend items sorted by its value?

![image](https://user-images.githubusercontent.com/4432491/73098631-8db43400-3ec8-11ea-9d84-ee37578834c1.png)

**Comment by leeoniya** [comment]
uplot initially renders legend labels in series order, and then updates them (without re-creating the dom) with that assumption. if they were reordered on every mousemove event, it would be very expensive to reorder, restyle and re-match them.

you can always do `legend: {show: false}` and use the `setCursor` hook to implement your own legend which would do all its own re-ordering stunts. if you have a lot of series, you may only want this legend to show the top 5 to improve perf.

**Comment by CrashLaker** [comment]
thank you so much!

![image](https://user-images.githubusercontent.com/4432491/73107352-66fff880-3edc-11ea-9a5f-6fd4806354e1.png)

I just couldn't figure out how it's generating that bTop value and kinda hacked it.
`const anchor = { left: left + bLeft, top: top + bTop - 400 };`
any advice on understanding it?

C.

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot/blob/b8ec662d3f2b7944e11e02050f4d301862502a5b/demos/cursor-tooltip.html#L50-L52

**Comment by leeoniya** [comment]
you know, this is probably a good case for adding some kind of callback and api for setLegend, so the work for fomatting the values is handled by the regular series `value` or `values`, otherwise you have to run the formatting manually, right?

**Comment by leeoniya** [comment]
never mind, i guess it's not that difficult to re-use the defined `series.value` formatters:

```js
hooks: {
  setCursor: [
    u => {
      u.series.forEach((s, i) => {
        console.log(s.value(u, u.data[i][u.cursor.idx]))
      })
    }
  ],
}
```

https://jsfiddle.net/dLqrao1f/

**Comment by CrashLaker** [comment]
> you know, this is probably a good case for adding some kind of callback and api for setLegend, so the work for fomatting the values is handled by the regular series value or values, otherwise you have to run the formatting manually, right?  

sorry. didn't quite understand what u meant here

Wow I wasn't aware of that `series.value` struct.
this is how i did it

```javascript
let map = [...new Array(labels.length)].map((d,i) => { return {index: i, val: u.data[i+1][idx]} })
map = map.sort(function (a,b) {
    a = (a.val == undefined) ? 0 : a.val
    b = (b.val == undefined) ? 0 : b.val
    return b - a
}).filter((d) => {return d.val != undefined})
```
`labels` being each label in `series`.

imma check on that `let bbox = can.getBoundingClientRect(); ` thank you

C.

**Comment by leeoniya** [comment]
`series.value` is the formatter for the legend that's passed in the opts. by default it just returns the raw value for y series and human-friendly datetime string for the x series (timestamps). `series.label` can be pulled from there as well.

the general idea is that you can define the opts as if you were rendering the standard legend, but with `legend.show = false` you're just using the same defined formatters and labels to render an alternate legend.

**Comment by alextrastero** [comment]
Sorry for bringing this topic back from the dead but I'm still wondering where's the best place to sort the series' for a custom tooltip.

```js
hooks: {
  setCursor: [
    u => {
      u.series.forEach((s, i) => {
        console.log(s.value(u, u.data[i][u.cursor.idx]))
      })
    }
  ],
}
```

If I do `[...u.series.sort(myCustomSorter)]` then I won't be able to access the data right? since the indexes will not be in sync between series and data. Any idea on where it's best to sort the series for my tooltip pluigin?
