### ISSUE TITLE
[Question] Add current or last value in the Legend

### ISSUE THREAD

**Issue by henjoe** [leeoniya/uPlot#992]
When I hover the mouse of my trend, it has already a tooltip showing values for that specific timeline:

![image](https://github.com/user-attachments/assets/02a5235c-5ca1-4260-900c-862406631cae)

But the legend (at the bottom) also shows the same information of my tooltip. What I want is it shows the latest or current value of my Trend instead of the hover (mouse) value. 

Is it possible? 

Regards,

**Comment by leeoniya** [comment]
you can supply a `series.value` callback that will render whatever you want in the legend.

the bubble demo uses this to show some arbitrary metric when nothing is hovered. it uses `series.values`, which is the table version of `series.value`.

https://leeoniya.github.io/uPlot/demos/scatter.html
