### ISSUE TITLE
Initial Zoom Range (X-Axis Time)

### ISSUE THREAD

**Issue by majew7** [leeoniya/uPlot#993]
## CHALLENGE
The challenge I’m trying to solve is on web page load, reading the url query string `?timeRange={ISO 8601}_{ISO 8601}`, parsing it and then passing the unixTimes to `uPlot`, to show an initial zoomed in range of the graph.  After page load, the user should be free to zoom in or out with click-n-drag, or double-click.

How can I achieve both?

**Context 1:** As I've read using, [`range: []` prevents zooming by making the range static](https://github.com/skalinichev/uplot-wrappers/issues/28#issuecomment-1763121673).  So, I'm unsure what to do.

**Context 2:** I'm already prepared to use `hooks` `setScale` to export the zoomed range back to client.

**Context 3:** I'm using `uplot-wrappers` with `UplotReact`.

Example of an url to share among users: 
![19280cab 1852x358](https://github.com/user-attachments/assets/d9e61a86-a721-4892-be75-d7250cfa1423)

**Comment by leeoniya** [comment]
> Context 1: As I've read using, https://github.com/skalinichev/uplot-wrappers/issues/28#issuecomment-1763121673. So, I'm unsure what to do.

it's only static when defined as an array, but when defined as a callback it will be dynamic.

https://jsfiddle.net/q2m7o1dc/

```js
let data = [
  [0, 1, 2],
  [0, 5, 2],
];

let initialRange = [0.5, 1.5];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
      range: (u, min, max) => {
        let range = [min, max];

        if (initialRange != null) {
          range = initialRange;
          initialRange = null;
        }

        return range;
      },
    },
  },
  series: [
    {},
    {
      stroke: "red",
      points: {
        show: false,
      },
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```
