### ISSUE TITLE
 Issue with valToPos Method Conversion on Mac Screen

### ISSUE THREAD

**Issue by guillonj** [leeoniya/uPlot#998]
**Description**:
I created a plugin for uPlot that displays a colored rectangle on a chart based on min and max dates. The rectangle displays correctly on my secondary screen, but when moving the window to a Mac screen, the rectangle no longer aligns with the correct dates.

**Steps to Reproduce**:

1. My plugin

```import dayjs from 'dayjs';

export type LiquidGraphPluginInput = Exclude<
  ConstructorParameters<typeof LiquidColorPluginOptions>[0],
  undefined
>;

export interface LiquidityRectSettings {
  xMin: dayjs.Dayjs;
  xMax: dayjs.Dayjs;
  color: string;
  label: string;
}

export class LiquidColorPluginOptions {
  constructor(data?: Partial<LiquidColorPluginOptions>) {
    Object.assign(this, data);
  }
  liquidPeriods: LiquidityRectSettings[] = [];
}

export function LiquidColorPlugin(opt: LiquidGraphPluginInput): uPlot.Plugin {
  const options = new LiquidColorPluginOptions(opt);

  const drawRectBg = (u: uPlot) => {
    let {left, top, height} = u.bbox;
    u.ctx.save();
    options.liquidPeriods.map((settings) => {
      const xMin = u.valToPos(settings.xMin.unix(), 'x');
      const xMax = u.valToPos(settings.xMax.unix(), 'x');

      u.ctx.fillStyle = settings.color;
      u.ctx.fillRect(
        left + u.valToPos(settings.xMin.unix(), 'x'),
        top,
        xMax - xMin,
        height
      );
    });
    u.ctx.restore();
  };

  return {
    hooks: {
      drawClear: drawRectBg
    }
  };
}
```

2. Example of usage
In my case, I want to display a colored rectangle between 10/01/2024 and 03/01/2025. 

- Classic screen:
![Capture d’écran 2024-09-12 à 16 54 04](https://github.com/user-attachments/assets/fc9a9744-bb94-421f-bff4-b59e9b44cd80)
![Capture d’écran 2024-09-12 à 16 54 19](https://github.com/user-attachments/assets/ec68a71a-477c-455f-b88f-805e1ca9f222)

- Mac screen:
<img width="1502" alt="Capture d’écran 2024-09-12 à 16 55 39" src="https://github.com/user-attachments/assets/56e12d15-7dfd-4b70-8ecd-857e74991dc8">
<img width="1478" alt="Capture d’écran 2024-09-12 à 16 55 51" src="https://github.com/user-attachments/assets/6bc8b324-d696-4aa0-8ceb-3b5b0ac71f34">

I use uplot-react version 1.2.2 for my development. This could be the cause of the problem
I can't explain this difference depending on the screen. I'm ready to give more details if necessary to understand and solve this issue.

**Comment by guillonj** [comment]
I found a solution by multiplying the xMin and xMax by the `windon.devicePixelRatio` parameter.

```    
const xMin = u.valToPos(settings.xMin.unix(), 'x') * window.devicePixelRatio;
const xMax = u.valToPos(settings.xMax.unix(), 'x') * window.devicePixelRatio;
```
Could this multiplication be integrated into the `valToPos` method by default?

**Comment by leeoniya** [comment]
> Could this multiplication be integrated into the `valToPos` method by default?

it is, you should pass `true` for the third arg ;)

https://github.com/leeoniya/uPlot/blob/a4edb297a9b80baf781f4d05a40fb52fae737bff/dist/uPlot.d.ts#L116-L117
